---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode 
summary: Si usa switches compatibles con MetroCluster, debe tener en cuenta las velocidades de red específicas de la plataforma y los requisitos del modo de puerto de switch. 
---
= Velocidades de red específicas de la plataforma ONTAP y modos de puerto de conmutador para conmutadores compatibles con MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si usa switches compatibles con MetroCluster, debe tener en cuenta las velocidades de red específicas de la plataforma y los requisitos del modo de puerto de switch.

En la siguiente tabla se muestran velocidades de red específicas de plataforma y modos de puertos de switch para switches conformes con MetroCluster. Debe configurar el modo de puerto de switch según la tabla.

[NOTE]
====
* Los valores que faltan indican que la plataforma no se puede utilizar con un switch compatible con MetroCluster.
* Los sistemas AFF A30, AFF C30, AFF C60 y FAS50 requieren un adaptador QSFP-to-SFP+ en la tarjeta de la controladora para admitir una velocidad de red de 25Gbps.


====
[cols="1,2,2"]
|===
| Plataforma | Velocidad de red (Gbps) | Modo puerto del switch 


 a| 
FAS9500

AFF A900

ASA A900
 a| 
100Gbps

40Gbps al actualizar PCM desde FAS9000 o AFF A700
 a| 
Modo trunk



 a| 
AFF C800

ASA C800

A800 de AFF

ASA A800
 a| 
40Gbps o 100Gbps
 a| 
Modo de acceso



 a| 
FAS9000

A700 de AFF
 a| 
40Gbps
 a| 
Modo de acceso



 a| 
FAS8300

AFF C400

ASA C400

AFF A400

ASA A400
 a| 
40Gbps o 100Gbps
 a| 
Modo trunk



 a| 
AFF A320
 a| 
40Gbps o 100Gbps
 a| 
Modo de acceso



 a| 
FAS8200

AFF A300
 a| 
25Gbps
 a| 
Modo de acceso



 a| 
FAS500f

AFF C250

ASA C250

AFF A250

ASA A250
 a| 
-
 a| 
-



 a| 
FAS2750

AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150

ASA A150
 a| 
-
 a| 
-



 a| 
AFF A20
 a| 
25Gbps
 a| 
Modo trunk



 a| 
AFF A30
 a| 
25Gbps o 100Gbps
 a| 
Modo trunk



 a| 
AFF C30
 a| 
25Gbps o 100Gbps
 a| 
Modo trunk



 a| 
AFF C60
 a| 
25Gbps o 100Gbps
 a| 
Modo trunk



 a| 
FAS50
 a| 
25Gbps o 100Gbps
 a| 
Modo trunk



 a| 
AFF A50
 a| 
100Gbps
 a| 
Modo trunk



 a| 
AFF A70
 a| 
100Gbps
 a| 
Modo trunk



 a| 
AFF A90
 a| 
100Gbps
 a| 
Modo trunk



 a| 
AFF A1K
 a| 
100Gbps
 a| 
Modo trunk



 a| 
AFF C80
 a| 
100Gbps
 a| 
Modo trunk



 a| 
FAS70
 a| 
100Gbps
 a| 
Modo trunk



 a| 
FAS90
 a| 
100Gbps
 a| 
Modo trunk

|===