---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: Las distintas configuraciones de MetroCluster tienen diferencias clave en los componentes necesarios. 
---
= Diferencias entre Mediador de ONTAP y tiebreaker de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.7, puede utilizar la conmutación automática no planificada (MAUSO) asistida por Mediator de ONTAP en la configuración IP de MetroCluster o puede utilizar el software MetroCluster Tiebreaker. No es necesario utilizar el software MAUSO o tiebreaker; sin embargo, si decide no utilizar ninguno de estos servicios, debe hacerlo link:../disaster-recovery/concept_dr_workflow.html["realizar una recuperación manual"] si se produce un desastre.

Las distintas configuraciones de MetroCluster realizan una conmutación de sitios automática bajo distintas circunstancias:

* *Configuraciones de MetroCluster FC que utilizan la capacidad DE AUSO (no presente en las configuraciones de MetroCluster IP)*
+
En estas configuraciones, SE inicia AUSO si las controladoras fallan pero el almacenamiento (y los puentes, si existen) permanecen operativos.

* *Configuraciones de IP de MetroCluster usando ONTAP Mediator (ONTAP 9.7 y posteriores)*
+
En estas configuraciones, MAUSO se inicia en las mismas circunstancias que SAUSO, como se ha descrito anteriormente, y también tras un fallo completo de las instalaciones (controladores, almacenamiento y switches).

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Obtenga más información sobre cómo Mediator de ONTAP admite la conmutación automática de sitios no planificados"].

* *Configuraciones MetroCluster IP o FC con el software Tiebreaker en modo activo*
+
En estas configuraciones, el tiebreaker inicia una conmutación de sitios no planificada después de un fallo completo del sitio.

+
Antes de utilizar el software Tiebreaker, revise la link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Instalación y configuración del software MetroCluster Tiebreaker"]





== Interoperabilidad de Mediador ONTAP con otras aplicaciones y aparatos

No puede utilizar aplicaciones o dispositivos de terceros que puedan activar una conmutación en combinación con Mediador ONTAP. Además, no es posible supervisar una configuración MetroCluster con el software MetroCluster Tiebreaker al usar ONTAP Mediator.
