---
permalink: install-ip/concept_considerations_isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: Debe conocer los requisitos de ISL para la configuración. 
---
= Consideraciones sobre ISL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Debe conocer los requisitos de ISL para la configuración.



== Requisitos básicos de ISL de MetroCluster

Se deben cumplir los siguientes requisitos para los ISL en todas las configuraciones IP de MetroCluster:

* Un puerto de switch ISL de velocidad nativa debe conectarse a un puerto de switch ISL de velocidad nativa.
+
Por ejemplo, un puerto de 40 Gbps se conecta a un puerto de 40 Gbps.

* Un puerto de 10 Gbps que está en modo nativo (es decir, no se utiliza un cable de arranque) puede conectarse a un puerto de 10 Gbps que está en modo nativo.
* Los ISL entre los switches MetroCluster IP y la red del cliente, así como los ISL entre los switches intermedios, siguen las mismas reglas en términos de velocidad.
* No es necesario que el número de ISL que se encuentre entre los switches de MetroCluster y los switches de red del cliente, ni el número de ISL que están entre los switches de red del cliente.
+
Por ejemplo, los switches MetroCluster pueden conectarse usando dos ISL a los switches intermedios y los switches intermedios se pueden conectar entre sí mediante 10 ISL.

* No es necesario que la velocidad de los ISL se encuentre entre los switches MetroCluster y los switches de red del cliente, así como la velocidad de los ISL que están entre los switches de red del cliente.
+
Por ejemplo, los switches MetroCluster pueden conectarse utilizando un ISL de 40 Gbps a los switches intermedios y los switches intermedios se pueden conectar entre sí utilizando ISL de 100 Gbps.

* El número y la velocidad de ISL que conectan cada switch MetroCluster al switch intermedio deben ser los mismos en ambos sitios de MetroCluster.




== Requisitos ISL en redes de capa 2 compartidas

Cuando link:../install-ip/concept_considerations_layer_2.html["Uso compartido del tráfico ISL en una red compartida"], Debe asegurarse de que tiene la capacidad adecuada y el tamaño de los ISLs apropiadamente. Una latencia baja es crucial para la replicación de datos entre los sitios MetroCluster. Los problemas de latencia en estas conexiones pueden afectar a las operaciones de I/o del cliente

Debe revisar estas secciones para calcular correctamente la capacidad completa necesaria de los ISL. La replicación continua en caché no volátil y del almacenamiento con baja latencia es crucial para las configuraciones de MetroCluster. La latencia de la red back-end afecta a la latencia y al rendimiento que ven las I/o del cliente.



=== Límites de latencia y pérdida de paquetes en los ISL

Deben cumplirse los siguientes requisitos para el tráfico de ida y vuelta entre los switches IP de MetroCluster en el sitio_A y el sitio_B, con la configuración de MetroCluster en estado de funcionamiento constante:

* Para obtener información específica sobre la latencia de los viajes completos y los requisitos de distancia máxima para su configuración, consulte link:https://hwu.netapp.com/["Hardware Universe."^]
+
A medida que aumenta la distancia entre dos sitios MetroCluster, la latencia aumenta, por lo general, dentro del rango de tiempo de retraso de ida y vuelta de 1 ms por 100 km (62 millas). Esta latencia también depende del acuerdo de nivel de servicio (SLA) de la red en términos de ancho de banda de los enlaces ISL, la tasa de caída de paquetes y la fluctuación de la red. Un ancho de banda bajo, una fluctuación elevada y caídas aleatorias de paquetes dan lugar a diferentes mecanismos de recuperación por parte de los conmutadores o el motor TCP en los módulos del controlador para que la entrega de paquetes sea correcta. Estos mecanismos de recuperación pueden aumentar la latencia general.

+
Cualquier dispositivo que contribuya a la latencia debe tenerse en cuenta.

* La pérdida de paquetes debe ser menor o igual al 0.01%.
+
La pérdida de paquetes incluye la pérdida física o la pérdida debido a la congestión o a la suscripción excesiva.

+
Las caídas de paquetes pueden provocar retransmisiones y una ventana de congestión reducida.

* El valor de fluctuación admitido es de 3 ms para ida y vuelta (o de 1.5 ms para una vía).
* La red debe asignar y mantener el SLA para el ancho de banda necesario para el tráfico de MetroCluster, lo que supone microráfagas y picos en el tráfico.
+
Un ancho de banda bajo puede provocar retrasos en la cola y caídas en los interruptores. Si utiliza ONTAP 9.7 o posterior, el intermediario de red entre los dos sitios debe proporcionar un ancho de banda mínimo de 4.5 Gbps para la configuración de MetroCluster.

* El tráfico de MetroCluster no debe consumir el ancho de banda completo y tener un impacto negativo en el tráfico que no sea de MetroCluster.
* La red compartida debe tener configurada la supervisión de red para supervisar los ISL en cuanto a uso, errores (caídas, solapas de enlace, daños, etc.) y fallos.




=== Límites de conexión y enlaces en los switches del cliente

Los switches intermedios proporcionados por el cliente deben cumplir los siguientes requisitos:

* El número de switches intermedios no se limita y se admiten más de dos switches entre los switches IP de MetroCluster.
+
Los interruptores MetroCluster IP deben estar situados lo más cerca posible de los interruptores intermedios que proporcionan el enlace de largo recorrido. Todas las conexiones ISL a lo largo de la ruta deben cumplir con todos los requisitos para MetroCluster ISL.

* Los ISL de la red del cliente (los ISL entre los switches del cliente) deben configurarse de manera que se proporcione suficiente ancho de banda y se mantenga el orden de entrega.
+
Esto se puede hacer mediante la conexión de enlaces de un número suficiente y la aplicación de políticas de equilibrio de carga para conservar el orden.





=== Otros requisitos de red

Los switches intermedios proporcionados por el cliente deben cumplir los siguientes requisitos:

* La red del cliente debe proporcionar las mismas VLAN entre los sitios que coinciden con las VLAN de MetroCluster establecidas en el archivo RCF.
+
Las VLAN de capa 2 con identificadores que coincidan con los identificadores de VLAN de MetroCluster deben abarcar la red compartida.

+
** En ONTAP 9.7 y versiones anteriores, los sistemas FAS2750 y AFF A220 requieren VLAN 10 y 20.
** En ONTAP 9.8 y posteriores, FAS2750, AFF A220, FAS500f, AFF A250 Los sistemas FAS8300, AFF A400 y FAS8700 usan VLAN 10 y 20 de manera predeterminada. Puede configurar otras VLAN durante la creación de interfaces y deben estar dentro del intervalo 101-4096. Para todas las plataformas mencionadas anteriormente, solo puede especificar la VLAN durante la creación de la interfaz. Una vez creadas las interfaces MetroCluster, no se puede cambiar el ID de VLAN. Para el resto de plataformas no mencionadas anteriormente, puede utilizar cualquier VLAN y puede cambiar el identificador de VLAN para esas plataformas en cualquier momento, pero es necesario crear y aplicar un nuevo archivo RCF.




--
[NOTE]
====
El RcfFileGenerator no permite la creación de un archivo RCF mediante VLAN que no son compatibles con la plataforma.

El RcfFileGenerator podría restringir el uso de ciertos identificadores de VLAN (por ejemplo, si están destinados a su uso futuro). Por lo general, las VLAN reservadas son de hasta 100, incluidas.

====
--
* El tamaño de MTU debe establecerse en 9216 en todos los dispositivos de la red completa.
* No se puede configurar ningún otro tráfico con una prioridad superior a la clase de servicio (COS) cinco.
* ECN (notificación de congestión explícita) debe configurarse en todas las rutas de extremo a extremo.




=== Los requisitos de cableado cuando se usan ISL compartidos

[role="lead"]
Cuando se usan ISL compartidos en una configuración de IP de MetroCluster, debe tener en cuenta los requisitos del ISL de MetroCluster extremo a extremo que se ejecuta desde los puertos de la controladora del sitio A a a los puertos de la controladora del sitio B.


NOTE: Debe seguir el <<Requisitos básicos de ISL de MetroCluster>>.



=== Número de ISL y cables de arranque en la red compartida

El número de ISL que conectan los switches IP de MetroCluster a la red compartida varía en función del modelo del switch y el tipo de puerto.

|===


| Modelo de switch MetroCluster IP | Tipo de puerto | Número de ISLs 


 a| 
Switches BES-53248 compatibles con Broadcom
 a| 
Puertos nativos
 a| 
4 ISL con 10 o 25 puertos Gbps



 a| 
Cisco 3132Q-V
 a| 
Puertos nativos
 a| 
6 ISL con puertos de 40 Gbps



 a| 
Cisco 3132Q-V
 a| 
Cables de desconexión
 a| 
16 ISL de 10 Gbps



 a| 
Cisco 3232C
 a| 
Puertos nativos
 a| 
6 ISL con 40 o 100 puertos Gbps



 a| 
Cisco 3232C
 a| 
Cables de desconexión
 a| 
16 ISL de 10 Gbps



 a| 
Cisco 9336C-FX2 (sin conexión de bandejas NS224)
 a| 
Puertos nativos
 a| 
6 ISL con 40 o 100 Gbps



 a| 
Cisco 9336C-FX2 (sin conexión de bandejas NS224)
 a| 
Cables de desconexión
 a| 
16 ISL con 10 Gbps



 a| 
Cisco 9336C-FX2 (conexión de bandejas NS224)
 a| 
Puertos nativos (2)
 a| 
4 ISL con 40 o 100 Gbps



 a| 
Cisco 9336C-FX2 (conexión de bandejas NS224)
 a| 
Cables de arranque (2)
 a| 
16 ISL con 10 Gbps

|===
* El uso de 40 o 100 puertos ISL en el switch BES-53248 requiere una licencia adicional.
* Al crear los archivos RCF para un Cisco 9336C-FX2 (que conecta las bandejas NS224), debe elegir configurar el ISL en modo de arranque *o* nativo.
* Los switches Cisco admiten el uso de cables de arranque (un puerto físico se usa como 4 puertos de 10 Gbps).
* Los archivos RCF para los conmutadores IP tienen configurados puertos en modo nativo y de arranque.
+
No se admite una combinación de puertos ISL en el modo de velocidad de puerto nativo y modo de arranque. Todos los ISL, desde los switches IP de MetroCluster a los switches intermedios de una red, deben tener la misma velocidad y longitud.

* Se admite el uso de dispositivos de cifrado externos (por ejemplo, cifrado de enlace externo o cifrado proporcionado a través de dispositivos WDM) siempre que la latencia de ida y vuelta se mantenga dentro de los requisitos anteriores.


Para lograr un rendimiento óptimo, debe utilizar al menos 1 x 40 Gbps o varios ISL de 10 Gbps por red. No se recomienda usar un único ISL de 10 Gbps por red para los sistemas AFF A800.

El rendimiento teórico máximo de los ISL compartidos (por ejemplo, 240 Gbps con seis ISL de 40 Gbps) es el mejor caso posible. Cuando se usan varios ISL, el equilibrio de carga estadístico puede afectar el rendimiento máximo. Se puede producir un equilibrio desigual y reducir el rendimiento a un único ISL.

Si la configuración utiliza VLAN L2, deben abarcar de forma nativa los sitios. No se admite la superposición de VLAN como la LAN extensible virtual (VXLAN).

Los ISL que transportan tráfico de MetroCluster deben ser enlaces nativos entre los switches. No se admiten servicios de uso compartido de enlaces como enlaces de conmutación de etiquetas multiprotocolo (MPLS).



=== Compatibilidad con ISL WAN en el switch BES-53248 de Broadcom

* Número mínimo de ISL de WAN por estructura: 1 (10 GbE, o 25 GbE, o 40 GbE, o 100 GbE)
* El número máximo de ISL WAN de 10 GbE por estructura: 4
* El número máximo de ISL WAN de 25 GbE por estructura: 4
* Número máximo de ISL WAN de 40 GbE por estructura: 2
* Número máximo de ISL WAN de 100 GbE por estructura: 2


Un ISL WAN de 40 GbE o 100 GbE requiere un archivo RCF, versión 1.40 o superior.


NOTE: Se requieren licencias adicionales para puertos adicionales.
