---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: Si la configuración incluye agregados no reflejados, debe tener en cuenta los posibles problemas de acceso tras las operaciones de conmutación. 
---
= Obtenga información sobre los agregados no reflejados en las configuraciones de IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la configuración incluye agregados no reflejados, debe tener en cuenta los posibles problemas de acceso tras las operaciones de conmutación.



== Agregados no reflejados y espacios de nombres jerárquicos

Si utiliza espacios de nombres jerárquicos, debe configurar la ruta de unión de modo que todos los volúmenes de esa ruta estén en agregados reflejados o solo en agregados no reflejados. La configuración de una combinación de agregados no reflejados y reflejados en la ruta de unión puede impedir el acceso a los agregados no reflejados después de la operación de conmutación.



== Agregados sin espejo y mantenimiento que requiere corte de energía

Si realiza una conmutación negociada para mantenimiento que requiere un apagado de energía en todo el sitio, primero debe desconectar manualmente todos los agregados no reflejados que sean propiedad del sitio del desastre.

Si no se desconectan los agregados no replicados del sitio del desastre, los nodos del sitio superviviente podrían dejar de funcionar debido a pánicos de múltiples discos. Esto puede ocurrir si los agregados no replicados conmutados se desconectan o se pierden debido a la pérdida de conectividad con el almacenamiento del sitio del desastre si se produce un corte de energía o una pérdida de ISL.



== Agregados no reflejados, volúmenes de metadatos CRS y volúmenes raíz de SVM de datos

El volumen de metadatos del servicio de replicación de configuración (CRS) y los volúmenes raíz de la SVM de datos deben estar en un agregado reflejado. No se pueden mover estos volúmenes a un agregado no reflejado. Si se encuentran en un agregado no reflejado, las operaciones de cambio y retroceso negociadas se vetan y  `metrocluster check` El comando devuelve una advertencia.



== Agregados no reflejados y SVM

Debe configurar las SVM solo en agregados reflejados o no reflejados. Configurar las SVM en una combinación de agregados reflejados y no reflejados puede resultar en una operación de conmutación que supere los 120 segundos. Esto puede provocar una interrupción de los datos si los agregados no reflejados no se conectan.



== Agregados no reflejados y SAN

Antes de ONTAP 9.9.1, un LUN no debía ubicarse en un agregado no reflejado. Configurar un LUN en un agregado no reflejado puede provocar una operación de conmutación por encima de 120 segundos y una interrupción del servicio de los datos.



== Agregue estantes de almacenamiento para agregados sin espejo

Si agrega estantes y desea usarlos para agregados no reflejados en una configuración de IP de MetroCluster , debe hacer lo siguiente:

. Antes de iniciar el procedimiento para añadir las bandejas, emita el siguiente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Compruebe que la asignación automática de discos está desactivada:
+
`disk option show`

. Siga los pasos del procedimiento para añadir la bandeja.
. Asigne manualmente todos los discos de la bandeja nueva al nodo que posea el agregado o los agregados no reflejados.
. Cree los agregados:
+
`storage aggregate create`

. Tras completar el procedimiento, ejecute el siguiente comando:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Compruebe que la asignación automática de discos está habilitada:
+
`disk option show`


