---
sidebar: sidebar 
permalink: install-ip/configure-mcc-site-system-manager.html 
keywords: metrocluster, configuration, config, mcc, HA, cluster 
summary: A partir de ONTAP 9.8, puede gestionar las operaciones de configuración de IP de MetroCluster con System Manager. Esto implica la configuración, la conexión y la configuración de dos clústeres. 
---
= Configurar un sitio IP de MetroCluster con ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.8, puede gestionar las operaciones de configuración de IP de MetroCluster con System Manager. Esto implica configurar dos clústeres, realizar relaciones de paridad de clústeres y configurar los clústeres.

.Antes de empezar
Realice los siguientes procedimientos:

* link:set-up-mcc-site-system-manager.html["Configurar un sitio IP de MetroCluster"]
* link:set-up-mcc-peering-system-manager.html["Configure las relaciones entre iguales de IP de MetroCluster"]




== Configure la conexión entre clústeres

.Pasos
. Inicie sesión en System Manager en uno de los sitios y seleccione *Panel*.
+
En la sección *MetroCluster*, el gráfico muestra los dos clústeres que ha configurado y tiene una relación entre iguales para los sitios MetroCluster. El clúster del que está trabajando desde (clúster local) se muestra a la izquierda.

. Haga clic en *Configurar MetroCluster*. Desde esta ventana, realice los siguientes pasos:
+
.. Se muestran los nodos para cada clúster en la configuración de MetroCluster. Use las listas desplegables para seleccionar los nodos del clúster local que serán partners de recuperación de desastres con los nodos del clúster remoto.
.. Haga clic en la casilla de verificación si desea configurar ONTAP Mediator. Consulte link:./task-sm-mediator.html["Configurar el mediador de ONTAP"].
.. Si ambos clústeres tienen una licencia para habilitar el cifrado, se muestra la sección *cifrado*.
+
Para habilitar el cifrado, introduzca una frase de contraseña.

.. Haga clic en la casilla de comprobación si desea configurar MetroCluster con una red de capa 3 compartida.
+

NOTE: Los nodos asociados de alta disponibilidad y los switches de red que se conectan a los nodos deben tener una configuración coincidente.



. Haga clic en *Guardar* para configurar los sitios MetroCluster.
+
En la sección *Tablero*, en la sección *MetroCluster*, el gráfico muestra una Marca de verificación en el enlace entre los dos grupos, lo que indica una conexión en buen estado.


