---
permalink: install-ip/switch-move-cluster-lifs.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 'Al actualizar el firmware del conmutador o el archivo de configuración de referencia (RCF), mueves las LIF del clúster al conmutador asociado para permitir operaciones del clúster sin interrupciones durante la actualización.' 
---
= Mueve los LIF del clúster antes de sustituir un conmutador IP de MetroCluster, cambiar el RCF o actualizar el firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando reemplazas un switch IP de MetroCluster o cambias el firmware del switch o el archivo de configuración de referencia (RCF), necesitas mover las LIF del clúster al switch asociado para permitir operaciones del clúster sin interrupciones.

.Acerca de esta tarea
* Debes realizar esta tarea antes de actualizar o revertir el firmware del switch, reemplazar el RCF del switch o reemplazar un switch IP.
+

NOTE: Si estás configurando los conmutadores por primera vez, puedes saltarte esta tarea a menos que estés realizando un reemplazo de conmutador.

* La tarea requiere que utilices tanto comandos de ONTAP como comandos del conmutador; se usan los comandos de ONTAP a menos que se indique lo contrario.
* En los ejemplos que se utilizan en este procedimiento, vas a actualizar el conmutador IP_switch_A_1, así que necesitas migrar las LIF del clúster al conmutador IP_switch_A_2.
* Los ejemplos de resultados de los comandos que aparecen en este procedimiento muestran los detalles de un conmutador Cisco. Los resultados pueden variar en función del modelo y el fabricante del conmutador.


.Pasos
. Muestra los puertos del clúster que están conectados a los switches del clúster en cada nodo:
+
`network device-discovery show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node_A_2/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/18      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/18      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/2       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/2       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/10      N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/10      N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/5       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/6       N9K-C9372PX
node_A_2/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:02)
                                             Eth121/1/1        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:a0)
                                             Ethernet1/18      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:48)
                                             Ethernet1/18      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:28)
                                             Ethernet1/10      -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:80)
                                             Ethernet1/10      -
            e9a    local_network_switch (88:f0:31:86:fe:a8)
                                             Ethernet1/5       -
            e9b    local_network_switch (88:f0:31:86:fe:a9)
                                             Ethernet1/6       -
node_A_1/cdp
            e10b   IP_switch_A_2
                                             Ethernet1/17      N9K-C9336C-FX2
            e2a    IP_switch_A_1
                                             Ethernet1/17      N9K-C9336C-FX2
            e4a    IP_switch_A_1
                                             Ethernet1/1       N9K-C9336C-FX2
            e4b    IP_switch_A_2
                                             Ethernet1/1       N9K-C9336C-FX2
            e5b    IP_switch_A_1
                                             Ethernet1/9       N9K-C9336C-FX2
            e7b    IP_switch_A_2
                                             Ethernet1/9       N9K-C9336C-FX2
            e9a    local_network_switch
                                             Ethernet1/3       N9K-C9372PX
            e9b    local_network_switch
                                             Ethernet1/4       N9K-C9372PX
node_A_1/lldp
            e0M    mgmt_switch (00:08:2f:16:8e:03)
                                             Eth121/1/2        -
            e10b   IP_switch_A_2 (cc:90:70:e8:73:9c)
                                             Ethernet1/17      -
            e2a    IP_switch_A_1 (cc:90:70:e8:50:44)
                                             Ethernet1/17      -
            e5b    IP_switch_A_1 (cc:90:70:e8:50:24)
                                             Ethernet1/9       -
            e7b    IP_switch_A_2 (cc:90:70:e8:73:7c)
                                             Ethernet1/9       -
            e9a    local_network_switch (88:f0:31:86:fe:a6)
                                             Ethernet1/3       -
            e9b    local_network_switch (88:f0:31:86:fe:a7)
                                             Ethernet1/4       -
30 entries were displayed.
----
====
. Comprueba el estado administrativo y operativo de cada puerto del clúster.
+
.. Comprueba que todos los puertos del clúster estén activos y en buen estado:
+
`network port show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network port show -role cluster

Node: node_A_1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false

Node: node_A_2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/40000 healthy  false
4 entries were displayed.
----
====
.. Comprueba que todas las interfaces del clúster (LIF) estén en el puerto principal:
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.

cluster_A::*>
----
====
.. Comprueba que el clúster muestre información de ambos conmutadores del clúster:
+
`system switch ethernet show -is-monitoring-enabled-operational true`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> system switch ethernet show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
IP_switch_A_1               cluster-network    10.231.7.251     N9K-C9336C-FX2
     Serial Number: FDO26020KLJ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

IP_switch_A_2               cluster-network    10.231.7.252     N9K-C9336C-FX2
     Serial Number: FDO26020KGL
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(4)
    Version Source: CDP/ISDP

2 entries were displayed.

cluster_A::*>
----
====


. Desactiva la reversión automática en las LIF del clúster. Las LIF del clúster se transfieren al conmutador del clúster asociado y permanecen allí mientras realizas el procedimiento de actualización en el conmutador de destino:
+

NOTE: Si vas a actualizar la segunda estructura, puedes saltarte este paso y pasar directamente a <<shut-down-ports,Paso 4>>.

+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert false

Warning: Disabling the auto-revert feature of the cluster logical interface may
         effect the availability of your cluster network. Are you sure you want
         to continue? {y|n}: y

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.
----
====
. [[shut-down-ports]]En el conmutador de clúster IP_switch_A1, desactiva los puertos conectados a los puertos de clúster de los nodos.
+
[role="tabbed-block"]
====
.Cisco
--
[listing]
----
IP_switch_A_1(config)# sh int eth1/1,eth1/2 brief

--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch
#
--------------------------------------------------------------------------------
Eth1/1          101     eth  access up      none                      40G(D) --
Eth1/2          101     eth  access up      none                      40G(D) --
IP_switch_A_1(config)#
IP_switch_A_1(config)# int eth1/1,eth1/2
IP_switch_A_1(config-if-range)# shut
IP_switch_A_1(config-if-range)#
----
--
.Broadcom
--
[listing]
----
IP_switch_A1(config)# interface eth1/1/1-2,eth1/7-8
IP_switch_A1(config-if-range)# shutdown
----
--
.NVIDIA
--
.. Muestra las interfaces del clúster:
+
[listing]
----
cumulus@IP_switch_A_1:mgmt:~$ nv show interface
Interface    Admin Status  Oper Status  Speed  MTU    Type      Remote Host     Remote Port  Summary
-----------  ------------  -----------  -----  -----  --------  --------------  -----------  ---------
swp1         up            up           100G   9216   swp       cluster1         e1a
----
.. Desactiva el puerto de la interfaz del clúster:
+
[listing]
----
sudo python3 <RCF_name> runCmd swp1 state down
----


--
====
. [[verify_cluster_lif_migration]] Verifica que las LIF del clúster se hayan migrado a los puertos alojados en el conmutador del clúster IP_switch_A2. Esto puede tardar unos segundos.
+
`network interface show -role cluster`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      101.101.101.88/18  node_A_1      e4b     false
            node_A_1_clus2 up/up      101.101.101.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      101.101.101.96/18  node_A_2      e4b     false
            node_A_2_clus2 up/up      101.101.101.97/18  node_A_2      e4b     true
4 entries were displayed.
----
====
. Compruebe que el clúster esté en buen estado:
+
`cluster show`

+
.Mostrar ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster_A::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node_A_1             true    true          false
node_A_2             true    true          false
2 entries were displayed.
----
====


.Después de terminar
Después de que los LIF del clúster se hayan movido al conmutador asociado, puedes seguir los procedimientos de configuración estándar según tu proveedor de conmutadores para completar la actualización al firmware o a la versión de RCF de destino:

* link:../install-ip/task_switch_config_broadcom.html["Configure los switches IP de Broadcom"]
* link:../install-ip/task_switch_config_cisco.html["Configure los switches IP de Cisco"]
* link:../install-ip/task_switch_config_nvidia.html["Configure los switches NVIDIA IP"]



NOTE: Después de configurar los switches en la primera estructura, debes repetir los pasos para mover los LIF del clúster en la segunda estructura.
