---
permalink: install-ip/task_sw_config_verify_haconfig.html 
sidebar: sidebar 
keywords: metrocluster, ha-config, mccip, haconfig, verify, high-availability 
summary: En una configuración IP de MetroCluster que no está preconfigurada de fábrica, debe comprobar que el estado ha-config de la controladora y los componentes del chasis está establecido en mccip para que se inicien correctamente. Para los sistemas recibidos de fábrica, este valor está preconfigurado y no es necesario verificarlo. 
---
= Verificación del estado de los componentes de la configuración de alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En una configuración IP de MetroCluster, debe verificar que el estado HA-config de los componentes del controlador y del chasis esté configurado en “mccip” para que se inicien correctamente. Aunque este valor debe preconfigurarse en los sistemas recibidos de fábrica, debe verificar el ajuste antes de continuar.

[CAUTION]
====
Si el estado de alta disponibilidad del módulo de la controladora y el chasis es incorrecto, no se puede configurar MetroCluster sin volver a inicializar el nodo. Debe corregir la configuración mediante este procedimiento y, a continuación, inicializar el sistema mediante uno de los siguientes procedimientos:

* En una configuración IP de MetroCluster, siga los pasos descritos en link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_restore_defaults.html["Restaurar los valores predeterminados del sistema en un módulo de controlador"].
* En una configuración de MetroCluster FC, siga los pasos que se indican en link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#restoring-system-defaults-and-configuring-the-hba-type-on-a-controller-module["Restaure los valores predeterminados del sistema y configure el tipo de HBA en un módulo de controlador"].


====
.Antes de empezar
Compruebe que el sistema está en modo de mantenimiento.

.Pasos
. En el modo de mantenimiento, muestre el estado de alta disponibilidad del módulo de controladora y el chasis:
+
`ha-config show`

+
El estado de alta disponibilidad correcto depende de la configuración de la MetroCluster.

+
|===


| Tipo de configuración de MetroCluster | Estado de ALTA DISPONIBILIDAD para todos los componentes... 


 a| 
Configuración FC MetroCluster de ocho o cuatro nodos
 a| 
mcc



 a| 
Configuración MetroCluster FC de dos nodos
 a| 
mcc-2n



 a| 
Configuración IP de MetroCluster de ocho o cuatro nodos
 a| 
mccip

|===
. Si el estado del sistema que se muestra en la controladora no es correcto, establezca el estado de alta disponibilidad correcto para su configuración en el módulo de controladora:
+
|===


| Tipo de configuración de MetroCluster | Comando 


 a| 
Configuración FC MetroCluster de ocho o cuatro nodos
 a| 
`ha-config modify controller mcc`



 a| 
Configuración MetroCluster FC de dos nodos
 a| 
`ha-config modify controller mcc-2n`



 a| 
Configuración IP de MetroCluster de ocho o cuatro nodos
 a| 
`ha-config modify controller mccip`

|===
. Si el estado del sistema que se muestra del chasis no es correcto, establezca el estado de alta disponibilidad correcto para su configuración en el chasis:
+
|===


| Tipo de configuración de MetroCluster | Comando 


 a| 
Configuración FC MetroCluster de ocho o cuatro nodos
 a| 
`ha-config modify chassis mcc`



 a| 
Configuración MetroCluster FC de dos nodos
 a| 
`ha-config modify chassis mcc-2n`



 a| 
Configuración IP de MetroCluster de ocho o cuatro nodos
 a| 
`ha-config modify chassis mccip`

|===
. Arrancar el nodo en ONTAP:
+
`boot_ontap`

. Repita todo este procedimiento para comprobar el estado HA en cada nodo de la configuración MetroCluster.

