---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: El servicio Mediator de ONTAP debe estar configurado en el nodo ONTAP para utilizarlo en una configuración IP de MetroCluster. 
---
= Configure el servicio Mediador ONTAP desde una configuración IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servicio Mediator de ONTAP debe estar configurado en el nodo ONTAP para utilizarlo en una configuración IP de MetroCluster.

.Antes de empezar
* El Mediador ONTAP debe haberse instalado correctamente en una ubicación de red a la que puedan acceder ambos sitios MetroCluster.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Instale o actualice el servicio Mediator de ONTAP"^]

* Debe tener la dirección IP del host que ejecuta el servicio Mediator de ONTAP.
* Debe tener el nombre de usuario y la contraseña del servicio Mediador de ONTAP.
* Todos los nodos de la configuración IP de MetroCluster deben estar en línea.



CAUTION: A partir de ONTAP 9.12.1, es posible habilitar la función de conmutación automática de sitios forzada MetroCluster en una configuración de IP de MetroCluster. Esta característica es una extensión de la conmutación no planificada asistida por Mediator. Antes de habilitar esta función, revise link:concept-risks-limitations-automatic-switchover.html["Riesgos y limitaciones del uso de conmutación forzada automática de MetroCluster"].

.Acerca de esta tarea
* Esta tarea habilita la conmutación automática no planificada de forma predeterminada.
* Esta tarea se puede realizar en la interfaz de ONTAP de cualquier nodo, en la configuración de IP de MetroCluster.
* Una única instalación del servicio Mediator de ONTAP se puede configurar con hasta cinco configuraciones IP de MetroCluster.


.Pasos
. Añada el servicio Mediator de ONTAP a ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address _ip-address-of-mediator-host_`

+

NOTE: Se le pedirá el nombre de usuario y la contraseña de la cuenta de usuario administrador de Mediator.

. Compruebe que la función de conmutación automática está activada:
+
`metrocluster show`

. Compruebe que el Mediator se está ejecutando.
+
.. Mostrar los discos virtuales de Mediator:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. Configure el modo de privilegio en Advanced:
+
`set advanced`

+
....
 cluster_A::> set advanced
....
.. Mostrar los iniciadores etiquetados como mediador:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. Verifique el estado del dominio de fallo de cambio no planificado automático (AUSO):
+
`metrocluster show`

+

NOTE: El resultado de ejemplo siguiente se aplica a ONTAP 9.13.1 y posteriores. Para ONTAP 9.12.1 y versiones anteriores, el estado de dominio de fallo de AUSO debe ser `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. Opcionalmente, configure el cambio forzado automático de MetroCluster.
+
Solo puede utilizar el siguiente comando en el nivel de privilegios avanzado.

+

IMPORTANT: Antes de usar este comando, revise el link:concept-risks-limitations-automatic-switchover.html["Riesgos y limitaciones del uso de conmutación forzada automática de MetroCluster"].

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

