---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Puede eliminar el mediador ONTAP de la configuración de IP de MetroCluster. 
---
= Eliminar el mediador de ONTAP de una configuración de IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desconfigurar ONTAP Mediator desde la configuración de IP de MetroCluster.

.Antes de empezar
Debe haber instalado y configurado exitosamente ONTAP Mediator en una ubicación de red a la que puedan acceder ambos sitios de MetroCluster.

.Pasos
. Desconfigure ONTAP Mediator mediante el siguiente comando:
+
`metrocluster configuration-settings mediator remove`

+
Se le pedirá el nombre de usuario y la contraseña de la cuenta de usuario administrador de ONTAP Mediator.

+

NOTE: Si el Mediador ONTAP no funciona, el  `metrocluster configuration-settings mediator remove` El comando aún le solicita que ingrese el nombre de usuario y la contraseña para la cuenta de usuario administrador de ONTAP Mediator y elimina ONTAP Mediator de la configuración de MetroCluster.

+
.. Compruebe si hay discos rotos utilizando el siguiente comando:
+
`disk show -broken`

+
*ejemplo*

+
....
There are no entries matching your query.
....


. Si estás usando un ONTAP Mediator que utiliza HTTPS para la comunicación, elimina los certificados de CA después de quitar el ONTAP Mediator:
+
.. Muestra los certificados CA instalados:
+
`security certificate show -common-name ONTAPMediatorCA`

.. Elimina los certificados raíz e intermedios instalados:
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. Confirma que ONTAP Mediator se ha eliminado de la configuración de MetroCluster ejecutando el siguiente comando en ambos clusters:
+
.. `metrocluster configuration-settings mediator show`
+
*ejemplo*

+
[listing]
----
This table is currently empty.
----



