---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Puede eliminar el mediador ONTAP de la configuración de IP de MetroCluster. 
---
= Desconfigurar ONTAP Mediator de la configuración de IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desconfigurar ONTAP Mediator desde la configuración de IP de MetroCluster.

.Antes de empezar
Debe haber instalado y configurado exitosamente ONTAP Mediator en una ubicación de red a la que puedan acceder ambos sitios de MetroCluster.

.Pasos
. Desconfigure ONTAP Mediator mediante el siguiente comando:
+
`metrocluster configuration-settings mediator remove`

+
Se le pedirá el nombre de usuario y la contraseña de la cuenta de usuario administrador de ONTAP Mediator.

+

NOTE: Si el Mediador ONTAP no funciona, el  `metrocluster configuration-settings mediator remove` El comando aún le solicita que ingrese el nombre de usuario y la contraseña para la cuenta de usuario administrador de ONTAP Mediator y elimina ONTAP Mediator de la configuración de MetroCluster.

+
.. Compruebe si hay discos rotos utilizando el siguiente comando:
+
`disk show -broken`

+
*ejemplo*

+
....
There are no entries matching your query.
....


. Confirme que ONTAP Mediator se haya eliminado de la configuración de MetroCluster ejecutando los siguientes comandos en ambos clústeres:
+
.. `metrocluster configuration-settings mediator show`
+
*ejemplo*

+
[listing]
----
This table is currently empty.
----
.. `storage iscsi-initiator show -label mediator`
+
*ejemplo*

+
[listing]
----
There are no entries matching your query.
----



