---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: Puede configurar los conmutadores IP para que utilicen SNMPv3 para la supervisión del estado. 
---
= Configure los conmutadores IP de MetroCluster para la supervisión del estado
:allow-uri-read: 


[role="lead"]
En las configuraciones IP de MetroCluster, puede configurar SNMPv3 para supervisar el estado de los switches IP.



== Paso 1: Configure el usuario SNMPv3 en los conmutadores IP de MetroCluster

Siga estos pasos para configurar el usuario SNMPv3 en los conmutadores IP de MetroCluster.


IMPORTANT: Se deben usar los protocolos de autenticación y de privacidad en los comandos. No se admite el uso de autenticación sin privacidad.

[role="tabbed-block"]
====
.Para switches IP Broadcom
--
.Pasos
. Si el grupo de usuarios 'network-admin' no existe, créelo:
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. Confirme que se ha creado el grupo 'network-admin':
+
`(IP_switch_1) (Config)# show snmp group`

. Configure el usuario SNMPv3 en los conmutadores IP de Broadcom:
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin auth-sha priv-aes128
----
+
Introduzca la contraseña de autenticación cuando se le solicite.

+
[listing]
----
#snmp-server user admin1 network-admin auth-sha priv-aes128

Enter Authentication Password:
----


--
.Para switches IP Cisco
--
.Pasos
. Ejecute los siguientes comandos para configurar el usuario SNMPv3 en un conmutador IP de Cisco:
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. Compruebe que el usuario SNMPv3 está configurado en el conmutador:
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
El siguiente ejemplo muestra que el usuario `admin` Está configurado para SNMPv3:

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== Paso 2: Configure el usuario SNMPv3 en ONTAP

Siga estos pasos para configurar el usuario SNMPv3 en ONTAP.

. Configure el usuario SNMPv3 en ONTAP:
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. Configure la supervisión del estado del switch para supervisar el switch utilizando el nuevo usuario SNMPv3:
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. Compruebe que el número de serie del dispositivo que se supervisará con el usuario SNMPv3 recién creado es correcto:
+
.. Muestra el periodo de tiempo de sondeo de monitorización del estado del switch:
+
`system switch ethernet polling-interval show`

.. Ejecute el siguiente comando una vez que haya transcurrido el tiempo de sondeo:
+
`system switch ethernet show-all -instance -device <device_serial_number>`




