---
permalink: install-ip/task-configure-end-to-end-encryption.html 
sidebar: sidebar 
keywords: metrocluster, ip, encryption, end-to-end, backend, aff a400, fas8300, fas8700, encrypt, enable, disable 
summary:  
---
= Configurar el cifrado integral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.15.1, puede configurar el cifrado integral para cifrar el tráfico de back-end, como NVlog y los datos de replicación de almacenamiento, entre los sitios en una configuración de IP de MetroCluster.

.Acerca de esta tarea
* Para realizar esta tarea, debe ser un administrador de clústeres.
* Para poder configurar el cifrado integral, se debe link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-concept.html["Configure la gestión de claves externas"^].
* Revise los sistemas compatibles y la versión mínima de ONTAP requerida para configurar el cifrado integral en una configuración de IP de MetroCluster:
+
|===


| Versión de ONTAP mínima | Sistemas compatibles 


 a| 
ONTAP 9.15.1
 a| 
** AFF A400
** FAS8300
** FAS8700


|===




== Habilite el cifrado integral

Realice los siguientes pasos para habilitar el cifrado de extremo a extremo.

.Pasos
. Compruebe el estado de la configuración de MetroCluster.
+
.. Compruebe que los componentes de MetroCluster están en buen estado:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run
----
+
La operación se ejecuta en segundo plano.

.. Después del `metrocluster check run` la operación finaliza, ejecute:
+
[source, cli]
----
metrocluster check show
----
+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. Comprobar el estado de la operación de comprobación de MetroCluster en ejecución:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Compruebe que no hay alertas de estado:
+
[source, cli]
----
system health alert show
----


. Compruebe que la gestión de claves externas está configurada en ambos clústeres:
+
[source, cli]
----
security key-manager external show-status
----
. Habilite el cifrado integral para cada grupo de recuperación ante desastres:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled true -dr-group-id <dr_group_id>
----
+
*ejemplo*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled true -dr-group-id 1
Warning: Enabling encryption for a DR Group will secure NVLog and Storage
         replication data sent between MetroCluster nodes and have an impact on
         performance. Do you want to continue? {y|n}: y
[Job 244] Job succeeded: Modify is successful.
----
+
Repita este paso con cada grupo de recuperación ante desastres de la configuración.

. Verifique que el cifrado integral está activado:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*ejemplo*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          true
1           cluster_A  node_A_2  configured          true
1           cluster_B  node_B_1  configured          true
1           cluster_B  node_B_2  configured          true
4 entries were displayed.
----




== Deshabilite el cifrado integral

Realice los siguientes pasos para desactivar el cifrado de extremo a extremo.

.Pasos
. Compruebe el estado de la configuración de MetroCluster.
+
.. Compruebe que los componentes de MetroCluster están en buen estado:
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run

----
+
La operación se ejecuta en segundo plano.

.. Después del `metrocluster check run` la operación finaliza, ejecute:
+
[source, cli]
----
metrocluster check show
----
+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. Comprobar el estado de la operación de comprobación de MetroCluster en ejecución:
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. Compruebe que no hay alertas de estado:
+
[source, cli]
----
system health alert show
----


. Compruebe que la gestión de claves externas está configurada en ambos clústeres:
+
[source, cli]
----
security key-manager external show-status
----
. Deshabilite el cifrado integral en cada grupo de recuperación ante desastres:
+
[source, cli]
----
metrocluster modify -is-encryption-enabled false -dr-group-id <dr_group_id>
----
+
*ejemplo*

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled false -dr-group-id 1
[Job 244] Job succeeded: Modify is successful.
----
+
Repita este paso con cada grupo de recuperación ante desastres de la configuración.

. Verifique que el cifrado integral está desactivado:
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
*ejemplo*

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          false
1           cluster_A  node_A_2  configured          false
1           cluster_B  node_B_1  configured          false
1           cluster_B  node_B_2  configured          false
4 entries were displayed.
----

