---
permalink: install-ip/task-configure-log-collection-mccip.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, log, collection, snmp, debugging 
summary: Puede configurar los conmutadores IP para que utilicen SNMPv3 para la supervisión del estado. 
---
= Configurar la recopilación de registros en un conmutador IP de MetroCluster
:allow-uri-read: 


[role="lead"]
En una configuración de IP de MetroCluster, puede configurar la recopilación de registros para recopilar registros de conmutadores con fines de depuración.


CAUTION: En los switches Broadcom y Cisco, se requiere un nuevo usuario para cada clúster con recopilación de registros. Por ejemplo, MetroCluster 1, MetroCluster 2, MetroCluster 3 y MetroCluster 4 requieren la configuración de un usuario independiente en los switches. No se admiten varias claves SSH para el mismo usuario.

.Antes de empezar
* Si utilizas el modo FIPS, realiza lo siguiente antes de configurar la recopilación de registros:
+
.. Vuelva a generar las claves SSH en el switch siguiendo las instrucciones del proveedor.
.. Regenera las claves SSH en ONTAP usando `debug system regenerate-systemshell-key-pair`.
.. Vuelve a ejecutar la configuración de la recopilación de registros usando el comando  `system switch ethernet log setup-password`.


* Debes tener acceso a los comandos del switch `show`. Si no lo tienes, crea un nuevo usuario del switch y otórgale los privilegios necesarios.
* Es necesario habilitar el control del estado del switch. Verifica que el campo  `Is Monitored:` esté establecido en *true* en la salida de  `system switch ethernet show`.
* Para la recopilación de registros con switches Broadcom y Cisco:
+
** El usuario local debe tener privilegios de administrador de red.
** Crea un nuevo usuario de conmutador para cada clúster con la recopilación de registros habilitada. Estos conmutadores no admiten varias claves SSH para el mismo usuario, si vuelves a ejecutar la configuración se sobrescribirá la clave SSH existente.


* Para la recopilación de registros de soporte con los switches de NVIDIA, el usuario encargado de la recopilación de registros debe poder ejecutar el comando  `cl-support` sin contraseña. Para permitir esto, ejecuta:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`



.Pasos
Sigue los pasos para tu versión de ONTAP para configurar la recopilación de registros, habilitar la recopilación periódica de datos y, opcionalmente, solicitar registros de soporte bajo demanda.

[role="tabbed-block"]
====
.ONTAP 9.15.1 y versiones posteriores
--
. Para configurar la recopilación de registros, ejecute el siguiente comando para cada conmutador. Se le pedirá que introduzca el nombre del switch, el nombre de usuario y la contraseña para la recopilación de registros.
+
*NOTA:* Si responde *y* a la solicitud de especificación del usuario, asegúrese de que el usuario tenga los permisos necesarios como se describe en <<Antes de empezar>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, cree el usuario *cumulus* y responda *y* al siguiente mensaje: ¿Desea especificar un usuario distinto de admin para la recopilación de registros? {y|n}: *y*

. [[paso 2]]Habilitar la recopilación periódica de registros:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Solicitar recogida de registros de soporte:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Para ver todos los detalles de la recogida de registros, incluida la habilitación, el mensaje de estado, la marca de hora y el nombre de archivo anteriores de la recogida periódica, el estado de la solicitud, el mensaje de estado, y la marca de hora y el nombre de archivo anteriores de la recogida de soporte, utilice lo siguiente:
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 y anteriores
--
. Para configurar la recopilación de registros, ejecute el siguiente comando para cada conmutador. Se le pedirá que introduzca el nombre del switch, el nombre de usuario y la contraseña para la recopilación de registros.
+
*NOTA:* Si responde `y` a la solicitud de especificación del usuario, asegúrese de que el usuario tiene los permisos necesarios como se describe en <<Antes de empezar>>.

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, cree el usuario *cumulus* y responda *y* al siguiente mensaje: ¿Desea especificar un usuario distinto de admin para la recopilación de registros? {y|n}: *y*

. [[paso 2]] Para solicitar la recopilación de registros de soporte y habilitar la recopilación periódica, ejecute el siguiente comando. Esto inicia ambos tipos de recopilación de registros: Los registros detallados `Support` y una recogida de datos por hora `Periodic` .
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Espere 10 minutos y compruebe que se complete la recopilación de registros:

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: Si la función de recopilación de registros informa de algún estado de error (visible en la salida de `system switch ethernet log show`), consulte link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/log-collection-troubleshoot.html["Solución de problemas de recopilación de registros"^] para obtener más información.
