---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: Si no ha recibido el equipo ya instalado en armarios, debe montar los componentes en rack. 
---
= Coloque en rack los componentes de hardware de configuración IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no ha recibido el equipo ya instalado en armarios, debe montar los componentes en rack.

.Acerca de esta tarea
Esta tarea debe realizarse en los dos sitios MetroCluster.

.Pasos
. Planifique la colocación de los componentes de MetroCluster.
+
El espacio en rack depende del modelo de plataforma de los módulos de la controladora, los tipos de switch y el número de pilas de bandejas de discos que haya en la configuración.

. Puesta a tierra apropiadamente usted mismo.
. Instale los módulos de la controladora en el rack o armario.
+
Siga los pasos para _Instalar hardware_ en las instrucciones de _Instalación y configuración_ para su modelo de plataforma en ellink:https://docs.netapp.com/us-en/ontap-systems/index.html["Documentación de los sistemas de hardware de ONTAP"^] .

. Instale los switches IP en el rack o armario.
. Instale las bandejas de discos, enciúdeles a encender y, a continuación, configure los ID de bandeja.
+
** Debe apagar y encender cada bandeja de discos.
** Los ID de bandeja únicos se recomiendan en gran medida para cada bandeja de discos SAS dentro de cada grupo de recuperación ante desastres de MetroCluster, como ayuda en la solución de problemas.


+

IMPORTANT: No conecte el cable de las bandejas de discos que estén destinadas a contener agregados no reflejados en este momento. Debe esperar a implementar bandejas destinadas a agregados no reflejados hasta que se complete la configuración de MetroCluster y solo implementarla después de utilizar el `metrocluster modify -enable-unmirrored-aggr-deployment true` comando.


