---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: Debe configurar los switches IP de Broadcom para su uso como Cluster Interconnect y para conectividad IP de MetroCluster back-end. 
---
= Configuración de switches IP de Broadcom
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar los switches IP de Broadcom para su uso como Cluster Interconnect y para conectividad IP de MetroCluster back-end.


NOTE: Su configuración requiere licencias adicionales (licencia de puerto de 6 x 100 GB) en las siguientes situaciones:

* Utiliza los puertos 53 y 54 como un ISL MetroCluster de 40 Gbps o 100 Gbps.
* Se utiliza una plataforma que conecta el clúster local y las interfaces MetroCluster a los puertos 49 - 52.




== Restablecer los valores predeterminados de fábrica del conmutador IP de Broadcom

Antes de instalar una nueva versión de software del conmutador y RCF, debe borrar la configuración del conmutador Broadcom y realizar la configuración básica.

.Acerca de esta tarea
* Debe repetir estos pasos en cada uno de los switches IP de la configuración de IP de MetroCluster.
* Debe estar conectado al conmutador mediante la consola serie.
* Esta tarea restablece la configuración de la red de gestión.


.Pasos
. Cambie al símbolo del sistema elevado (`#`): `enable`
+
[listing]
----
(IP_switch_A_1)> enable
(IP_switch_A_1) #
----
. Borre la configuración de inicio y elimine el banner
+
.. Borrar la configuración de inicio:
+
*`erase startup-config`*

+
[listing]
----
(IP_switch_A_1) #erase startup-config

Are you sure you want to clear the configuration? (y/n) y

(IP_switch_A_1) #
----
+
Este comando no borra el banner.

.. Quite el banner:
+
*`no set clibanner`*

+
[listing]
----
(IP_switch_A_1) #configure
(IP_switch_A_1)(Config) # no set clibanner
(IP_switch_A_1)(Config) #
----


. Reinicie el switch:*`(IP_switch_A_1) #reload*`
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: Si el sistema pregunta si desea guardar la configuración no guardada o modificada antes de volver a cargar el conmutador, seleccione *no*.

. Espere a que el conmutador se vuelva a cargar y, a continuación, inicie sesión en el conmutador.
+
El usuario predeterminado es "'admin'" y no se establece ninguna contraseña. Se muestra un símbolo del sistema similar a lo siguiente:

+
[listing]
----
(Routing)>
----
. Cambie al símbolo del sistema elevado:
+
`enable`

+
[listing]
----
Routing)> enable
(Routing) #
----
. Establezca el protocolo del puerto de servicio en `none`:
+
`serviceport protocol none`

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. Asigne la dirección IP al puerto de servicio:
+
`serviceport ip _ip-address_ _netmask_ _gateway_`

+
En el ejemplo siguiente se muestra una dirección IP asignada a un puerto de servicio "10.10.10.10" con subred "255.255.255.0" y puerta de enlace "10.10.10.1":

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. Compruebe que el puerto de servicio esté configurado correctamente:
+
`show serviceport`

+
En el ejemplo siguiente se muestra que el puerto está activo y que se han asignado las direcciones correctas:

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. Si lo desea, configure el servidor SSH.
+

NOTE: El archivo RCF desactiva el protocolo Telnet. Si no configura el servidor SSH, sólo puede acceder al puente utilizando la conexión de puerto serie.

+
.. Generar claves RSA.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. Generar claves DSA (opcional)
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. Si está utilizando la versión compatible con FIPS de EFOS, genere las claves ECDSA. El siguiente ejemplo crea las claves con una longitud de 521. Los valores válidos son 256, 384 o 521.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 521
----
.. Habilite el servidor SSH.
+
Si es necesario, salga del contexto de configuración.

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: Si las claves ya existen, es posible que se le pida que las sobrescriba.



. Si lo desea, configure el dominio y el servidor de nombres:
+
`configure`

+
En el siguiente ejemplo se muestra el `ip domain` y.. `ip name server` comandos:

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. Si lo desea, configure la zona horaria y la sincronización horaria (SNTP).
+
En el siguiente ejemplo se muestra el `sntp` Comandos, que especifican la dirección IP del servidor SNTP y la zona horaria relativa.

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
+
Para la versión 3.10.0.3 de EFOS y posterior, utilice el `ntp` comando, como se muestra en el siguiente ejemplo:

+
[listing]
----
> (Config)# ntp ?

authenticate             Enables NTP authentication.
authentication-key       Configure NTP authentication key.
broadcast                Enables NTP broadcast mode.
broadcastdelay           Configure NTP broadcast delay in microseconds.
server                   Configure NTP server.
source-interface         Configure the NTP source-interface.
trusted-key              Configure NTP authentication key number for trusted time source.
vrf                      Configure the NTP VRF.

>(Config)# ntp server ?

ip-address|ipv6-address|hostname  Enter a valid IPv4/IPv6 address or hostname.

>(Config)# ntp server 10.99.99.5
----
. Configure el nombre del switch:
+
`hostname IP_switch_A_1`

+
El indicador del interruptor mostrará el nuevo nombre:

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. Guarde la configuración:
+
`write memory`

+
Recibe mensajes y resultados similares al ejemplo siguiente:

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. Repita los pasos anteriores en los otros tres switches de la configuración IP de MetroCluster.




== Descarga e instalación del software EFOS del conmutador Broadcom

Debe descargar el archivo del sistema operativo del conmutador y el archivo RCF en cada switch de la configuración IP de MetroCluster.

.Acerca de esta tarea
Esta tarea debe repetirse en cada switch de la configuración de IP de MetroCluster.

[]
====
*Tenga en cuenta lo siguiente:*

* Al actualizar desde EFOS 3.4.x.x a EFOS 3.7.x.x o posterior, el conmutador debe ejecutar EFOS 3.4.4.6 (o posterior versión 3.4.x.x). Si está ejecutando una versión anterior a esa, actualice primero el conmutador a EFOS 3.4.4.6 (o posterior versión 3.4.x.x) y, a continuación, actualice el conmutador a EFOS 3.7.x.x o posterior.
* La configuración para EFOS 3.4.x.x y 3.7.x.x o posterior es diferente. Para cambiar la versión de EFOS de 3.4.x.x a 3.7.x.x o posterior, o viceversa, es necesario restablecer los valores predeterminados de fábrica del conmutador y aplicar los archivos RCF de la versión de EFOS correspondiente. Este procedimiento requiere acceso a través del puerto de la consola de serie.
* A partir de la versión 3.7.x.x de EFOS o posterior, está disponible una versión no compatible con FIPS y compatible con FIPS. Se aplican diferentes pasos al cambiar a desde una versión que no sea compatible con FIPS a una versión compatible con FIPS o viceversa. Si cambia EFOS de una versión no conforme a FIPS a una versión compatible con FIPS o viceversa, el cambio se restablecerá a los valores predeterminados de fábrica. Este procedimiento requiere acceso a través del puerto de la consola de serie.


====
.Pasos
. Compruebe si su versión de EFOS cumple con FIPS o no cumple con FIPS mediante el uso de `show fips status` comando. En los ejemplos siguientes: `IP_switch_A_1` Está utilizando EFOS y EFOS compatibles con FIPS `IP_switch_A_2` Utiliza EFOS no compatibles con FIPS.
+
*Ejemplo 1*

+
[listing]
----
IP_switch_A_1 #show fips status

System running in FIPS mode

IP_switch_A_1 #
----
+
*Ejemplo 2*

+
[listing]
----
IP_switch_A_2 #show fips status
                     ^
% Invalid input detected at `^` marker.

IP_switch_A_2 #
----
. Utilice la siguiente tabla para determinar qué método debe seguir:
+
|===


| *Procedimiento* | *Versión EFOS actual* | *Nueva versión EFOS* | * Pasos de alto nivel* 


 a| 
Pasos para actualizar EFOS entre dos versiones (no compatibles con FIPS) compatibles con FIPS
 a| 
3.4.x.x.
 a| 
3.4.x.x.
 a| 
Instale la nueva imagen de EFOS utilizando el método 1) se conserva la información de configuración y licencia



 a| 
3.4.4.6 (o posterior 3.4.x.x)
 a| 
3.7.x.x o superior, no conforme a FIPS
 a| 
Actualice el EFOS mediante el método 1. Restablezca el conmutador a los valores predeterminados de fábrica y aplique el archivo RCF para EFOS 3.7.x.x o posterior



.2+| 3.7.x.x o superior, no conforme a FIPS  a| 
3.4.4.6 (o posterior 3.4.x.x)
 a| 
Degradar EFOS mediante el método 1. Restablezca el interruptor a los valores predeterminados de fábrica y aplique el archivo RCF para EFOS 3.4.x.x.



 a| 
3.7.x.x o superior, no conforme a FIPS
 a| 
Instale la nueva imagen del EFOS mediante el método 1. Se conserva la información de configuración y licencia



 a| 
3.7.x.x o posterior, conforme a FIPS
 a| 
3.7.x.x o posterior, conforme a FIPS
 a| 
Instale la nueva imagen del EFOS mediante el método 1. Se conserva la información de configuración y licencia



 a| 
Pasos para actualizar a/desde una versión de EFOS conforme a FIPS
 a| 
No conforme a FIPS
 a| 
Conforme a FIPS
 a| 
Instalación de la imagen del EFOS mediante el método 2. Se perderá la información de licencia y configuración del switch.



 a| 
Conforme a FIPS
 a| 
No conforme a FIPS

|===
+
** Método 1: <<Pasos para actualizar EFOS con la descarga de la imagen de software a la partición de inicio de copia de seguridad>>
** Método 2: <<Pasos para actualizar EFOS mediante LA instalación DEL SO>>






=== Pasos para actualizar EFOS con la descarga de la imagen de software a la partición de inicio de copia de seguridad

Sólo puede realizar los siguientes pasos si ambas versiones de EFOS no son compatibles con FIPS o ambas son compatibles con FIPS.


NOTE: No utilice estos pasos si una versión es compatible con FIPS y la otra no es compatible con FIPS.

.Pasos
. Copie el software del conmutador en el conmutador: `+copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup+`
+
En este ejemplo, el archivo del sistema operativo efos-3.4.4.6.stk se copia desde el servidor SFTP en 50.50.50.50 a la partición de copia de seguridad. Debe utilizar la dirección IP del servidor TFTP/SFTP y el nombre de archivo del archivo RCF que necesita instalar.

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. Ajuste el conmutador a arrancar desde la partición de copia de seguridad en el siguiente reinicio del conmutador:
+
`boot system backup`

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. Compruebe que la nueva imagen de arranque estará activa en el siguiente arranque:
+
`show bootvar`

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.4.2    3.4.4.6      3.4.4.2        3.4.4.6

(IP_switch_A_1) #
----
. Guarde la configuración:
+
`write memory`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. Reinicie el switch:
+
`reload`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. Espere a que se reinicie el switch.
+

NOTE: En raras ocasiones, es posible que el conmutador no se inicie. Siga la <<Pasos para actualizar EFOS mediante LA instalación DEL SO>> para instalar la nueva imagen.

. Si cambia el cambio de EFOS 3.4.x.x a EFOS 3.7.x.x o viceversa, siga los dos procedimientos siguientes para aplicar la configuración correcta (RCF):
+
.. <<Restablecer los valores predeterminados de fábrica del conmutador IP de Broadcom>>
.. <<Descarga e instalación de los archivos Broadcom RCF>>


. Repita estos pasos en los tres switches IP restantes de la configuración IP de MetroCluster.




=== Pasos para actualizar EFOS mediante LA instalación DEL SO

Puede realizar los siguientes pasos si una versión de EFOS es compatible con FIPS y la otra versión de EFOS no es compatible con FIPS. Estos pasos se pueden utilizar para instalar la imagen EFOS 3.7.x.x no compatible con FIPS o FIPS desde ONIE si el conmutador no arranca.

.Pasos
. Arranque el interruptor en el modo DE instalación ONIE.
+
Durante el arranque, seleccione ONIE cuando aparezca la siguiente pantalla:

+
[listing]
----
 +--------------------------------------------------------------------+
 |EFOS                                                                |
 |*ONIE                                                               |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
Después de seleccionar "ONIE", el interruptor se cargará y le presentará las siguientes opciones:

+
[listing]
----
 +--------------------------------------------------------------------+
 |*ONIE: Install OS                                                   |
 | ONIE: Rescue                                                       |
 | ONIE: Uninstall OS                                                 |
 | ONIE: Update ONIE                                                  |
 | ONIE: Embed ONIE                                                   |
 | DIAG: Diagnostic Mode                                              |
 | DIAG: Burn-In Mode                                                 |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
El conmutador se iniciará ahora en el modo DE instalación ONIE.

. Detenga EL descubrimiento DE ONIE y configure la interfaz ethernet
+
Una vez que aparezca el siguiente mensaje, pulse <enter> para invocar LA consola ONIE:

+
[listing]
----
 Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: El descubrimiento DE ONIE continuará y los mensajes se imprimirán en la consola.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure la interfaz ethernet y agregue la ruta mediante `ifconfig eth0 <ipAddress> netmask <netmask> up` y.. `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Compruebe que se puede acceder al servidor que aloja el archivo DE instalación ONIE:
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. Instale el nuevo software del conmutador
+
[listing]
----

ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
El software instalará y reiniciará el conmutador. Deje que el interruptor se reinicie normalmente en la nueva versión de EFOS.

. Compruebe que el nuevo software del conmutador está instalado
+
*`show bootvar`*

+
[listing]
----

(Routing) #show bootvar
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	   backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(Routing) #
----
. Complete la instalación
+
El conmutador se reiniciará sin que se aplique ninguna configuración y se restablecerán los valores predeterminados de fábrica. Siga los dos procedimientos para configurar los ajustes básicos del conmutador y aplicar el archivo RCF como se describe en los dos documentos siguientes:

+
.. Configure los ajustes básicos del conmutador. Siga el paso 4 y posterior: <<Restablecer los valores predeterminados de fábrica del conmutador IP de Broadcom>>
.. Cree y aplique el archivo RCF como se indica en la <<Descarga e instalación de los archivos Broadcom RCF>>






== Descarga e instalación de los archivos Broadcom RCF

Debe descargar e instalar el archivo RCF del conmutador en cada conmutador de la configuración IP de MetroCluster.

.Antes de empezar
Esta tarea requiere software de transferencia de archivos, como FTP, TFTP, SFTP o SCP para copiar los archivos en los switches.

.Acerca de esta tarea
Estos pasos deben repetirse en cada switch IP de la configuración de IP de MetroCluster.

Existen cuatro archivos RCF, uno para cada uno de los cuatro conmutadores de la configuración IP de MetroCluster. Debe utilizar los archivos RCF correctos para el modelo de conmutador que esté utilizando.

|===


| Conmutador | Archivo RCF 


 a| 
IP_switch_A_1
 a| 
v1.32_Switch-A1.txt



 a| 
IP_switch_A_2
 a| 
v1.32_Switch-A2.txt



 a| 
IP_switch_B_1
 a| 
v1.32_Switch-B1.txt



 a| 
IP_switch_B_2
 a| 
v1.32_Switch-B2.txt

|===

NOTE: Los archivos RCF para EFOS versión 3.4.4.6 o posterior 3.4.x.x. La versión 3.7.0.4 y la versión de EFOS son diferentes. Debe asegurarse de que ha creado los archivos RCF correctos para la versión EFOS en la que se está ejecutando el conmutador.

|===


| Versión EFOS | Versión de archivo RCF 


| 3.4.x.x. | v1.3x, v1.4x 


| 3.7.x.x. | v2.x 
|===
.Pasos
. Genere los archivos RCF de Broadcom para MetroCluster IP.
+
.. Descargue el https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator para MetroCluster IP"]
.. Genere el archivo RCF para su configuración utilizando el RcfFileGenerator para MetroCluster IP.
+

NOTE: No se admiten las modificaciones realizadas en los archivos RCF después de la descarga.



. Copie los archivos RCF en los conmutadores:
+
.. Copie los archivos RCF en el primer conmutador:
`copy sftp://user@FTP-server-IP-address/RcfFiles/switch-specific-RCF/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr`
+
En este ejemplo, el archivo RCF "BES-53248_v1.32_Switch-A1.txt" se copia desde el servidor SFTP en "50.50.50.50" al bootflash local. Debe utilizar la dirección IP del servidor TFTP/SFTP y el nombre de archivo del archivo RCF que necesita instalar.

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "***************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. Compruebe que el archivo RCF se guarda como una secuencia de comandos:
+
`script list`

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. Aplicar el script RCF:
+
`script apply BES-53248_v1.32_Switch-A1.scr`

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. Guarde la configuración:
+
`write memory`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. Reinicie el switch:
+
`reload`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. Repita los pasos anteriores para cada uno de los otros tres conmutadores, asegurándose de copiar el archivo RCF correspondiente al conmutador correspondiente.


. Vuelva a cargar el interruptor:
+
`reload`

+
[listing]
----
IP_switch_A_1# reload
----
. Repita los pasos anteriores en los otros tres switches de la configuración IP de MetroCluster.




== Deshabilite los puertos ISL y los canales de puertos no utilizados

NetApp recomienda deshabilitar los puertos ISL y los canales de puertos no utilizados para evitar alertas de estado innecesarias.

. Identifique los puertos ISL y los canales de puerto no utilizados mediante el banner del archivo RCF:
+

NOTE: Si el puerto está en modo de separación, el nombre de puerto especificado en el comando puede ser diferente al nombre indicado en el banner de RCF. También puede usar los archivos de cableado RCF para buscar el nombre del puerto.

+
[role="tabbed-block"]
====
.Para los detalles del puerto ISL
--
Ejecute el comando `show port all`.

--
.Para obtener detalles del canal de puerto
--
Ejecute el comando `show port-channel all`.

--
====
. Deshabilite los puertos ISL y los canales de puertos sin utilizar.
+
Debe ejecutar los siguientes comandos para cada puerto o canal de puerto no utilizado identificado.

+
[listing]
----
(SwtichA_1)> enable
(SwtichA_1)# configure
(SwtichA_1)(Config)# <port_name>
(SwtichA_1)(Interface 0/15)# shutdown
(SwtichA_1)(Interface 0/15)# end
(SwtichA_1)# write memory
----

