---
permalink: disaster-recovery/task_complete_recovery.html 
sidebar: sidebar 
keywords: object, fabricpool, mirror, co-located, metrocluster, disaster, site, destroy, reestablish, store, reestablish, store, configuration, verify, license, replace, node, perform, switchback, successful, root, aggregates, replacement, health, reconfiguring, reconfigure, ontap, mediator, service, ip, configuration 
summary: Si uno de los almacenes de objetos de un reflejo de FabricPool se colocalizó con el centro de desastres de MetroCluster y fue destruido, debe restablecer el almacén de objetos y el mirror de FabricPool. 
---
= Completando la recuperación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Realizar las tareas requeridas para completar la recuperación tras un fallo de varias controladoras o de almacenamiento.



== Restablecer almacenes de objetos para configuraciones de FabricPool

Si uno de los almacenes de objetos de un reflejo de FabricPool se colocalizó con el centro de desastres de MetroCluster y fue destruido, debe restablecer el almacén de objetos y el mirror de FabricPool.

.Acerca de esta tarea
* Si los almacenes de objetos son remotos y se destruye un sitio MetroCluster, no necesita reconstruir el almacén de objetos y se conservan las configuraciones del almacén de objetos original y el contenido de datos inactivos.
* Para obtener más información acerca de las configuraciones FabricPool, consulte link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestión de discos y agregados"^].


.Paso
. Siga el procedimiento "Sustitución de un espejo FabricPool en una configuración de MetroCluster" en la link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestión de discos y agregados"^].




== Verificación de licencias en los nodos sustituidos

Debe instalar licencias nuevas para los nodos de reemplazo si los nodos dañados utilizaban funciones de ONTAP que requieren una licencia estándar (de bloqueo de nodo). Para funciones con licencias estándar, cada nodo del clúster debe tener su propia clave para la función.

.Acerca de esta tarea
Hasta que instale las claves de licencia, las funciones que requieren licencias estándar siguen estando disponibles para el nodo de reemplazo. Sin embargo, si el nodo dañado era el único nodo del clúster con una licencia de la función, no se permiten cambios de configuración en la función. Además, el uso de funciones sin licencia en el nodo podría descumplir con el acuerdo de licencia, de modo que debe instalar la clave de licencia o las claves de reemplazo en la Lo antes posible. del nodo de reemplazo.

Las claves de licencia deben tener el formato de 28 caracteres.

Dispone de un período de gracia de 90 días para instalar las claves de licencia. Una vez transcurrido el período de gracia, se invalidarán todas las licencias antiguas. Después de instalar una clave de licencia válida, dispone de 24 horas para instalar todas las claves antes de que finalice el período de gracia.


NOTE: Si todos los nodos de un sitio han sido reemplazados (un único nodo en el caso de una configuración MetroCluster de dos nodos), es necesario instalar claves de licencia en el nodo de reemplazo o los nodos antes de regresar.

.Pasos
. Identifique las licencias del nodo:
+
`license show`

+
En el siguiente ejemplo, se muestra la información sobre las licencias del sistema:

+
[listing]
----
cluster_B::>  license show
         (system license show)

Serial Number: 1-80-00050
Owner: site1-01
Package           Type       Description             Expiration
-------          -------     -------------           -----------
Base             license     Cluster Base License        -
NFS              site        NFS License                 -
CIFS             site        CIFS License                -
iSCSI            site        iSCSI License               -
FCP              site        FCP License                 -
FlexClone        site        FlexClone License           -

6 entries were displayed.
----
. Verifique que las licencias sean buenas para el nodo después de regresar:
+
`metrocluster check license show`

+
En el siguiente ejemplo, se muestran las licencias que son buenas para el nodo:

+
[listing]
----
cluster_B::> metrocluster check license show

Cluster           Check                             Result
-------           -------                           -------------
Cluster_B         negotiated-switchover-ready       not-applicable
NFS               switchback-ready                  not-applicable
CIFS              job-schedules                     ok
iSCSI             licenses                          ok
FCP               periodic-check-enabled            ok
----
. Si necesita claves de licencia nuevas, obtenga las claves de licencia de reemplazo en el sitio de soporte de NetApp, en la sección My Support, en licencias de software.
+

NOTE: Las claves de licencia nuevas que necesita se generan automáticamente y se envían a la dirección de correo electrónico que está registrada. Si no recibe el correo electrónico con las claves de licencia en un plazo de 30 días, consulte la sección _"a quién debo contactar si tengo problemas con mis licencias?"_ del artículo de Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system["Proceso de sustitución posterior a la placa base para actualizar las licencias en un sistema AFF/FAS."^]

. Instale cada clave de licencia:
+
`system license add -license-code license-key, license-key...+`

. Elimine las licencias antiguas, si lo desea:
+
.. Comprobar si hay licencias no utilizadas:
+
`license clean-up -unused -simulate`

.. Si la lista parece correcta, elimine las licencias no utilizadas:
+
`license clean-up -unused`







== Restauración de gestión de claves

Si los volúmenes de datos están cifrados, debe restaurar la gestión de claves. Si el volumen raíz se cifra, se debe recuperar la gestión de claves.

.Pasos
. Si se cifran los volúmenes de datos, restaure las claves con el comando correcto para la configuración de gestión de claves.
+
[cols="1,2"]
|===


| Si está usando... | Se usa este comando... 


 a| 
*Gestión de claves a bordo*
 a| 
`security key-manager onboard sync`

Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["Restauración de las claves de cifrado de gestión de claves incorporadas"^].



 a| 
*Gestión de claves externas*
 a| 
`security key-manager key query -node node-name`

Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["Restauración de claves de cifrado de gestión de claves externas"^].

|===
. Si el volumen raíz está cifrado, utilice el procedimiento en link:../transition/task_connect_the_mcc_ip_controller_modules_2n_mcc_transition_supertask.html#recovering-key-management-if-the-root-volume-is-encrypted["Se recupera la gestión de claves si el volumen raíz se cifra"].




== Realización de una conmutación de regreso

Después de recuperar la configuración de MetroCluster, puede ejecutar la operación de conmutación de estado de MetroCluster. La operación de conmutación de estado de MetroCluster devuelve la configuración a su estado operativo normal, con las máquinas virtuales de almacenamiento (SVM) sincronizada en el sitio de desastre activas y suministrando datos de los pools de discos locales.

.Antes de empezar
* El clúster de desastres debe haber cambiado correctamente al clúster superviviente.
* La reparación debe haberse realizado en los agregados de datos y raíz.
* Los nodos de clúster supervivientes no deben estar en estado de conmutación por error de alta disponibilidad (todos los nodos deben estar en funcionamiento para cada par de alta disponibilidad).
* Los módulos de controladoras del centro de recuperación ante desastres deben arrancarse por completo y no en el modo de toma de control ha.
* Se debe reflejar el agregado raíz.
* Los enlaces Inter-Switch (ISL) deben estar en línea.
* Deben instalarse las licencias necesarias en el sistema.


.Pasos
. Confirme que todos los nodos se encuentran en estado habilitado:
+
`metrocluster node show`

+
En el ejemplo siguiente se muestran los nodos que están en el estado Enabled:

+
[listing]
----
cluster_B::>  metrocluster node show

DR                        Configuration  DR
Group Cluster Node        State          Mirroring Mode
----- ------- ----------- -------------- --------- --------------------
1     cluster_A
              node_A_1    configured     enabled   heal roots completed
              node_A_2    configured     enabled   heal roots completed
      cluster_B
              node_B_1    configured     enabled   waiting for switchback recovery
              node_B_2    configured     enabled   waiting for switchback recovery
4 entries were displayed.
----
. Confirme que se completó la resincronización en todas las SVM:
+
`metrocluster vserver show`

. Compruebe que se hayan completado correctamente las migraciones automáticas LIF que realizan las operaciones de reparación:
+
`metrocluster check lif show`

. Lleve a cabo la conmutación de estado ejecutando el `metrocluster switchback` comando desde cualquier nodo del clúster superviviente.
. Compruebe el progreso de la operación de regreso:
+
`metrocluster show`

+
La operación de conmutación de estado aún está en curso cuando el resultado muestra "esperando a que se haga regresar":

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                switchover
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                waiting-for-switchback
                          AUSO Failure Domain -
----
+
La operación de conmutación de estado finaliza cuando el resultado muestra "normal":

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain -
----
+
Si una conmutación de regreso tarda mucho tiempo en terminar, puede comprobar el estado de las líneas base en curso utilizando el siguiente comando en el nivel de privilegio avanzado:

+
`metrocluster config-replication resync-status show`

. Restablecer cualquier configuración de SnapMirror o SnapVault.
+
En ONTAP 8.3, es necesario restablecer manualmente una configuración de SnapMirror perdida después de una operación de conmutación de estado de MetroCluster. En ONTAP 9.0 y versiones posteriores, la relación se restablece de forma automática.





== Verificación de una conmutación de regreso exitosa

Después de llevar a cabo la conmutación de estado, querrá confirmar que todos los agregados y las máquinas virtuales de almacenamiento (SVM) hayan vuelto a conectarse y estén en línea.

.Pasos
. Compruebe que los agregados de datos conmutados están conmutados de nuevo:
+
`storage aggregate show`

+
En el siguiente ejemplo, aggr_b2 en el nodo B2 ha vuelto a activarse:

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal

node_A_1::> aggr show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2          -         -     - unknown      - node_A_1
----
+
Si el site del desastre incluía agregados no reflejados y los agregados no reflejados ya no están presentes, el agregado podría aparecer con un estado de "'desconocido'" en el resultado del comando show del agregado de almacenamiento. Póngase en contacto con el soporte técnico para eliminar las entradas desfasadas de los agregados no reflejados; consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_stale_unmirrored_aggregate_entries_in_a_MetroCluster_following_disaster_where_storage_was_lost["Cómo eliminar entradas de agregado no reflejadas obsoletas en una MetroCluster tras un desastre en el que se perdió el almacenamiento."^]

. Verifique que todas las SVM sync-destination del cluster superviviente estén latentes (mostrando un estado operativo de “alto”):
+
`vserver show -subtype sync-destination`

+
[listing]
----
node_B_1::> vserver show -subtype sync-destination
                                 Admin    Operational  Root
Vserver       Type    Subtype    State    State        Volume    Aggregate
-----------   ------- ---------- -------- ----------   --------  ----------
...
cluster_A-vs1a-mc data sync-destination
                               running    stopped    vs1a_vol   aggr_b2

----
+
Los agregados de sincronización-destino de la configuración de MetroCluster adjuntan automáticamente el sufijo "'-mc'" a su nombre para ayudar a identificarlos.

. Compruebe que las SVM de origen sincronizado en el clúster de desastres están activas y en ejecución:
+
`vserver show -subtype sync-source`

+
[listing]
----
node_A_1::> vserver show -subtype sync-source
                                  Admin    Operational  Root
Vserver        Type    Subtype    State    State        Volume     Aggregate
-----------    ------- ---------- -------- ----------   --------   ----------
...
vs1a           data    sync-source
                                  running  running    vs1a_vol  aggr_b2

----
. Confirme que las operaciones de conmutación de estado han sido realizadas correctamente mediante el `metrocluster operation show` comando.
+
|===


| Si el resultado del comando muestra... | Realice lo siguiente... 


 a| 
Que el estado de la operación de conmutación de estado sea correcto.
 a| 
El proceso de conmutación de estado ha finalizado y puede continuar con el funcionamiento del sistema.



 a| 
Que la operación de regreso o la operación de continuación de regreso del agente es parcialmente exitosa.
 a| 
Ejecute la corrección sugerida proporcionada en el resultado del comando MetroCluster operation show.

|===


.Después de terminar
Debe repetir las secciones anteriores para realizar la rotación en la dirección opuesta. Si Site_A hizo una conmutación de Site_B, haga que Site_B haga una conmutación de Site_A.



== Hacer mirroring de los agregados raíz de los nodos de reemplazo

Si se han sustituido los discos, debe reflejar los agregados raíz de los nuevos nodos en el sitio de recuperación ante desastres.

.Pasos
. En el sitio de recuperación tras siniestros, identifique las agrupaciones que no están duplicadas:
+
`storage aggregate show`

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1         raid4,
                                                                   normal
node_A_2_aggr0
            1.49TB   74.12GB   95% online       1 node_A_2         raid4,
                                                                   normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1         raid 4, normal
                                                                   mirrored
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2         raid 4, normal
                                                                   mirrored
4 entries were displayed.

cluster_A::>
----
. Refleje uno de los agregados raíz:
+
`storage aggregate mirror -aggregate root-aggregate`

+
El siguiente ejemplo muestra cómo el comando selecciona discos y solicita su confirmación al reflejar el agregado.

+
[listing]
----
cluster_A::> storage aggregate mirror -aggregate node_A_2_aggr0

Info: Disks would be added to aggregate "node_A_2_aggr0" on node "node_A_2" in
      the following manner:

      Second Plex

        RAID Group rg0, 3 disks (block checksum, raid4)
          Position   Disk                      Type                  Size
          ---------- ------------------------- ---------- ---------------
          parity     2.10.0                    SSD                      -
          data       1.11.19                   SSD                894.0GB
          data       2.10.2                    SSD                894.0GB

      Aggregate capacity available for volume use would be 1.49TB.

Do you want to continue? {y|n}: y

cluster_A::>
----
. Compruebe que se haya completado el mirroring del agregado raíz:
+
`storage aggregate show`

+
El ejemplo siguiente muestra que los agregados raíz se han duplicado.

+
[listing]
----
cluster_A::> storage aggregate show

Aggregate     Size Available Used% State   #Vols  Nodes       RAID Status
--------- -------- --------- ----- ------- ------ ----------- ------------
node_A_1_aggr0
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr0
            2.24TB   838.5GB   63% online       1 node_A_2    raid4,
                                                              mirrored,
                                                              normal
node_A_1_aggr1
            1.49TB   74.12GB   95% online       1 node_A_1    raid4,
                                                              mirrored,
                                                              normal
node_A_2_aggr1
            1.49TB   74.12GB   95% online       1 node_A_2    raid4
                                                              mirrored,
                                                              normal
4 entries were displayed.

cluster_A::>
----
. Repita estos pasos para los otros agregados raíz.
+
Se debe reflejar cualquier agregado raíz que no tenga el estado de reflejo.





== Reconfiguración del mediador de ONTAP (configuraciones de IP de MetroCluster)

Si tiene una configuración de IP de MetroCluster que se configuró con ONTAP Mediator, debe eliminar y volver a configurar la asociación con ONTAP Mediator.

.Antes de empezar
* Debe tener la dirección IP, el nombre de usuario y la contraseña de ONTAP Mediator.
* ONTAP Mediator debe estar configurado y funcionando en el host Linux.


.Pasos
. Elimine la configuración existente del Mediador ONTAP:
+
`metrocluster configuration-settings mediator remove`

. Vuelva a configurar la configuración del Mediador ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address mediator-IP-address`





== Comprobación del estado de la configuración de MetroCluster

Debe comprobar el estado de la configuración de MetroCluster para verificar que funciona correctamente.

.Pasos
. Compruebe que la MetroCluster esté configurada y en modo normal de cada clúster:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. Compruebe que el mirroring está habilitado en cada nodo:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. Compruebe que los componentes de MetroCluster sean los mismos en buen estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the `metrocluster check show -instance` command or sub-commands in `metrocluster check` directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run `metrocluster switchover -simulate` or `metrocluster switchback -simulate`, respectively.
----
. Compruebe que no hay alertas de estado:
+
`system health alert show`

. Simular una operación de switchover:
+
.. Desde el símbolo del sistema de cualquier nodo, cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

+
Debe responder con `y` cuando se le solicite que continúe en el modo avanzado y vea el indicador del modo avanzado (*).

.. Realice la operación de conmutación con el `-simulate` parámetro:
+
`metrocluster switchover -simulate`

.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



. Para las configuraciones de IP de MetroCluster que utilizan ONTAP Mediator, confirme que ONTAP Mediator esté activo y en funcionamiento.
+
.. Compruebe que los discos del Mediator son visibles para el sistema:
+
`storage failover mailbox-disk show`

+
El ejemplo siguiente muestra que se han reconocido los discos del buzón.

+
[listing]
----
node_A_1::*> storage failover mailbox-disk show
                 Mailbox
Node             Owner     Disk    Name        Disk UUID
-------------     ------   -----   -----        ----------------
sti113-vsim-ucs626g
.
.
     local     0m.i2.3L26      7BBA77C9:AD702D14:831B3E7E:0B0730EE:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i2.3L27      928F79AE:631EA9F9:4DCB5DE6:3402AC48:00000000:00000000:00000000:00000000:00000000:00000000
     local     0m.i1.0L60      B7BCDB3C:297A4459:318C2748:181565A3:00000000:00000000:00000000:00000000:00000000:00000000
.
.
.
     partner   0m.i1.0L14      EA71F260:D4DD5F22:E3422387:61D475B2:00000000:00000000:00000000:00000000:00000000:00000000
     partner   0m.i2.3L64      4460F436:AAE5AB9E:D1ED414E:ABF811F7:00000000:00000000:00000000:00000000:00000000:00000000
28 entries were displayed.
----
.. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

.. Compruebe que las LUN de buzón estén visibles para el sistema:
+
`storage iscsi-initiator show`

+
El resultado mostrará la presencia de las LUN de los buzones:

+
[listing]
----

Node    Type       Label      Target Portal     Target Name                                 Admin/Op
----    ----       --------   ---------    --------- --------------------------------       --------
.
.
.
.node_A_1
               mailbox
                     mediator 172.16.254.1    iqn.2012-05.local:mailbox.target.db5f02d6-e3d3    up/up
.
.
.
17 entries were displayed.
----
.. Volver al nivel de privilegio administrativo:
+
`set -privilege admin`




