---
permalink: disaster-recovery/task-enable-console-logging.html 
sidebar: sidebar 
keywords: enable, console, logging, devices, maintenance, autosupport, cli, 
summary: Active el registro de la consola en sus dispositivos. 
---
= Active el registro de la consola
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active el registro de la consola en sus dispositivos antes de proceder a reemplazar el hardware e iniciar nuevos controladores.

NetApp recomienda encarecidamente que habilite el inicio de sesión de la consola en los dispositivos que esté utilizando y realice las siguientes acciones al realizar este procedimiento:

* Deje la función AutoSupport habilitada durante el mantenimiento.
* Active un mensaje de AutoSupport de mantenimiento antes y después de las tareas de mantenimiento para deshabilitar la creación de casos durante la actividad de mantenimiento.
+
Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Cómo impedir la creación automática de casos durante las ventanas de mantenimiento programado"^].

* Habilite el registro de sesiones para cualquier sesión de CLI. Para obtener instrucciones sobre cómo activar el registro de sesiones, consulte la sección Salida de sesión de registro en el artículo de la Base de conocimientos link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con sistemas ONTAP"^].

