---
permalink: disaster-recovery/task_reassign_pool1_disastersite_mcip.html 
sidebar: sidebar 
keywords: metrocluster, disaster, site, replacement, controller, module, reassign, ownership 
summary: Si los módulos de controladora o las tarjetas NVRAM se reemplazaron en el sitio de recuperación ante desastres, debe reasignar los discos pertenecientes a los agregados raíz a los módulos de controladora de sustitución. 
---
= Reasignar la propiedad de disco para discos de pool 1 en el sitio de recuperación ante desastres (configuraciones de IP de MetroCluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se reemplazaron uno o ambos módulos de controladora o tarjetas NVRAM en el centro de recuperación ante desastres, el ID del sistema ha cambiado y debe reasignar los discos que pertenecen a los agregados raíz a los módulos de controladora de reemplazo.

.Acerca de esta tarea
Debido a que los nodos están en modo de conmutación, en esta tarea solo se reasignarán los discos que contengan los agregados raíz de la agrupación 1 del sitio de desastre. Son los únicos discos que aún pertenecen al ID de sistema antiguo de este momento.

Esta tarea se lleva a cabo en los nodos de reemplazo del sitio de desastre.

Esta tarea se realiza en modo de mantenimiento.

En los ejemplos se da por sentado lo siguiente:

* El sitio A es el sitio de recuperación tras desastres.
* Se ha sustituido Node_A_1.
* Se reemplazó Node_A_2.
* El sitio B es el sitio superviviente.
* El nodo B_1 está en buen estado.
* El nodo B_2 está en buen estado.


Los ID de sistema antiguos y nuevos se identificaron en link:../disaster-recovery/task_replace_hardware_and_boot_new_controllers.html["Sustituir el hardware e arrancar nuevas controladoras"].

Los ejemplos de este procedimiento utilizan controladoras con los siguientes ID de sistema:

|===


| Nodo | ID original del sistema | Nuevo ID del sistema 


 a| 
Node_a_1
 a| 
4068741258
 a| 
1574774970



 a| 
Node_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
Node_B_1
 a| 
4068741254
 a| 
sin cambios



 a| 
Node_B_2
 a| 
4068741256
 a| 
sin cambios

|===
.Pasos
. Con el nodo de sustitución en modo de mantenimiento, reasigne los discos de agregado raíz mediante el comando correcto, en función de si su sistema está configurado con ADP y su versión ONTAP.
+
Puede continuar con la reasignación cuando se le solicite.

+
|===


| Si el sistema está utilizando ADP... | Use este comando para reasignar discos... 


 a| 
Sí (ONTAP 9.8)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -r dr-partner-system-ID`



 a| 
Sí (ONTAP 9.7.x y anterior)
 a| 
`disk reassign -s old-system-ID -d new-system-ID -p old-partner-system-ID`



 a| 
No
 a| 
`disk reassign -s old-system-ID -d new-system-ID`

|===
+
En el siguiente ejemplo, se muestra la reasignación de unidades en un sistema que no sea ADP:

+
[listing]
----
*> disk reassign -s 4068741256 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537037643.
Do you want to continue (y/n)? y
disk reassign parameters: new_home_owner_id 537070473 , new_home_owner_name
Disk 0m.i0.3L14 will be reassigned.
Disk 0m.i0.1L6 will be reassigned.
Disk 0m.i0.1L8 will be reassigned.
Number of disks to be reassigned: 3
----
. Destruir el contenido de los discos del buzón:
+
`mailbox destroy local`

+
Puede continuar con la operación de destrucción cuando se le solicite.

+
En el siguiente ejemplo se muestra el resultado del comando local Destroy del buzón:

+
[listing]
----
*> mailbox destroy local
Destroying mailboxes forces a node to create new empty mailboxes,
which clears any takeover state, removes all knowledge
of out-of-date plexes of mirrored volumes, and will prevent
management services from going online in 2-node cluster
HA configurations.
Are you sure you want to destroy the local mailboxes? y
...............Mailboxes destroyed.
*>
----
. Si los discos se han sustituido, habrá complejos locales fallidos que se deben eliminar.
+
.. Mostrar el estado del agregado:
+
`aggr status`

+
En el ejemplo siguiente, el plex node_A_1_aggr0/plex0 ha fallado.

+
[listing]
----
*> aggr status
Aug 18 15:00:07 [node_B_1:raid.vol.mirror.degraded:ALERT]: Aggregate node_A_1_aggr0 is
   mirrored and one plex has failed. It is no longer protected by mirroring.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex0
   clean(-1), online(0)
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex2
   clean(0), online(1)
Aug 18 15:00:07 [node_B_1:raid.mirror.vote.noRecord1Plex:error]: WARNING: Only one plex
   in aggregate node_A_1_aggr0 is available. Aggregate might contain stale data.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: volobj_mark_sb_recovery_aggrs: tree:
   node_A_1_aggr0 vol_state:1 mcc_dr_opstate: unknown
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (VOL):
   raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (MIRROR):
   raid state change UNINITD -> DEGRADED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex0
   (PLEX): raid state change UNINITD -> FAILED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2
   (PLEX): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2/rg0
   (GROUP): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Topology updated for aggregate node_A_1_aggr0
   to plex plex2
*>
----
.. Eliminar el complejo defectuoso:
+
`aggr destroy plex-id`

+
[listing]
----
*> aggr destroy node_A_1_aggr0/plex0
----


. Detenga el nodo para mostrar el símbolo del sistema del CARGADOR:
+
`halt`

. Repita estos pasos en el otro nodo del sitio de desastre.

