---
permalink: disaster-recovery/task_boot_new_mcfc.html 
sidebar: sidebar 
keywords: boot, controller, modules, fc 
summary: Después de que se haya completado la reparación de agregados de datos y raíz, debe arrancar el nodo o los nodos en el sitio de desastre. 
---
= Arrancar los nuevos módulos de la controladora (configuraciones de FC de MetroCluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de que se haya completado la reparación de agregados de datos y raíz, debe arrancar el nodo o los nodos en el sitio de desastre.

.Acerca de esta tarea
Esta tarea comienza con los nodos que muestran el aviso del CARGADOR.

.Pasos
. Mostrar el menú de inicio:
+
`boot_ontap menu`

. [[step2,Paso 2]]en el menú de inicio, seleccione la opción 6, *Actualizar flash desde backup config*.
. Responda `y` en el siguiente símbolo del sistema:
+
`This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: y`

+
El sistema se iniciará dos veces, la segunda vez para cargar la nueva configuración.

+

NOTE: Si no ha borrado el contenido de la NVRAM de una controladora de reemplazo utilizada, podría ver una alerta con el siguiente mensaje:
`PANIC: NVRAM contents are invalid...`Si esto ocurre, repita <<step2,En el menú de inicio, seleccione la opción 6, *Actualizar flash desde backup config*.>> Para arrancar el sistema en el símbolo del sistema de ONTAP. Entonces necesita hacerlo <<Reset-the-boot-recovery,Restablezca la recuperación de arranque y los bootargs rdb_corrupt>>

. Reflejar el agregado raíz en el complejo 0:
+
.. Asigne tres discos pool0 al nuevo módulo de controlador.
.. Duplicar el complejo de agrupación root 1:
+
`aggr mirror root-aggr-name`

.. Asigne discos sin propietario a pool0 en el nodo local


. Si tiene una configuración de cuatro nodos, repita los pasos anteriores en el otro nodo del sitio de desastre.
. Actualice la configuración de MetroCluster:
+
.. Entre en el modo de privilegio avanzado:
+
`set -privilege advanced`

.. Actualice la configuración:
+
`metrocluster configure -refresh true`

.. Volver al modo de privilegios de administrador:
+
`set -privilege admin`



. Confirme que los nodos de repuesto en el sitio del desastre están listos para la conmutación de estado:
+
`metrocluster node show`

+
Los nodos de repuesto deben estar en modo «"esperando recuperación de regreso"». Si se encuentran en el modo "'normal'", puede reiniciar los nodos de sustitución. Después de ese arranque, los nodos deberían estar en modo «'esperando la recuperación de regreso'».

+
El ejemplo siguiente muestra que los nodos de reemplazo están listos para regresar:

+
....

cluster_B::> metrocluster node show
DR                    Configuration  DR
Grp Cluster Node      State          Mirroring Mode
--- ------- --------- -------------- --------- --------------------
1   cluster_B
            node_B_1  configured     enabled   switchover completed
            node_B_2  configured     enabled   switchover completed
    cluster_A
            node_A_1  configured     enabled   waiting for switchback recovery
            node_A_2  configured     enabled   waiting for switchback recovery
4 entries were displayed.

cluster_B::>
....


.Qué hacer a continuación
Vaya a. link:../disaster-recovery/task_complete_recovery.html["Complete el proceso de recuperación ante desastres"].



=== [[Reset-the-boot-recovery]]reinicie los arranques boot_recovery y rdb_corrupt

[role="lead"]
Si es necesario, puede restablecer el boot_recovery y rdb_corrupt_bootargs

.Pasos
. Detenga el nodo de nuevo en el símbolo del sistema del CARGADOR:
+
[listing]
----
node_A_1::*> halt -node _node-name_
----
. Compruebe si se han configurado los siguientes bootargs:
+
[listing]
----
LOADER> printenv bootarg.init.boot_recovery
LOADER> printenv bootarg.rdb_corrupt
----
. Si se ha establecido un valor en bootarg, desconconfigúrelo y arranque ONTAP:
+
[listing]
----
LOADER> unsetenv bootarg.init.boot_recovery
LOADER> unsetenv bootarg.rdb_corrupt
LOADER> saveenv
LOADER> bye
----

