---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de MetroCluster
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: Comprender la protecci贸n de datos y la recuperaci贸n ante desastres de MetroCluster
    entries:
    - title: C贸mo MetroCluster protege los datos y proporciona la recuperaci贸n ante
        desastres
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: Avisos legales
    url: "/legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
