---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html 
sidebar: sidebar 
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip 
summary: Antes de iniciar el proceso de transición, debe asegurarse de que la configuración cumpla los requisitos. 
---
= Requisitos para la transición de FC a IP sin interrupciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar el proceso de transición, compruebe que la configuración cumple los requisitos.

Puede realizar una transición de FC a IP sin interrupciones si la configuración cumple los siguientes requisitos:

* Si tiene una configuración de ocho nodos, todos los nodos ejecutan ONTAP 9.13.1 o una versión posterior.
* Si tiene una configuración de cuatro nodos, todos los nodos ejecutan ONTAP 9,8 o una versión posterior.
* Las plataformas nuevas y existentes son una combinación compatible para la transición.
+
link:concept_choosing_your_transition_procedure_mcc_transition.html["Plataformas compatibles para realizar transiciones sin interrupciones"]

* La configuración admite una configuración de clúster de switches.
+
https://hwu.netapp.com["Hardware Universe"^]



[CAUTION]
====
Si utiliza switches MetroCluster de almacenamiento compartido, solo puede realizar la transición a una configuración de IP de MetroCluster de cuatro nodos. No se admite la transición a una configuración de IP de MetroCluster de ocho nodos mediante switches MetroCluster de almacenamiento compartido. Después de completar la transición a una configuración de IP de MetroCluster para cuatro nodos, link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Expanda a una configuración IP de MetroCluster de ocho nodos"]puede .

====
* La configuración cumple todos los requisitos y se realiza mediante cable como se describe en los siguientes procedimientos _Instalación y configuración de MetroCluster_.
+
link:../install-fc/index.html["Instalación y configuración de MetroCluster estructural"]

+
link:../install-stretch/concept_considerations_differences.html["Instalación y configuración de MetroCluster con ampliación"]


