---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partir de ONTAP 9.13.1, puede ejecutar una transición no disruptiva de cargas de trabajo y datos desde una configuración FC de MetroCluster de ocho nodos existente a una nueva configuración de IP de MetroCluster. 
---
= Realizar la transición de forma no disruptiva de un FC de MetroCluster a una configuración IP de MetroCluster (ONTAP 9.8 y posterior)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar transiciones no disruptivas de cargas de trabajo y datos de una configuración FC de MetroCluster existente a una nueva configuración de IP de MetroCluster.

A partir de ONTAP 9.13.1, este procedimiento es compatible con las configuraciones IP de MetroCluster en las que MetroCluster y las bandejas de unidades están conectadas a los mismos switches IP (una configuración de switch de almacenamiento compartido).

A partir de ONTAP 9.13.1, puede realizar una transición no disruptiva de cargas de trabajo y datos desde una configuración MetroCluster FC de ocho nodos existente a una nueva configuración MetroCluster IP de ocho nodos.  Este procedimiento se utiliza para realizar la transición de un grupo FC DR de cuatro nodos, eliminar el grupo FC DR vacío y, a continuación, repetir el procedimiento para el segundo grupo FC DR. 

A partir de ONTAP 9.8, puede realizar una transición no disruptiva de cargas de trabajo y datos desde una configuración MetroCluster FC de cuatro nodos existente a una nueva configuración MetroCluster IP de cuatro nodos.  Una vez completada la transición, puede ampliarla a una configuración IP de MetroCluster de ocho nodos si fuera necesario. Verlink:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Expanda una configuración IP de MetroCluster"] .

* Este procedimiento no es disruptivo.
+
La configuración de MetroCluster puede continuar sirviendo datos durante la operación.

* Este procedimiento solo se aplica a configuraciones FC MetroCluster de cuatro y ocho nodos.
+
Si tiene una configuración MetroCluster FC de dos nodos, consulte link:concept_choosing_your_transition_procedure_mcc_transition.html["Cómo elegir el procedimiento de transición"].

* Este procedimiento describe los pasos necesarios para realizar la transición de un grupo FC de DR de cuatro nodos. Si tiene una configuración de ocho nodos (dos grupos DR de FC), debe repetir el procedimiento completo para cada grupo de DR de FC.
+

NOTE: Cuando agregue o elimine un grupo DR como parte de este procedimiento, debe verificar que la eliminación o adición del grupo DR se haya realizado correctamente antes de agregar o eliminar otro grupo DR.

* Debe cumplir con todos los requisitos y seguir todos los pasos del procedimiento.




[[transition-scenarios-supported-by-this-procedure]]
== Escenarios de transición compatibles con este procedimiento

Revisa la siguiente tabla para conocer los escenarios de transición compatibles con este procedimiento.


NOTE: En todos los escenarios de transición, solo puedes añadir o eliminar un único grupo de DR a la vez. Después de que la adición o eliminación del grupo de DR sea exitosa, necesitas verificar que el MetroCluster esté en buen estado y funcionando normalmente antes de continuar.

[cols="2*"]
|===
| En este escenario de transición... | Haz lo siguiente... 


 a| 
Configuración de FC de cuatro nodos a configuración IP de cuatro nodos
 a| 
Sigue este procedimiento tal y como se indica.



 a| 
Configuración de FC de cuatro nodos a IP de ocho nodos
 a| 
Es necesario añadir un grupo de IP DR de MetroCluster. Después de añadir el primer grupo de IP DR de MetroCluster, comprueba el estado general del clúster y repite los pasos para el segundo grupo de IP DR de MetroCluster.



 a| 
Configuración de FC de ocho nodos a IP de cuatro nodos
 a| 
Sigue este procedimiento tal y como se indica. Durante la transición, la configuración MetroCluster se ampliará de ocho nodos a doce nodos. Cuando termine la transición y todos los nodos FC MetroCluster estén desconectados, la configuración final será una configuración IP de cuatro nodos MetroCluster.



 a| 
Configuración de FC de ocho nodos a IP de ocho nodos
 a| 
Esta transición requiere añadir un grupo IP DR de MetroCluster al clúster.

Una vez que hayas comprobado el estado de la configuración de doce nodos, traslada los datos y los LIF (según sea necesario) de uno de los grupos DR de FC de MetroCluster al grupo DR de IP de MetroCluster. Cuando uno de los grupos DR de FC de MetroCluster esté vacío, elimina ese grupo DR y separa esos nodos. La configuración resultante es un clúster de ocho nodos compuesto por un grupo DR de FC de MetroCluster y un grupo DR de IP de MetroCluster.

A continuación, añade el segundo grupo de IP DR de MetroCluster al clúster y realiza la transición de los datos y las LIF (según sea necesario). Cuando el último grupo de FC DR de MetroCluster que quede esté vacío, elimínalo y separa esos nodos.

En ningún momento durante la transición, el número de nodos en la configuración MetroCluster no supera los doce nodos.

|===
Para más información, consulta la link:concept_transition_workflow_fc_to_ip_transition.html["Flujo de trabajo para una transición de MetroCluster sin interrupciones"].



[[important-information-when-adding-an-older-platform-model]]
== Información importante a la hora de añadir un modelo de plataforma más antiguo

La siguiente guía es para un escenario poco común en el que necesita agregar un modelo de plataforma más antiguo (plataformas lanzadas antes de ONTAP 9.15.1) a una configuración de MetroCluster existente que contiene un modelo de plataforma más nuevo (plataformas lanzadas en ONTAP 9.15.1 o posterior).  Para una transición de FC a IP de ocho nodos, esta guía se aplica si ha efectuado la transición de su primer grupo de recuperación ante desastres de FC a un modelo de plataforma introducido en ONTAP 9.15.1 o posterior y planea migrar el segundo grupo de recuperación ante desastres a una plataforma introducida antes de ONTAP 9.15.1.

Si su configuración de MetroCluster existente contiene una plataforma que utiliza *puertos de clúster/HA compartidos* (plataformas lanzadas en ONTAP 9.15.1 o posterior), no puede agregar una plataforma que utilice *puertos de MetroCluster/HA compartidos* (plataformas lanzadas antes de ONTAP 9.15.1) sin actualizar todos los nodos en la configuración a ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior.

[CAUTION]
====
Agregar un modelo de plataforma más antiguo que usa *puertos HA/ MetroCluster compartidos* a un MetroCluster que contiene un modelo de plataforma más nuevo que usa *puertos HA/clúster compartidos* es un escenario poco común y la mayoría de las combinaciones no se ven afectadas.

====
Utilice la siguiente tabla para verificar si su combinación está afectada.  Si su plataforma existente aparece en la primera columna y la plataforma que desea agregar a la configuración aparece en la segunda columna, todos los nodos de la configuración deben ejecutar ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior para agregar el nuevo grupo de DR.

[cols="20,20,20,20,20"]
|===
2+| Si su MetroCluster existente contiene... 2+| Y la plataforma que estás agregando es... | Realice lo siguiente... 


 a| 
Un sistema AFF que utiliza *puertos de alta disponibilidad/clúster compartidos*:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Un sistema FAS que utiliza *puertos de alta disponibilidad/clúster compartidos*:

* FAS50
* FAS70
* FAS90

 a| 
Un sistema AFF que utiliza *puertos MetroCluster/HA compartidos*:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* A700 de AFF
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Un sistema FAS que utiliza *puertos MetroCluster/HA compartidos*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Antes de agregar la nueva plataforma a su configuración existente de MetroCluster, actualice todos los nodos en la configuración existente y nueva a ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior. 
|===