---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partir de ONTAP 9.13.1, puede ejecutar una transición no disruptiva de cargas de trabajo y datos desde una configuración FC de MetroCluster de ocho nodos existente a una nueva configuración de IP de MetroCluster. 
---
= Realizar la transición de forma no disruptiva de un FC de MetroCluster a una configuración IP de MetroCluster (ONTAP 9.8 y posterior)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar transiciones no disruptivas de cargas de trabajo y datos de una configuración FC de MetroCluster existente a una nueva configuración de IP de MetroCluster.

A partir de ONTAP 9.13.1, este procedimiento es compatible con las configuraciones IP de MetroCluster en las que MetroCluster y las bandejas de unidades están conectadas a los mismos switches IP (una configuración de switch de almacenamiento compartido).

A partir de ONTAP 9.13.1, puede ejecutar una transición no disruptiva de cargas de trabajo y datos desde una configuración FC de MetroCluster de ocho nodos existente a una nueva configuración de IP de MetroCluster.

A partir de ONTAP 9,8, puede realizar una transición no disruptiva de cargas de trabajo y datos desde una configuración FC de MetroCluster de cuatro nodos existente a una nueva configuración de IP de MetroCluster.

* Este procedimiento no es disruptivo.
+
La configuración de MetroCluster puede continuar sirviendo datos durante la operación.

* Este procedimiento solo se aplica a configuraciones FC MetroCluster de cuatro y ocho nodos.
+
Si tiene una configuración MetroCluster FC de dos nodos, consulte link:concept_choosing_your_transition_procedure_mcc_transition.html["Cómo elegir el procedimiento de transición"].

* Este procedimiento describe los pasos necesarios para realizar la transición de un grupo FC de DR de cuatro nodos. Si tiene una configuración de ocho nodos (dos grupos DR de FC), debe repetir el procedimiento completo para cada grupo de DR de FC.
* Debe cumplir con todos los requisitos y seguir todos los pasos del procedimiento.


.Información adicional
Durante los procedimientos de transición, actualización y expansión, podría agregar un nuevo modelo de plataforma a su configuración de MetroCluster. En cualquier etapa de estos procedimientos, si su configuración de MetroCluster contiene una plataforma que utiliza *puertos de clúster/HA compartidos*, no podrá agregar una plataforma que utilice *puertos de MetroCluster/HA compartidos* a la configuración sin actualizar su versión de ONTAP a ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior.

Antes de decidir usar este procedimiento, revise detenidamente la información de la siguiente tabla. Si su plataforma actual aparece en la primera columna y la plataforma que desea agregar a la configuración aparece en la segunda, todos los nodos de la configuración deben ejecutar ONTAP 9.15.1P11, ONTAP 9.16.1P4 o posterior para que este procedimiento sea compatible.


CAUTION: La plataforma existente y la plataforma que desea agregar a la configuración deben ejecutar ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior.

[cols="20,20,20,20,20"]
|===
2+| Si su MetroCluster existente contiene... 2+| Y la plataforma que estás agregando es... | Realice lo siguiente... 


 a| 
Un sistema AFF que utiliza *puertos de alta disponibilidad/clúster compartidos*:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Un sistema FAS que utiliza *puertos de alta disponibilidad/clúster compartidos*:

* FAS50
* FAS70
* FAS90

 a| 
Un sistema AFF que utiliza *puertos MetroCluster/HA compartidos*:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* A700 de AFF
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Un sistema FAS que utiliza *puertos MetroCluster/HA compartidos*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Antes de agregar la nueva plataforma a su configuración existente de MetroCluster, actualice todos los nodos en la configuración existente y nueva a ONTAP 9.15.1P11 u ONTAP 9.16.1P4 o posterior. 
|===