---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: A partir de ONTAP 9.8, se admite la transición de datos y cargas de trabajo sin interrupciones de una configuración FC MetroCluster de cuatro nodos existente a una configuración IP nueva de MetroCluster. 
---
= Realizar la transición de forma no disruptiva de un FC de MetroCluster a una configuración IP de MetroCluster (ONTAP 9.8 y posterior)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.8, se admite la transición de datos y cargas de trabajo sin interrupciones de una configuración FC MetroCluster de cuatro nodos existente a una configuración IP nueva de MetroCluster.

* Este procedimiento se admite en sistemas que ejecutan ONTAP 9.8 y versiones posteriores.
* Este procedimiento no es disruptivo.
+
La configuración de MetroCluster puede continuar sirviendo datos durante la operación.

* Este procedimiento solo se aplica a configuraciones FC de MetroCluster de cuatro nodos.
+
Si tiene una configuración MetroCluster FC de dos nodos, consulte link:concept_choosing_your_transition_procedure_mcc_transition.html["Cómo elegir el procedimiento de transición"].

* Debe cumplir con todos los requisitos y seguir todos los pasos del procedimiento.

