---
permalink: transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: transition, metrocluster, node, fc, ip, iscsi, host, connection, moving, move, linux, set, up, add, report, removing, remove, rescan, path 
summary: Después de realizar la transición de los nodos MetroCluster de FC a IP, es posible que deba mover las conexiones de host iSCSI a los nodos nuevos. 
---
= Mover hosts iSCSI de Linux de nodos FC de MetroCluster a nodos IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de realizar la transición de los nodos MetroCluster de FC a IP, es posible que deba mover las conexiones de host iSCSI a los nodos nuevos.

En este procedimiento se crean interfaces IPv4.

Los comandos de host y los ejemplos que se dan en estos procedimientos son específicos de los sistemas operativos LINUX.



== Configuración de nuevas conexiones iSCSI

[role="lead"]
Para mover conexiones iSCSI, debe configurar conexiones iSCSI nuevas a los nodos IP de MetroCluster.

. Cree interfaces iSCSI en los nodos IP de MetroCluster y compruebe la conectividad ping de los clientes iSCSI a las nuevas interfaces IP en los nodos IP de MetroCluster.
+
https://docs.netapp.com/us-en/ontap/networking/create_a_lif.html["Creación de interfaces de red"^]

+
El cliente iSCSI debe acceder a todas las interfaces iSCSI de la SVM.

. En el host o cliente iSCSI, identifique las conexiones iSCSI existentes desde el host al nodo FC de MetroCluster: `iscsiadm -m session`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session

tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)

tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. Compruebe las conexiones del nodo IP de MetroCluster: `iscsi session show -vserver svm-name`
+
[listing]
----
node_A_1-IP::*> iscsi session show -vserver vsa_1

 Tpgroup Initiator Initiator

Vserver Name TSIH Name ISID Alias
--------- ------- ---- ------------------------ --------- ---------------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 scspr1789621001.gdl.englab.netapp.com
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 scspr1789621001.gdl.englab.netapp.com

2 entries were displayed.
----
. Enumere las interfaces de iSCSI en ONTAP para la SVM que contiene las interfaces: `iscsi interface show -vserver svm-name`
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi interface show -vserver vsa_1

 Logical Status Curr Curr

Vserver    Interface  TPGT Admin/Oper IP Address Node Port Enabled
---------- ---------- ---- ---------- --------------- ----------- ---- -------

vsa_1 iscsi_lf__n1_p1_ 1156 up/up 10.230.68.236 sti8200mcc-htp-001 e0g true
vsa_1 iscsi_lf__n1_p2_ 1157 up/up fd20:8b1e:b255:805e::78c9 sti8200mcc-htp-001 e0h true
vsa_1 iscsi_lf__n2_p1_ 1158 up/up 10.230.68.237 sti8200mcc-htp-002 e0g true
vsa_1 iscsi_lf__n2_p2_ 1159 up/up fd20:8b1e:b255:805e::78ca sti8200mcc-htp-002 e0h true
vsa_1 iscsi_lf__n3_p1_ 1183 up/up 10.226.43.134 sti8200mccip-htp-005 e0c true
vsa_1 iscsi_lf__n4_p1_ 1188 up/up 10.226.43.142 sti8200mccip-htp-006 e0c true

6 entries were displayed.
----
. En el cliente iSCSI, ejecute la detección en cualquiera de las direcciones IP de iSCSI en la SVM para detectar los nuevos destinos: `iscsiadm -m discovery -t sendtargets -p iscsi-ip-address`
+
La detección se puede ejecutar en cualquier dirección IP de la SVM, incluidas las interfaces que no son iSCSI.

+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m discovery -t sendtargets -p 10.230.68.236:3260

10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.226.43.134:3260,1183 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6
----
. En el cliente iSCSI, inicie sesión en todas las direcciones detectadas: `iscsiadm -m node -L all -T node-address -p portal-address -l`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m node -L all -T iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 -p 10.230.68.236:3260 -l

Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] (multiple)
Logging in to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] (multiple)
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.142,3260] successful.
Login to [iface: default, target: iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6, portal: 10.226.43.134,3260] successful.
----
. En el cliente iSCSI, compruebe el inicio de sesión y las conexiones: `iscsiadm -m session`
+
[listing]
----
[root@scspr1789621001 ~]# iscsiadm -m session

tcp: [1] 10.230.68.236:3260,1156 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [2] 10.230.68.237:3260,1158 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
tcp: [3] 10.226.43.142:3260,1188 iqn.1992-08.com.netapp:sn.58d7f6df2cc611eaa9c500a098a71638:vs.6 (non-flash)
----
. En el nodo MetroCluster, verifique el inicio de sesión y la conexión con el cliente: `iscsi initiator show -vserver vsa_1`
+
[listing]
----
sti8200mcchtp001htp_siteA::*> iscsi initiator show -vserver vsa_1

 Tpgroup Initiator

Vserver Name             TSIH Name                  ISID              Igroup Name
------- --------         ---- --------------------- ----------------- -----------------
vsa_1 iscsi_lf__n1_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:01 igroup_linux
vsa_1 iscsi_lf__n2_p1_ 4 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:02 igroup_linux
vsa_1 iscsi_lf__n3_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:04 igroup_linux
vsa_1 iscsi_lf__n4_p1_ 1 iqn.2020-01.com.netapp.englab.gdl:scspr1789621001 00:02:3d:00:00:03 igroup_linux

4 entries were displayed.
----


Al final de esta tarea, el cliente puede ver todas las interfaces iSCSI (en los nodos IP de MetroCluster y FC de MetroCluster) y ha iniciado sesión en todas esas interfaces.

Los LUN y volúmenes siguen alojados físicamente en los nodos FC. Dado que las LUN se notifican únicamente en las interfaces de nodos FC de MetroCluster, el cliente solo mostrará las rutas a través de nodos FC de MetroCluster. Esto se puede ver en los resultados de comandos sanlun lun show -p y multipath -ll -d. El siguiente paso es añadir nodos IP como nodos de generación de informes.

[listing]
----
[root@scspr1789621001 ~]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state     type       node     adapter     LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_

[root@scspr1789621001 ~]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


== Añadir nodos IP de MetroCluster como nodos de generación de informes

[role="lead"]
Después de configurar las conexiones con los nodos IP de MetroCluster nuevos, debe añadir nodos de generación de informes nuevos.

. En el nodo MetroCluster, enumere los nodos de generación de informes de las LUN de la SVM: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
Los siguientes nodos de generación de informes son nodos locales, ya que las LUN se encuentran físicamente en los nodos FC node_A_1-FC y node_A_2-FC.

+
[listing]
----
node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-FC,node_A_2-FC
.
.
.
vsa_1 /vol/vsa_1_vol9/lun_linux_19 igroup_linux node_A_1-FC,node_A_2-FC
12 entries were displayed.
----
. En el nodo MetroCluster, añada nodos de generación de informes: `lun mapping add-reporting-nodes -vserver svm-name -path /vol/vsa_1_vol*/lun_linux_* -nodes node1,node2 -igroup igroup_linux`
+
[listing]
----
node_A_1-IP::*> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes node_A_1-IP,node_A_2-IP
-igroup igroup_linux

12 entries were acted on.
----
. En el nodo MetroCluster, compruebe que los nodos recién añadidos estén presentes: `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes`
+
[listing]
----

node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux vserver path igroup reporting-nodes
------- --------------------------- ------------ -------------------------------------------------------------------------------

vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux node_A_1-FC,node_A_2-FC,node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux node_A_1-FC,node_A_2-FC,node_A_1-IP,node_A_2-IP.
.
.
.

12 entries were displayed.
----
. Compruebe que el `sg3-utils` El paquete se instala en el host Linux. Esto evita un `rescan-scsi-bus.sh utility not found` Error al volver a analizar el host Linux para los LUN recién asignados mediante el `rescan-scsi-bus` comando.
. En el host, emita el siguiente comando para volver a analizar el bus SCSI en el host y detectar las rutas recién agregadas: `/usr/bin/rescan-scsi-bus.sh -a`
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
. En el host, emita el siguiente comando para enumerar las rutas recientemente añadidas: `sanlun lun show -p`
+
Se muestran cuatro rutas para cada LUN.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
. En el MetroCluster, mueva los volúmenes que contienen LUN de nodos FC a IP.
+
[listing]
----
node_A_1-IP::*> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate sti8200mccip_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "sti8200mccip_htp_005_aggr1". Use the "volume move show -vserver
vsa_1 -volume vsa_1_vol1" command to view the status of this operation.
node_A_1-IP::*> vol move show
Vserver    Volume     State       Move       Phase            Percent-Complete  Time-To-Complete
---------  ---------- --------    ---------- ---------------- ----------------  ----------------
vsa_1     vsa_1_vol1  healthy                initializing     -                 -
----
. Una vez completado el movimiento de volúmenes, en la MetroCluster, utilice el comando volume show para confirmar que el volumen o LUN están en línea.
. Las interfaces iSCSI de los nodos IP de MetroCluster donde reside el LUN ahora se actualizan como rutas principales. Si la ruta principal no se actualiza después de mover el volumen, ejecute /usr/bin/rescan-scsi-bus.sh -a y multipath -v3 o simplemente espere a que tenga lugar el reexamen multipath.
+
En el ejemplo siguiente, la ruta principal es una LIF en el nodo IP de MetroCluster.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ -----------------------
host vserver
path path /dev/ host vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ------------------------
up        primary    sdag    host4        iscsi_lf__n4_p1_
up        secondary  sdk     host3        iscsi_lf__n2_p1_
up        secondary  sdh     host2        iscsi_lf__n1_p1_
up        secondary  sdah    host5        iscsi_lf__n3_p1_
----




== Eliminación de nodos de generación de informes y rutas de reexploración

[role="lead"]
Debe quitar los nodos de informes y volver a analizar las rutas.

. En el nodo IP de MetroCluster, quite los nodos de generación de informes remotos (los nodos IP de MetroCluster) para los LUN de Linux: `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
En este caso, los nodos remotos son nodos FC.

+
[listing]
----
node_A_1-IP::*> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true

12 entries were acted on.
----
. En el nodo IP de MetroCluster, compruebe los nodos de generación de informes para las LUN: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
node_A_1-IP::*> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup      reporting-nodes
------- --------------------------- ------------ -----------------------------------------

vsa_1 /vol/vsa_1_vol1/lun_linux_2   igroup_linux  node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol1/lun_linux_3   igroup_linux  node_A_1-IP,node_A_2-IP
vsa_1 /vol/vsa_1_vol2/lun_linux_4   group_linux   node_A_1-IP,node_A_2-IP
.
.
.

12 entries were displayed.
----
. Compruebe que el `sg3-utils` El paquete se instala en el host Linux. Esto evita un `rescan-scsi-bus.sh utility not found` Error al volver a analizar el host Linux para los LUN recién asignados mediante el `rescan-scsi-bus` comando.
. En el host iSCSI, vuelva a analizar el bus SCSI: `/usr/bin/rescan-scsi-bus.sh -r`
+
Las rutas que se quitan son las rutas de los nodos FC.

+
[listing]
----
[root@scspr1789621001 ~]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
 .
.
.
----
. En el host iSCSI, compruebe que solo se puedan ver las rutas desde los nodos IP de MetroCluster:
+
`sanlun lun show -p`

+
`multipath -ll -d`


