---
permalink: transition/task_configure_the_new_nodes_and_complete_transition.html 
sidebar: sidebar 
keywords: node, complete, transition, configure, metrocluster, ip, node, configuring, disabling, disable, data, set, up, lif, bring, svm, moving, move, system, volume 
summary: Con los nuevos nodos añadidos, debe completar los pasos de transición y configurar los nodos IP de MetroCluster. 
---
= Configurar los nodos nuevos y completar la transición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con los nuevos nodos añadidos, debe completar los pasos de transición y configurar los nodos IP de MetroCluster.



== Configurar los nodos IP de MetroCluster y deshabilitar la transición

Debe implementar las conexiones IP de MetroCluster, actualizar la configuración de MetroCluster y deshabilitar el modo de transición.

. Forme los nodos nuevos en un grupo de recuperación ante desastres emitiendo los siguientes comandos desde Controller node_A_1-IP:
+
`metrocluster configuration-settings dr-group create -partner-cluster peer-cluster-name -local-node local-controller-name -remote-node remote-controller-name`

+
`metrocluster configuration-settings dr-group show`

. Create MetroCluster interfaces IP (node_A_1-IP, node_A_2-IP, node_B_1-IP, node_B_2-IP) -- se necesitan crear dos interfaces por controladora; ocho interfaces en total:
+
`metrocluster configuration-settings interface create -cluster-name cluster-name -home-node controller-name -home-port port -address ip-address -netmask netmask -vlan-id vlan-id``metrocluster configuration-settings interface show`

+

NOTE: A partir de ONTAP 9.9.1, si utiliza una configuración de capa 3, también debe especificar el `-gateway` Al crear interfaces IP de MetroCluster. Consulte link:../install-ip/concept_considerations_layer_3.html["Consideraciones sobre las redes de área amplia de capa 3"].

+
El parámetro -vlan-id solo es obligatorio si no utiliza los identificadores de VLAN predeterminados. Solo ciertos sistemas admiten identificadores de VLAN no predeterminados.

+
--
[NOTE]
====
** Algunas plataformas utilizan una VLAN para la interfaz de IP de MetroCluster. De manera predeterminada, cada uno de los dos puertos utiliza una VLAN diferente: 10 y 20. También puede especificar una VLAN diferente (no predeterminada) mayor que 100 (entre 101 y 4095) mediante el `-vlan-id parameter` en la `metrocluster configuration-settings interface create` comando.
** A partir de ONTAP 9.9.1, si utiliza una configuración de capa 3, también debe especificar el `-gateway` Al crear interfaces IP de MetroCluster. Consulte link:../install-ip/concept_considerations_layer_3.html["Consideraciones sobre las redes de área amplia de capa 3"].


====
--
+
Los siguientes modelos de plataforma se pueden añadir a la configuración de MetroCluster existente si las VLAN utilizadas son 10/20 o superiores a 100. Si se usan otras VLAN, no es posible agregar estas plataformas a la configuración existente, ya que no se puede configurar la interfaz de MetroCluster. Si utiliza cualquier otra plataforma, la configuración de VLAN no es relevante, ya que no es necesaria en ONTAP.

+
|===


| Plataformas AFF | Plataformas FAS 


 a| 
** AFF A220
** AFF A250
** AFF A400

 a| 
** FAS2750
** FAS500f
** FAS8300
** FAS8700


|===


. Ejecute la operación de conexión MetroCluster desde Controller node_A_1-IP para conectar los sitios MetroCluster;- esta operación puede tardar unos minutos en completarse:
+
`metrocluster configuration-settings connection connect`

. Compruebe que los discos del clúster remoto son visibles en cada controladora a través de las conexiones iSCSI:
+
`disk show`

+
Debería ver los discos remotos que pertenecen al resto de nodos de la configuración.

. Refleje el agregado raíz para node_A_1-IP y node_B_1-IP:
+
`aggregate mirror -aggregate root-aggr`

. Asigne discos para node_A_2-IP y node_B_2-IP.
+
Asignaciones de disco de pool 1 donde ya se han realizado para nodo_A_1-IP y nodo_B_1-IP cuando se emitió el comando boot_after_mcc_transtion en el menú de arranque.

+
.. Emita los siguientes comandos en node_A_2-IP:
+
`disk assign disk1disk2disk3 ... diskn -sysid node_B_2-IP-controller-sysid -pool 1 -force`

.. Emita los siguientes comandos en node_B_2-IP:
+
`disk assign disk1disk2disk3 ... diskn -sysid node_A_2-IP-controller-sysid -pool 1 -force`



. Confirmar que se ha actualizado la propiedad de los discos remotos:
+
`disk show`

. Si es necesario, actualice la información de propiedad con los siguientes comandos:
+
.. Vaya al modo de privilegio avanzado e introduzca y cuando se le solicite continuar:
+
`set priv advanced`

.. Actualizar la propiedad de disco:
+
`disk refresh-ownership controller-name`

.. Volver al modo admin:
+
`set priv admin`



. Refleje los agregados raíz para node_A_2-IP y node_B_2-IP:
+
`aggregate mirror -aggregate root-aggr`

. Compruebe que la resincronización del agregado se haya completado para los agregados raíz y de datos:
+
`aggr show``aggr plex show`

+
La resincronización puede demorar un tiempo, pero debe completarse antes de continuar con los siguientes pasos.

. Actualice la configuración de MetroCluster para incorporar los nodos nuevos:
+
.. Vaya al modo de privilegio avanzado e introduzca y cuando se le solicite continuar:
+
`set priv advanced`

.. Actualice la configuración:
+
|===


| Si configuró... | Emita este comando... 


 a| 
Un único agregado en cada clúster:
 a| 
`metrocluster configure -refresh true -allow-with-one-aggregate true`



 a| 
Más de un único agregado en cada clúster
 a| 
`metrocluster configure -refresh true`

|===
.. Volver al modo admin:
+
`set priv admin`



. Desactivar el modo de transición de MetroCluster:
+
.. Entre en el modo de privilegio avanzado y escriba "'y'" cuando se le solicite continuar:
+
`set priv advanced`

.. Desactivar el modo de transición:
+
`metrocluster transition disable`

.. Volver al modo admin:
+
`set priv admin`







== Configurar LIF de datos en los nuevos nodos

Debe configurar LIF de datos en los nodos nuevos, node_A_2-IP y node_B_2-IP.

Debe añadir todos los puertos nuevos disponibles en las controladoras nuevas a un dominio de retransmisión si todavía no le han asignado uno. Si es necesario, cree VLAN o grupos de interfaces en los puertos nuevos. Consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["Gestión de redes y LIF"^]

. Identifique el uso del puerto y los dominios de retransmisión actuales:
+
`network port show``network port broadcast-domain show`

. Añada puertos a dominios de retransmisión y VLAN como corresponda.
+
.. Vea los espacios IP:
+
`network ipspace show`

.. Cree espacios IP y asigne puertos de datos según sea necesario.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-69120CF0-F188-434F-913E-33ACB8751A5D.html["Configurar espacios IP (solo administradores de clúster)"^]

.. Vea los dominios de retransmisión:
+
`network port broadcast-domain show`

.. Añada cualquier puerto de datos a un dominio de retransmisión según sea necesario.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["Agregar o quitar puertos de un dominio de retransmisión"^]

.. Vuelva a crear las VLAN y los grupos de interfaces según sea necesario.
+
La pertenencia a la VLAN y al grupo de interfaces puede ser diferente de la del nodo antiguo.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["Creación de una VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["Combinación de puertos físicos para crear grupos de interfaces"^]



. Compruebe que los LIF se alojan en el nodo y los puertos adecuados en los nodos IP de MetroCluster (incluida la SVM con Vserver -mc) según sea necesario.
+
Vea la información recopilada en link:task_connect_the_mcc_ip_controller_modules_2n_mcc_transition_supertask.html["Creación de la configuración de red"].

+
.. Compruebe el puerto de inicio de las LIF:
+
`network interface show -field home-port`

.. Si es necesario, modifique la configuración de LIF:
+
`vserver config override -command "network interface modify -vserver vserver_name -home-port active_port_after_upgrade -lif lif_name -home- node new_node_name"`

.. Revierte los LIF a sus puertos principales:
+
`network interface revert * -vserver _vserver_name_`







== Ponga en marcha las SVM

Debido a los cambios si la configuración de LIF, debe reiniciar las SVM en los nodos nuevos.

.Pasos
. Compruebe el estado de las SVM:
+
`metrocluster vserver show`

. Reinicie las SVM en cluster_A que no tengan un sufijo "'-mc":
+
`vserver start -vserver svm-name -force true`

. Repita los pasos anteriores en el clúster de partners.
. Compruebe que todas las SVM estén en buen estado:
+
`metrocluster vserver show`

. Compruebe que todas las LIF de datos están en línea:
+
`network interface show`





== Mover un volumen del sistema a los nodos nuevos

Para mejorar la resiliencia, debe moverse un volumen del sistema desde Controller node_A_1-IP a Controller node_A_2-IP, y también desde node_B_1-IP a node_B_2-IP. Debe crear un agregado reflejado en el nodo de destino para el volumen del sistema.

.Acerca de esta tarea
Los volúmenes del sistema tienen el nombre "VDM\_CRS_*\_A" o "VDV_CRS_*\_B." Las designaciones «»_A» y «»_B» no están relacionadas con las referencias del sitio a y del sitio B utilizadas en esta sección; por ejemplo, MDV_CRS_*_A no está asociado con el sitio_A.

.Pasos
. Asigne al menos tres discos de pool 0 y tres discos de pool 1 para las controladoras node_A_2-IP y node_B_2-IP como sea necesario.
. Habilitar la asignación automática de discos.
. Mueva el volumen del sistema _B de node_A_1-IP a node_A_2-IP siguiendo los pasos siguientes de site_A.
+
.. Cree un agregado reflejado en node_A_2-IP de la controladora para alojar el volumen del sistema:
+
`aggr create -aggregate new_node_A_2-IP_aggr -diskcount 10 -mirror true -node nodename_node_A_2-IP`

+
`aggr show`

+
El agregado reflejado requiere cinco discos de repuesto de pool 0 y cinco pools 1 propiedad del nodo de la controladora_A_2-IP.

+
La opción avanzada « »-force-small-aggregate true» se puede utilizar para limitar el uso del disco a 3 discos de los pools 0 y 3 discos de los pools 1, si los discos se encuentran en un acceso breve.

.. Enumere los volúmenes del sistema asociados con la SVM de administrador:
+
`vserver show`

+
`volume show -vserver _admin-vserver-name_`

+
Debe identificar los volúmenes contenidos por agregados que pertenecen a Site_A. También se mostrarán los volúmenes del sistema Site_B.



. Mueva el volumen del sistema MDV_CRS_*_B del sitio_A al agregado reflejado creado en el nodo_A_2-IP del controlador
+
.. Compruebe los posibles agregados de destino:
+
`volume move target-aggr show -vserver _admin-vserver-name_ -volume system_vol_MDV_B`

+
Debe aparecer el agregado recién creado en node_A_2-IP.

.. Mueva el volumen al agregado recién creado en node_A_2-IP:
+
`set advanced`

+
`volume move start -vserver _admin-vserver_ -volume system_vol_MDV_B -destination-aggregate new_node_A_2-IP_aggr -cutover-window 40`

.. Compruebe el estado de la operación de movimiento:
+
`volume move show -vserver _admin-vserver-name_ -volume system_vol_MDV_B`

.. Una vez completada la operación de movimiento, compruebe que el nuevo agregado del sistema MDV_CRS_*_B está contenido en node_A_2-IP:
+
`set admin`

+
`volume show -vserver _admin-vserver_`



. Repita los pasos anteriores en site_B (node_B_1-IP y node_B_2-IP).

