---
permalink: transition/task_move_an_fc_san_workload_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: non-disruptively, transition, metrocluster, fc, ip, node, san, host, moving, move 
summary: Cuando se realiza la transición sin interrupciones de los nodos FC a IP de MetroCluster, se deben mover objetos de host SAN FC sin interrupciones de los nodos IP a FC de MetroCluster. 
---
= Mover una carga de trabajo DE SAN FC de MetroCluster a nodos IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se realiza la transición sin interrupciones de los nodos FC a IP de MetroCluster, se deben mover objetos de host SAN FC sin interrupciones de los nodos IP a FC de MetroCluster.

. Configure nuevas interfaces FC (LIF) en los nodos IP de MetroCluster:
+
.. Si es necesario, en los nodos IP de MetroCluster, modifique los puertos FC que se utilizarán para establecer la conectividad del cliente con la personalidad de destino FC.
+
Esto puede requerir un reinicio de los nodos.

.. Crear LIFS/interfaces FC en nodos IP para todas las SVM de SAN. De manera opcional, compruebe que los WWPN de los LIF FC recién creados estén registrados en el switch SAN FC


. Actualice la configuración de particiones DE SAN para los LIF FC recién añadidos a los nodos IP de MetroCluster.
+
Para facilitar el movimiento de volúmenes que contienen LUN que sirven datos activamente a clientes SAN FC, actualice las zonas de switches FC existentes para permitir que los clientes SAN FC accedan a LUN de nodos IP de MetroCluster.

+
.. En el switch SAN FC (Cisco o Brocade), añada los WWPN de las LIF SAN FC recién añadidas a la zona.
.. Actualice, guarde y confirme los cambios en la división en zonas.
.. Desde el cliente, compruebe si hay inicios de sesión de iniciador de FC a las nuevas LIF DE SAN en los nodos IP de MetroCluster: `sanlun lun show -p`
+
En este momento, el cliente debe ver y estar iniciado sesión en las interfaces FC en los nodos IP de MetroCluster y FC de MetroCluster. Los LUN y volúmenes siguen alojados físicamente en los nodos FC de MetroCluster.

+
Dado que las LUN se notifican únicamente en las interfaces de nodos FC de MetroCluster, el cliente solo muestra rutas a través de nodos FC. Esto se puede ver en la salida del `sanlun lun show -p` y.. `multipath -ll -d` comandos.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_

[root@stemgr]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


. Modifique los nodos de generación de informes para añadir los nodos IP de MetroCluster
+
.. Enumerar los nodos de generación de informes para las LUN en la SVM: `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux`
+
Los nodos de generación de informes que se muestran son nodos locales, ya que las LUN se encuentran físicamente en los nodos FC A_1 y A_2.

+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup         reporting-nodes
-------  --------------------------- ------------   -------------------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol1/lun_linux_3 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol2/lun_linux_4 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol3/lun_linux_7 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_8 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_9 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_12 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_13 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol7/lun_linux_14 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol8/lun_linux_17 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_18 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_19 igroup_linux  A_1,A_2
12 entries were displayed.
----
.. Añada nodos de generación de informes para incluir nodos IP de MetroCluster.
+
[listing]
----
cluster_A::> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes B_1,B_2 -igroup igroup_linux

12 entries were acted on.
----
.. Enumerar nodos de generación de informes y verificar la presencia de los nuevos nodos:
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path                          igroup          reporting-nodes
------- ---------------------------   ------------    -------------------------------------------------------------------------------

vsa_1   /vol/vsa_1_vol1/lun_linux_2   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol1/lun_linux_3   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol2/lun_linux_4   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol3/lun_linux_7   igroup_linux    A_1,A_2,B_1,B_2
...

12 entries were displayed.
----
.. Compruebe que el `sg3-utils` El paquete se instala en el host Linux. Esto evita un `rescan-scsi-bus.sh utility not found` Error al volver a analizar el host Linux para los LUN recién asignados mediante el `rescan-scsi-bus` comando.
.. Vuelva a analizar el bus SCSI en el host para detectar las rutas recién añadidas: `/usr/bin/rescan-scsi-bus.sh -a`
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
.. Mostrar las rutas recién agregadas: `sanlun lun show -p`
+
Cada LUN tendrá cuatro rutas.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
.. En las controladoras, mueva los volúmenes que contienen LUN de MetroCluster FC a los nodos IP de MetroCluster.
+
[listing]
----
cluster_A::> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate A_1_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "A_1_htp_005_aggr1". Use the "volume move show -vserver vsa_1 -volume vsa_1_vol1"
command to view the status of this operation.
cluster_A::> volume move show
Vserver    Volume    State    Move Phase   Percent-Complete Time-To-Complete
--------- ---------- -------- ----------   ---------------- ----------------
vsa_1     vsa_1_vol1 healthy  initializing
 - -
----
.. En el cliente SAN FC, muestre la información de la LUN: `sanlun lun show -p`
+
Las interfaces de FC de los nodos IP de MetroCluster donde reside el LUN ahora se actualizan como rutas principales. Si la ruta principal no se actualiza después de mover el volumen, ejecute /usr/bin/rescan-scsi-bus.sh -a o simplemente espere a que tenga lugar el reexamen multipath.

+
La ruta principal del ejemplo siguiente es la LIF del nodo IP de MetroCluster.

+
[listing]
----
[root@localhost ~]# sanlun lun show -p

                    ONTAP Path: vsa_1:/vol/vsa_1_vol1/lun_linux_2
                           LUN: 22
                      LUN Size: 2g
                       Product: cDOT
                   Host Device: 3600a098038302d324e5d50305063546e
              Multipath Policy: service-time 0
            Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host      vserver
path      path       /dev/   host         vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sddv    host6        fc_5
up        primary    sdjx    host7        fc_6
up        secondary  sdgv    host6        fc_8
up        secondary  sdkr    host7        fc_8
----
.. Repita los pasos anteriores para todos los volúmenes, LUN e interfaces FC que pertenecen a un host SAN FC.
+
Una vez finalizado, todos los LUN de un host de SVM y FC SAN deberían estar en nodos IP de MetroCluster.



. Quite los nodos de informes y las rutas de nuevo análisis del cliente.
+
.. Quite los nodos de generación de informes remotos (los nodos FC de MetroCluster) para los LUN de linux: `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
[listing]
----
cluster_A::> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
.. Compruebe los nodos de creación de informes para las LUN: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -----------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol2/lun_linux_4 igroup_linux B_1,B_2
...

12 entries were displayed.
----
.. Vuelva a escanear el bus SCSI en el cliente: `/usr/bin/rescan-scsi-bus.sh -r`
+
Se quitan las rutas de los nodos FC de MetroCluster:

+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
...
----
.. Verifique que solo las rutas de los nodos IP de MetroCluster sean visibles en el host: `sanlun lun show -p`
.. Si es necesario, quite LIF iSCSI de los nodos FC de MetroCluster.
+
Esto debe hacerse si no hay otras LUN en los nodos asignados a otros clientes.




