---
permalink: transition/task_move_data_to_new_drive_shelves.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Durante la transición, se mueven los datos de las bandejas de unidades en la configuración FC de MetroCluster a la nueva configuración IP de MetroCluster. 
---
= Mover los datos a las bandejas de unidades nuevas
:allow-uri-read: 


[role="lead"]
Durante la transición, se mueven los datos de las bandejas de unidades en la configuración FC de MetroCluster a la nueva configuración IP de MetroCluster.

.Antes de empezar
Debe crear nuevos LIF DE SAN en los nodos IP o de destino y conectar hosts antes de mover los volúmenes a nuevos agregados.

. Para reanudar la generación automática de casos de soporte, envíe un mensaje de AutoSupport para indicar que se ha completado el mantenimiento.
+
.. Emita el siguiente comando: `system node autosupport invoke -node * -type all -message MAINT=end`
.. Repita el comando en el clúster de partners.


. Mueva los volúmenes de datos a agregados en las nuevas controladoras, de un volumen a la vez.
+
Utilice el procedimiento descrito en http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/GUID-AFE432F6-60AD-4A79-86C0-C7D12957FA63.html["Crear un agregado y mover volúmenes a los nuevos nodos"].

. Cree LIF SAN en los nodos añadidos recientemente.
+
Utilice el procedimiento siguiente en http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-expand/GUID-E3BB89AF-6251-4210-A979-130E845BC9A1.html["Actualizar las rutas de LUN para los nodos nuevos"^].

. Compruebe si hay alguna licencia de nodo bloqueado en los nodos FC. Si hay alguna, deberán añadirse a los nodos recién añadidos.
+
Utilice el procedimiento siguiente en http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-expand/GUID-487FAC36-3C5C-4314-B4BD-4253CB67ABE8.html["Agregar licencias bloqueadas por nodo"^].

. Migre los LIF de datos.
+
Utilice el procedimiento descrito en  http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/GUID-95CA9262-327D-431D-81AA-C73DEFF3DEE2.html["Traslado de LIF de datos no SAN y LIF de administración del clúster a los nuevos nodos"^] Pero *no* realice los dos últimos pasos para migrar LIF de administración de clúster.



[NOTE]
====
* No se puede migrar una LIF que se usa para operaciones de descarga de copias con las API de VMware vStorage para la integración de cabinas (VAAI).
* Después de completar la transición de los nodos MetroCluster de FC a IP, es posible que deba mover las conexiones de host iSCSI a los nodos nuevos, consulte link:task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html["Mover hosts iSCSI de Linux de nodos FC de MetroCluster a nodos IP de MetroCluster."]


====