---
permalink: upgrade/task_verify_the_state_of_the_mcc_configuration_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, verify, state, configuration 
summary: 'Debe identificar las controladoras existentes y confirmar las relaciones de recuperación ante desastres \(DR\) entre ellas, que las controladoras están en modo normal y que los agregados se han duplicado.' 
---
= Verificar el estado de la configuración de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe identificar las controladoras existentes y confirmar las relaciones de recuperación ante desastres (DR) entre ellas, que las controladoras están en modo normal y que los agregados se han duplicado.

.Pasos
. Muestre los detalles de los nodos en la configuración de MetroCluster desde cualquier nodo de la configuración:
+
`metrocluster node show -fields node,dr-partner,dr-partner-systemid`

+
El siguiente resultado muestra que esta configuración MetroCluster tiene un solo grupo de recuperación ante desastres y un nodo en cada clúster.

+
[listing]
----
cluster_A::> metrocluster node show -fields node,dr-partner,dr-partner-systemid

dr-group-id  cluster         node            dr-partner      dr-partner-systemid
-----------  -------------   -------         ----------      -------------------
1            cluster_A       controller_A_1  controller_B_1  536946192
1            cluster_B       controller_B_1  controller_A_1  536946165
2 entries were displayed.
----
. Muestra el estado de la configuración de MetroCluster:
+
`metrocluster show`

+
El siguiente resultado muestra que los nodos existentes en la configuración de MetroCluster están en modo normal:

+
[listing]
----

cluster_A::> metrocluster show

Configuration: two-node-fabric

Cluster                        Entry Name             State
------------------------------ ---------------------- ---------------------
Local: cluster_A               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
Remote: controller_B_1_siteB
                               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
----
. Compruebe el estado de los agregados de cada nodo en la configuración de MetroCluster:
+
`storage aggregate show`

+
El siguiente resultado muestra que los agregados en cluster_A están en línea y reflejados:

+
[listing]
----
cluster_A::> storage aggregate show


Aggregate                Size     Available Used%  State   #Vols  Nodes            RAID Status
---------                -------- --------- -----  ------- ------ ---------------- ------------
aggr0_controller_A_1_0   1.38TB   68.63GB   95%    online    1    controller_A_1   raid_dp,mirrored
controller_A_1_aggr1     4.15TB   4.14TB    0%     online    2    controller_A_1   raid_dp,mirrored
controller_A_1_aggr2     4.15TB   4.14TB    0%     online    1    controller_A_1   raid_dp,mirrored
3 entries were displayed.

cluster_A::>
----

