---
permalink: upgrade/task-expand-four-to-eight-mcc-fc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: Debe crear un agregado de datos reflejados en cada nodo del grupo de recuperación ante desastres. 
---
= Crea un agregado de datos reflejados en cada nodo FC de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear un agregado de datos reflejados en cada nodo del grupo de recuperación ante desastres.

.Acerca de esta tarea
* Debe conocer qué unidades se utilizarán en el nuevo agregado.
* Si tienes varios tipos de unidades en tu sistema (almacenamiento heterogéneo), deberías entender cómo puedes asegurarte de que se selecciona el tipo de unidad correcto.
* Las unidades son propiedad de un nodo específico; cuando se crea un agregado, todas las unidades de ese agregado deben ser propiedad del mismo nodo, que se convierte en el nodo inicial para ese agregado.
+
En los sistemas que utilizan ADP, los agregados se crean utilizando particiones en las que cada unidad se divide en particiones P1, P2 y P3.

* Los nombres de agregados deben ajustarse al esquema de nomenclatura que se determinó al planificar la configuración de MetroCluster.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Gestión de discos y agregados"]

* Los nombres de los agregados deben ser únicos en todos los sitios MetroCluster. Esto significa que no puedes tener dos agregados diferentes con el mismo nombre en el sitio A y en el sitio B.



NOTE: Se recomienda que mantengas al menos un 20% de espacio libre para los agregados reflejados para un rendimiento y disponibilidad óptimos del almacenamiento. Aunque la recomendación es 10% para los agregados no reflejados, el 10% adicional de espacio puede ser usado por el sistema de archivos para absorber cambios incrementales. Los cambios incrementales aumentan la utilización del espacio para los agregados reflejados debido a la arquitectura de ONTAP basada en Snapshot de copia sobre escritura. No seguir estas prácticas recomendadas podría tener un impacto negativo en el rendimiento.

.Pasos
. Mostrar una lista de repuestos disponibles:
+
`storage disk show -spare -owner <node_name>`

. Cree el agregado:
+
`storage aggregate create -mirror true`

+
Si has iniciado sesión en el clúster en la interfaz de gestión del clúster, puedes crear un agregado en cualquier nodo del clúster. Para verificar que el agregado se crea en un nodo específico, usa el parámetro `-node` o especifica las unidades que son propiedad de ese nodo.

+
Puede especificar las siguientes opciones:

+
** Nodo principal del agregado (es decir, el nodo al que pertenece el agregado en un funcionamiento normal)
** Lista de unidades específicas que se añadirán al agregado
** Cantidad de unidades que se incluirán
+

NOTE: En la configuración mínima admitida, en la que haya disponible una cantidad limitada de unidades, debe utilizar la opción force-small-aggregate para permitir la creación de un agregado de tres discos RAID-DP.

** Estilo de suma de comprobación que se utilizará para el agregado
** El tipo de unidades que se van a utilizar
** El tamaño de las unidades que se van a utilizar
** Conduzca la velocidad que se va a utilizar
** Tipo de RAID para grupos RAID en el agregado
** Cantidad máxima de unidades que se pueden incluir en un grupo RAID
** Si se permiten unidades con RPM diferentes
+
Para obtener más información acerca de estas opciones, consulte `storage aggregate create` página de manual.

+
El siguiente comando crea un agregado con 10 discos:

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. Compruebe el grupo RAID y las unidades del nuevo agregado:
+
`storage aggregate show-status -aggregate <aggregate-name>`


