---
permalink: upgrade/task_check_for_mcc_configuration_errors_with_config_advisor.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, check, configuration, errors, config, advisor 
summary: Puede ir al sitio de soporte de NetApp y descargar la herramienta Config Advisor para comprobar si hay errores de configuración comunes. 
---
= Comprobación de errores de configuración de MetroCluster con Config Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ir al sitio de soporte de NetApp y descargar la herramienta Config Advisor para comprobar si hay errores de configuración comunes.

.Acerca de esta tarea
Config Advisor es una herramienta de validación de configuración y comprobación del estado. Puede implementarlo tanto en sitios seguros como en sitios no seguros para la recopilación de datos y el análisis del sistema.


NOTE: El soporte para Config Advisor es limitado y solo está disponible en línea.

.Pasos
. Vaya a la página de descarga de Config Advisor y descargue la herramienta.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"]

. Ejecute Config Advisor, revise el resultado de la herramienta y siga las recomendaciones del resultado para solucionar los problemas detectados.

