---
permalink: upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, refresh, configuration, new, controller 
summary: Es necesario actualizar la configuración de MetroCluster al ampliarla de una configuración de dos nodos a una de cuatro nodos. 
---
= Actualizar la configuración de MetroCluster con nuevas controladoras
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario actualizar la configuración de MetroCluster al ampliarla de una configuración de dos nodos a una de cuatro nodos.



== Active el registro de la consola

NetApp recomienda encarecidamente que habilite el inicio de sesión de la consola en los dispositivos que esté utilizando y realice las siguientes acciones al realizar este procedimiento:

* Deje la función AutoSupport habilitada durante el mantenimiento.
* Active un mensaje de AutoSupport de mantenimiento antes y después de las tareas de mantenimiento para deshabilitar la creación de casos durante la actividad de mantenimiento.
+
Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Cómo impedir la creación automática de casos durante las ventanas de mantenimiento programado"^].

* Habilite el registro de sesiones para cualquier sesión de CLI. Para obtener instrucciones sobre cómo activar el registro de sesiones, consulte la sección Salida de sesión de registro en el artículo de la Base de conocimientos link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Cómo configurar PuTTY para una conectividad óptima con sistemas ONTAP"^].




== Realice el procedimiento de actualización

.Pasos
. Actualice la configuración de MetroCluster:
+
.. Entre en el modo de privilegio avanzado: +
`set -privilege advanced`
.. Actualice la configuración de MetroCluster: +
`metrocluster configure -refresh true -allow-with-one-aggregate true`
+
El siguiente comando actualiza la configuración del MetroCluster en todos los nodos del grupo DR que contiene Controller_A_1:

+
[listing]
----
controller_A_1::*> metrocluster configure -refresh true -allow-with-one-aggregate true

[Job 726] Job succeeded: Configure is successful.
----
.. Volver al modo de privilegios de administrador:
+
`set -privilege admin`



. Compruebe el estado de la red en el sitio A:
+
`network port show`

+
En el ejemplo siguiente se muestra el uso de puerto de red en una configuración de MetroCluster de cuatro nodos:

+
[listing]
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----
. Compruebe la configuración de MetroCluster en ambos sitios de la configuración de MetroCluster.
+
.. Verifique la configuración desde el sitio A:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Verifique la configuración desde el sitio B:
+
`metrocluster show`

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Compruebe que las relaciones de recuperación ante desastres se han creado correctamente:
+
`metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner`

+
[listing]
----
metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner
dr-group-id cluster     node    ha-partner dr-cluster  dr-partner   dr-auxiliary  node-object-limit automatic-uso
----------- ---------   ----    ---------- ----------  ----------   ------------  ----------------- -------------
2           cluster_A   node_A_1 node_A_2    cluster_B  node_B_1     node_B_2      on                true
2           cluster_A   node_A_2 node_A_1    cluster_B  node_B_2     node_B_1      on                true
2           cluster_B   node_B_1 node_B_2    cluster_A  node_A_1     node_A_2      on                true
2           cluster_B   node_B_2 node_B_1    cluster_A  node_A_2     node_A_1      on                true
4 entries were displayed.
----



