---
permalink: upgrade/task_configure_intercluster_lifs_to_share_data_ports.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, shared, data, ports 
summary: Las LIF de interconexión de clústeres se pueden configurar en los puertos compartidos con la red de datos. De este modo, se reduce el número de puertos necesarios para interconectar redes. 
---
= Configurar las LIF de interconexión de clústeres en puertos de datos compartidos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las LIF de interconexión de clústeres se pueden configurar en los puertos compartidos con la red de datos. De este modo, se reduce el número de puertos necesarios para interconectar redes.

.Pasos
. Enumere los puertos del clúster:
+
`network port show`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se muestran los puertos de red en cluster01:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Crear LIF de interconexión de clústeres en la SVM del sistema:
+
|===


| *En ONTAP 9.6 y posterior:* 


 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`



| *En ONTAP 9.5 y anteriores:* 


 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -role intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

|===
+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo se crean LIF de interconexión de clústeres `cluster01_icl01` y.. `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Compruebe que se han creado las LIF de interconexión de clústeres:
+
|===


| *En ONTAP 9.6 y posterior:* 


 a| 
`network interface show -service-policy default-intercluster`



| *En ONTAP 9.5 y anteriores:* 


 a| 
`network interface show -role intercluster`

|===
+
Para obtener una sintaxis de comando completa, consulte la página man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Compruebe que las LIF de interconexión de clústeres son redundantes:
+
|===


| *En ONTAP 9.6 y posterior:* 


 a| 
`network interface show –service-policy default-intercluster -failover`



| *En ONTAP 9.5 y anteriores:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el siguiente ejemplo, se muestra que las LIF de interconexión de clústeres "cluster01_icl01" y "cluster01_icl02" en el puerto "e0c" conmutarán al puerto "e0d".

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

