---
permalink: upgrade/task_determin_the_new_cable_layout_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, determine, new, cabling, layout 
summary: Debe determinar el cableado de los módulos de controladora nuevos y de todas las bandejas de discos nuevas a los switches FC existentes. 
---
= Determinando la disposición del nuevo cableado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe determinar el cableado de los módulos de controladora nuevos y de todas las bandejas de discos nuevas a los switches FC existentes.

.Acerca de esta tarea
Esta tarea debe realizarse en cada sitio MetroCluster.

.Pasos
. Utilice el procedimiento descrito en link:../install-fc/index.html["Instalación y configuración de MetroCluster estructural"] Para crear una distribución de cableado para el tipo de switch, se usa el uso del puerto para una configuración de MetroCluster de ocho nodos.
+
El uso del puerto del switch FC debe coincidir con el uso descrito en el procedimiento para poder utilizar los archivos de configuración de referencia (RCF).

+

NOTE: Si el entorno no puede cablearse de forma que se puedan utilizar los archivos RCF, deberá configurar manualmente el sistema de acuerdo con las instrucciones que se encuentran en link:../install-fc/index.html["Instalación y configuración de MetroCluster estructural"]. No utilice este procedimiento si el cableado no puede utilizar archivos RCF.


