---
permalink: upgrade/task_cable_the_controller_module_s_fc_vi_hba_ports_to_the_fc_switches_controller_to_fc_sw.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, cable, new, controller, module, fc, vi, hba, ports, switches, mcc 
summary: 'Los puertos FC-VI y los HBA \(adaptadores de bus de host\) del nuevo módulo de controlador deben conectarse a los switches FC de sitio.' 
---
= Cableado de los puertos FC-VI y HBA del nuevo módulo de controlador a los switches FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los puertos FC-VI y los HBA (adaptadores de bus de host) del nuevo módulo de la controladora deben cablearse a los switches FC del sitio.

.Pasos
. Conecte mediante cable los puertos FC-VI y los puertos HBA, mediante la tabla correspondiente a su configuración y modelo de switch.
+
** link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Asignaciones de puertos para los switches FC cuando se utiliza ONTAP 9.1 y versiones posteriores"]
** link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["Asignación de puertos para los switches FC cuando se utiliza ONTAP 9.0"]
** link:../install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html["Las asignaciones de puertos para los sistemas que utilizan dos puertos iniciadores"]



