---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg 
summary: Las actualizaciones de los sistemas introducidos en ONTAP 9.15.1 o versiones posteriores requieren establecer un arranque para poder continuar con la actualización de la controladora. 
---
= Establecer el arranque necesario (para actualizaciones de IP de MetroCluster de los sistemas introducidos en ONTAP 9.15.1 o versiones posteriores)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está actualizando a un sistema introducido en ONTAP 9.15.1 o posterior, generalmente deberá configurar un bootarg en los controladores antiguos antes de poder comenzar la actualización.


NOTE: Si su combinación de actualización se ve afectada, es necesario configurar un bootarg en todos los controladores antiguos para lograr una actualización exitosa.  Revise atentamente la información de esta sección para verificar si su combinación de actualización requiere que configure un bootarg y cómo configurar el bootarg correcto para su combinación.



== Paso 1: Determine si necesita configurar un bootarg en los controladores antiguos

Utilice la siguiente información para comprobar si necesita configurar un bootarg obligatorio antes de iniciar la actualización:

* Debe configurar un bootarg en los controladores antiguos para las actualizaciones compatibles con los siguientes sistemas a menos que se indique lo contrario:
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30 y AFF C60
** FAS50


* No es necesario que configures ningún bootarg en los controladores antiguos si tu actualización es una de las siguientes combinaciones:
+
** De un sistema AFF A70 a un sistema AFF A90
** De un sistema FAS70 a un sistema FAS90





CAUTION: Si su actualización no requiere que configure ningún bootarg, puede omitir esta tarea e ir directamente alink:upgrade-mcc-ip-prepare-system.html["Prepare el sistema para la actualización"] .



== Paso 2: Determine el bootarg que necesita configurar en los controladores antiguos

La mayoría de las actualizaciones afectadas requieren que configures la `hw.cxgbe.toe_keepalive_disable` bootarg en los controladores antiguos.  Sin embargo, ciertas rutas de actualización requieren que configures la `bootarg.siw.interop_enabled` bootarg en su lugar.

Utilice la siguiente tabla para determinar qué inicio debe definir para su combinación de actualización específica.

[cols="2*"]
|===
| Para esta actualización... | Establecer el inicio... 


| De AFF A250 a AFF A30 | `bootarg.siw.interop_enabled` 


| De AFF C250 a AFF C30 | `bootarg.siw.interop_enabled` 


| De AFF A150 a AFF A20 | `bootarg.siw.interop_enabled` 


| De AFF A220 a AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
Todas las demás actualizaciones de los sistemas AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A30, AFF C30, AFF C60 o FAS50

*Nota:* No es necesario configurar ningún bootarg si la actualización es de un sistema AFF A70 a AFF A90 o de un sistema FAS70 a FAS90.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== Paso 3: Configure el bootarg requerido en los controladores antiguos

Una vez que haya determinado el bootarg requerido para su combinación de actualización, siga los pasos para configurar el bootarg en los controladores antiguos.  Esta tarea *sólo* es necesaria para las actualizaciones afectadas.


NOTE: Debe configurar el bootarg en todos los nodos antiguos en ambos sitios antes de comenzar la actualización.

.Pasos
. Detenga un nodo en ambos sitios y permita a su compañero de alta disponibilidad realizar una toma de control de almacenamiento del nodo:
+
`halt  -node <node_name>`

. Defina el inicio necesario para la combinación de actualización. Ya ha determinado el arranque que necesita establecer mediante el uso de la tabla en <<upgrade_paths_bootarg_manual,determine qué inicio debe definir>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. En `LOADER` el símbolo del sistema del nodo detenido, introduzca lo siguiente:
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. En `LOADER` el símbolo del sistema del nodo detenido, introduzca lo siguiente:
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Arrancar el nodo:
+
`boot_ontap`

. Cuando el nodo arranque, realice un retorno al nodo en el símbolo del sistema:
+
`storage failover giveback -ofnode <node_name>`

. Repita los pasos en todos los nodos del grupo de recuperación ante desastres o los grupos de recuperación ante desastres que esté actualizando.


.El futuro
link:upgrade-mcc-ip-prepare-system.html["Prepare el sistema para la actualización"].
