---
permalink: upgrade/upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, rcf, bootarg 
summary: Actualice los archivos RCF del switch para las nuevas plataformas y establezca los valores de arranque IP de MetroCluster en los módulos del controlador. 
---
= Actualice los RFC del switch y defina los valores de inicio de IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Actualice los archivos de configuración de referencia de switches (RDM) para las nuevas plataformas y establezca los valores de arranque de IP de MetroCluster en los módulos del controlador.



== Actualice los RFC del switch para acomodar las nuevas plataformas

Debe actualizar los switches a una configuración que admita los nuevos modelos de plataforma.

.Acerca de esta tarea
Esta tarea debe realizarse en el sitio que contiene las controladoras que se están actualizando. En los ejemplos mostrados en este procedimiento, estamos actualizando site_B primero.

Los switches de Site_A se actualizarán cuando se actualicen las controladoras de Site_A.

.Pasos
. Prepare los switches IP para la aplicación de los nuevos RFC.
+
Siga los pasos de la sección para su proveedor de switches:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Restablezca el conmutador IP Broadcom a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Restablezca el conmutador IP de Cisco a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Restablece el switch NVIDIA IP SN2100 a los valores predeterminados de fábrica"]


. Descargue e instale los RCF.
+
Siga los pasos de la sección para su proveedor de switches:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Descargue e instale los RCFs de Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Descargue e instale los Cisco IP RCF"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Descargue e instale los NVIDIA IP RCF"]






== Establezca las variables bootarg de MetroCluster IP

Debe configurar ciertos valores de arranque de IP de MetroCluster en los nuevos módulos del controlador. Los valores de inicio deben coincidir con los configurados en los módulos del controlador antiguo.

.Acerca de esta tarea
* Utilice los UUID y los ID del sistema identificados anteriormente en el procedimiento de actualización de link:upgrade-mcc-ip-prepare-system.html#gather-information-before-the-upgrade["Recopile información antes de la actualización"].
* Según el modelo de la plataforma, puede especificar el identificador de VLAN mediante el `-vlan-id` parámetro. Las siguientes plataformas no admiten `-vlan-id` el parámetro:
+
** FAS8200 y AFF A300
** AFF A320
** FAS9000 y AFF A700
** AFF C800, ASA C800, AFF A800 y ASA A800
+
Todas las demás plataformas admiten `-vlan-id` el parámetro.



* Los valores de arranque de MetroCluster que establezca dependen de si su nuevo sistema utiliza puertos de clúster/alta disponibilidad compartidos o puertos MetroCluster/alta disponibilidad compartidos.
+
Los sistemas enumerados en la siguiente tabla utilizan *puertos MetroCluster/HA compartidos*.

+
Todos los demás sistemas utilizan *cluster compartido/puertos HA*.

+
[cols="2*"]
|===
| Sistemas AFF y ASA que utilizan puertos MetroCluster/HA compartidos | Sistemas FAS que utilizan puertos compartidos MetroCluster/HA 


 a| 
** AFF A150, ASA A150
** AFF A220
** AFF C250, ASA C250
** AFF A250, ASA A250
** AFF A300
** AFF A320
** AFF C400, ASA C400
** AFF A400, ASA A400
** A700 de AFF
** AFF C800, ASA C800
** AFF A800, ASA A800
** AFF A900, ASA A900

 a| 
** FAS2750
** FAS500f
** FAS8200
** FAS8300
** FAS8700
** FAS9000
** FAS9500


|===


.Pasos
. En la `LOADER>` Prompt, establezca los siguientes bootargs en los nuevos nodos en el site_B:
+
Los pasos que siga dependerán de los puertos que utilice el nuevo modelo de plataforma.

+
[role="tabbed-block"]
====
.Sistemas que utilizan puertos compartidos clúster/alta disponibilidad
--
.. Defina los siguientes arranques:
+
`setenv bootarg.mcc.port_a_ip_config <local-IP-address/local-IP-mask,0,0,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id>`

+
`setenv bootarg.mcc.port_b_ip_config <local-IP-address/local-IP-mask,0,0,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id>`

+

NOTE: Si las interfaces están usando un ID de VLAN predeterminado, el `vlan-id` parámetro no es necesario.

+
En el siguiente ejemplo se configuran los valores de node_B_1-new usando VLAN 120 para la primera red y VLAN 130 para la segunda red:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,0,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,0,172.17.27.13,172.17.27.12,130
----
+
En el siguiente ejemplo se configuran los valores de node_B_2-new usando VLAN 120 para la primera red y VLAN 130 para la segunda red:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,0,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,0,172.17.27.12,172.17.27.13,130
----
+
En el ejemplo siguiente se establecen los valores de node_B_1-new mediante VLAN predeterminadas para todas las conexiones de DR IP de MetroCluster:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config
172.17.26.10/23,0,0,172.17.26.13,172.17.26.12
setenv bootarg.mcc.port_b_ip_config
172.17.27.10/23,0,0,172.17.27.13,172.17.27.12
----
+
En el ejemplo siguiente se establecen los valores de node_B_2-new mediante VLAN predeterminadas para todas las conexiones de DR IP de MetroCluster:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config
172.17.26.11/23,0,0,172.17.26.12,172.17.26.13
setenv bootarg.mcc.port_b_ip_config
172.17.27.11/23,0,0,172.17.27.12,172.17.27.13
----


--
.Sistemas que utilizan puertos compartidos MetroCluster/HA
.. Defina los siguientes arranques:
+
`setenv bootarg.mcc.port_a_ip_config <local-IP-address/local-IP-mask,0,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id>`

+
`setenv bootarg.mcc.port_b_ip_config <local-IP-address/local-IP-mask,0,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id>`

+

NOTE: Si las interfaces están usando un ID de VLAN predeterminado, el `vlan-id` parámetro no es necesario.

+
En el siguiente ejemplo se configuran los valores de node_B_1-new usando VLAN 120 para la primera red y VLAN 130 para la segunda red:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
----
+
En el siguiente ejemplo se configuran los valores de node_B_2-new usando VLAN 120 para la primera red y VLAN 130 para la segunda red:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13,130
----
+
En el ejemplo siguiente se establecen los valores de node_B_1-new mediante VLAN predeterminadas para todas las conexiones de DR IP de MetroCluster:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config
172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12
setenv bootarg.mcc.port_b_ip_config
172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12
----
+
En el ejemplo siguiente se establecen los valores de node_B_2-new mediante VLAN predeterminadas para todas las conexiones de DR IP de MetroCluster:

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config
172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13
setenv bootarg.mcc.port_b_ip_config
172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13
----


--

--
====
. En el símbolo del sistema DEL CARGADOR de nodos nuevos, establezca los UUID:
+
`setenv bootarg.mgwd.partner_cluster_uuid <partner-cluster-UUID>`

+
`setenv bootarg.mgwd.cluster_uuid <local-cluster-UUID>`

+
`setenv bootarg.mcc.pri_partner_uuid <DR-partner-node-UUID>`

+
`setenv bootarg.mcc.aux_partner_uuid <DR-aux-partner-node-UUID>`

+
`setenv bootarg.mcc_iscsi.node_uuid <local-node-UUID>`

+
.. Establezca los UUID en node_B_1-new:
+
En el ejemplo siguiente se muestran los comandos para configurar los UUID en node_B_1-new:

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
----
.. Establezca los UUID en node_B_2-new:
+
En el ejemplo siguiente se muestran los comandos para configurar los UUID en node_B_2-new:

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
----


. Determine si los sistemas originales se configuraron para la partición avanzada de unidades (ADP) ejecutando el siguiente comando desde el sitio que está activo:
+
`disk show`

+
La columna de tipo de contenedor muestra “compartido” en la `disk show` salida si ADP está configurado. Si el tipo de contenedor tiene otro valor, ADP no está configurado en el sistema. La siguiente salida de ejemplo muestra un sistema configurado con ADP:

+
[listing]
----
::> disk show
                    Usable               Disk    Container   Container
Disk                Size       Shelf Bay Type    Type        Name      Owner

Info: This cluster has partitioned disks. To get a complete list of spare disk
      capacity use "storage aggregate show-spare-disks".
----------------    ---------- ----- --- ------- ----------- --------- --------
1.11.0              894.0GB    11    0   SSD      shared     testaggr  node_A_1
1.11.1              894.0GB    11    1   SSD      shared     testaggr  node_A_1
1.11.2              894.0GB    11    2   SSD      shared     testaggr  node_A_1
----
. Si los sistemas originales se configuraron con discos particionados para ADP, actívelos en `LOADER` el mensaje de cada nodo de reemplazo:
+
`setenv bootarg.mcc.adp_enabled true`

. Configure las siguientes variables:
+
`setenv bootarg.mcc.local_config_id <original-sys-id>`

+
`setenv bootarg.mcc.dr_partner <dr-partner-sys-id>`

+

NOTE: La `setenv bootarg.mcc.local_config_id` La variable se debe establecer en sys-id del módulo de controlador *original*, node_B_1-old.

+
.. Establezca las variables en node_B_1-new.
+
En el ejemplo siguiente se muestran los comandos para configurar los valores en node_B_1-new:

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403322
setenv bootarg.mcc.dr_partner 537403324
----
.. Establezca las variables en node_B_2-new.
+
En el ejemplo siguiente se muestran los comandos para configurar los valores en node_B_2-new:

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403321
setenv bootarg.mcc.dr_partner 537403323
----


. Si utiliza cifrado con gestor de claves externo, defina los bootargs necesarios:
+
`setenv bootarg.kmip.init.ipaddr`

+
`setenv bootarg.kmip.kmip.init.netmask`

+
`setenv bootarg.kmip.kmip.init.gateway`

+
`setenv bootarg.kmip.kmip.init.interface`



.El futuro
link:upgrade-mcc-ip-manual-reassign-root-agg.html["Reasigne los discos del agregado raíz"].
