---
permalink: upgrade/upgrade-mcc-ip-manual-reassign-root-agg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Reasigne los discos de agregado raíz al nuevo módulo de controlador, con los ID de sistema que ha recopilado anteriormente. 
---
= Reasigne los discos de agregado raíz al nuevo módulo de controlador IP de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vuelva a asignar los discos de agregado raíz al nuevo módulo de controlador mediante los ID de sistema que recopiló anteriormente.

.Acerca de esta tarea
Los ID de sistema antiguos se identificaron en link:upgrade-mcc-ip-prepare-system.html#gather-information-before-the-upgrade["Recopile información antes de la actualización"].

Siga los pasos en modo de mantenimiento.


NOTE: Los discos de agregado raíz son los únicos discos que se deben volver a asignar durante el proceso de actualización de la controladora. La propiedad de disco de los agregados de datos se trata como parte de la operación de conmutación de sitios/conmutación de estado.

.Pasos
. Arranque el sistema en modo de mantenimiento:
+
`boot_ontap maint`

. Muestre los discos en node_B_1-new en la indicación Maintenance mode:
+
`disk show -a`

+

CAUTION: Antes de continuar con la reasignación de discos, compruebe que la salida de los discos pool0 y pool1 que pertenecen al agregado raíz del nodo se muestren `disk show`. En el ejemplo siguiente, la salida enumera los discos pool0 y pool1 que son propiedad de node_B_1-old.

+
El resultado del comando muestra el ID del sistema del nuevo módulo de la controladora (1574774970). Sin embargo, el antiguo ID del sistema (537403322) sigue siendo propietario de los discos de agregado raíz. Este ejemplo no muestra las unidades que son propiedad de otros nodos en la configuración de MetroCluster.

+
[listing]
----
*> disk show -a
Local System ID: 1574774970
DISK                  OWNER                 POOL   SERIAL NUMBER   HOME                  DR HOME
------------          ---------             -----  -------------   -------------         -------------
prod3-rk18:9.126L44   node_B_1-old(537403322)  Pool1  PZHYN0MD     node_B_1-old(537403322)  node_B_1-old(537403322)
prod4-rk18:9.126L49   node_B_1-old(537403322)  Pool1  PPG3J5HA     node_B_1-old(537403322)  node_B_1-old(537403322)
prod4-rk18:8.126L21   node_B_1-old(537403322)  Pool1  PZHTDSZD     node_B_1-old(537403322)  node_B_1-old(537403322)
prod2-rk18:8.126L2    node_B_1-old(537403322)  Pool0  S0M1J2CF     node_B_1-old(537403322)  node_B_1-old(537403322)
prod2-rk18:8.126L3    node_B_1-old(537403322)  Pool0  S0M0CQM5     node_B_1-old(537403322)  node_B_1-old(537403322)
prod1-rk18:9.126L27   node_B_1-old(537403322)  Pool0  S0M1PSDW     node_B_1-old(537403322)  node_B_1-old(537403322)
.
.
.
----
. Reasigne los discos de agregado raíz en las bandejas de unidades a las nuevas controladoras.
+
|===


| Si está utilizando ADP... | A continuación, se usa este comando... 


 a| 
Sí
 a| 
`disk reassign -s <old-sysid> -d <new-sysid> -r <dr-partner-sysid>`



 a| 
No
 a| 
`disk reassign -s <old-sysid> -d <new-sysid>`

|===
. Reasigne los discos de agregado raíz de las bandejas de unidades a las nuevas controladoras:
+
`disk reassign -s <old-sysid> -d <new-sysid>`

+
En el siguiente ejemplo, se muestra la reasignación de unidades en una configuración que no sea de ADP:

+
[listing]
----
*> disk reassign -s 537403322 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537403322.
Do you want to continue (y/n)? y
----
. Compruebe que los discos del agregado raíz se han reasignado correctamente:
+
`disk show`

+
`storage aggr status`

+
[listing]
----

*> disk show
Local System ID: 537097247

  DISK                    OWNER                    POOL   SERIAL NUMBER   HOME                     DR HOME
------------              -------------            -----  -------------   -------------            -------------
prod03-rk18:8.126L18 node_B_1-new(537097247)  Pool1  PZHYN0MD        node_B_1-new(537097247)   node_B_1-new(537097247)
prod04-rk18:9.126L49 node_B_1-new(537097247)  Pool1  PPG3J5HA        node_B_1-new(537097247)   node_B_1-new(537097247)
prod04-rk18:8.126L21 node_B_1-new(537097247)  Pool1  PZHTDSZD        node_B_1-new(537097247)   node_B_1-new(537097247)
prod02-rk18:8.126L2  node_B_1-new(537097247)  Pool0  S0M1J2CF        node_B_1-new(537097247)   node_B_1-new(537097247)
prod02-rk18:9.126L29 node_B_1-new(537097247)  Pool0  S0M0CQM5        node_B_1-new(537097247)   node_B_1-new(537097247)
prod01-rk18:8.126L1  node_B_1-new(537097247)  Pool0  S0M1PSDW        node_B_1-new(537097247)   node_B_1-new(537097247)
::>
::> aggr status
           Aggr          State           Status                Options
aggr0_node_B_1           online          raid_dp, aggr         root, nosnap=on,
                                         mirrored              mirror_resync_priority=high(fixed)
                                         fast zeroed
                                         64-bit
----


.El futuro
link:upgrade-mcc-ip-manual-boot-new-controllers.html["Arranque las nuevas controladoras y restaure la configuración de LIF"].
