---
permalink: upgrade/upgrade-mcc-ip-manual-boot-new-controllers.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Arranque las nuevas controladoras y compruebe que las LIF están alojadas en los nodos y puertos adecuados. 
---
= Arranque las nuevas controladoras IP de MetroCluster y restaure la configuración de LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arranque las nuevas controladoras y compruebe que las LIF están alojadas en los nodos y puertos adecuados.



[[boot-the-new-controllers]]
== Arranque las nuevas controladoras

Debe arrancar los nuevos controladores, teniendo cuidado de asegurarse de que las variables bootarg son correctas y, si es necesario, llevar a cabo los pasos de recuperación de cifrado.

.Pasos
. Detenga los nuevos nodos:
+
`halt`

. Si se configura el gestor de claves externo, defina los bootargs relacionados:
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`

+
`setenv bootarg.kmip.init.netmask <netmask>`

+
`setenv bootarg.kmip.init.gateway <gateway-addres>`

+
`setenv bootarg.kmip.init.interface <interface-id>`

. Compruebe si la sísid del compañero es la actual:
+
`printenv partner-sysid`

+
Si el sid del socio no es correcto, configúrelo:

+
`setenv partner-sysid <partner-sysID>`

. Abra el menú de inicio de ONTAP:
+
`boot_ontap menu`

. Si el SVM de administración del sistema MetroCluster está configurado con un gestor de claves, selecciona la opción correcta del menú de arranque para tu configuración de gestión de claves.
+
|===


| Si está usando... | Seleccione esta opción del menú de inicio... 


 a| 
Gestión de claves incorporada
 a| 
Opción `10`

Sigue las instrucciones para proporcionar los siguientes datos para recuperar y restaurar la configuración del key manager:

** La copia de seguridad y la frase de contraseña de Onboard Key Manager




 a| 
Gestión de claves externas
 a| 
Opción `11`

Sigue las instrucciones para proporcionar los siguientes datos para recuperar y restaurar la configuración del key manager:

** El número de puerto y la dirección de uno de los servidores de claves primarios para el SVM admin
** El nombre de usuario y la contraseña si están asociados al servidor de claves primarias elegido
** El UUID del almacén de claves para el SVM admin (requerido en ONTAP 9.16.1 o posterior)


*Nota:* Aunque el SVM admin puede tener hasta cuatro servidores de claves principales, durante el proceso de recuperación solo se puede especificar la información de un servidor de claves principal.

|===
. En el menú de inicio, seleccione "'(6) Actualizar flash desde backup config'".
+

NOTE: La opción 6 reinicia el nodo dos veces antes de que se complete el proceso.

+
Responda con «`y`» a las indicaciones de cambio de ID del sistema. Espere a que aparezcan los segundos mensajes de reinicio:

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
. En `LOADER` la petición de datos, verifique los valores de inicio y actualice los valores según sea necesario.
+
Siga los pasos indicados en link:upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html#set-the-metrocluster-ip-bootarg-variables["Establezca las variables bootarg de MetroCluster IP"].

. Compruebe que el símbolo de partner es el correcto:
+
`printenv partner-sysid`

+
Si el sid del socio no es correcto, configúrelo:

+
`setenv partner-sysid <partner-sysID>`

. Si se utiliza el cifrado del volumen raíz, selecciona de nuevo la opción del menú de arranque para tu configuración de gestión de claves.
+
|===


| Si está usando... | Seleccione esta opción del menú de inicio... 


 a| 
Gestión de claves incorporada
 a| 
Opción `10`

Sigue las instrucciones para proporcionar los siguientes datos para recuperar y restaurar la configuración del key manager:

** La copia de seguridad y la frase de contraseña de Onboard Key Manager




 a| 
Gestión de claves externas
 a| 
Opción `11`

Sigue las instrucciones para proporcionar los siguientes datos para recuperar y restaurar la configuración del key manager:

** El número de puerto y la dirección de uno de los servidores de claves primarios para el SVM admin
** El nombre de usuario y la contraseña si están asociados al servidor de claves primarias elegido
** El UUID del almacén de claves para el SVM admin (requerido en ONTAP 9.16.1 o posterior)


*Nota:* Aunque el SVM admin puede tener hasta cuatro servidores de claves principales, durante el proceso de recuperación solo se puede especificar la información de un servidor de claves principal.

|===
+
Dependiendo del tipo de key manager, realiza el procedimiento de recuperación seleccionando la opción "`10`" o la opción "`11`", seguida de la opción `6` en el primer prompt del menú de arranque. Para arrancar los nodos completamente, puede que necesites repetir el procedimiento de recuperación continuando con la opción "`1`" (arranque normal).

. Espere a que los nodos sustituidos arranquen.
+
Si alguno de los nodos está en modo de toma de control, realice una devolución mediante el `storage failover giveback` comando.

. Si el cifrado está activado en la SVM administradora, restaura las claves utilizando el comando correcto para tu configuración de gestión de claves.
+
|===


| Si está usando... | Se usa este comando... 


 a| 
Gestión de claves incorporada
 a| 
`security key-manager onboard sync`

Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["Restaure las claves de cifrado de gestión de claves incorporadas"^].



 a| 
Gestión de claves externas
 a| 
`security key-manager external restore -vserver <admin-svm> -key-server <host_name|IP_address:port>`

Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["Restaure las claves de cifrado de gestión de claves externas"^].

|===
. Verifique que todos los puertos estén en un dominio de retransmisión:
+
.. Vea los dominios de retransmisión:
+
`network port broadcast-domain show`

.. Si se crea un nuevo dominio de retransmisión para los puertos de datos en las controladoras recién actualizadas, elimine el dominio de retransmisión:
+

NOTE: Elimine sólo el nuevo dominio de difusión. No elimine ninguno de los dominios de difusión que existían antes de iniciar la actualización.

+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`

.. Añada puertos a un dominio de retransmisión según sea necesario.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["Añada o quite puertos de un dominio de retransmisión"^]

.. Vuelva a crear las VLAN y los grupos de interfaces según sea necesario.
+
La pertenencia a la VLAN y al grupo de interfaces puede diferir del nodo antiguo.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["Cree una VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["Combine puertos físicos para crear grupos de interfaces"^]







[[verify-and-restore-lif-configuration]]
== Verifique y restaure la configuración de LIF

Confirmar que las LIF se alojan en los nodos y puertos adecuados, según lo asignado al principio del procedimiento de actualización.

.Acerca de esta tarea
* Esta tarea se realiza en el sitio_B.
* Consulte el plan de asignación de puertos que ha creado en link:upgrade-mcc-ip-prepare-system.html#map-ports-from-the-old-nodes-to-the-new-nodes["Asigne puertos de los nodos antiguos a los nuevos"].



CAUTION: Debe verificar que la ubicación de las LIF de datos sea correcta en los nodos nuevos antes de volver a cambiar. Cuando conmuta la configuración, ONTAP intenta reanudar el tráfico en el puerto de inicio que utilizan las LIF. Se puede producir un fallo de E/S cuando la conexión del puerto de inicio al puerto del switch y la VLAN es incorrecta.

.Pasos
. Compruebe que las LIF están alojadas en el nodo y los puertos adecuados antes de volver a cambiar.
+
.. Cambie al nivel de privilegio avanzado:
+
`set -privilege advanced`

.. Muestre las LIF y confirme que cada LIF de datos está utilizando el puerto de inicio correcto:
+
`network interface show`

.. Modifique los LIF que no estén utilizando el puerto raíz correcto:
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
Si el comando devuelve un error, puede anular la configuración del puerto:

+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`

+
Al introducir el comando de modificación de la interfaz de red dentro del `vserver config override` no se puede utilizar la función de tabulación automática. Puede crear la red `interface modify` con la opción de autocompletar y, a continuación, escríbala en la `vserver config override` comando.

.. Confirme que todas las LIF de datos se encuentran ahora en el puerto de inicio correcto:
+
`network interface show`

.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



. Revierte las interfaces a su nodo de inicio:
+
`network interface revert * -vserver <svm-name>`

+
Realice este paso en todas las SVM según sea necesario.



.El futuro
link:upgrade-mcc-ip-manual-switchback.html["Vuelva a cambiar la configuración de MetroCluster"].
