---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-prechecks.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Para preparar la actualización de la controladora, se deben realizar comprobaciones previas del sistema y recoger la información de configuración. 
---
= Preparar el sistema IP de MetroCluster para la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para prepararse para la actualización de la controladora, es posible que deba actualizar los archivos de configuración de referencia de switches (RFC) según los modelos de plataforma antiguos y nuevos. A continuación, deberá realizar las comprobaciones previas del sistema, recopilar información de configuración y eliminar el software de supervisión existente.



== Actualice los RFC del switch de MetroCluster antes de actualizar los controladores

Según los modelos de plataforma antiguos y nuevos, es posible que deba actualizar los archivos de configuración de referencia de switch de MetroCluster antes de actualizar las controladoras.

.Acerca de esta tarea
Realice esta tarea en las siguientes circunstancias:

* La configuración de RCF del switch no está en la versión mínima.
* Debe cambiar los ID de VLAN que utilizan las conexiones MetroCluster back-end.


.Antes de empezar
Determine si debe actualizar los RFC antes de actualizar las controladoras:

* Si la configuración del switch no estaba configurada con la versión mínima de RCF compatible, debe actualizar los RCF antes de actualizar las controladoras:
+
|===


| Modelo de switch | Versión RCF necesaria 


 a| 
Cisco 3132Q-V
 a| 
1.7 o posterior



 a| 
Cisco 3232C
 a| 
1.7 o posterior



 a| 
Broadcom BES-53248
 a| 
1.3 o posterior



 a| 
NVIDIA SN2100
 a| 
2,0 o posterior

|===
* Si ambos modelos de plataforma antiguos y nuevos se encuentran en la siguiente lista, *no* necesita actualizar el ID de VLAN antes de actualizar los controladores:
+
** FAS8200 o AFF A300
** AFF A320
** FAS9000 o AFF A700
** AFF A800, AFF C800, ASA A800 o ASA C800
+
Si alguno de sus modelos de plataforma antiguos o nuevos no aparece en la lista anterior, debe confirmar que las interfaces de MetroCluster utilizan un ID de VLAN compatible. Los identificadores de VLAN compatibles para las interfaces de MetroCluster son: 10, 20, o en el rango de 101 a 4096.

+
[CAUTION]
====
*** Si el ID de VLAN no es 10, 20, o está en el rango de 101 a 4096, debe actualizar el RCF del switch antes de actualizar las controladoras.
*** Las conexiones del clúster local pueden utilizar cualquier VLAN, no es necesario que estén en el rango dado.
*** El nuevo RCF al que va a actualizar debe utilizar las VLAN 10, 20, o estar entre 101 y 4096. No cambie la VLAN para el clúster local a menos que sea necesario.


====




.Pasos
. Prepare los switches IP para la aplicación de los nuevos RFC.
+
Siga los pasos de la sección para su proveedor de switches:

+

NOTE: Debe actualizar los conmutadores en el siguiente orden: Switch_A_1, SWITCH_B_1, SWITCH_A_2, SWITCH_B_2.

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Restablezca el conmutador IP Broadcom a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Restablezca el conmutador IP de Cisco a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Restablece el switch NVIDIA IP SN2100 a los valores predeterminados de fábrica"]


. Descargue e instale los RCF.
+
Siga los pasos de la sección para su proveedor de switches:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Descargue e instale los RCFs de Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Descargue e instale los Cisco IP RCF"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Descargue e instale los NVIDIA IP RCF"]






== Iniciar la operación de reemplazo del controlador

Cuando se inicia la operación de reemplazo del controlador automatizado, la operación emite una serie de comprobaciones previas y luego se pausa para que pueda recopilar manualmente la información relacionada con la configuración.

.Acerca de esta tarea
Antes de que comiencen las comprobaciones de MetroCluster, si ONTAP Mediator está instalado, se detecta y se elimina automáticamente. Para confirmar la eliminación, se le pedirá que introduzca un nombre de usuario y una contraseña. Al finalizar la actualización, si las comprobaciones previas fallan o si decide no continuar con la actualización, deberá hacerlo manualmente. link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Vuelva a configurar el servicio ONTAP Mediator"] .

En cualquier momento durante la actualización, puede ejecutar el `system controller replace show` o. `system controller replace show-details` Comando del sitio A para comprobar el estado. Si los comandos devuelven un resultado en blanco, espere unos minutos y vuelva a ejecutar el comando.

.Pasos
. Ejecute el siguiente comando desde el sitio A para reemplazar los controladores en el sitio B:
+
`system controller replace start -nso true`

+
[NOTE]
====
** Si no utiliza el  `-nso true` parámetro en el comando, el procedimiento de actualización del controlador elige el cambio y la conversión automáticos basados en NSO como el procedimiento predeterminado en los sistemas IP de MetroCluster.
** Si se repite el procedimiento en un sitio, tras haber reemplazado los controladores en el otro, se produce un error debido a una discrepancia entre los nodos de cada sitio. Este es el comportamiento esperado cuando hay diferentes modelos de plataforma en ambos sitios.
+
Si solo se devuelve el error de falta de coincidencia, puede utilizar el  `-skip-metrocluster-check true` opción con el  `system controller replace start` Comando para omitir las comprobaciones de MetroCluster.



====
+
La operación automatizada ejecuta las comprobaciones. Si no se encuentra ningún problema, la operación se coloca en pausa para recopilar manualmente la información relacionada con la configuración.

+
Se muestran el sistema de origen actual y todos los sistemas de destino compatibles. Si ha reemplazado el controlador de origen por uno con una versión de ONTAP diferente o una plataforma incompatible, la operación de automatización se detiene y genera un error después del arranque de los nuevos nodos. Para restablecer el clúster a un estado correcto, siga el procedimiento de recuperación manual.

+
La `system controller replace start` el comando puede informar el siguiente error de las comprobaciones previas:

+
[listing]
----
Cluster-A::*>system controller replace show
Node        Status         Error-Action
----------- -------------- ------------------------------------
Node-A-1    Failed         MetroCluster check failed. Reason : MCC check showed errors in component aggregates
----
+
Compruebe si se ha producido este error porque ha reflejado agregados o debido a otro problema de agregado. Verifique que todos los agregados reflejados estén en buen estado y no degradado o con estado de reflejo degradado. Si este error se debe únicamente a agregados no reflejados, puede seleccionar la opción para anular este error `-skip-metrocluster-check true` en la `system controller replace start` comando. Si puede accederse al almacenamiento remoto, los agregados no reflejados entran en línea tras realizar la conmutación. Si el enlace de almacenamiento remoto falla, los agregados no reflejados no pueden conectarse.

. Para recopilar manualmente la información de configuración, inicie sesión en el sitio B y siga los comandos enumerados en el mensaje de la consola en `system controller replace show` o. `system controller replace show-details` comando.




== Recopile información antes de la actualización

Antes de la actualización, si el volumen raíz está cifrado, se debe recopilar la clave de backup y otra información para arrancar las nuevas controladoras con los volúmenes raíz cifrados anteriores.

.Acerca de esta tarea
Esta tarea se lleva a cabo en la configuración de IP de MetroCluster existente.

.Pasos
. Etiquete los cables de las controladoras existentes para que puedan identificar fácilmente los cables cuando configure las nuevas controladoras.
. Muestre los comandos para capturar la clave de backup y otra información:
+
`system controller replace show`

+
Ejecute los comandos enumerados en `show` del clúster de partners.

+
La `show` La salida del comando muestra tres tablas que contienen las direcciones IP de la interfaz de MetroCluster, los ID del sistema y los UUID del sistema. Esta información es necesaria más adelante en el procedimiento para establecer los arranques al iniciar el nuevo nodo.

. Recopile los ID del sistema de los nodos en la configuración de MetroCluster:
+
--
`metrocluster node show -fields node-systemid,dr-partner-systemid`

Durante el procedimiento de actualización, reemplazará estos antiguos ID del sistema por los ID de sistema de los nuevos módulos del controlador.

En este ejemplo, para una configuración de IP de MetroCluster de cuatro nodos, se recuperan los siguientes ID de sistema anteriores:

** Node_A_1-old: 4068741258
** Node_A_2-old: 4068741260
** Node_B_1-old: 4068741254
** Node_B_2-old: 4068741256


[listing]
----
metrocluster-siteA::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid
dr-group-id        cluster           node            node-systemid     ha-partner-systemid     dr-partner-systemid    dr-auxiliary-systemid
-----------        ---------------   ----------      -------------     -------------------     -------------------    ---------------------
1                    Cluster_A       Node_A_1-old    4068741258        4068741260              4068741256             4068741256
1                    Cluster_A       Node_A_2-old    4068741260        4068741258              4068741254             4068741254
1                    Cluster_B       Node_B_1-old    4068741254        4068741256              4068741258             4068741260
1                    Cluster_B       Node_B_2-old    4068741256        4068741254              4068741260             4068741258
4 entries were displayed.
----
En este ejemplo, para una configuración de IP de MetroCluster de dos nodos, se recuperan los siguientes ID de sistema antiguos:

** Node_a_1: 4068741258
** Node_B_1: 4068741254


[listing]
----
metrocluster node show -fields node-systemid,dr-partner-systemid

dr-group-id cluster    node          node-systemid dr-partner-systemid
----------- ---------- --------      ------------- ------------
1           Cluster_A  Node_A_1-old  4068741258    4068741254
1           Cluster_B  node_B_1-old  -             -
2 entries were displayed.
----
--
. Recopile información del puerto y LIF para cada nodo antiguo.
+
Debe recopilar el resultado de los siguientes comandos para cada nodo:

+
** `network interface show -role cluster,node-mgmt`
** `network port show -node <node-name> -type physical`
** `network port vlan show -node <node-name>`
** `network port ifgrp show -node <node-name> -instance`
** `network port broadcast-domain show`
** `network port reachability show -detail`
** `network ipspace show`
** `volume show`
** `storage aggregate show`
** `system node run -node <node-name> sysconfig -a`
** `aggr show -r`
** `disk show`
** `system node run <node-name> disk show`
** `vol show -fields type`
** `vol show -fields type , space-guarantee`
** `vserver fcp initiator show`
** `storage disk show`
** `metrocluster configuration-settings interface show`


. Si los nodos MetroCluster tienen una configuración SAN, recopile la información pertinente.
+
Debe recopilar el resultado de los siguientes comandos:

+
** `fcp adapter show -instance`
** `fcp interface show -instance`
** `iscsi interface show`
** `ucadmin show`


. Si el volumen raíz está cifrado, recopile y guarde la clave de acceso usada para Key-Manager:
+
`security key-manager backup show`

. Si los nodos de MetroCluster utilizan el cifrado de volúmenes o agregados, copie información sobre las claves y las Passphrases.
+
Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html["Realice un backup manual de la información de gestión de claves incorporada"^].

+
.. Si se configuró el gestor de claves incorporado:
+
`security key-manager onboard show-backup`

+
Necesitará la contraseña más adelante en el procedimiento de actualización.

.. Si está configurada la gestión de claves empresariales (KMIP), ejecute los siguientes comandos:
+
`security key-manager external show -instance`

+
`security key-manager key query`



. Después de terminar de recoger la información de configuración, reanude la operación:
+
`system controller replace resume`





== Elimine la configuración existente de tiebreaker u otro software de supervisión

Antes de iniciar la actualización, elimine la configuración existente de tiebreaker u otro software de supervisión.

Si la configuración existente se supervisa con la configuración de tiebreaker para MetroCluster u otras aplicaciones de terceros (por ejemplo, ClusterLion) que pueden iniciar una conmutación de sitios, debe eliminar la configuración de MetroCluster del tiebreaker o de otro software antes de sustituir el controlador antiguo.

.Pasos
. link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations["Quitar la configuración de MetroCluster existente"] Del software Tiebreaker.
. Elimine la configuración de MetroCluster existente de cualquier aplicación de terceros que pueda iniciar la conmutación.
+
Consulte la documentación de la aplicación.



.El futuro
link:upgrade-mcc-ip-system-controller-replace-prepare-network-configuration.html["Prepare la configuración de red de las controladoras antiguas"].
