---
permalink: tiebreaker/concept_monitoring_the_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, tiebreaker, software, automate, recovery, process, enabling, enable, monitor, configuration, status, evaluate, snmp, event, trap, netapp, customer, support, operation, configuring, configure, autosupport, display, status, monitor, operation, information, creating, create, dump, file 
summary: El software MetroCluster Tiebreaker automatiza el proceso de recuperación al permitirle supervisar el estado de la configuración de MetroCluster, evaluar los eventos y las capturas de SNMP que se envían al soporte de cliente de NetApp y ver el estado de las operaciones de supervisión. 
---
= Supervisar la configuración de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software MetroCluster Tiebreaker automatiza el proceso de recuperación al permitirle supervisar el estado de la configuración de MetroCluster, evaluar los eventos y las capturas de SNMP que se envían al soporte de cliente de NetApp y ver el estado de las operaciones de supervisión.



== Configurando AutoSupport

De forma predeterminada, los mensajes de AutoSupport se envían a NetApp una semana después de la instalación del software Tiebreaker. Los eventos que activan la notificación de AutoSupport incluyen una alarma del software de tiebreaker, la detección de condiciones de desastre en configuraciones de MetroCluster o el estado de configuración de MetroCluster desconocido.

.Antes de empezar
Debe tener acceso directo para configurar los mensajes de AutoSupport.

.Pasos
. Use el comando AutoSupport de la CLI de Tiebreaker con cualquiera de las siguientes opciones:
+
[cols="1,2"]
|===


| Opción | Descripción 


 a| 
-invoque
 a| 
Envía un mensaje de AutoSupport al servicio de soporte al cliente



 a| 
-configure el asistente
 a| 
Asistente para configurar las credenciales del servidor proxy



 a| 
-eliminar configuración
 a| 
Elimina las credenciales del servidor proxy



 a| 
--enable
 a| 
Habilita la notificación AutoSupport (este es el valor predeterminado).



 a| 
-disable
 a| 
Desactiva la notificación de AutoSupport



 a| 
-show
 a| 
Muestra el estado de AutoSupport

|===
+
El ejemplo siguiente muestra que AutoSupport está habilitado o deshabilitado y el destino al que se publica el contenido de AutoSupport:

+
[listing]
----

NetApp MetroCluster Tiebreaker :> autosupport enable
AutoSupport already enabled.

NetApp MetroCluster Tiebreaker :> autosupport disable
AutoSupport status            : disabled
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup

NetApp MetroCluster Tiebreaker :> autosupport enable
AutoSupport status            : enabled
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup

NetApp MetroCluster Tiebreaker :> autosupport invoke
AutoSupport transmission      : success
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup
----
+
En el ejemplo siguiente se muestra AutoSupport configurado mediante un servidor proxy autenticado, mediante una dirección IP y un número de puerto:

+
[listing]
----
NetApp MetroCluster Tiebreaker :> autosupport configure wizard
Enter Proxy Server IP address :  10.234.168.79
Enter Proxy Server port number :  8090
Enter Proxy Server Username :  admin
Enter Proxy Server Password : 123abc
Autosupport configuration updated successfully.
----
+
En el ejemplo siguiente se muestra la eliminación de una configuración de AutoSupport:

+
[listing]
----
NetApp MetroCluster Tiebreaker :> autosupport delete configuration
Autosupport configuration deleted successfully.
----




=== Eventos y capturas SNMP

El software MetroCluster Tiebreaker de NetApp utiliza capturas de SNMP para notificar eventos importantes. Estos retos forman parte del archivo MIB de NetApp. Cada captura contiene la siguiente información: Nombre de captura, gravedad, nivel de impacto, Marca de tiempo y mensaje.

[cols="2,3,1"]
|===


| Nombre del evento | Detalles del evento | Número de captura 


 a| 
El disyuntor de corbata MetroCluster no puede alcanzar la configuración de MetroCluster
 a| 
Advierte al administrador de que el software no puede detectar un desastre. Este evento se produce cuando no se puede acceder a ambos clústeres.
 a| 
25000



 a| 
El disyuntor de acoplamiento MetroCluster no puede alcanzar el clúster
 a| 
Advierte al administrador que el software no puede llegar a uno de los clústeres.
 a| 
25001



 a| 
El disyuntor MetroCluster Tie-Breaker ha detectado un desastre en el cluster
 a| 
Notifica al administrador que el software detecta un fallo en el sitio. Se entregará una notificación.
 a| 
25002



 a| 
Todos los enlaces entre el clúster de partners están cortados.
 a| 
El software detecta que ambos clústeres están accesibles, pero todas las rutas de red entre los dos clústeres están incapacitadas y los clústeres no pueden comunicarse entre sí.
 a| 
25005



 a| 
Captura de prueba SNMP
 a| 
Ahora se puede probar la configuración de SNMP ejecutando el comando de prueba de configuración de snmp.
 a| 
25006

|===


== Mostrar el estado de las operaciones de supervisión

Puede visualizar el estado general de las operaciones de supervisión de una configuración de MetroCluster.

.Paso
. Use el comando Tiebreaker CLI show para mostrar el estado de una operación de MetroCluster con cualquiera de las siguientes opciones:
+
[cols="1,2"]
|===


| Opción | Descripción 


 a| 
-nombre-monitor
 a| 
Muestra el estado del nombre del monitor especificado



 a| 
-operación-historia
 a| 
Muestra hasta 10 operaciones de supervisión que se realizaron en un clúster por última vez



 a| 
-stats
 a| 
Muestra las estadísticas relacionadas con el clúster especificado



 a| 
-estado
 a| 
Muestra el estado del clúster especificado *Nota:* el software MetroCluster Tiebreaker puede tardar hasta 10 minutos para reflejar el estado de finalización de operaciones como agregados Heal, raíces curales o regreso.

|===
+
En el ejemplo siguiente se muestra que los clústeres cluster_A y cluster_B están conectados y en buen estado:

+
[listing]
----

NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
----
+
En el ejemplo siguiente, se muestran las últimas siete operaciones que se ejecutaron en cluster_B:

+
[listing]
----

NetApp MetroCluster Tiebreaker:> monitor show -operation-history
MetroCluster: cluster_B
 [ 2014-09-15 04:48:32.274 ] MetroCluster Monitor is initialized
 [ 2014-09-15 04:48:32.278 ] Started Discovery and validation of MetroCluster Setup
 [ 2014-09-15 04:48:35.078 ] Discovery and validation of MetroCluster Setup succeeded. Started monitoring.
 [ 2014-09-15 04:48:35.246 ] NetApp MetroCluster Tiebreaker software is able to reach cluster "mcc5a"
 [ 2014-09-15 04:48:35.256 ] NetApp MetroCluster Tiebreaker software is able to reach cluster "mcc5b"
 [ 2014-09-15 04:48:35.298 ] Link to remote DR cluster is up for cluster "mcc5a"
 [ 2014-09-15 04:48:35.308 ] Link to remote DR cluster is up for cluster "mcc5b"
----




== Mostrar la información de configuración de MetroCluster

Puede mostrar el nombre y la dirección IP del monitor de todas las instancias de configuraciones de MetroCluster en el software Tiebreaker.

.Paso
. Use el comando Tiebreaker CLI Configuration show para mostrar la información de configuración de MetroCluster.
+
En el ejemplo siguiente se muestra la información de los clústeres cluster_A y cluster_B:

+
[listing]
----
MetroCluster: North America
    Monitor Enabled: true
    ClusterA name: cluster_A
    ClusterA IpAddress: 10.222.196.130
    ClusterB name: cluster_B
    ClusterB IpAddress: 10.222.196.140
----




== Creando archivos de volcado

Guarde el estado general del software Tiebreaker en un archivo de volcado para propósitos de depuración.

.Paso
. Use el comando dump -status de la interfaz de línea de comandos de Tiebreaker para crear un archivo de volcado del estado general de todas las configuraciones de MetroCluster.
+
En el siguiente ejemplo, se muestra cómo se crea correctamente el archivo de volcado /var/log/netapp/mccctb/metrocluster-tiebreaker-status.xml:

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor dump -status
MetroCluster Tiebreaker status successfully dumped in file /var/log/netapp/mcctb/metrocluster-tiebreaker-status.xml
----

