---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: Tras la instalación del software Tiebreaker, puede agregar o modificar configuraciones de MetroCluster o eliminarlas del software de tiebreaker. 
---
= Configurar el software MetroCluster Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras la instalación del software Tiebreaker, puede agregar o modificar configuraciones de MetroCluster o eliminarlas del software de tiebreaker.



== Inicie la interfaz de línea de comandos (CLI) del software Tiebreaker.

Después de instalar el software Tiebreaker, debe iniciar su CLI para configurar el software.

. Inicie la CLI desde el símbolo del sistema del host en el que ha instalado el software:
+
`netapp-metrocluster-tiebreaker-software-cli`

. Después de la instalación y durante el primer inicio, introduzca la contraseña para que el usuario de tiebreaker acceda a la base de datos. Esta es la contraseña que ha especificado para el usuario de la base de datos durante la instalación.




== Agregue configuraciones de MetroCluster

Después de instalar el software MetroCluster Tiebreaker de NetApp, puede añadir más configuraciones de MetroCluster de una en una.

.Acerca de esta tarea
* Debe haber instalado la configuración de MetroCluster en un entorno de ONTAP y habilitado los ajustes en el software.
* Los pasos y el resultado del comando esperado dependen de la versión de Tiebreaker que esté ejecutando.


[role="tabbed-block"]
====
.Desempate 1.5 o anterior
--
.Pasos
. Use el comando Tiebreaker desde la interfaz de línea de comandos (CLI) monitor add para agregar configuraciones de MetroCluster.
+
Si se utiliza el nombre de host, debe ser el nombre de dominio completo (FQDN).

+
En el ejemplo siguiente se muestra la configuración de cluster_A:

+
.Ejemplo
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. Confirme que la configuración de MetroCluster se ha añadido correctamente mediante la interfaz de línea de comandos de Tiebreaker `monitor show -status` comando.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Desactive el modo observador del software Tiebreaker para iniciar automáticamente una conmutación después de que detecte un fallo del sitio:
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tiebreaker 1,6 o posterior
--
.Pasos
. Use el comando Tiebreaker desde la interfaz de línea de comandos (CLI) monitor add para agregar configuraciones de MetroCluster.
+
Si se utiliza el nombre de host, debe ser el nombre de dominio completo (FQDN).

+
En el ejemplo siguiente se muestra la configuración de cluster_A:

+
.Ejemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. Confirme que la configuración de MetroCluster se ha añadido correctamente mediante la interfaz de línea de comandos de Tiebreaker `monitor show -status` comando.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Importe los certificados faltantes realizando los pasos para su versión de Tiebreaker en<<import-certificates-tb17,Certificados de importación>> .


--
====
.Información relacionada
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Riesgos y limitaciones del uso de MetroCluster Tiebreaker en el modo activo"]



== Certificados de importación

Para habilitar la supervisión sin interrupciones en Tiebreaker 1.6 o posterior, debe importar el certificado Secure Sockets Layer (SSL) del servidor, el certificado intermedio (si existe) y el certificado raíz de ONTAP al almacén de claves en la Máquina Virtual Java (JVM).

.Acerca de esta tarea
* Esta tarea es necesaria en Tiebreaker 1.6 o posterior.
* Esta tarea se realiza después de haber agregado correctamente una configuración de MetroCluster a Tiebreaker o si caducan sus certificados.
* En Tiebreaker 1.7 o posterior, puede realizar una simulación de cambio para verificar si necesita importar un certificado.  Si la simulación de cambio falla, deberá importar certificados desde ONTAP al almacén de claves en la máquina virtual Java (JVM).


[role="tabbed-block"]
====
.Desempate 1.7 o posterior
--
.Pasos
. Ejecute una simulación de cambio para comprobar si necesita importar certificados.
+
.. Verifique el estado de monitoreo del desempate:
`monitor show -status`
+
.Ejemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Activar una simulación de cambio:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
El comando devuelve la siguiente salida si necesita importar certificados a la JVM:

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. Ejecute el siguiente comando para cada certificado que necesite importar (servidor SSL, intermedio o raíz).
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** El `<certificate_file_name>` El valor especifica el nombre del archivo del certificado que desea importar.
** El `-alias <certificate>` El valor especifica el nombre con el que desea almacenar el certificado después de importarlo a la JVM.
+
El siguiente ejemplo muestra cómo importar un certificado raíz con el nombre de archivo `root.crt` y un certificado de servidor SSL con el nombre de archivo `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Reinicie el software Tiebreaker:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. Realice nuevamente las comprobaciones de simulación de conmutación:
+
.. Verifique el estado de monitoreo del desempate:
`monitor show -status`
+
.Ejemplo
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Activar una simulación de cambio:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.Desempate 1.6 o 1.6P1
--
.Pasos
. Importar todos los certificados de ONTAP. Ejecute el siguiente comando para cada certificado que necesite importar (servidor SSL, intermedio o raíz).
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** El `<certificate_file_name>` El valor especifica el nombre del archivo del certificado que desea importar.
** El `-alias <certificate>` El valor especifica el nombre con el que desea almacenar el certificado después de importarlo a la JVM.
+
El siguiente ejemplo muestra cómo importar un certificado raíz con el nombre de archivo `root.crt` y un certificado de servidor SSL con el nombre de archivo `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Reinicie el software Tiebreaker:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== Comandos para modificar las configuraciones de tiebreaker para MetroCluster

Es posible modificar la configuración de MetroCluster siempre que se deba cambiar la configuración.

El comando Tiebreaker CLI monitor puede utilizarse con cualquiera de las siguientes opciones. Puede confirmar los cambios con el comando monitor show -status.

[cols="30,70"]
|===


| Opción | Descripción 


 a| 
-nombre-monitor
 a| 
Nombre de la configuración de MetroCluster



 a| 
-enable-monitor
 a| 
Habilita y deshabilita la supervisión de la configuración de MetroCluster



 a| 
-período silencioso
 a| 
Período en segundos durante el que el software MetroCluster Tiebreaker espera para confirmar un fallo del sitio después de la detección



 a| 
-modo observador
 a| 
El modo observador (true) solo proporciona supervisión y no activa una conmutación si se produce un desastre en el sitio. El modo en línea (falso) activa una conmutación de sitios si se produce un desastre.

* link:concept_overview_of_the_tiebreaker_software.html["Cómo detecta el software Tiebreaker un fallo del sitio"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Riesgos y limitaciones del uso de MetroCluster Tiebreaker en el modo activo"]


|===
En el ejemplo siguiente se cambia el período de silencio de la configuración.

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
La CLI de Tiebreaker `debug` se puede utilizar el comando para cambiar el modo de registro.

[cols="30,70"]
|===


| Comando | Descripción 


 a| 
estado de depuración
 a| 
Muestra el estado del modo de depuración



 a| 
depuración habilitada
 a| 
Activa el modo de depuración para el registro



 a| 
depuración deshabilitada
 a| 
Deshabilita el modo de depuración para el registro

|===
En sistemas que ejecutan Tiebreaker 1.4 y anteriores, la interfaz de línea de comandos de Tiebreaker `update-mcctb-password` se puede utilizar el comando para actualizar la contraseña de usuario. Este comando queda obsoleto en Tiebreaker 1.5 y posteriores.

[cols="30,70"]
|===


| Comando | Descripción 


 a| 
update-mcctb-password
 a| 
La contraseña de usuario se ha actualizado correctamente

|===


== Eliminar configuraciones de MetroCluster

Puede eliminar la configuración de MetroCluster que está supervisando el software Tiebreaker cuando ya no desee supervisar una configuración de MetroCluster.

. Utilice la CLI de Tiebreaker `monitor remove` Comando para quitar la configuración de MetroCluster.
+
En el siguiente ejemplo, «'cluster_A'» se elimina del software:

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. Confirme que la configuración de MetroCluster se ha eliminado correctamente mediante la interfaz de línea de comandos de Tiebreaker `monitor show -status` comando.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

