---
permalink: tiebreaker/concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html 
sidebar: sidebar 
keywords: switchover, upon, detection, site, failure, automatic, metrocluster, tiebreaker, active, mode, supplement, ontap, fas, capability, risk, limitation 
summary: La conmutación de sitios tras la detección de un fallo de sitio se realiza automáticamente, con MetroCluster Tiebreaker en el modo activo. Este modo se puede utilizar para complementar la funcionalidad de conmutación automática de ONTAP/FAS. 
---
= Riesgos y limitaciones del uso de MetroCluster Tiebreaker en el modo activo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La conmutación de sitios tras la detección de un fallo de sitio se realiza automáticamente, con MetroCluster Tiebreaker en el modo activo. Este modo se puede utilizar para complementar la funcionalidad de conmutación automática de ONTAP/FAS.

Cuando se implementa MetroCluster Tiebreaker en el modo activo, los siguientes problemas conocidos pueden provocar la pérdida de datos:

* Cuando el enlace entre sitios falla, las controladoras de cada sitio continúan sirviendo a los clientes. Sin embargo, las controladoras no se reflejarán. El fallo de una controladora en un sitio se identifica como fallo del sitio y MetroCluster Tiebreaker inicia una conmutación de sitios. Los datos que no se reflejan después de un error de enlace entre sitios con el sitio remoto se perderán.
* La conmutación se produce cuando los agregados del sitio remoto se encuentran en estado degradado. Los datos no se replicarán si la conmutación de sitios ha ocurrido antes de realizar una resincronización del agregado.
* Un fallo del almacenamiento remoto se produce cuando la conmutación está en curso.
* La memoria no volátil (NVRAM o NVMEM, según el modelo de plataforma) de las controladoras de almacenamiento no se refleja en el partner de recuperación ante desastres remota del sitio del partner.
* Los metadatos se pierden si la red de paridad de clústeres no funciona durante un período prolongado y los volúmenes de metadatos no están en línea después de una conmutación.



NOTE: Puede encontrar situaciones que no se mencionan. NetApp no se hace responsable de ningún daño que pueda surgir durante el uso de MetroCluster Tiebreaker en el modo activo. No utilice MetroCluster Tiebreaker en el modo activo si los riesgos y limitaciones no son aceptables para usted.
