---
permalink: tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html 
sidebar: sidebar 
keywords: snmp, tiebreaker, software, configure, setting 
summary: Para utilizar SNMP con el software Tiebreaker, debe configurar los ajustes de SNMP. 
---
= Configuración de la configuración de SNMP para el software Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para utilizar SNMP con el software Tiebreaker, debe configurar los ajustes de SNMP.

.Acerca de esta tarea
* Tiebreaker 1,6 solo admite SNMPv3.
* Aunque tiebreaker 1,5 y 1,4 son compatibles con SNMPv1 y SNMPv3, NetApp recomienda encarecidamente que configure SNMPv3 para obtener una seguridad óptima.


.Pasos
. Utilice la CLI de Tiebreaker `snmp config wizard` Para añadir configuraciones de MetroCluster.
+

NOTE: Actualmente, solo se admite un host de captura SNMP.

+
La `snmp config wizard` respuesta del comando depende de la versión de tiebreaker que esté ejecutando.

+
[role="tabbed-block"]
====
.Tiebreaker 1,6
--
En el ejemplo siguiente, se muestra la configuración de un receptor SNMP que admite SNMPv3 con una dirección IP 192.0.2.255 y el número de puerto 162 para los mensajes de captura. El software Tierbreaker está listo para enviar capturas al receptor SNMP que ha especificado.


NOTE: Tiebreaker 1,6 solo admite SNMPv3

[listing]
----
NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Host: 192.0.2.255
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
----
--
.Tiebreaker 1,5 y 1,4
--
En el ejemplo siguiente, se muestra la configuración de un receptor SNMP que admite SNMPv3 con una dirección IP 192.0.2.255 y el número de puerto 162 para los mensajes de captura. El software Tierbreaker está listo para enviar capturas al receptor SNMP que ha especificado.

....

NetApp MetroCluster Tiebreaker :> snmp config wizard
Enter SNMP Version[V1/V3]: v3
Enter SNMP Host: 192.0.2.255
Enter SNMP Port: 162
Enter SNMP V3 Security Name: v3sec
Enter SNMP V3 Authentication password:
Enter SNMP V3 Privacy password:
Engine ID : 8000031504932eff571825192a6f1193b265e24593
Successfully added SNMP properties to NetApp MetroCluster Tiebreaker software.
....

NOTE: Debe configurar SNMPv3 porque SNMPv1 no es segura. Verifique que la cadena de comunidad predeterminada esté *NOT* establecida en PUBLIC.

--
====
. Compruebe que los ajustes de SNMP están configurados:
+
`snmp config test`

+
El siguiente ejemplo muestra que el software Tiebreaker puede enviar una captura de SNMP para el evento TEST_SNMP_CONFIG:

+
....

NetApp MetroCluster Tiebreaker :> snmp config test
Sending SNMP trap to localhost. Version : V3.
Successfully sent SNMP trap for event TEST_SNMP_CONFIG
NetApp MetroCluster Tiebreaker :>
....

