---
permalink: tiebreaker/task_install_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: El software Tiebreaker proporciona funcionalidades de supervisión para un entorno de almacenamiento en clúster. También envía notificaciones SNMP en el caso de problemas de conectividad de los nodos y de desastres del sitio. 
---
= Instalación del software Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software Tiebreaker proporciona funcionalidades de supervisión para un entorno de almacenamiento en clúster. También envía notificaciones SNMP en el caso de problemas de conectividad de los nodos y de desastres del sitio.

El software MetroCluster debe estar instalado y configurado.



== Requisitos del sistema para instalar o actualizar el software Tiebreaker

El software Tierbreaker se instala en un tercer sitio, lo que permite al software distinguir entre un fallo de enlace entre switches (ISL) (cuando los enlaces entre sitios están inactivos) y un fallo de sitio. El sistema host debe cumplir determinados requisitos antes de poder instalar o actualizar el software Tiebreaker en el equipo local para supervisar la configuración de MetroCluster.

El software MetroCluster Tiebreaker tiene las siguientes funcionalidades y requisitos de supervisión:

* Sin requisitos para una configuración especial para las distintas configuraciones de MetroCluster.
* Capacidades de supervisión simultánea de hasta 15 configuraciones de MetroCluster.
+

NOTE: Solo debe tener un monitor MetroCluster Tiebreaker por configuración de MetroCluster para evitar cualquier conflicto con varios monitores de tiebreaker.

* Admite una combinación de configuraciones de MetroCluster IP, MetroCluster FC y MetroCluster con ampliación.
* Hardware y software:
+
** ONTAP 8.3.x, 9.0, 9.1, 9.2, 9.3 9.4, 9.5, 9.6, 9.7, 9.8, 9.9.1, 9.10.1 o 9.11.1.


* Red Hat Enterprise Linux 7 a 7.9, o CentOS de 7 a 7.9 64 bits (instalación física o máquina virtual)
+
** MariaDB 5.5.52.x/MySQL Server 5.6x
** 4 GB DE MEMORIA RAM
** Abra Java Runtime Environment 8


* Red Hat Enterprise Linux 8.1 a 8.5
+
** MariaDB 10.x (utilice la versión predeterminada que se instala utilizando "yum install mariadb-Server.x86_64")
** 4 GB DE MEMORIA RAM
** Abra Java Runtime Environment 8




* Capacidad del disco: 8 GB
* Usuario: Acceso raíz
* Firewall:
+
** Acceso directo para configurar mensajes AutoSupport
** SSH (puerto 22/TCP), HTTPS (puerto 443/TCP) y ping (ICMP)


* No se admite la instalación en hosts con la función FIPS habilitada.




== Instalar las dependencias de tiebreaker para MetroCluster

Debe instalar un servidor MySQL o MariaDB en función del sistema operativo Linux que sea el host antes de instalar o actualizar el software Tiebreaker.

.Pasos
. Instalar Java Runtime Environment.
+
<<install-java-1-8,Instalación de Java Runtime Environment 1.8>>

. Instalar el servidor MySQL o MariaDB:
+
[cols="30,70"]
|===


| Si el host Linux es | Realice lo siguiente... 


 a| 
Red Hat Enterprise Linux 7/CentOS 7
 a| 
Instale MySQL

<<install-mysql-redhat,Instalar MySQL Server 5.5.30 o posterior y las versiones 5.6.x en Red Hat Enterprise Linux 7 o CentOS 7>>



 a| 
Red Hat Enterprise Linux 8
 a| 
Instalar MariaDB

<<install-mariadb,Instalación del servidor MariaDB en Red Hat Enterprise Linux 8>>

|===




=== Instalación de Java Runtime Environment 1.8

Debe instalar Java Runtime Environment 1.8 en el sistema host antes de instalar o actualizar el software Tiebreaker.

.Pasos
. Inicie sesión como `root` al sistema host.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Instalar Java Runtime Environment 1.8:
+
`[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64`

+
....
[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
... shortened....
Dependencies Resolved

=======================================================================
Package               Arch   Version                 Repository    Size
=======================================================================
Installing:
 java-1.8.0-openjdk  x86_64  1:1.8.0.144-0.b01.el7_4 updates      238 k
 ..
 ..
Transaction Summary
=======================================================================
Install  1 Package  (+ 4 Dependent packages)

Total download size: 34 M
Is this ok [y/d/N]: y

Installed:
java-1.8.0-openjdk.x86_64 1:1.8.0.144-0.b01.el7_4
Complete!
....




=== Instalar MySQL Server 5.5.30 o posterior y las versiones 5.6.x en Red Hat Enterprise Linux 7 o CentOS 7

Debe instalar MySQL Server 5.5.30 o posterior y la versión 5.6.x en el sistema host antes de instalar o actualizar el software Tiebreaker.

.Pasos
. Inicie sesión como `root` al sistema host.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2016 from host.domain.com
----
. Añada el repositorio de MySQL al sistema host:
+
`[root@mcctb ~]# yum localinstall \https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm`

+
....

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Local Package Process
Examining /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm: mysql-community-release-el6-5.noarch
Marking /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mysql-community-release.noarch 0:el6-5 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
Package               Arch   Version
                                    Repository                             Size
================================================================================
Installing:
mysql-community-release
                       noarch el6-5 /mysql-community-release-el6-5.noarch 4.3 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 4.3 k
Installed size: 4.3 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-release-el6-5.noarch                         1/1
  Verifying  : mysql-community-release-el6-5.noarch                         1/1
Installed:
  mysql-community-release.noarch 0:el6-5
Complete!
....
. Desactive el repositorio de mysql 57:
+
`[root@mcctb ~]# yum-config-manager --disable mysql57-community`

. Activar el repositorio mysql 56:
+
`[root@mcctb ~]# yum-config-manager --enable mysql56-community`

. Habilite el repositorio:
+
`[root@mcctb ~]# yum repolist enabled | grep "mysql.*-community.*"`

+
....

mysql-connectors-community           MySQL Connectors Community            21
mysql-tools-community                MySQL Tools Community                 35
mysql56-community                    MySQL 5.6 Community Server           231
....
. Instale el servidor de comunidad MySQL:
+
`[root@mcctb ~]# yum install mysql-community-server`

+
[listing]
----

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager
to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
.....Output truncated.....
---> Package mysql-community-libs-compat.x86_64 0:5.6.29-2.el6 will be obsoleting
--> Finished Dependency Resolution
Dependencies Resolved
==============================================================================
Package                          Arch   Version       Repository          Size
==============================================================================
Installing:
 mysql-community-client         x86_64  5.6.29-2.el6  mysql56-community  18  M
     replacing  mysql.x86_64 5.1.71-1.el6
 mysql-community-libs           x86_64  5.6.29-2.el6  mysql56-community  1.9 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-libs-compat    x86_64  5.6.29-2.el6  mysql56-community  1.6 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-server         x86_64  5.6.29-2.el6  mysql56-community  53  M
     replacing  mysql-server.x86_64 5.1.71-1.el6
Installing for dependencies:
mysql-community-common          x86_64  5.6.29-2.el6  mysql56-community   308 k

Transaction Summary
===============================================================================
Install       5 Package(s)
Total download size: 74 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): mysql-community-client-5.6.29-2.el6.x86_64.rpm       |  18 MB     00:28
(2/5): mysql-community-common-5.6.29-2.el6.x86_64.rpm       | 308 kB     00:01
(3/5): mysql-community-libs-5.6.29-2.el6.x86_64.rpm         | 1.9 MB     00:05
(4/5): mysql-community-libs-compat-5.6.29-2.el6.x86_64.rpm  | 1.6 MB     00:05
(5/5): mysql-community-server-5.6.29-2.el6.x86_64.rpm       |  53 MB     03:42
-------------------------------------------------------------------------------
Total                                              289 kB/s |  74 MB     04:24
warning: rpmts_HdrFromFdno: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
Retrieving key from file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid : MySQL Release Engineering <mysql-build@oss.oracle.com>
Package: mysql-community-release-el6-5.noarch
         (@/mysql-community-release-el6-5.noarch)
 From   : file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-common-5.6.29-2.el6.x86_64
....Output truncated....
1.el6.x86_64                                                               7/8
  Verifying  : mysql-5.1.71-1.el6.x86_64                       	           8/8
Installed:
  mysql-community-client.x86_64 0:5.6.29-2.el6
  mysql-community-libs.x86_64 0:5.6.29-2.el6
  mysql-community-libs-compat.x86_64 0:5.6.29-2.el6
  mysql-community-server.x86_64 0:5.6.29-2.el6

Dependency Installed:
  mysql-community-common.x86_64 0:5.6.29-2.el6

Replaced:
  mysql.x86_64 0:5.1.71-1.el6 mysql-libs.x86_64 0:5.1.71-1.el6
  mysql-server.x86_64 0:5.1.71-1.el6
Complete!
----
. Inicie el servidor MySQL:
+
`[root@mcctb ~]# service mysqld start`

+
....

Initializing MySQL database:  2016-04-05 19:44:38 0 [Warning] TIMESTAMP
with implicit DEFAULT value is deprecated. Please use
--explicit_defaults_for_timestamp server option (see documentation
for more details).
2016-04-05 19:44:38 0 [Note] /usr/sbin/mysqld (mysqld 5.6.29)
        starting as process 2487 ...
2016-04-05 19:44:38 2487 [Note] InnoDB: Using atomics to ref count
        buffer pool pages
2016-04-05 19:44:38 2487 [Note] InnoDB: The InnoDB memory heap is disabled
....Output truncated....
2016-04-05 19:44:42 2509 [Note] InnoDB: Shutdown completed; log sequence
       number 1625987

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER!
To do so, start the server, then issue the following commands:

  /usr/bin/mysqladmin -u root password 'new-password'
  /usr/bin/mysqladmin -u root -h mcctb password 'new-password'

Alternatively, you can run:
  /usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
.....Output truncated.....
WARNING: Default config file /etc/my.cnf exists on the system
This file will be read by default by the MySQL server
If you do not want to use this, either remove it, or use the
--defaults-file argument to mysqld_safe when starting the server

                                                           [  OK  ]
Starting mysqld:                                           [  OK  ]
....
. Confirme que el servidor MySQL está ejecutando:
+
`[root@mcctb ~]# service mysqld status`

+
[listing]
----

mysqld (pid  2739) is running...
----
. Configure los ajustes de seguridad y contraseña:
+
`[root@mcctb ~]# mysql_secure_installation`

+
....

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
       SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

 In order to log into MySQL to secure it, we'll need the current
 password for the root user.  If you've just installed MySQL, and
 you haven't set the root password yet, the password will be blank,
 so you should just press enter here.

 Enter current password for root (enter for none):   <== on default install
                                                         hit enter here
 OK, successfully used password, moving on...

 Setting the root password ensures that nobody can log into the MySQL
 root user without the proper authorization.

 Set root password? [Y/n] y
 New password:
 Re-enter new password:
 Password updated successfully!
 Reloading privilege tables..
  ... Success!

 By default, a MySQL installation has an anonymous user, allowing anyone
 to log into MySQL without having to have a user account created for
 them.  This is intended only for testing, and to make the installation
 go a bit smoother.  You should remove them before moving into a
 production environment.

 Remove anonymous users? [Y/n] y
  ... Success!

 Normally, root should only be allowed to connect from 'localhost'.  This
 ensures that someone cannot guess at the root password from the network.

 Disallow root login remotely? [Y/n] y
  ... Success!

 By default, MySQL comes with a database named 'test' that anyone can
 access.  This is also intended only for testing, and should be removed
 before moving into a production environment.

 Remove test database and access to it? [Y/n] y
  - Dropping test database...
 ERROR 1008 (HY000) at line 1: Can't drop database 'test';
 database doesn't exist
  ... Failed!  Not critical, keep moving...
  - Removing privileges on test database...
  ... Success!

 Reloading the privilege tables will ensure that all changes made so far
 will take effect immediately.

 Reload privilege tables now? [Y/n] y
  ... Success!

 All done!  If you've completed all of the above steps, your MySQL
 installation should now be secure.

 Thanks for using MySQL!

 Cleaning up...
....
. Compruebe que el inicio de sesión de MySQL funciona:
+
`[root@mcctb ~]# mysql -u root –p`

+
....

Enter password: <configured_password>
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql>
....
+
Si el inicio de sesión de MySQL está funcionando, la salida finalizará en la `mysql>` prompt.





==== Habilitar la configuración de inicio automático de MySQL

Debe asegurarse de que la función de inicio automático esté activada para MySQL deamon. Al activar el daemon MySQL se reinicia automáticamente si se reinicia el sistema en el que reside el software MetroCluster Tiebreaker. Si el daemon MySQL no se está ejecutando, el software Tiebreaker continúa ejecutándose, pero no puede reiniciarse y no se pueden realizar cambios de configuración.

.Paso
. Compruebe que MySQL está habilitado para el inicio automático cuando arranque:
+
`[root@mcctb ~]# systemctl list-unit-files mysqld.service`

+
....
UNIT FILE          State
------------------ ----------
mysqld.service     enabled

....
+
Si MySQL no está habilitado para el inicio automático al arrancar, consulte la documentación de MySQL para activar la función de inicio automático para la instalación.





=== Instalación del servidor MariaDB en Red Hat Enterprise Linux 8

Debe instalar el servidor MariaDB en el sistema host antes de instalar o actualizar el software Tiebreaker.

.Antes de empezar
El sistema host debe ejecutarse en Red Hat Enterprise Linux (RHEL) 8.

.Pasos
. Inicie sesión como `root` al sistema host.
+
....

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
....
. Instalar el servidor MariaDB:
+
`[root@mcctb ~]# yum install mariadb-server.x86_64`

+
....
 [root@mcctb ~]# yum install mariadb-server.x86_64
Loaded plugins: fastestmirror, langpacks
...
...

===========================================================================
 Package                      Arch   Version         Repository        Size
===========================================================================
Installing:
mariadb-server               x86_64   1:5.5.56-2.el7   base            11 M
Installing for dependencies:

Transaction Summary
===========================================================================
Install  1 Package  (+8 Dependent packages)
Upgrade             ( 1 Dependent package)

Total download size: 22 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for base warning:
/var/cache/yum/x86_64/7/base/packages/mariadb-libs-5.5.56-2.el7.x86_64.rpm:
Header V3 RSA/SHA256 Signature,
key ID f4a80eb5: NOKEY] 1.4 MB/s | 3.3 MB  00:00:13 ETA
Public key for mariadb-libs-5.5.56-2.el7.x86_64.rpm is not installed
(1/10): mariadb-libs-5.5.56-2.el7.x86_64.rpm  | 757 kB  00:00:01
..
..
(10/10): perl-Net-Daemon-0.48-5.el7.noarch.rpm|  51 kB  00:00:01
-----------------------------------------------------------------------------------------
Installed:
  mariadb-server.x86_64 1:5.5.56-2.el7

Dependency Installed:
mariadb.x86_64 1:5.5.56-2.el7
perl-Compress-Raw-Bzip2.x86_64 0:2.061-3.el7
perl-Compress-Raw-Zlib.x86_64 1:2.061-4.el7
perl-DBD-MySQL.x86_64 0:4.023-5.el7
perl-DBI.x86_64 0:1.627-4.el7
perl-IO-Compress.noarch 0:2.061-2.el7
perl-Net-Daemon.noarch 0:0.48-5.el7
perl-PlRPC.noarch 0:0.2020-14.el7

Dependency Updated:
  mariadb-libs.x86_64 1:5.5.56-2.el7
Complete!
....
. Inicie el servidor MariaDB:
+
`[root@mcctb ~]# systemctl start mariadb`

. Compruebe que el servidor MariaDB se ha iniciado:
+
`[root@mcctb ~]# systemctl status mariadb`

+
....

[root@mcctb ~]# systemctl status mariadb
mariadb.service - MariaDB database server
...
Nov 08 21:28:59 mcctb systemd[1]: Starting MariaDB database server...
...
Nov 08 21:29:01 scspr0523972001 systemd[1]: Started MariaDB database server.
....
+

NOTE: Asegúrese de que la configuración "Activar inicio automático" esté activada para MariaDB. Consulte <<mariadb-autostart>>.

. Configure los ajustes de seguridad y contraseña:
+
`[root@mcctb ~]# mysql_secure_installation`

+
....

[root@mcctb ~]# mysql_secure_installation
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
SERVERS IN PRODUCTION USE! PLEASE READ EACH STEP CAREFULLY!
Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Remove anonymous users? [Y/n] y
... Success!
Normally, root should only be allowed to connect from 'localhost'. This
ensures that someone cannot guess at the root password from the network.
Disallow root login remotely? [Y/n] y
... Success!
Remove test database and access to it? [Y/n] y
- Dropping test database...
... Success!
- Removing privileges on test database...
... Success!
Reload privilege tables now? [Y/n]
... Success!
Cleaning up...
All done! If you've completed all of the above steps, your MariaDB
installation should now be secure.
Thanks for using MariaDB!
....




==== Activación de la configuración de inicio automático para MariaDB

Debe asegurarse de que la función de inicio automático esté activada para MariaDB. Si no activa la función de inicio automático y el sistema en el que reside el software MetroCluster Tiebreaker debe reiniciarse, el software de tiebreaker, pero el servicio MariaDB no puede reiniciarse y no se pueden realizar cambios de configuración.

.Pasos
. Active el servicio de inicio automático:
+
`[root@mcctb ~]# systemctl enable mariadb.service`

. Compruebe que MariaDB está habilitado para iniciarse automáticamente al arrancar:
+
`[root@mcctb ~]# systemctl list-unit-files mariadb.service`

+
....
UNIT FILE          State
------------------ ----------
mariadb.service    enabled

....




== Instalar o actualizar el paquete de software

Debe instalar o actualizar el software MetroCluster Tiebreaker en el equipo local para supervisar las configuraciones de MetroCluster.

* El sistema de almacenamiento debe ejecutar ONTAP 8.3.x o una versión posterior.
* Debe haber instalado OpenJDK mediante el `yum install java-1.8.0-openjdk` comando.


.Pasos
. Descargue la última versión del software MetroCluster Tiebreaker. En este ejemplo se utiliza la versión 1.21P3-1.
+
https://mysupport.netapp.com/site/["Soporte de NetApp"]

. Inicie sesión en el host como usuario raíz.
. Instale o actualice el software Tiebreaker:
+
[cols="20,80"]
|===


| Si está... | Emita este comando... 


 a| 
Realizando una instalación nueva
 a| 
`rpm -ivh NetApp-MetroCluster-Tiebreaker-Software-1.21P3-1x86_64.rpm`

El sistema muestra el siguiente resultado para una instalación correcta:

....
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Post installation start Wed Oct 20 09:59:19 EDT 2021
Enter MetroCluster Tiebreaker user password:

Please enter mysql root password when prompted
Enter password:
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post installation end Wed Oct 20 09:59:28 EDT 2021
Successfully installed NetApp MetroCluster Tiebreaker software version 1.21P3.
....


 a| 
Actualizar una instalación existente
 a| 
`rpm -Uvh NetApp-MetroCluster-Tiebreaker-Software-1.21P3-1.x86_64.rpm`

El sistema muestra el siguiente resultado para una actualización correcta:

....

MetroCluster-Tiebreaker-Software-1.21P3-1.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Upgrading NetApp MetroCluster Tiebreaker software....
Stopping NetApp MetroCluster Tiebreaker software services before upgrade.
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]
Post installation start Wed Oct 20 09:57:49 EDT 2021
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Starting NetApp MetroCluster Tiebreaker software services. Retry: 1
Started NetApp MetroCluster Tiebreaker software services
Enabled autostart of NetApp MetroCluster Tiebreaker software daemon during boot
Created symbolic link for NetApp MetroCluster Tiebreaker software CLI
Post upgrade end Wed Oct 20 09:57:52 EDT 2021
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.21P3.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]

....
|===
+

NOTE: Si introduce la contraseña raíz de MySQL incorrecta, el software Tiebreaker indica que se ha instalado correctamente, pero muestra mensajes de acceso denegado. Para resolver el problema, debe desinstalar el software Tiebreaker mediante `rpm -e` Y a continuación, vuelva a instalar el software utilizando la contraseña raíz de MySQL correcta.

. Compruebe la conectividad de tiebreaker con el software MetroCluster abriendo una conexión SSH desde el host Tiebreaker hasta cada LIF de gestión de nodos y LIF de gestión de clústeres.


.Información relacionada
https://mysupport.netapp.com/site/["Soporte de NetApp"]



== Actualizar el host donde se ejecuta el monitor de tiebreaker

Puede actualizar el host en el que se ejecuta el monitor de tiebreaker si coloca los monitores en modo observador antes de la actualización.

.Pasos
. Compruebe que los monitores están en modo observador:
+
`monitor show –status`

+
....
NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
....
. Cambie todos los monitores al modo observador.
+
....
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode true
....
. Para actualizar el host Tiebreaker, siga todos los pasos del siguiente procedimiento:
+
<<install-upgrade-sw-pkg,Instalar o actualizar el paquete de software>>

. Desactive el modo observador para volver a mover todos los monitores al modo en línea.
+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name _monitor_name_ -observer-mode false
----




== Seleccione el origen de NTP para el software Tiebreaker

Debe usar un origen de Protocolo de hora de red (NTP) local para el software Tiebreaker. No debe utilizar el mismo origen que los sitios MetroCluster que supervisa el software Tiebreaker.
