---
permalink: tiebreaker/task_install_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: El software Tiebreaker proporciona funcionalidades de supervisión para un entorno de almacenamiento en clúster. También envía notificaciones SNMP en el caso de problemas de conectividad de los nodos y de desastres del sitio. 
---
= Instalación del software Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software Tiebreaker proporciona funcionalidades de supervisión para un entorno de almacenamiento en clúster. También envía notificaciones SNMP en el caso de problemas de conectividad de los nodos y de desastres del sitio.

El software Tierbreaker debe estar instalado y configurado.



== Requisitos del sistema para instalar o actualizar el software Tiebreaker

El software Tierbreaker se instala en un tercer sitio, lo que permite al software distinguir entre un fallo de enlace entre switches (ISL) (cuando los enlaces entre sitios están inactivos) y un fallo de sitio. El sistema host debe cumplir determinados requisitos antes de poder instalar o actualizar el software Tiebreaker en el equipo local para supervisar la configuración de MetroCluster.


NOTE: Debe tener privilegios de "root" para instalar el software MetroCluster Tiebreaker y los paquetes dependientes.

El software MetroCluster Tiebreaker tiene las siguientes funcionalidades y requisitos de supervisión:

* Capacidades de supervisión simultánea de hasta 15 configuraciones de MetroCluster.
+

NOTE: Solo puede usar un monitor MetroCluster Tiebreaker por configuración de MetroCluster para evitar cualquier conflicto con varios monitores de tiebreaker.

* Admite una combinación de configuraciones de MetroCluster IP, MetroCluster FC y MetroCluster con ampliación.
* Hardware y software:
+
** ONTAP 8.3.x, 9.0, 9.1, 9.2, 9.3 9.4, 9.5, 9.6, 9.7, 9.8, 9.9.1, 9.10.1, 9.11.1 o 9.12.1


* Red Hat Enterprise Linux 7 a 7.9, o CentOS de 7 a 7.9 64 bits (instalación física o máquina virtual)
+

NOTE: Solo MetroCluster Tiebreaker 1.4 es compatible con las versiones de RHEL 7-7.9.

+
** MariaDB 5.5.52.x/MySQL Server 5.6x
** 4 GB DE MEMORIA RAM
** Abra JRE 8


* Red Hat Enterprise Linux 8.1 a 8.7
+
** MariaDB 10.x (utilice la versión predeterminada que se instala utilizando "yum install mariadb-Server.x86_64")
** 4 GB DE MEMORIA RAM
** Abra JRE 8
+
Para sistemas que ejecuten Tiebreaker 1.4 y versiones anteriores, ejecute JRE 8. Para sistemas que ejecuten Tiebreaker 1.5 y posteriores, ejecute OpenJDK 17, 18 o 19.





* Capacidad del disco: 8 GB
* Firewall:
+
** Acceso directo para configurar mensajes AutoSupport
** SSH (puerto 22/TCP), HTTPS (puerto 443/TCP) y ping (ICMP)






== Asegurar la instalación de hosts y bases de datos

Para configuraciones que ejecuten MetroCluster Tiebreaker 1.5 y posteriores, puede proteger y reforzar el sistema operativo del host y la base de datos.



=== Proteja el host

Las siguientes directrices muestran cómo proteger el host donde está instalado el software Tiebreaker.

* Limite el acceso del usuario "raíz".
+
** Puede utilizar usuarios que puedan elevar el acceso raíz para instalar y administrar el software Tiebreaker.
** Puede utilizar usuarios que no puedan elevar al acceso raíz para administrar el software Tiebreaker.
+

NOTE: Durante la instalación, debe crear un grupo denominado "mcctbgrp". El usuario raíz del host y el usuario creado durante la instalación son ambos miembros. Sólo los miembros de este grupo pueden administrar completamente el software Tiebreaker.

** Los usuarios que no sean miembros de este grupo no pueden acceder al software Tiebreaker o a la CLI. Puede crear usuarios adicionales en el host y hacerlos miembros del grupo. Estos miembros adicionales no pueden administrar completamente el software Tiebreaker, tienen acceso a ReadOnly y no pueden agregar, cambiar ni eliminar monitores.


* Utilizar el cifrado de disco
+
** Puede habilitar el cifrado de disco. Puede ser FullDiskEncryption (hardware), o el cifrado proporcionado por Hostos (software), o por el host de SVM.


* Desactive los servicios no utilizados que permiten las conexiones entrantes. Puede deshabilitar cualquier servicio que no esté en uso. El software Tierbreaker no requiere un servicio para conexiones entrantes porque todas las conexiones de la instalación de tiebreaker son salientes. Los servicios que se pueden activar de forma predeterminada y que se pueden desactivar son:
+
** Servidor HTTP/HTTPS
** Servidor FTP
** Telnet, RSH, rlogin
** Acceso a NFS, CIFS y otros protocolos
** RDP (RemoteDesktopProtocol), X11 Server, VNC u otros proveedores de servicios de "escritorio" remotos.
+

NOTE: Debe dejar el acceso a la consola serie (si es compatible) o al menos un protocolo habilitado para administrar el host de forma remota. Si deshabilita todos los protocolos, deberá tener acceso físico al host para la administración.



* Proteger el host mediante FIPS
+
** Puede instalar el sistema operativo host en modo conforme a FIPS y, a continuación, instalar Tiebreaker.
+

NOTE: OpenJDK 19 comprueba al inicio si el host está instalado en modo FIPS. No es necesario realizar cambios manuales.



* Recomendaciones de referencia
+
** No ejecute tiebreaker como usuario raíz. Utilice una cuenta de servicio dedicada y sin privilegios para ejecutar tiebreaker.
** Cambie la cadena de comunidad predeterminada en el archivo "/etc/snmp/snmpd.conf".
** Permita privilegios de escritura mínimos. La cuenta de servicio de tiebreaker sin privilegios no debe tener acceso para sobrescribir su binario ejecutable o cualquier archivo de configuración. El usuario de tiebreaker solo debe escribir los directorios y archivos para el almacenamiento local de tiebreaker (por ejemplo, para el almacenamiento de back-end integrado) o los registros de auditoría.
** Seguridad de capa de transporte (TLS) de extremo a extremo. Tiebreaker siempre debe usarse con TLS. Si se utilizan equilibradores de carga intermedios o proxies reversos para front Tiebreaker, debe utilizar TLS para todas las conexiones de red entre todos los componentes del sistema (incluido el almacenamiento de back-end) para garantizar que todo el tráfico esté cifrado en tránsito hacia y desde Tiebreaker. Cuando sea posible, debe establecer el encabezado HTTP estricto Transport Security (HSTS) utilizando la función de encabezados de respuesta personalizados de tiebreaker.
** Debe instalar y ejecutar la versión más reciente de OpenSSH.
** No permita usuarios anónimos.
** Establezca AllowTcpForwarding en "no" o utilice la directiva Match para restringir los usuarios anónimos.
** Desactive el historial de comandos de Shell.
** Actualice con frecuencia. Tiebreaker está activamente desarrollado y actualizar con frecuencia es importante para incorporar correcciones de seguridad y cambios en la configuración predeterminada, como longitudes de clave o conjuntos de cifrado.
** Suscríbete a la lista de correo de HashiCorp Anuncio para recibir anuncios de nuevos lanzamientos y visita el CHANGELOG de Tiebreaker para obtener información sobre las últimas actualizaciones para nuevos lanzamientos.
** Utilice los permisos de archivo correctos. Asegúrese siempre de que se aplican los permisos adecuados a los archivos antes de iniciar el software Tiebreaker, especialmente los que contienen información confidencial.
** La autenticación multifactor (MFA) mejora la seguridad de su organización al requerir que los administradores se identifiquen usando más del nombre de usuario y la contraseña. Aunque es importante, los nombres de usuario y las contraseñas son vulnerables a ataques de fuerza bruta y pueden ser robados por terceros. RHEL 8 ofrece MFA que requiere que los usuarios proporcionen más de un elemento de información para autenticarse correctamente en una cuenta o host Linux. La información adicional puede ser una contraseña única enviada a su teléfono móvil a través de SMS o credenciales de una aplicación como Google Authenticator, hyphhydramine io Authy, o FreeOTP.






==== Información relacionada

.Gestión de usuarios
link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_getting-started-with-managing-user-accounts_configuring-basic-system-settings["Introducción a la gestión de cuentas de usuario"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/introduction-to-managing-user-and-group-accounts_configuring-basic-system-settings["Introducción a la administración de cuentas de usuarios y grupos"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-user-accounts-in-the-web-console-new_configuring-basic-system-settings["Administración de cuentas de usuario en la consola Web"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-from-the-command-line_configuring-basic-system-settings["Administrar usuarios desde la línea de comandos"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/editing-user-groups-using-the-command-line_configuring-basic-system-settings["Editar grupos de usuarios mediante la línea de comandos"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-sudo-access_configuring-basic-system-settings["Gestión del acceso sudo"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/changing-and-resetting-the-root-password-from-the-command-line_configuring-basic-system-settings["Administrar y restablecer la contraseña raíz"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/index["Seguridad reforzada"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/index["Proteger las redes"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-system-services-with-systemctl_configuring-basic-system-settings["Administrar servicios del sistema con systemctl"^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8["Documentación de RHEL 8"^]

link:https://access.redhat.com/documentation/ru-ru/openjdk/8/html/configuring_openjdk_8_on_rhel_with_fips/openjdk-default-fips-configuration["Configuración de FIPS predeterminada en OpenJDK 8"^]


NOTE: Si asegura el host, debe asegurarse de que pueda arrancar sin intervención del usuario. Si es necesaria la intervención del usuario, es posible que la funcionalidad de tiebreaker siempre esté disponible si el host se reinicia de forma inesperada. En este caso, la funcionalidad de tiebreaker solo está disponible tras la intervención manual y cuando el host se inicia por completo.



=== Proteja la instalación de la base de datos

Las siguientes directrices muestran cómo proteger y reforzar la instalación de la base de datos MariaDB 10.x.

* Limite el acceso del usuario "raíz".
+
** Tiebreaker utiliza una cuenta dedicada. La cuenta y las tablas para almacenar datos (configuración) se crean durante la instalación de Tiebreaker. El único tiempo que se requiere un acceso elevado a la base de datos es durante la instalación.


* Durante la instalación se requieren los siguientes privilegios y acceso:
+
** La capacidad de crear una base de datos y tablas
** Capacidad de crear opciones globales
** La capacidad de crear un usuario de base de datos y establecer la contraseña
** Capacidad de asociar el usuario de la base de datos a la base de datos y a las tablas y asignar derechos de acceso
+

NOTE: La cuenta de usuario que especifique durante la instalación de tiebreaker debe tener todos estos privilegios. No se admite el uso de varias cuentas de usuario para las distintas tareas.



* Utilice el cifrado de la base de datos
+
** Ofrecemos compatibilidad con el cifrado de datos en reposo
** Los datos en tránsito no están cifrados. Los datos en vuelo usan una conexión de archivos "SOCKS" local.
** FIPS conformidad para MariaDB -- no es necesario habilitar FIPS conformidad con la base de datos. La instalación del host en modo conforme a FIPS es suficiente.


+

NOTE: Si necesita cifrado, la configuración de cifrado debe estar activada antes de instalar el software Tiebreaker.





==== Información relacionada

* Gestión de usuarios de bases de datos
+
link:https://dev.mysql.com/doc/refman/8.0/en/access-control.html["Control de acceso y gestión de cuentas"^]

* Proteja la base de datos
+
link:https://dev.mysql.com/doc/refman/8.0/en/security-against-attack.html["Hacer que MySQL sea seguro contra atacantes"^]

+
link:https://mariadb.com/kb/en/securing-mariadb/["Asegurar MariaDB"^]

* Cifrado de datos en reposo
+
link:https://mariadb.com/kb/en/data-at-rest-encryption-overview/["Información general del cifrado de datos en reposo"^]

+
link:https://www.mysql.com/products/enterprise/tde.html["Cifrado de datos transparente de MySQL Enterprise (TDE)"^]

* Asegure la instalación del almacén
+
link:https://developer.hashicorp.com/vault/tutorials/operations/production-hardening/["Refuerzo de la producción"^]





== Instalar las dependencias de tiebreaker para MetroCluster

Debe instalar un servidor MySQL o MariaDB en función del sistema operativo Linux que sea el host antes de instalar o actualizar el software Tiebreaker.

.Pasos
. Instale JRE.
+
<<install-java-1-8,Instale JRE>>

. Instalar y configurar el almacén.
+
<<install-vault,Instalar y configurar el almacén>>

. Instalar el servidor MySQL o MariaDB:
+
[cols="30,70"]
|===


| Si el host Linux es | Realice lo siguiente... 


 a| 
Red Hat Enterprise Linux 7/CentOS 7
 a| 
Instale MySQL

<<install-mysql-redhat,Instalar MySQL Server 5.5.30 o posterior y las versiones 5.6.x en Red Hat Enterprise Linux 7 o CentOS 7>>



 a| 
Red Hat Enterprise Linux 8
 a| 
Instalar MariaDB

<<install-mariadb,Instalación del servidor MariaDB en Red Hat Enterprise Linux 8>>

|===




=== Instale JRE

Debe instalar JRE en el sistema host antes de instalar o actualizar el software Tiebreaker. Para sistemas que ejecuten Tiebreaker 1.4 y versiones anteriores, ejecute JRE 8. Para sistemas que ejecuten Tiebreaker 1.5 y posteriores, ejecute OpenJDK 17, 18 o 19. Las salidas del ejemplo muestran JRE 1.8.0. (JRE 8).

.Pasos
. Inicie sesión como usuario "raíz" o como usuario sudo que puede cambiar al modo de privilegios avanzado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Instale JRE.
+
`yum install java-1.8.0-openjdk.x86_64`

+
....
[root@mcctb ~]# yum install java-1.8.0-openjdk.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
... shortened....
Dependencies Resolved

=======================================================================
Package               Arch   Version                 Repository    Size
=======================================================================
Installing:
 java-1.8.0-openjdk  x86_64  1:1.8.0.144-0.b01.el7_4 updates      238 k
 ..
 ..
Transaction Summary
=======================================================================
Install  1 Package  (+ 4 Dependent packages)

Total download size: 34 M
Is this ok [y/d/N]: y

Installed:
java-1.8.0-openjdk.x86_64 1:1.8.0.144-0.b01.el7_4
Complete!
....




=== Instalar y configurar el almacén

Si no tiene o desea utilizar el servidor local del almacén, debe instalar el almacén. Puede consultar este procedimiento estándar para instalar el almacén o consultar las instrucciones de instalación de Hashicorp para obtener directrices alternativas.


NOTE: Si tiene un servidor Vault en la red, puede configurar el host MetroCluster Tiebreaker para usar la instalación de dicho almacén. En este caso, no es necesario instalar Vault en el host.

.Pasos
. Descargue el archivo zip del almacén.
+
[listing]
----
[root@mcctb /bin]#  curl -sO https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
----
. Descomprima el archivo del almacén.
+
[listing]
----
[root@mcctb /bin]# unzip vault_1.12.2_linux_amd64.zip
Archive:  vault_1.12.2_linux_amd64.zip
  inflating: vault
----
. Compruebe la instalación.
+
[listing]
----
[root@mcctb /bin]# vault -version
Vault v1.12.2 (415e1fe3118eebd5df6cb60d13defdc01aa17b03), built 2022-11-23T12:53:46Z
----
. Cree un archivo de configuración del almacén y asegúrese de que el archivo de configuración se crea en el directorio "/root".
+

NOTE: Para asegurar la comunicación con Vault, debe usar TLS.

+
[listing]
----
[root@mcctb ~]# cat > config.hcl
 storage "file" {
  address = "127.0.0.1:8500"
  path    = "/mcctb_vdata/data"
 }
 listener "tcp" {
   address     = "127.0.0.1:8200"
   tls_disable = 1
 }
----
. Inicie el servidor del almacén: `vault server -config config.hcl &`
+
[listing]
----
[root@mcctb ~] vault server -config config.hcl
----
. Exporte la dirección del almacén.
+
Seleccione la opción correcta en función de si está utilizando TLS.

+
[role="tabbed-block"]
====
.Opción 1. Cuando utilice TLS
--
[listing]
----
[root@mcctb ~]# export VAULT_ADDR=’https://127.0.0.1:8300'
----
--
.Opción 2. Cuando no utilice TLS
--
[listing]
----
[root@mcctb ~]# export VAULT_ADDR="http://127.0.0.1:8200"
----
--
====
. Inicialice el almacén.
+
[listing]
----
[root@mcctb ~]# vault operator init
2022-12-15T14:57:22.113+0530 [INFO]  core: security barrier not initialized
2022-12-15T14:57:22.113+0530 [INFO]  core: seal configuration missing, not initialized
2022-12-15T14:57:22.114+0530 [INFO]  core: security barrier not initialized
2022-12-15T14:57:22.116+0530 [INFO]  core: security barrier initialized: stored=1 shares=5 threshold=3
2022-12-15T14:57:22.118+0530 [INFO]  core: post-unseal setup starting
2022-12-15T14:57:22.137+0530 [INFO]  core: loaded wrapping token key
2022-12-15T14:57:22.137+0530 [INFO]  core: Recorded vault version: vault version=1.12.2 upgrade time="2022-12-15 09:27:22.137200412 +0000 UTC" build date=2022-11-23T12:53:46Z
2022-12-15T14:57:22.137+0530 [INFO]  core: successfully setup plugin catalog: plugin-directory=""
2022-12-15T14:57:22.137+0530 [INFO]  core: no mounts; adding default mount table
2022-12-15T14:57:22.143+0530 [INFO]  core: successfully mounted backend: type=cubbyhole version="" path=cubbyhole/
2022-12-15T14:57:22.144+0530 [INFO]  core: successfully mounted backend: type=system version="" path=sys/
2022-12-15T14:57:22.144+0530 [INFO]  core: successfully mounted backend: type=identity version="" path=identity/
2022-12-15T14:57:22.148+0530 [INFO]  core: successfully enabled credential backend: type=token version="" path=token/ namespace="ID: root. Path: "
2022-12-15T14:57:22.149+0530 [INFO]  rollback: starting rollback manager
2022-12-15T14:57:22.149+0530 [INFO]  core: restoring leases
2022-12-15T14:57:22.150+0530 [INFO]  expiration: lease restore complete
2022-12-15T14:57:22.150+0530 [INFO]  identity: entities restored
2022-12-15T14:57:22.150+0530 [INFO]  identity: groups restored
2022-12-15T14:57:22.151+0530 [INFO]  core: usage gauge collection is disabled
2022-12-15T14:57:23.385+0530 [INFO]  core: post-unseal setup complete
2022-12-15T14:57:23.387+0530 [INFO]  core: root token generated
2022-12-15T14:57:23.387+0530 [INFO]  core: pre-seal teardown starting
2022-12-15T14:57:23.387+0530 [INFO]  rollback: stopping rollback manager
2022-12-15T14:57:23.387+0530 [INFO]  core: pre-seal teardown complete
Unseal Key 1: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Unseal Key 2: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Unseal Key 3: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Unseal Key 4: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Unseal Key 5: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Initial Root Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


Vault initialized with 5 key shares and a key threshold of 3. Please securely
distribute the key shares printed above. When the Vault is re-sealed,
restarted, or stopped, you must supply at least 3 of these keys to unseal it
before it can start servicing requests.

Vault does not store the generated root key. Without at least 3 keys to
reconstruct the root key, Vault will remain permanently sealed!

It is possible to generate new unseal keys, provided you have a quorum of
existing unseal keys shares. See "vault operator rekey" for more information.
----
. Exporte el token raíz del almacén.
+
[listing]
----
[root@mcctb ~]#  export VAULT_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
----
. Desselle el almacén utilizando cualquiera de las tres claves que se crearon.
+
[listing]
----

[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    1/3
Unseal Nonce       d45a3848-8338-febc-2e0b-b72b76ef3394
Version            1.12.2
Build Date         2022-11-23T12:53:46Z
Storage Type       file
HA Enabled         false
[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
Key                Value
---                -----
Seal Type          shamir
Initialized        true
Sealed             true
Total Shares       5
Threshold          3
Unseal Progress    2/3
Unseal Nonce       d45a3848-8338-febc-2e0b-b72b76ef3394
Version            1.12.2
Build Date         2022-11-23T12:53:46Z
Storage Type       file
HA Enabled         false
[root@mcctb ~]# vault operator unseal
Unseal Key (will be hidden):
2022-12-15T15:15:00.980+0530 [INFO]  core.cluster-listener.tcp: starting listener: listener_address=127.0.0.1:8201
2022-12-15T15:15:00.980+0530 [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2022-12-15T15:15:00.981+0530 [INFO]  core: post-unseal setup starting
2022-12-15T15:15:00.981+0530 [INFO]  core: loaded wrapping token key
2022-12-15T15:15:00.982+0530 [INFO]  core: successfully setup plugin catalog: plugin-directory=""
2022-12-15T15:15:00.983+0530 [INFO]  core: successfully mounted backend: type=system version="" path=sys/
2022-12-15T15:15:00.984+0530 [INFO]  core: successfully mounted backend: type=identity version="" path=identity/
2022-12-15T15:15:00.984+0530 [INFO]  core: successfully mounted backend: type=cubbyhole version="" path=cubbyhole/
2022-12-15T15:15:00.986+0530 [INFO]  core: successfully enabled credential backend: type=token version="" path=token/ namespace="ID: root. Path: "
2022-12-15T15:15:00.986+0530 [INFO]  rollback: starting rollback manager
2022-12-15T15:15:00.987+0530 [INFO]  core: restoring leases
2022-12-15T15:15:00.987+0530 [INFO]  expiration: lease restore complete
2022-12-15T15:15:00.987+0530 [INFO]  identity: entities restored
2022-12-15T15:15:00.987+0530 [INFO]  identity: groups restored
2022-12-15T15:15:00.988+0530 [INFO]  core: usage gauge collection is disabled
2022-12-15T15:15:00.989+0530 [INFO]  core: post-unseal setup complete
2022-12-15T15:15:00.989+0530 [INFO]  core: vault is unsealed
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault-cluster-2d3ed3b4
Cluster ID      fc47f0fd-135d-39a1-7a7c-97c7c4710166
HA Enabled      false
----
. Compruebe que el estado sellado del almacén es falso.
+
[listing]
----
[root@mcctb ~]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault-cluster-2d3ed3b4
Cluster ID      fc47f0fd-135d-39a1-7a7c-97c7c4710166
HA Enabled      false
----
. Compruebe que el servicio Vault se inicia en el host durante el arranque.
+
.. Ejecute el siguiente comando: `cd /etc/systemd/`
+
[listing]
----
[root@mcctb ~]#  cd /etc/systemd/
----
.. Ejecute el siguiente comando: `cat > vault.service`
+
[listing]
----
[root@mcctb system]# cat > vault.service
[Unit]
Description=Vault Service
After=mariadb.service

[Service]
Type=forking
ExecStart=/usr/bin/vault server -config /root/config.hcl &
Restart=on-failure

[Install]
WantedBy=multi-user.target
----
.. Ejecute el siguiente comando: `systemctl daemon-reload`
+
[listing]
----
[root@mcctb system]#  systemctl daemon-reload
----
.. Ejecute el siguiente comando: `systemctl enable vault.service`
+
[listing]
----
[root@mcctb system]#  systemctl enable vault.service
Created symlink /etc/systemd/system/multi-user.target.wants/vault.service → /etc/systemd/system/vault.service.
----


+

NOTE: Se le solicitará que utilice esta función durante la instalación de MetroCluster Tiebreaker. Si desea cambiar el método para dessellar el almacén, deberá desinstalar y volver a instalar el software MetroCluster Tiebreaker.





=== Instalar MySQL Server 5.5.30 o posterior y las versiones 5.6.x en Red Hat Enterprise Linux 7 o CentOS 7

Debe instalar MySQL Server 5.5.30 o posterior y la versión 5.6.x en el sistema host antes de instalar o actualizar el software Tiebreaker.

.Pasos
. Inicie sesión como usuario raíz o como usuario sudo que puede cambiar al modo de privilegios avanzado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2016 from host.domain.com
----
. Añada el repositorio de MySQL al sistema host:
+
`[root@mcctb ~]# yum localinstall \https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm`

+
[listing]
----

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Local Package Process
Examining /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm: mysql-community-release-el6-5.noarch
Marking /var/tmp/yum-root-LLUw0r/mysql-community-release-el6-5.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package mysql-community-release.noarch 0:el6-5 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
Package               Arch   Version
                                    Repository                             Size
================================================================================
Installing:
mysql-community-release
                       noarch el6-5 /mysql-community-release-el6-5.noarch 4.3 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 4.3 k
Installed size: 4.3 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-release-el6-5.noarch                         1/1
  Verifying  : mysql-community-release-el6-5.noarch                         1/1
Installed:
  mysql-community-release.noarch 0:el6-5
Complete!
----
. Deshabilite el repositorio de MySQL 57:
+
`[root@mcctb ~]# yum-config-manager --disable mysql57-community`

. Habilite el repositorio de MySQL 56:
+
`[root@mcctb ~]# yum-config-manager --enable mysql56-community`

. Habilite el repositorio:
+
`[root@mcctb ~]# yum repolist enabled | grep "mysql.*-community.*"`

+
[listing]
----

mysql-connectors-community           MySQL Connectors Community            21
mysql-tools-community                MySQL Tools Community                 35
mysql56-community                    MySQL 5.6 Community Server           231
----
. Instale el servidor de comunidad MySQL:
+
`[root@mcctb ~]# yum install mysql-community-server`

+
[listing]
----

Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager
to register.
Setting up Install Process
Resolving Dependencies
--> Running transaction check
.....Output truncated.....
---> Package mysql-community-libs-compat.x86_64 0:5.6.29-2.el6 will be obsoleting
--> Finished Dependency Resolution
Dependencies Resolved
==============================================================================
Package                          Arch   Version       Repository          Size
==============================================================================
Installing:
 mysql-community-client         x86_64  5.6.29-2.el6  mysql56-community  18  M
     replacing  mysql.x86_64 5.1.71-1.el6
 mysql-community-libs           x86_64  5.6.29-2.el6  mysql56-community  1.9 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-libs-compat    x86_64  5.6.29-2.el6  mysql56-community  1.6 M
     replacing  mysql-libs.x86_64 5.1.71-1.el6
 mysql-community-server         x86_64  5.6.29-2.el6  mysql56-community  53  M
     replacing  mysql-server.x86_64 5.1.71-1.el6
Installing for dependencies:
mysql-community-common          x86_64  5.6.29-2.el6  mysql56-community   308 k

Transaction Summary
===============================================================================
Install       5 Package(s)
Total download size: 74 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): mysql-community-client-5.6.29-2.el6.x86_64.rpm       |  18 MB     00:28
(2/5): mysql-community-common-5.6.29-2.el6.x86_64.rpm       | 308 kB     00:01
(3/5): mysql-community-libs-5.6.29-2.el6.x86_64.rpm         | 1.9 MB     00:05
(4/5): mysql-community-libs-compat-5.6.29-2.el6.x86_64.rpm  | 1.6 MB     00:05
(5/5): mysql-community-server-5.6.29-2.el6.x86_64.rpm       |  53 MB     03:42
-------------------------------------------------------------------------------
Total                                              289 kB/s |  74 MB     04:24
warning: rpmts_HdrFromFdno: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
Retrieving key from file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid : MySQL Release Engineering <mysql-build@oss.oracle.com>
Package: mysql-community-release-el6-5.noarch
         (@/mysql-community-release-el6-5.noarch)
 From   : file:/etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : mysql-community-common-5.6.29-2.el6.x86_64
....Output truncated....
1.el6.x86_64                                                               7/8
  Verifying  : mysql-5.1.71-1.el6.x86_64                       	           8/8
Installed:
  mysql-community-client.x86_64 0:5.6.29-2.el6
  mysql-community-libs.x86_64 0:5.6.29-2.el6
  mysql-community-libs-compat.x86_64 0:5.6.29-2.el6
  mysql-community-server.x86_64 0:5.6.29-2.el6

Dependency Installed:
  mysql-community-common.x86_64 0:5.6.29-2.el6

Replaced:
  mysql.x86_64 0:5.1.71-1.el6 mysql-libs.x86_64 0:5.1.71-1.el6
  mysql-server.x86_64 0:5.1.71-1.el6
Complete!
----
. Inicie el servidor MySQL:
+
`[root@mcctb ~]# service mysqld start`

+
[listing]
----

Initializing MySQL database:  2016-04-05 19:44:38 0 [Warning] TIMESTAMP
with implicit DEFAULT value is deprecated. Please use
--explicit_defaults_for_timestamp server option (see documentation
for more details).
2016-04-05 19:44:38 0 [Note] /usr/sbin/mysqld (mysqld 5.6.29)
        starting as process 2487 ...
2016-04-05 19:44:38 2487 [Note] InnoDB: Using atomics to ref count
        buffer pool pages
2016-04-05 19:44:38 2487 [Note] InnoDB: The InnoDB memory heap is disabled
....Output truncated....
2016-04-05 19:44:42 2509 [Note] InnoDB: Shutdown completed; log sequence
       number 1625987

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER!
To do so, start the server, then issue the following commands:

  /usr/bin/mysqladmin -u root password 'new-password'
  /usr/bin/mysqladmin -u root -h mcctb password 'new-password'

Alternatively, you can run:
  /usr/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
.....Output truncated.....
WARNING: Default config file /etc/my.cnf exists on the system
This file will be read by default by the MySQL server
If you do not want to use this, either remove it, or use the
--defaults-file argument to mysqld_safe when starting the server

                                                           [  OK  ]
Starting mysqld:                                           [  OK  ]
----
. Confirme que el servidor MySQL está ejecutando:
+
`[root@mcctb ~]# service mysqld status`

+
[listing]
----

mysqld (pid  2739) is running...
----
. Configure los ajustes de seguridad y contraseña:
+
`[root@mcctb ~]# mysql_secure_installation`

+
[listing]
----

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MySQL
       SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

 In order to log into MySQL to secure it, we'll need the current
 password for the root user.  If you've just installed MySQL, and
 you haven't set the root password yet, the password will be blank,
 so you should just press enter here.

 Enter current password for root (enter for none):   <== on default install
                                                         hit enter here
 OK, successfully used password, moving on...

 Setting the root password ensures that nobody can log into the MySQL
 root user without the proper authorization.

 Set root password? [Y/n] y
 New password:
 Re-enter new password:
 Password updated successfully!
 Reloading privilege tables..
  ... Success!

 By default, a MySQL installation has an anonymous user, allowing anyone
 to log into MySQL without having to have a user account created for
 them.  This is intended only for testing, and to make the installation
 go a bit smoother.  You should remove them before moving into a
 production environment.

 Remove anonymous users? [Y/n] y
  ... Success!

 Normally, root should only be allowed to connect from 'localhost'.  This
 ensures that someone cannot guess at the root password from the network.

 Disallow root login remotely? [Y/n] y
  ... Success!

 By default, MySQL comes with a database named 'test' that anyone can
 access.  This is also intended only for testing, and should be removed
 before moving into a production environment.

 Remove test database and access to it? [Y/n] y
  - Dropping test database...
 ERROR 1008 (HY000) at line 1: Can't drop database 'test';
 database doesn't exist
  ... Failed!  Not critical, keep moving...
  - Removing privileges on test database...
  ... Success!

 Reloading the privilege tables will ensure that all changes made so far
 will take effect immediately.

 Reload privilege tables now? [Y/n] y
  ... Success!

 All done!  If you've completed all of the above steps, your MySQL
 installation should now be secure.

 Thanks for using MySQL!

 Cleaning up...
----
. Compruebe que el inicio de sesión de MySQL funciona:
+
`[root@mcctb ~]# mysql -u root –p`

+
[listing]
----
Enter password: <configured_password>
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 5.6.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql>
----
+
Si el inicio de sesión de MySQL está funcionando, la salida finalizará en la `mysql>` prompt.





==== Habilitar la configuración de inicio automático de MySQL

Debe verificar que la función de inicio automático esté activada para el daemon MySQL. Al activar el daemon MySQL se reinicia automáticamente si se reinicia el sistema en el que reside el software MetroCluster Tiebreaker. Si el daemon MySQL no se está ejecutando, el software Tiebreaker continúa ejecutándose, pero no puede reiniciarse y no se pueden realizar cambios de configuración.

.Paso
. Compruebe que MySQL está habilitado para el inicio automático cuando arranque:
+
`[root@mcctb ~]# systemctl list-unit-files mysqld.service`

+
[listing]
----
UNIT FILE          State
------------------ ----------
mysqld.service     enabled

----
+
Si MySQL no está habilitado para el inicio automático al arrancar, consulte la documentación de MySQL para activar la función de inicio automático para la instalación.





=== Instalación del servidor MariaDB en Red Hat Enterprise Linux 8

Debe instalar el servidor MariaDB en el sistema host antes de instalar o actualizar el software Tiebreaker.

.Antes de empezar
El sistema host debe ejecutarse en Red Hat Enterprise Linux (RHEL) 8.

.Pasos
. Inicie sesión como `root` usuario o un usuario que puede sudo al modo de privilegios avanzado.
+
[listing]
----

login as: root
root@mcctb's password:
Last login: Fri Jan  8 21:33:00 2017 from host.domain.com
----
. Instalar el servidor MariaDB:
+
`[root@mcctb ~]# yum install mariadb-server.x86_64`

+
[listing]
----
 [root@mcctb ~]# yum install mariadb-server.x86_64
Loaded plugins: fastestmirror, langpacks
...
...

===========================================================================
 Package                      Arch   Version         Repository        Size
===========================================================================
Installing:
mariadb-server               x86_64   1:5.5.56-2.el7   base            11 M
Installing for dependencies:

Transaction Summary
===========================================================================
Install  1 Package  (+8 Dependent packages)
Upgrade             ( 1 Dependent package)

Total download size: 22 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for base warning:
/var/cache/yum/x86_64/7/base/packages/mariadb-libs-5.5.56-2.el7.x86_64.rpm:
Header V3 RSA/SHA256 Signature,
key ID f4a80eb5: NOKEY] 1.4 MB/s | 3.3 MB  00:00:13 ETA
Public key for mariadb-libs-5.5.56-2.el7.x86_64.rpm is not installed
(1/10): mariadb-libs-5.5.56-2.el7.x86_64.rpm  | 757 kB  00:00:01
..
..
(10/10): perl-Net-Daemon-0.48-5.el7.noarch.rpm|  51 kB  00:00:01
-----------------------------------------------------------------------------------------
Installed:
  mariadb-server.x86_64 1:5.5.56-2.el7

Dependency Installed:
mariadb.x86_64 1:5.5.56-2.el7
perl-Compress-Raw-Bzip2.x86_64 0:2.061-3.el7
perl-Compress-Raw-Zlib.x86_64 1:2.061-4.el7
perl-DBD-MySQL.x86_64 0:4.023-5.el7
perl-DBI.x86_64 0:1.627-4.el7
perl-IO-Compress.noarch 0:2.061-2.el7
perl-Net-Daemon.noarch 0:0.48-5.el7
perl-PlRPC.noarch 0:0.2020-14.el7

Dependency Updated:
  mariadb-libs.x86_64 1:5.5.56-2.el7
Complete!
----
. Inicie el servidor MariaDB:
+
`[root@mcctb ~]# systemctl start mariadb`

. Compruebe que el servidor MariaDB se ha iniciado:
+
`[root@mcctb ~]# systemctl status mariadb`

+
....

[root@mcctb ~]# systemctl status mariadb
mariadb.service - MariaDB database server
...
Nov 08 21:28:59 mcctb systemd[1]: Starting MariaDB database server...
...
Nov 08 21:29:01 scspr0523972001 systemd[1]: Started MariaDB database server.
....
+

NOTE: Compruebe que la configuración "Activar inicio automático" está activada para MariaDB. Consulte <<mariadb-autostart>>.

. Configure los ajustes de seguridad y contraseña:
+
`[root@mcctb ~]# mysql_secure_installation`

+
[listing]
----

[root@mcctb ~]# mysql_secure_installation
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
SERVERS IN PRODUCTION USE! PLEASE READ EACH STEP CAREFULLY!
Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Remove anonymous users? [Y/n] y
... Success!
Normally, root should only be allowed to connect from 'localhost'. This
ensures that someone cannot guess at the root password from the network.
Disallow root login remotely? [Y/n] y
... Success!
Remove test database and access to it? [Y/n] y
- Dropping test database...
... Success!
- Removing privileges on test database...
... Success!
Reload privilege tables now? [Y/n]
... Success!
Cleaning up...
All done! If you've completed all of the above steps, your MariaDB
installation should now be secure.
Thanks for using MariaDB!
----




==== Activación de la configuración de inicio automático para MariaDB

Debe comprobar que la función de inicio automático está activada para MariaDB. Si no activa la función de inicio automático y el sistema en el que reside el software MetroCluster Tiebreaker debe reiniciarse, el software de tiebreaker, pero el servicio MariaDB no puede reiniciarse y no se pueden realizar cambios de configuración.

.Pasos
. Active el servicio de inicio automático:
+
`[root@mcctb ~]# systemctl enable mariadb.service`

. Compruebe que MariaDB está habilitado para iniciarse automáticamente al arrancar:
+
`[root@mcctb ~]# systemctl list-unit-files mariadb.service`

+
[listing]
----
UNIT FILE          State
------------------ ----------
mariadb.service    enabled
----




== Instalar o actualizar el paquete de software

Debe instalar o actualizar el software MetroCluster Tiebreaker en el equipo local para supervisar las configuraciones de MetroCluster.

* El sistema de almacenamiento debe ejecutar ONTAP 8.3.x o una versión posterior.
* Debe haber instalado OpenJDK mediante el `yum install java-x.x.x-openjdk` comando. Para sistemas que ejecuten Tiebreaker 1.4 y versiones anteriores, ejecute JRE 8. Para sistemas que ejecuten Tiebreaker 1.5 y posteriores, ejecute OpenJDK 17, 18 o 19. Las salidas del ejemplo muestran JRE 1.8.0. (JRE 8).
* Puede instalar MetroCluster Tiebreaker como usuario que no sea raíz con suficientes privilegios de administración para realizar la instalación de tiebreaker, crear tablas, usuarios, y establecer la contraseña de usuario, etc.


.Pasos
. Descargue la última versión del software MetroCluster Tiebreaker. En este ejemplo se usa la versión 1.5.
+
https://["Soporte de NetApp"^]

. Inicie sesión en el host como usuario raíz.
. Verifique el archivo RPM.
+
.. Descargue e importe el archivo de claves RPM:
+
[listing]
----
[root@mcctb ~]# rpm --import MetroCluster_Tiebreaker_RPM_GPG.key
----
.. Compruebe la huella digital para comprobar que se ha importado la clave correcta.
+
En el ejemplo siguiente se muestra una huella digital correcta de la clave:

+
[listing]
----
root@mcctb:~/signing/mcctb-rpms# gpg --show-keys --with-fingerprint MetroCluster_Tiebreaker_RPM_GPG.key
pub   rsa3072 2022-11-17 [SCEA] [expires: 2025-11-16]
      65AC 1562 E28A 1497 7BBD  7251 2855 EB02 3E77 FAE5
uid                      MCCTB-RPM (mcctb RPM production signing) <mcctb-rpm@netapp.com>
----
.. Compruebe la firma: `rpm --checksig NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
[listing]
----
NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm: digests OK
----
+

NOTE: Sólo debe continuar con la instalación una vez que haya verificado correctamente la firma.



. [[install-Tiebreaker]]instale o actualice el software de tiebreaker:
+

NOTE: Solo puede actualizar a tiebreaker versión 1.5 cuando actualice desde la versión 1.4 de tiebreaker. No se puede actualizar desde versiones anteriores a Tiebreaker 1.5.

+
Seleccione el procedimiento correcto de abajo dependiendo de si está realizando una instalación nueva o actualizando una instalación existente.

+
[role="tabbed-block"]
====
.Realice una instalación nueva
--
.. Ejecute el comando:
`rpm -ivh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
El sistema muestra el siguiente resultado para una instalación correcta:

+
[listing]
----

Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Enter database user name:
root
Please enter database password for root
Enter password:
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully installed NetApp MetroCluster Tiebreaker software version 1.5.

----


--
.Actualizar una instalación existente
--
.. Compruebe que una versión compatible de OpenJDK está instalada y es la versión actual de Java que se encuentra en el host.
+

NOTE: Para las actualizaciones de Tiebreaker 1.5, debe instalar OpenJDK versión 17, 18 o 19.

+
[listing]
----
[root@mcctb ~]# readlink -f /usr/bin/java
/usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
----
.. Compruebe que el servicio del almacén no está sellado y en funcionamiento: `vault status`
+
[listing]
----
[root@mcctb ~]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault-cluster-2d3ed3b4
Cluster ID      fc47f0fd-135d-39a1-7a7c-97c7c4710166
HA Enabled      false
----
.. Actualice el software Tiebreaker.
+
[listing]
----
[root@mcctb ~]# rpm -Uvh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm
----
+
El sistema muestra el siguiente resultado para una actualización correcta:

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]
Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Enter database user name : root
Please enter database password for root
Enter password:
Password updated successfully in the database.
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.5.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
----


--
====
+

NOTE: Si introduce la contraseña raíz de MySQL incorrecta, el software Tiebreaker indica que se ha instalado correctamente, pero muestra mensajes de acceso denegado. Para resolver el problema, debe desinstalar el software Tiebreaker mediante `rpm -e` Y a continuación, vuelva a instalar el software utilizando la contraseña raíz de MySQL correcta.

. Compruebe la conectividad de tiebreaker con el software MetroCluster abriendo una conexión SSH desde el host Tiebreaker hasta cada LIF de gestión de nodos y LIF de gestión de clústeres.


.Información relacionada
https://["Soporte de NetApp"^]



== Actualizar el host donde se ejecuta el monitor de tiebreaker

Puede actualizar el host en el que se ejecuta el monitor de tiebreaker si coloca los monitores en modo observador antes de la actualización.

.Pasos
. Compruebe que los monitores están en modo observador:
+
`monitor show –status`

+
[listing]
----
NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
----
. Cambie todos los monitores al modo observador.
+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name monitor_name -observer-mode true
----
. Para actualizar el host Tiebreaker, siga todos los pasos del siguiente procedimiento:
+
<<install-upgrade-sw-pkg,Instalar o actualizar el paquete de software>>

. Desactive el modo observador para volver a mover todos los monitores al modo en línea.
+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name monitor_name -observer-mode false
----




== Seleccione el origen de NTP para el software Tiebreaker

Debe usar un origen de Protocolo de hora de red (NTP) local para el software Tiebreaker. No debe utilizar el mismo origen que los sitios MetroCluster que supervisa el software Tiebreaker.
