---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: A la hora de planificar la configuración de MetroCluster para su uso con discos y LUN de cabina, debe tener en cuenta diversos factores, como el orden de configuración del acceso al almacenamiento, la ubicación del agregado raíz y el uso de puertos iniciadores FC, switches y puentes FC a SAS. 
---
= Consideraciones que tener en cuenta al implementar una configuración de MetroCluster con discos y LUN de cabina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A la hora de planificar la configuración de MetroCluster para su uso con discos y LUN de cabina, debe tener en cuenta diversos factores, como el orden de configuración del acceso al almacenamiento, la ubicación del agregado raíz y el uso de puertos iniciadores FC, switches y puentes FC a SAS.

Tenga en cuenta la información de la siguiente tabla al planificar la configuración:

|===


| Consideración | Pautas 


 a| 
Orden de configuración del acceso al almacenamiento
 a| 
Puede configurar el acceso a los discos o a las LUN de cabina en primer lugar. Debe completar toda la configuración para ese tipo de almacenamiento y comprobar que está correctamente configurada antes de configurar el otro tipo de almacenamiento.



 a| 
Ubicación del agregado raíz
 a| 
* Si va a configurar una implementación de _new_ MetroCluster tanto con discos como LUN de cabina, debe crear el agregado raíz en discos nativos.
+
Al hacerlo, asegúrese de configurar _al menos una bandeja de discos (con 24 unidades de disco) en cada uno de los sitios.

* Si va a agregar discos nativos a una configuración _existing_ MetroCluster que utiliza LUN de cabina, el agregado raíz puede permanecer en un LUN de cabina.




 a| 
Uso de switches y puentes de FC a SAS
 a| 
Los puentes de FC a SAS se necesitan en configuraciones de cuatro nodos y en configuraciones FAS de dos nodos para conectar los sistemas ONTAP a las bandejas de discos a través de los switches.

Debe utilizar los mismos switches para conectarse a las cabinas de almacenamiento y a los puentes de FC a SAS.



 a| 
El uso de los puertos iniciadores FC
 a| 
Los puertos de iniciador que se utilizan para conectar a un puente FC-a-SAS deben ser diferentes de los puertos utilizados para conectarse a los switches, que se conectan a las cabinas de almacenamiento.

Se requiere un mínimo de ocho puertos de iniciador para conectar un sistema ONTAP a los discos y LUN de cabina.

|===
.Información relacionada
* Los procedimientos y comandos de configuración del switch son diferentes, dependiendo del proveedor del switch.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuración manual de los switches Brocade FC"]

+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configurar manualmente los switches Cisco FC"]

* Puede instalar y cablear los puentes de ATTO FiberBridge y las bandejas de discos SAS cuando agregue nuevo almacenamiento a la configuración.
+
link:task_fb_new_install.html["Instalar puentes de FC a SAS y bandejas de discos SAS"]

* La división en zonas de switches define las rutas entre los nodos conectados. La configuración de la división en zonas permite definir los LUN de cabina que puede ver un sistema ONTAP específico.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Ejemplo de división en zonas de switches en una configuración de MetroCluster de cuatro nodos con LUN de cabina"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Ejemplo de división en zonas de switches en una configuración MetroCluster de ocho nodos con LUN de cabina"]

* https://hwu.netapp.com["Hardware Universe de NetApp"]

