---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: Puede configurar sistemas FAS8020, AFF8020, FAS8200 y AFF A300 utilizando un único puerto de iniciador para cada estructura y dos puertos de iniciador para cada controladora. 
---
= Las asignaciones de puertos para los sistemas que utilizan dos puertos iniciadores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar los sistemas FAS8200 y AFF A300 utilizando un solo puerto iniciador para cada estructura y dos puertos iniciadores para cada controlador.

Puede seguir el cableado del puente FibreBridge 7600N usando solo un puerto FC (FC1 o FC2). En lugar de usar cuatro iniciadores, conecte solo dos y deje vacíos los otros dos conectados al puerto del switch.

Si la zonificación se realiza manualmente, siga la zonificación utilizada para un puente FibreBridge 7600N con un puerto FC (FC1 o FC2). En este caso, se añade un puerto iniciador en lugar de dos a cada miembro de zona por estructura.

Puede cambiar la zonificación o realizar una actualización de un FibreBridge 6500N a un FibreBridge 7500N mediante el procedimiento de link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["Intercambio en caliente de un puente FibreBridge 6500N con un puente FibreBridge 7600N o 7500N"].

La siguiente tabla muestra las asignaciones de puertos para los conmutadores Brocade FC cuando se utiliza un solo puerto iniciador para cada estructura y dos puertos iniciadores para cada controlador.

[cols="2a,2a,2a,2a"]
|===
4+| Configuraciones que utilicen FibreBridge 7500N o 7600N con solo un puerto FC (FC1 o FC2) 


 a| 
*MetroCluster 1 o Grupo DR 1*



 a| 
*Componente*
 a| 
*Puerto*
 a| 
*6505, 6510, 6520, 7840, G620, G630, G610, G710, G720, G730 y DCX 8510-8*



 a| 
*Se conecta al conmutador FC...*
 a| 
*Se conecta al puerto del conmutador...*



 a| 
controller_x_1
 a| 
Puerto a FC-VI
 a| 
1
 a| 
0



 a| 
Puerto FC-VI b
 a| 
2
 a| 
0



 a| 
Puerto FC-VI c
 a| 
1
 a| 
1



 a| 
Puerto d de FC-VI
 a| 
2
 a| 
1



 a| 
Puerto HBA a
 a| 
1
 a| 
2



 a| 
Puerto HBA b
 a| 
2
 a| 
2



 a| 
Puerto HBA c
 a| 
-
 a| 
-



 a| 
Puerto HBA d
 a| 
-
 a| 
-



 a| 
Pila 1
 a| 
bridge_x_1a
 a| 
1
 a| 
8



 a| 
bridge_x_1b
 a| 
2
 a| 
8



 a| 
Apilar y
 a| 
bridge_x_ya
 a| 
1
 a| 
11



 a| 
bridge_x_yb
 a| 
2
 a| 
11

|===