---
permalink: install-fc/concept_fcsw_brocade_reviewing_brocade_license_requirements.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, review, brocade, license, requirements 
summary: Se necesitan ciertas licencias para los switches de una configuración de MetroCluster. Debe instalar estas licencias en los cuatro switches. 
---
= Revisión de los requisitos de licencia de Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necesitan ciertas licencias para los switches de una configuración de MetroCluster. Debe instalar estas licencias en los cuatro switches.

La configuración de MetroCluster tiene los siguientes requisitos de licencia de Brocade:

* Licencia de conexión de enlaces para sistemas que usan más de un ISL, según se recomienda.
* Licencia de Extended Fabric (para distancias de ISL más de 6 km)
* Licencia empresarial para sitios con más de un ISL y una distancia ISL mayor de 6 km
+
La licencia de empresa incluye Brocade Network Advisor y todas las licencias, a excepción de las licencias de puertos adicionales.



Puede verificar que las licencias se instalan mediante el comando 'license'.

[role="tabbed-block"]
====
.Para Fabric OS 8,2.x y versiones anteriores
--
Ejecute el comando `licenseshow`.

--
.Para Fabric OS 9,0 y posterior
--
Ejecute el comando `license --show`.

--
====
Si no tiene estas licencias, debe ponerse en contacto con su representante de ventas antes de continuar.
