---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: Debe verificar que está utilizando las asignaciones de puertos especificadas al conectar los switches FC cuando utiliza ONTAP 9.1 y versiones posteriores. 
---
= Asignación de puertos para switches FC cuando se utilizan sistemas AFF A900 o FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe verificar que está utilizando las asignaciones de puertos especificadas al conectar los switches FC cuando utiliza ONTAP 9.10.1 y versiones posteriores.

Los puertos que no se utilizan para conectar puertos de iniciador, puertos FC-VI o ISL se pueden volver a configurar para que funcionen como puertos de almacenamiento. Sin embargo, si se están utilizando los RCF compatibles, la división en zonas debe cambiarse en consecuencia.

Si se utilizan los RCF admitidos, es posible que los puertos ISL no se conecten a los mismos puertos mostrados y que deban volver a configurarse manualmente.

Si ha configurado los switches utilizando las asignaciones de puertos para ONTAP 9, puede continuar usando las asignaciones anteriores. Sin embargo, las configuraciones que ejecuten versiones ONTAP 9.1 o posteriores deberían usar las asignaciones de puertos que se muestran aquí.



== Directrices generales para el cableado

Debe tener en cuenta las siguientes directrices al utilizar las tablas de cableado:

* Los sistemas de almacenamiento AFF A900 o FAS9500 requieren ocho puertos FC-VI. Si está utilizando un AFF A900 o FAS9500, debe utilizar la configuración de ocho puertos. Si la configuración incluye los otros modelos de sistema de almacenamiento, utilice el cableado que se muestra en las tablas pero ignore el cableado para los puertos FC-VI innecesarios.
* Si tiene dos configuraciones de MetroCluster que comparten ISL, utilice las mismas asignaciones de puertos que para un cableado MetroCluster de ocho nodos.
* El número de ISL que conecte con cables puede variar en función de los requisitos del sitio.
* Consulte la sección sobre consideraciones sobre ISL.
+
link:concept_considerations_isls_mcfc.html["Consideraciones sobre ISL"]


