---
permalink: install-fc/concept_considerations_7mt.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: Al preparar la instalación de MetroCluster, debe comprender la arquitectura de hardware de MetroCluster y los componentes necesarios. 
---
= Consideraciones durante la transición de 7-Mode a ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener la nueva configuración de MetroCluster completamente configurada y en funcionamiento antes de utilizar las herramientas de transición para mover datos de una configuración de MetroCluster 7-Mode a una configuración de ONTAP. Si la configuración 7-Mode utiliza switches Brocade 6510, la nueva configuración puede compartir las estructuras existentes para reducir los requisitos de hardware.

Si tiene switches Brocade 6510 y tiene pensado compartir las estructuras de switches entre la estructura MetroCluster de 7-Mode y la estructura MetroCluster en ONTAP, debe utilizar el procedimiento específico para configurar los componentes de MetroCluster.

link:task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html["Configuración del hardware de MetroCluster para compartir una estructura 7-Mode Brocade 6510 FC durante la transición"]
