---
permalink: install-fc/reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, switch, zoning, array, luns, requirements 
summary: Al utilizar la división en zonas de switches en una configuración de MetroCluster con LUN de cabina, debe asegurarse de que se cumplan ciertos requisitos básicos. 
---
= Requisitos para la división en zonas de switches en una configuración de MetroCluster con LUN de cabina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al utilizar la división en zonas de switches en una configuración de MetroCluster con LUN de cabina, debe asegurarse de que se cumplan ciertos requisitos básicos.

Los requisitos para la división en zonas de switches en una configuración de MetroCluster con LUN de cabina son los siguientes:

* La configuración de MetroCluster debe seguir el esquema de división en zonas de un solo iniciador a un destino.
+
La división en zonas de iniciador único a destino único limita cada zona a un único puerto iniciador de FC y a un único puerto de destino.

* Los puertos FC-VI deben dividirse en zonas en toda la estructura.
* El uso compartido de varios puertos iniciadores con un único puerto de destino puede ocasionar problemas de rendimiento.
+
De igual modo, el uso compartido de varios puertos de destino con un único puerto iniciador puede provocar problemas de rendimiento.

* Debe haber realizado una configuración básica de los switches FC utilizados en la configuración de MetroCluster.
+
** link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Configure los switches Cisco FC manualmente"]
** link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurar los switches FC Brocade manualmente"]






== Compatibilidad con el iniciador compartido y el destino compartido para la configuración de MetroCluster con LUN de cabina

Poder compartir un puerto de iniciador FC o puertos de destino dados es útil para las organizaciones que desean minimizar el número de puertos de iniciador o de destino utilizados. Por ejemplo, una organización que espera un uso de I/o bajo a través de un puerto iniciador FC o de puertos de destino puede preferir compartir el puerto iniciador FC o los puertos de destino en lugar de dedicar cada puerto iniciador FC a un único puerto de destino.

Sin embargo, el uso compartido de puertos de iniciador o de destino puede afectar negativamente al rendimiento.

.Información relacionada
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment["Cómo admitir la configuración de iniciador compartido y destino compartido con LUN de cabina en un entorno de MetroCluster"]

* La división en zonas de switches define las rutas entre los nodos conectados. La configuración de la división en zonas permite definir los LUN de cabina que pueden ver los sistemas ONTAP específicos.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Ejemplo de división en zonas de switches en una configuración MetroCluster de dos nodos con LUN de cabina"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Ejemplo de división en zonas de switches en una configuración de MetroCluster de cuatro nodos con LUN de cabina"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Ejemplo de división en zonas de switches en una configuración MetroCluster de ocho nodos con LUN de cabina"]


