---
permalink: install-fc/task_fmc_mcc_transition_disable_one_of_the_switch_fabrics.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, disable, switch, fabrics 
summary: Debe desactivar una de las estructuras del conmutador para poder modificar su configuración. Una vez finalizada la configuración y vuelva a habilitar la estructura del switch, repita el proceso en la otra estructura. 
---
= Desactivación de una de las estructuras del conmutador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe desactivar una de las estructuras del conmutador para poder modificar su configuración. Una vez finalizada la configuración y vuelva a habilitar la estructura del switch, repita el proceso en la otra estructura.

.Antes de empezar
Debe haber ejecutado la utilidad fmc_dc en la configuración existente de la estructura 7-Mode MetroCluster y haber resuelto cualquier problema antes de iniciar el proceso de configuración.

.Acerca de esta tarea
Para garantizar el funcionamiento continuo de la configuración de MetroCluster, no debe deshabilitar la segunda estructura mientras la primera está deshabilitada.

.Pasos
. Deshabilite cada uno de los switches de la estructura:
+
`switchCfgPersistentDisable`

+
Si este comando no está disponible, utilice `switchDisable` comando.

+
** En el ejemplo siguiente se muestra el comando emitido en FC_switch_A_1:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
** En el ejemplo siguiente se muestra el comando emitido en FC_switch_B_1:
+
[listing]
----
FC_switch_B_1:admin> switchCfgPersistentDisable
----


. Asegúrese de que la configuración de MetroCluster 7-Mode funcione correctamente con la estructura redundante:
+
.. Confirme que el estado de la conmutación por error de la controladora es correcto: +
`cf status`
+
[listing]
----
node_A> cf status
Controller Failover enabled, node_A is up.
VIA Interconnect is up (link 0 down, link 1 up).
----
.. Confirmar que los discos están visibles: +
`storage show disk –p`
+
[listing]
----
node_A> storage show disk –p

PRIMARY                     PORT  SECONDARY          PORT SHELF BAY
--------------------------- ----  ------------------ ---- ---------
Brocade-6510-2K0GG:5.126L27  B                              1    0
Brocade-6510-2K0GG:5.126L28  B                              1    1
Brocade-6510-2K0GG:5.126L29  B                              1    2
Brocade-6510-2K0GG:5.126L30  B                              1    3
Brocade-6510-2K0GG:5.126L31  B                              1    4

.
.
.
----
.. Confirme que los agregados están en buen estado: +
`aggr status`
+
[listing]
----
node_A> aggr status
           Aggr State           Status              Options
          aggr0 online          raid_dp, aggr       root, nosnap=on
                                mirrored
                                64-bit
----



