---
permalink: install-fc/task_reset_the_brocade_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, brocade, fc, switch, factory, defaults 
summary: Antes de instalar una nueva versión de software y archivos RCF, debe borrar la configuración actual del conmutador y realizar la configuración básica. 
---
= Restablecer los valores predeterminados de fábrica del switch FC de Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar una nueva versión de software y archivos RCF, debe borrar la configuración actual del conmutador y realizar la configuración básica.

.Acerca de esta tarea
Debe repetir estos pasos en cada uno de los switches FC de la configuración de la estructura de MetroCluster.

.Pasos
. Inicie sesión en el conmutador como administrador.
. Desactive la función Brocade Virtual Fabrics (VF):
+
`fosconfig options`

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
WARNING:  This is a disruptive operation that requires a reboot to take effect.
Would you like to continue  [Y/N]: y
----
. Desconecte los cables ISL de los puertos del switch.
. Desactivar el interruptor:
+
`switchcfgpersistentdisable`

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentdisable
----
. Desactivar la configuración:
+
`cfgDisable`

+
[listing]
----
FC_switch_A_1:admin> cfgDisable
You are about to disable zoning configuration. This action will disable any previous zoning configuration enabled.
Do you want to disable zoning configuration? (yes, y, no, n): [no] y
Updating flash ...
Effective configuration is empty. "No  Access" default zone mode is ON.
----
. Borrar la configuración:
+
`cfgClear`

+
[listing]
----
FC_switch_A_1:admin> cfgClear
The Clear All action will clear all Aliases, Zones, FA Zones
and configurations in the Defined configuration.
Run cfgSave to commit the transaction or cfgTransAbort to
cancel the transaction.
Do you really want to clear all configurations?  (yes, y, no, n): [no] y
----
. Guarde la configuración:
+
`cfgSave`

+
[listing]
----
FC_switch_A_1:admin> cfgSave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] y
Updating flash ...
----
. Establezca la configuración predeterminada:
+
`configDefault`

+
[listing]
----
FC_switch_A_1:admin> configDefault
WARNING:  This is a disruptive operation that requires a switch reboot.
Would you like to continue [Y/N]: y
Executing configdefault...Please wait
2020/10/05-08:04:08, [FCR-1069], 1016, FID 128, INFO, FC_switch_A_1, The FC Routing service is enabled.
2020/10/05-08:04:08, [FCR-1068], 1017, FID 128, INFO, FC_switch_A_1, The FC Routing service is disabled.
2020/10/05-08:04:08, [FCR-1070], 1018, FID 128, INFO, FC_switch_A_1, The FC Routing configuration is set to default.
Committing configuration ... done.
2020/10/05-08:04:12, [MAPS-1113], 1019, FID 128, INFO, FC_switch_A_1, Policy dflt_conservative_policy activated.
2020/10/05-08:04:12, [MAPS-1145], 1020, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for E-Ports.
2020/10/05-08:04:12, [MAPS-1144], 1021, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for F-Ports.
The switch has to be rebooted to allow the changes to take effect.
2020/10/05-08:04:12, [CONF-1031], 1022, FID 128, INFO, FC_switch_A_1, configDefault completed successfully for switch.
----
. Establezca la configuración predeterminada de todos los puertos:
+
`portcfgdefault _port-number_`

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault <port number>
----
+
Debe completar este paso para cada puerto.

. Compruebe que el switch utiliza el método de puerto dinámico bajo demanda (POD).
+

NOTE: En las versiones de SO Brocade Fabric anteriores a la 8.0, se ejecutan los siguientes comandos como administrador, y para las versiones 8.0 y posteriores, se ejecutan como raíz.

+
.. Ejecute el comando license:
+
`licenseport --show`

+
[listing]
----
FC_switch_A_1:admin> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Active el usuario raíz si está deshabilitado por Brocade.
+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. Ejecute el comando license:
+
`licenseport --show`

+
[listing]
----
FC_switch_A_1:root> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Cambie el método de licencia a dinámico:
+
`licenseport --method dynamic`

+

NOTE: Si el método Dynamic POD no está en uso (si el método POD está estático), debe cambiar el método de asignación de licencia a dinámico. Omita este paso si el método Dynamic POD está en uso.

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. Reinicie el switch:
+
`fastBoot`

+
[listing]
----
FC_switch_A_1:admin> fastboot
Warning: This command would cause the switch to reboot
and result in traffic disruption.
Are you sure you want to reboot the switch [y/n]?y
----
. Confirme que se ha implementado la configuración predeterminada:
+
`switchShow`

. Compruebe que la dirección IP esté configurada correctamente:
+
`ipAddrShow`

+
Puede establecer la dirección IP con el siguiente comando, si es necesario:

+
`ipAddrSet`


