---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file 
summary: 'Debe descargar el archivo de configuración de referencia \(RCF\) en cada switch de la configuración de la estructura de MetroCluster.' 
---
= Descarga del archivo RCF del switch FC de Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar el archivo de configuración de referencia (RCF) en cada switch de la configuración de la estructura de MetroCluster.

.Acerca de esta tarea
Para utilizar estos archivos RCF, el sistema debe ejecutar ONTAP 9.1 o posterior y debe utilizar el diseño de puerto para ONTAP 9.1 o posterior.

Si tiene pensado utilizar sólo uno de los puertos FC de los puentes FibreBridge, configure los switches de canal de fibra back-end manualmente siguiendo las instrucciones de la sección, link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Asignaciones de puertos para los switches FC cuando se utiliza ONTAP 9.1 y versiones posteriores"].

.Pasos
. Consulte la tabla de archivos RCF de la página de descarga de Brocade RCF e identifique el archivo RCF correcto para cada switch de la configuración.
+
Los archivos RCF deben aplicarse a los interruptores correctos.

. Descargue los archivos RCF de los conmutadores desde https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["Descarga de RCF de MetroCluster"] página.
+
Los archivos se deben colocar en una ubicación en la que puedan transferirse al conmutador. Hay un archivo separado para cada uno de los cuatro switches que conforman la estructura de dos switches.

. Repita estos pasos en cada switch de la configuración.

