---
permalink: install-fc/task_prepare_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, prepare, storage, array, systems 
summary: Antes de empezar a configurar sistemas ONTAP en una configuración MetroCluster con LUN de cabina, el administrador de la cabina de almacenamiento debe preparar el almacenamiento para su uso con ONTAP. 
---
= Preparar una cabina de almacenamiento para usar con sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de empezar a configurar sistemas ONTAP en una configuración MetroCluster con LUN de cabina, el administrador de la cabina de almacenamiento debe preparar el almacenamiento para su uso con ONTAP.

.Antes de empezar
Las cabinas de almacenamiento, el firmware y los switches que planea utilizar en la configuración deben ser compatibles con la versión de ONTAP específica.

* https://["Interoperabilidad de NetApp (IMT)"]
+
En IMT, puede utilizar el campo solución de almacenamiento para seleccionar su solución de MetroCluster. Utilice el *Explorador de componentes* para seleccionar los componentes y la versión ONTAP para refinar la búsqueda. Puede hacer clic en *Mostrar resultados* para mostrar la lista de configuraciones compatibles que coinciden con los criterios.

* https://["Hardware Universe de NetApp"]


.Acerca de esta tarea
Debe coordinarse con el administrador de la cabina de almacenamiento para realizar esta tarea en la cabina de almacenamiento.

.Pasos
. Cree LUN en la cabina de almacenamiento según el número de nodos en la configuración de MetroCluster.
+
Cada nodo de la configuración MetroCluster requiere LUN de cabina para el agregado raíz, el agregado de datos y los repuestos.

. Configure los parámetros en la cabina de almacenamiento que se necesitan para trabajar con ONTAP.
+
** https://["Implementación de virtualización FlexArray para almacenamiento de terceros"]
** https://["Implementación de virtualización FlexArray para almacenamiento E-Series de NetApp"]



