---
permalink: install-fc/task_assign_ownership_of_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, assigning, ownership, array, luns 
summary: Los LUN de cabina deben ser propiedad de un nodo para que se puedan añadir a un agregado que se usará como almacenamiento. 
---
= Asignación de propiedad de LUN de cabina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los LUN de cabina deben ser propiedad de un nodo para que se puedan añadir a un agregado que se usará como almacenamiento.

.Antes de empezar
* Deben realizarse pruebas de configuración back-end (prueba de la conectividad y configuración de los dispositivos tras los sistemas ONTAP).
* Las LUN de cabina que desea asignar deben presentarse a los sistemas de ONTAP.


.Acerca de esta tarea
Es posible asignar propiedad de LUN de cabina que tienen las siguientes características:

* No son de propiedad.
* No tienen errores de configuración de la cabina de almacenamiento, como los siguientes:
+
** El LUN de la cabina es menor o mayor que el tamaño compatible con ONTAP.
** El LDEV está asignado en un solo puerto.
** El LDEV tiene asignados ID de LUN incoherentes.
** El LUN solo está disponible en una ruta.




ONTAP emite un mensaje de error si se intenta asignar la propiedad de un LUN de cabina con errores de configuración back-end que pudieran interferir en el funcionamiento del sistema ONTAP y de la cabina de almacenamiento. Debe corregir estos errores para poder continuar con la asignación de LUN de cabina.

ONTAP alerta si se intenta asignar un LUN de cabina con un error de redundancia: Por ejemplo, todas las rutas a este LUN de cabina están conectadas a la misma controladora o solo una ruta al LUN de cabina. Es posible corregir un error de redundancia antes o después de asignar la propiedad de la LUN.

.Pasos
. Vea los LUN de cabina que aún no se han asignado a un nodo:
+
`storage disk show -container-type unassigned`

. Asigne un LUN de cabina a este nodo:
+
`storage disk assign -disk _array_LUN_name_ -owner _nodename_`

+
Si desea corregir un error de redundancia después de la asignación de disco en lugar de antes, debe utilizar el `-force` parámetro con el comando storage disk assign.



.Información relacionada
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["Referencias y requisitos de instalación de la virtualización FlexArray"]
