---
permalink: install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html 
sidebar: sidebar 
keywords: MetroCluster configurations 
summary: Debe configurar cada una de las estructuras de switches de Brocade en la configuración de MetroCluster. 
---
= Configuración manual de los switches Brocade FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar cada una de las estructuras de switches de Brocade en la configuración de MetroCluster.

.Antes de empezar
* Debe tener un PC o estación de trabajo UNIX con acceso Telnet o Secure Shell (SSH) a los switches FC.
* Debe usar cuatro switches Brocade compatibles del mismo modelo con la misma versión y licencia del sistema operativo Brocade Fabric (FOS).
+
https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"]

+
En IMT, puede utilizar el campo solución de almacenamiento para seleccionar su solución de MetroCluster. Utilice el *Explorador de componentes* para seleccionar los componentes y la versión ONTAP para refinar la búsqueda. Puede hacer clic en *Mostrar resultados* para mostrar la lista de configuraciones compatibles que coinciden con los criterios.

* Los cuatro switches Brocade admitidos deben estar conectados a dos estructuras de dos switches cada uno, con cada estructura que abarque ambos sitios.
* Cada controladora de almacenamiento debe tener cuatro puertos de iniciador disponibles para conectarse a las estructuras de switches. Deben conectarse dos puertos de iniciador desde cada controladora de almacenamiento a cada estructura.
+

NOTE: Puede configurar sistemas FAS8020, AFF8020, FAS8200 y AFF A300 con dos puertos iniciadores por controladora (un solo puerto de iniciador para cada estructura) si se cumplen todos los criterios siguientes:

+
** Hay menos de cuatro puertos iniciadores FC disponibles para conectar el almacenamiento en disco y no se pueden configurar puertos adicionales como iniciadores de FC.
** Todas las ranuras están en uso y no se puede añadir ninguna tarjeta iniciador FC.




.Acerca de esta tarea
* Debe habilitar la conexión troncal de enlace entre switches (ISL) cuando sea compatible con los enlaces.
+
link:concept_tdm_wdm.html["Consideraciones sobre el uso de equipos TDM/WDM con configuraciones MetroCluster conectadas a la estructura"]

* Si utiliza una configuración xWDM, puede que necesite ajustes adicionales en las ISLs. Consulte la documentación del proveedor de xWDM para obtener más información.
* Todos los ISL deben tener la misma longitud y la misma velocidad en una misma estructura.
+
Se pueden utilizar diferentes longitudes en los diferentes tejidos. Se debe utilizar la misma velocidad en todas las telas.

* Metro-E y TDM (SONET/SDH) no son compatibles, y no se admite ningún encuadre o señalización nativo no FC.
+
Metro-E significa que la trama o la señalización Ethernet se produce de forma nativa en una distancia de metro o a través de algún multiplexado de división de tiempo (TDM), conmutación de etiquetas multiprotocolo (MPLS) o multiplexación de división de longitud de onda (WDM).

* Las extensiones TDMS, FCR (enrutamiento FC nativo) o FCIP no son compatibles con la estructura de switches FC MetroCluster.
* Algunos switches de la estructura del switch FC de MetroCluster admiten cifrado o compresión, y en ocasiones admiten ambos.
+
https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp (IMT)"]

+
En IMT, puede utilizar el campo solución de almacenamiento para seleccionar su solución de MetroCluster. Utilice el *Explorador de componentes* para seleccionar los componentes y la versión ONTAP para refinar la búsqueda. Puede hacer clic en *Mostrar resultados* para mostrar la lista de configuraciones compatibles que coinciden con los criterios.

* No se admite la función Brocade Virtual Fabric (VF).
* Se admite la división en zonas de FC basada en el puerto de dominio, pero no se admite la división en zonas basada en el nombre a nivel mundial (WWN).




== Revisión de los requisitos de licencia de Brocade

Se necesitan ciertas licencias para los switches de una configuración de MetroCluster. Debe instalar estas licencias en los cuatro switches.

.Acerca de esta tarea
La configuración de MetroCluster tiene los siguientes requisitos de licencia de Brocade:

* Licencia de conexión de enlaces para sistemas que usan más de un ISL, según se recomienda.
* Licencia de Extended Fabric (para distancias de ISL más de 6 km)
* Licencia empresarial para sitios con más de un ISL y una distancia ISL mayor de 6 km
+
La licencia de empresa incluye Brocade Network Advisor y todas las licencias, a excepción de las licencias de puertos adicionales.



.Paso
. Compruebe que las licencias estén instaladas:
+
[role="tabbed-block"]
====
.Para Fabric OS 8,2.x y versiones anteriores
--
Ejecute el comando `licenseshow`.

--
.Para Fabric OS 9,0 y posterior
--
Ejecute el comando `license --show`.

--
====
+
Si no tiene estas licencias, debe ponerse en contacto con su representante de ventas antes de continuar.





== Configurar los valores del switch Brocade FC a los valores predeterminados de fábrica

Debe ajustar el conmutador a sus valores predeterminados de fábrica para garantizar una configuración correcta. Además, debe asignar un nombre exclusivo a cada switch.

.Acerca de esta tarea
En los ejemplos de este procedimiento, el tejido consta de BrocadeSwitchA y BrocadeSwitchB.

.Pasos
. Establezca una conexión de consola e inicie sesión en ambos switches en una estructura.
. Desactive el interruptor de forma persistente:
+
`switchcfgpersistentdisable`

+
Esto garantiza que el conmutador permanecerá desactivado después de un reinicio o fastboot. Si este comando no está disponible, utilice `switchdisable` comando.

+
El ejemplo siguiente muestra el comando en BrocadeSwitchA:

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
En el siguiente ejemplo se muestra el comando en BrocadeSwitchB:

+
[listing]
----
BrocadeSwitchB:admin> switchcfgpersistentdisable
----
. Establezca el nombre del switch:
+
`switchname switch_name`

+
Cada uno de los switches debe tener un nombre único. Después de establecer el nombre, el mensaje cambia en consecuencia.

+
El ejemplo siguiente muestra el comando en BrocadeSwitchA:

+
[listing]
----
BrocadeSwitchA:admin> switchname "FC_switch_A_1"
FC_switch_A_1:admin>
----
+
En el siguiente ejemplo se muestra el comando en BrocadeSwitchB:

+
[listing]
----
BrocadeSwitchB:admin> switchname "FC_Switch_B_1"
FC_switch_B_1:admin>
----
. Establezca todos los puertos en sus valores predeterminados:
+
`portcfgdefault`

+
Esto se debe hacer para todos los puertos del conmutador.

+
En el ejemplo siguiente se muestran los comandos en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault 0
FC_switch_A_1:admin> portcfgdefault 1
...
FC_switch_A_1:admin> portcfgdefault 39
----
+
En el ejemplo siguiente se muestran los comandos en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> portcfgdefault 0
FC_switch_B_1:admin> portcfgdefault 1
...
FC_switch_B_1:admin> portcfgdefault 39
----
. Borre la información de la división en zonas:
+
`cfgdisable`

+
`cfgclear`

+
`cfgsave`

+
En el ejemplo siguiente se muestran los comandos en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> cfgdisable
FC_switch_A_1:admin> cfgclear
FC_switch_A_1:admin> cfgsave
----
+
En el ejemplo siguiente se muestran los comandos en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> cfgdisable
FC_switch_B_1:admin> cfgclear
FC_switch_B_1:admin> cfgsave
----
. Ajuste los ajustes generales del interruptor a los valores predeterminados:
+
`configdefault`

+
En el ejemplo siguiente se muestra el comando en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> configdefault
----
+
En el ejemplo siguiente se muestra el comando en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> configdefault
----
. Establezca todos los puertos en el modo sin conexión de enlaces:
+
`switchcfgtrunk 0`

+
En el ejemplo siguiente se muestra el comando en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchcfgtrunk 0
----
+
En el ejemplo siguiente se muestra el comando en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchcfgtrunk 0
----
. En los switches Brocade 6510, desactive la función Brocade Virtual Fabrics (VF):
+
`fosconfig options`

+
En el ejemplo siguiente se muestra el comando en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
----
+
En el ejemplo siguiente se muestra el comando en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> fosconfig --disable vf
----
. Borrar la configuración de dominio de administración (AD):
+
En el ejemplo siguiente se muestran los comandos en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
----
+
En el ejemplo siguiente se muestran los comandos en FC_switch_B_1:

+
[listing]
----
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
----
. Reinicie el switch:
+
`reboot`

+
En el ejemplo siguiente se muestra el comando en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
En el ejemplo siguiente se muestra el comando en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> reboot
----




== Configuración de los ajustes básicos del switch

Debe configurar la configuración global básica, incluido el ID de dominio, para los switches Brocade.

.Acerca de esta tarea
Esta tarea contiene los pasos que deben realizarse en cada switch de ambos sitios MetroCluster.

En este procedimiento, se establece el identificador de dominio único para cada switch como se muestra en el ejemplo siguiente. En el ejemplo, los ID de dominio 5 y 7 Form Fabric_1, y los ID de dominio 6 y 8 Form Fabric_2.

* FC_switch_A_1 está asignado al ID de dominio 5
* FC_switch_A_2 está asignado al ID de dominio 6
* FC_switch_B_1 está asignado al ID de dominio 7
* FC_switch_B_2 se asigna al ID de dominio 8


.Pasos
. Entrar al modo de configuración:
+
`configure`

. Siga las indicaciones:
+
.. Configure el ID de dominio del switch.
.. Pulse *Intro* en respuesta a las indicaciones hasta que llegue a "ciclo de sondeo RDP" y, a continuación, establezca ese valor en `0` para desactivar el sondeo.
.. Pulse *Intro* hasta que vuelva al indicador del interruptor.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = 5
.
.

RSCN Transmission Mode [yes, y, no, no: [no] y

End-device RSCN Transmission Mode
 (0 = RSCN with single PID, 1 = RSCN with multiple PIDs, 2 = Fabric RSCN): (0..2) [1]
Domain RSCN To End-device for switch IP address or name change
 (0 = disabled, 1 = enabled): (0..1) [0] 1

.
.
RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
----


. Si utiliza dos o más ISL por estructura, puede configurar la entrega bajo pedido (IOD) de tramas o la entrega fuera de servicio (OOD) de tramas.
+

NOTE: Se recomienda la configuración de IOD estándar. Sólo debe configurar OOD si es necesario.

+
link:concept_prepare_for_the_mcc_installation.html["Consideraciones sobre el uso de equipos TDM/WDM con configuraciones MetroCluster conectadas a la estructura"]

+
.. Se deben realizar los siguientes pasos en cada estructura de switch para configurar la IOD de las tramas:
+
... Habilitar IOD:
+
`iodset`

... Establezca la directiva de ajuste avanzado del rendimiento (APT) en 1:
+
`aptpolicy 1`

... Desactivar el uso compartido dinámico de la carga (DLS):
+
`dlsreset`

... Compruebe la configuración de IOD mediante la `iodshow`, `aptpolicy`, y. `dlsshow` comandos.
+
Por ejemplo, emita los siguientes comandos en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 1 0(ap)

    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
         0: AP Shared Link Policy
         1: AP Dedicated Link Policy
    command aptpolicy completed

    FC_switch_A_1:admin> dlsshow
    DLS is not set
----
... Repita estos pasos en la segunda estructura del switch.


.. Se deben realizar los siguientes pasos en cada estructura de switch para configurar OOD de tramas:
+
... Habilitar OOD:
+
`iodreset`

... Establezca la directiva de ajuste avanzado del rendimiento (APT) en 3:
+
`aptpolicy 3`

... Desactivar el uso compartido dinámico de la carga (DLS):
+
`dlsreset`

... Verifique los ajustes de OOD:
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
Por ejemplo, emita los siguientes comandos en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is not set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 3 0(ap)
    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
    0: AP Shared Link Policy
    1: AP Dedicated Link Policy
    command aptpolicy completed


    FC_switch_A_1:admin> dlsshow
    DLS is set by default with current routing policy
----
... Repita estos pasos en la segunda estructura del switch.
+

NOTE: Al configurar ONTAP en los módulos de controlador, OOD debe configurarse explícitamente en cada módulo de controlador de la configuración de MetroCluster.

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["Configurar la entrega bajo pedido o la entrega fuera de servicio de tramas en el software ONTAP"]





. Compruebe que el switch utiliza el método de licencia de puerto dinámico.
+
.. Ejecute el comando license:
+
[role="tabbed-block"]
====
.Para Fabric OS 8,2.x y versiones anteriores
--
Ejecute el comando `licenseport --show`.

--
.Para Fabric OS 9,0 y posterior
--
Ejecute el comando `license --show -port`.

--
====
+
[listing]
----
FC_switch_A_1:admin> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
+

NOTE: Las versiones de Brocade FabricOS anteriores a la versión 8.0 ejecutan los siguientes comandos como admin y las versiones 8.0 y posteriores como root.

.. Habilite el usuario raíz.
+
Si el usuario raíz ya está desactivado por Brocade, habilite el usuario raíz como se muestra en el siguiente ejemplo:

+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. Ejecute el comando license:
+
`license --show -port`

+
[listing]
----
FC_switch_A_1:root> license --show -port
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Si ejecuta Fabric OS 8,2.x y versiones anteriores, debe cambiar el método de licencia a dinámico:
+
`licenseport --method dynamic`

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----
+

NOTE: En Fabric OS 9,0 y posterior, el método de licencia es dinámico de forma predeterminada. El método de licencia estática no es compatible.



. Habilite el reto de T11-FC-ZONE-SERVER-MIB para que pueda ofrecer una supervisión de estado correcta de los switches de ONTAP:
+
.. Habilite T11-FC-ZONE-SERVER-MIB:
+
`snmpconfig --set mibCapability -mib_name T11-FC-ZONE-SERVER-MIB -bitmask 0x3f`

.. Habilite la captura T11-FC-ZONE-SERVER-MIB:
+
`snmpconfig --enable mibcapability -mib_name SW-MIB -trap_name swZoneConfigChangeTrap`

.. Repita los pasos anteriores en la segunda estructura del switch.


. *Opcional*: Si establece la cadena de comunidad en un valor distinto de "public", debe configurar los monitores de estado de ONTAP mediante la cadena de comunidad que especifique:
+
.. Cambie la cadena de comunidad existente:
+
`snmpconfig --set snmpv1`

.. Pulse *Intro* hasta que aparezca el texto "Comunidad (ro): [Public]".
.. Introduzca la cadena de comunidad que desee.
+
En FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm     <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]    in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_A_1:admin>
----
+
En FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm      <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]     in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_B_1:admin>
----


. Reinicie el switch:
+
`reboot`

+
En FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
En FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> reboot
----
. Active el interruptor de forma persistente:
+
`switchcfgpersistentenable`

+
En FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentenable
----
+
En FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchcfgpersistentenable
----




== Configuración de los ajustes básicos del switch en un switch Brocade DCX 8510-8

Debe configurar la configuración global básica, incluido el ID de dominio, para los switches Brocade.

.Acerca de esta tarea
Debe realizar los pasos de cada switch en ambos sitios de MetroCluster. En este procedimiento, se establece el ID de dominio para cada switch como se muestra en los ejemplos siguientes:

* FC_switch_A_1 está asignado al ID de dominio 5
* FC_switch_A_2 está asignado al ID de dominio 6
* FC_switch_B_1 está asignado al ID de dominio 7
* FC_switch_B_2 se asigna al ID de dominio 8


En el ejemplo anterior, los ID de dominio 5 y 7 Form Fabric_1, y los ID de dominio 6 y 8 Form Fabric_2.


NOTE: También puede utilizar este procedimiento para configurar los conmutadores cuando sólo utiliza un conmutador DCX 8510-8 por centro.

Mediante este procedimiento, deberá crear dos switches lógicos en cada switch Brocade DCX 8510-8. Los dos conmutadores lógicos creados en ambos conmutadores Brocade DCX8510-8 formarán dos estructuras lógicas, como se muestra en los siguientes ejemplos:

* ESTRUCTURA LÓGICA 1: Switch1/Blade1 y Switch 2 Blade 1
* ESTRUCTURA LÓGICA 2: Switch 1/Blade2 y Switch 2 Blade


.Pasos
. Introduzca el modo de comando:
+
`configure`

. Siga las indicaciones:
+
.. Configure el ID de dominio del switch.
.. Siga seleccionando *Intro* hasta que llegue a "ciclo de sondeo RDP" y, a continuación, establezca el valor en `0` para desactivar el sondeo.
.. Seleccione *Intro* hasta que vuelva al indicador del interruptor.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = `5


RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
`
----


. Repita estos pasos en todos los switches de Fabric_1 y Fabric_2.
. Configurar las estructuras virtuales.
+
.. Habilite las estructuras virtuales del switch:
+
`fosconfig --enablevf`

.. Configure el sistema para que utilice la misma configuración base en todos los switches lógicos:
+
`configurechassis`

+
En el siguiente ejemplo, se muestra el resultado del `configurechassis` comando:

+
[listing]
----
System (yes, y, no, n): [no] n
cfgload attributes (yes, y, no, n): [no] n
Custom attributes (yes, y, no, n): [no] y
Config Index (0 to ignore): (0..1000) [3]:
----


. Crear y configurar el conmutador lógico:
+
`scfg --create fabricID`

. Añada todos los puertos de un blade a la estructura virtual:
+
`lscfg --config fabricID -slot slot -port lowest-port - highest-port`

+

NOTE: Las palas que forman una estructura lógica (p. ej., Switch 1 Blade 1 y Switch 3 Blade 1) deben tener el mismo ID de estructura.

+
[listing]
----
setcontext fabricid
switchdisable
configure
<configure the switch per the above settings>
switchname unique switch name
switchenable
----


.Información relacionada
link:concept_prepare_for_the_mcc_installation.html["Requisitos para usar un switch Brocade DCX 8510-8"]



== Configuración de los puertos E en los switches FC de Brocade mediante puertos FC

En el caso de los switches Brocade en los que se configuran los enlaces Inter-Switch (ISL) mediante puertos FC, debe configurar los puertos del switch en cada estructura del switch que conecte el ISL. Estos puertos ISL también se conocen como puertos E-ports.

.Antes de empezar
* Todos los ISL de una estructura de switch FC deben configurarse con la misma velocidad y distancia.
* La combinación del puerto del switch y el factor de forma pequeño conectable (SFP) debe admitir la velocidad.
* La distancia ISL admitida depende del modelo de switch de FC.
+
https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"]

+
En IMT, puede utilizar el campo solución de almacenamiento para seleccionar su solución de MetroCluster. Utilice el *Explorador de componentes* para seleccionar los componentes y la versión ONTAP para refinar la búsqueda. Puede hacer clic en *Mostrar resultados* para mostrar la lista de configuraciones compatibles que coinciden con los criterios.

* El enlace ISL debe tener una lambda dedicada y el enlace debe ser compatible con Brocade para la distancia, el tipo de switch y el sistema operativo Fabric (FOS).


.Acerca de esta tarea
No debe utilizar el ajuste L0 al emitir el `portCfgLongDistance` comando. En su lugar, debe utilizar EL ajuste LE o LS para configurar la distancia en los conmutadores Brocade con un nivel DE distancia MÍNIMO LE.

No debe utilizar el valor LD al emitir el `portCfgLongDistance` Comando al trabajar con equipos xWDM/TDM. En su lugar, debe utilizar EL ajuste LE o LS para configurar la distancia en los conmutadores Brocade.

Debe realizar esta tarea para cada estructura de switch de FC.

En las siguientes tablas, se muestran los puertos ISL para los diferentes switches y un número diferente de ISL en una configuración que ejecute ONTAP 9.1 o 9.2. Los ejemplos que se muestran en esta sección son para un switch Brocade 6505. Debe modificar los ejemplos para utilizar los puertos que se aplican al tipo de switch.

Debe usar el número necesario de ISL para la configuración.

|===


| Modelo de switch | Puerto ISL | Puerto del switch 


.4+| Brocade 6520 | Puerto ISL 1 | 23 


| Puerto ISL 2 | 47 


| Puerto ISL 3 | 71 


| Puerto ISL 4 | 95 


.4+| Brocade 6505 | Puerto ISL 1 | 20 


| Puerto ISL 2 | 21 


| Puerto ISL 3 | 22 


| Puerto ISL 4 | 23 


.8+| Brocade 6510 y Brocade DCX 8510-8 | Puerto ISL 1 | 40 


| Puerto ISL 2 | 41 


| Puerto ISL 3 | 42 


| Puerto ISL 4 | 43 


| Puerto ISL 5 | 44 


| Puerto ISL 6 | 45 


| Puerto ISL 7 | 46 


| Puerto ISL 8 | 47 


.6+| Brocade 7810  a| 
Puerto ISL 1
 a| 
ge2 (10 Gbps)



 a| 
Puerto ISL 2
 a| 
Ge3 (10 Gbps)



 a| 
Puerto ISL 3
 a| 
ge4 (10 Gbps)



 a| 
Puerto ISL 4
 a| 
Ge5 (10 Gbps)



 a| 
Puerto ISL 5
 a| 
Ge6 (10 Gbps)



 a| 
Puerto ISL 6
 a| 
G7 (10 Gbps)



.4+| Brocade 7840 *Nota:* el conmutador Brocade 7840 admite dos puertos ve de 40 Gbps o hasta cuatro puertos ve de 10 Gbps por switch para la creación de FCIP ISL.  a| 
Puerto ISL 1
 a| 
Ge0 (40 Gbps) o ge2 (10 Gbps)



 a| 
Puerto ISL 2
 a| 
ge1 (40 Gbps) o ge3 (10 Gbps)



 a| 
Puerto ISL 3
 a| 
G10 (10 Gbps)



 a| 
Puerto ISL 4
 a| 
Ge11 (10 Gbps)



.4+| Brocade G610  a| 
Puerto ISL 1
 a| 
20



 a| 
Puerto ISL 2
 a| 
21



 a| 
Puerto ISL 3
 a| 
22



 a| 
Puerto ISL 4
 a| 
23



.7+| BROCADE G620, G620-1, G630, G630-1, G720  a| 
Puerto ISL 1
 a| 
40



 a| 
Puerto ISL 2
 a| 
41



 a| 
Puerto ISL 3
 a| 
42



 a| 
Puerto ISL 4
 a| 
43



 a| 
Puerto ISL 5
 a| 
44



 a| 
Puerto ISL 6
 a| 
45



 a| 
Puerto ISL 7
 a| 
46

|===
.Pasos
. [[step1_brocado_config]] Configurar la velocidad del puerto:
+
`portcfgspeed port-numberspeed`

+
Debe utilizar la velocidad común más alta que admiten los componentes de la ruta.

+
En el ejemplo siguiente, hay dos ISL para cada estructura:

+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 20 16
FC_switch_A_1:admin> portcfgspeed 21 16

FC_switch_B_1:admin> portcfgspeed 20 16
FC_switch_B_1:admin> portcfgspeed 21 16
----
. Configure el modo de conexión de enlaces para cada ISL:
+
`portcfgtrunkport port-number`

+
** Si está configurando los ISL para la conexión troncal (IOD), establezca el puerto portcfgtrunk-numberPort-number en 1 como se muestra en el ejemplo siguiente:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
----
** Si no desea configurar el ISL para canaleta (OOD), establezca portcfgtrunkport-number en 0 como se muestra en el siguiente ejemplo:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
----


. Habilite el tráfico de calidad de servicio para cada uno de los puertos ISL:
+
`portcfgqos --enable port-number`

+
En el ejemplo siguiente, hay dos ISL por estructura de switch:

+
[listing]
----
FC_switch_A_1:admin> portcfgqos --enable 20
FC_switch_A_1:admin> portcfgqos --enable 21

FC_switch_B_1:admin> portcfgqos --enable 20
FC_switch_B_1:admin> portcfgqos --enable 21
----
. Compruebe la configuración:
+
`portCfgShow command`

+
En el ejemplo siguiente se muestra el resultado de una configuración que utiliza dos ISL cableadas al puerto 20 y al puerto 21. El valor del puerto de enlace debe ESTAR ACTIVADO para IOD y DESACTIVADO para OOD:

+
[listing]
----

Ports of Slot 0   12  13   14 15    16  17  18  19   20  21 22  23    24  25  26  27
----------------+---+---+---+---+-----+---+---+---+----+---+---+---+-----+---+---+---
Speed             AN  AN  AN  AN    AN  AN  8G  AN   AN  AN  16G  16G    AN  AN  AN  AN
Fill Word         0   0   0   0     0   0   3   0    0   0   3   3     3   0   0   0
AL_PA Offset 13   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Trunk Port        ..  ..  ..  ..    ..  ..  ..  ..   ON  ON  ..  ..    ..  ..  ..  ..
Long Distance     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
VC Link Init      ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked L_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked G_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Disabled E_Port   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked E_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
ISL R_RDY Mode    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
RSCN Suppressed   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Persistent Disable..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
LOS TOV enable    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
NPIV capability   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
NPIV PP Limit    126 126 126 126   126 126 126 126  126 126 126 126   126 126 126 126
QOS E_Port        AE  AE  AE  AE    AE  AE  AE  AE   AE  AE  AE  AE    AE  AE  AE  AE
Mirror Port       ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Rate Limit        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Credit Recovery   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
Fport Buffers     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Port Auto Disable ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
CSCTL mode        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..

Fault Delay       0  0  0  0    0  0  0  0   0  0  0  0    0  0  0  0
----
. Calcule la distancia ISL.
+
Debido al comportamiento de FC-VI, la distancia debe ser 1.5 veces la distancia real con una distancia mínima de 10 km (utilizando el nivel DE distancia LE).

+
La distancia para el ISL se calcula de la siguiente manera, redondeada hasta el siguiente kilómetro completo:

+
1.5 × distancia_real = distancia

+
Si la distancia es de 3 km, entonces 1.5 × 3 km = 4.5 km Esto es inferior a 10 km, por lo que el ISL debe ajustarse al nivel DE distancia LE.

+
Si la distancia es de 20 km, entonces 1.5 × 20 km = 30 km El ISL debe establecerse en 30 km y debe utilizar el nivel de distancia LS.

. Establezca la distancia en cada puerto ISL:
+
`portcfglongdistance _portdistance-level_ vc_link_init _distance_`

+
A. `vc_link_init` valor de `1` Utiliza la palabra de relleno ARB (valor predeterminado). Valor de `0` Utiliza INACTIVO. El valor requerido puede depender del enlace que se esté utilizando. Los comandos deben repetirse para cada puerto ISL.

+
Para una distancia ISL de 3 km, como se indica en el ejemplo del paso anterior, el valor es de 4.5 km con el valor predeterminado `vc_link_init` valor de `1`. Debido a que un valor de 4.5 km es inferior a 10 km, el puerto debe ajustarse al nivel DE distancia LE:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LE 1

FC_switch_B_1:admin> portcfglongdistance 20 LE 1
----
+
Para una distancia ISL de 20 km, como se indica en el ejemplo del paso anterior, el valor es 30 km con el valor vc_link_init predeterminado de `1`:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LS 1 -distance 30

FC_switch_B_1:admin> portcfglongdistance 20 LS 1 -distance 30
----
. Verifique el ajuste de distancia:
+
`portbuffershow`

+
EL nivel DE distancia DE LE está a 10 km

+
En el ejemplo siguiente se muestra el resultado de una configuración que utiliza ISL en el puerto 20 y el puerto 21:

+
[listing]
----
FC_switch_A_1:admin> portbuffershow

User  Port     Lx      Max/Resv    Buffer Needed    Link      Remaining
Port  Type    Mode     Buffers     Usage  Buffers   Distance  Buffers
----  ----    ----     -------     ------ -------   --------- ---------
...
 20     E      -          8         67      67       30km
 21     E      -          8         67      67       30km
...
 23            -          8          0      -        -        466
----
. Compruebe que ambos switches forman una estructura:
+
`switchshow`

+
En el ejemplo siguiente se muestra el resultado de una configuración que utiliza ISL en el puerto 20 y el puerto 21:

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...

FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       7
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State Proto
==============================================
...
20   20  030C00   id    16G  Online  FC  LE E-Port  10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)(Trunk master)
21   21  030D00   id    16G  Online  FC  LE E-Port  (Trunk port, master is Port 20)
...
----
. Confirmar la configuración de los fabrics:
+
`fabricshow`

+
[listing]
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----
+
[listing]
----
FC_switch_B_1:admin> fabricshow
   Switch ID   Worldwide Name     Enet IP Addr FC IP Addr   Name
----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0     "FC_switch_A_1"

3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0    >"FC_switch_B_1
----
. [[step10_brocado_config]]confirme la conexión de enlaces de los ISL:
+
`trunkshow`

+
** Si está configurando los ISL para la conexión troncal (IOD), debería ver una salida similar a la siguiente:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16
 FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16
----
** Si no está configurando los ISL para canaleta (OOD), debería ver una salida similar a la siguiente:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16 MASTER
FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16 MASTER
----


. Repetición <<step1_brocade_config,Paso 1>> por <<step10_brocade_config,Paso 10>> Para la segunda estructura de switch de FC.


.Información relacionada
link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Asignaciones de puertos para los switches FC cuando se utiliza ONTAP 9.1 y versiones posteriores"]



== Configuración de puertos ve de 10 Gbps en conmutadores Brocade FC 7840

Al utilizar los puertos ve de 10 Gbps (que utilizan FCIP) para ISL, debe crear interfaces IP en cada puerto y configurar túneles y circuitos FCIP en cada túnel.

.Acerca de esta tarea
Este procedimiento debe realizarse en cada estructura de switch de la configuración de MetroCluster.

En los ejemplos de este procedimiento se asume que los dos switches Brocade 7840 tienen las siguientes direcciones IP:

* FC_switch_A_1 es local.
* FC_switch_B_1 es remoto.


.Pasos
. Cree direcciones IP de interfaz (ipf) para los puertos de 10 Gbps en ambos switches de la estructura:
+
`portcfg ipif FC_switch1_namefirst_port_name create FC_switch1_IP_address netmask netmask_number vlan 2 mtu auto`

+
El siguiente comando crea direcciones ipf en los puertos ge2.dp0 y ge3.dp0 de FC_switch_A_1:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.71 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.71 netmask 255.255.0.0 vlan 2 mtu auto
----
+
El siguiente comando crea direcciones ipf en los puertos ge2.dp0 y ge3.dp0 de FC_switch_B_1:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.72 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.72 netmask 255.255.0.0 vlan 2 mtu auto
----
. Compruebe que las direcciones ipf se han creado correctamente en ambos switches:
+
`portshow ipif all`

+
El siguiente comando muestra las direcciones ipf en el switch FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.71                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.71                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
El siguiente comando muestra las direcciones ipf en el switch FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.72                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.72                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Cree el primero de los dos túneles FCIP utilizando los puertos en dp0:
+
`portcfg fciptunnel`

+
Este comando crea un túnel con un único circuito.

+
El siguiente comando crea el túnel en el switch FC_switch_A_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.71  -D 10.10.20.72 -b 10000000 -B 10000000
----
+
El siguiente comando crea el túnel en el switch FC_switch_B_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.72  -D 10.10.20.71 -b 10000000 -B 10000000
----
. Compruebe que los túneles FCIP se han creado correctamente:
+
`portshow fciptunnel all`

+
El siguiente ejemplo muestra que se crearon túneles y que los circuitos están en marcha:

+
[listing]
----
FC_switch_B_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
--------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Cree un circuito adicional para dp0.
+
El siguiente comando crea un circuito en el switch FC_switch_A_1 para dp0:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.71 -D 10.10.21.72  --min-comm-rate 5000000 --max-comm-rate 5000000
----
+
El siguiente comando crea un circuito en el conmutador FC_switch_B_1 para dp0:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.72 -D 10.10.21.71  --min-comm-rate 5000000 --max-comm-rate 5000000
----
. Compruebe que todos los circuitos se han creado correctamente:
+
`portshow fcipcircuit all`

+
El siguiente comando muestra los circuitos y su estado:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge2     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge3     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
--------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Configuración de puertos ve de 40 Gbps en conmutadores FC Brocade 7810 y 7840

Cuando se utilizan los dos puertos ve de 40 GbE (que utilizan FCIP) para ISL, debe crear interfaces IP en cada puerto y configurar túneles y circuitos FCIP en cada túnel.

.Acerca de esta tarea
Este procedimiento debe realizarse en cada estructura de switch de la configuración de MetroCluster.

Los ejemplos de este procedimiento utilizan dos interruptores:

* FC_switch_A_1 es local.
* FC_switch_B_1 es remoto.


.Pasos
. Cree direcciones IP de interfaz (ipf) para los puertos de 40 Gbps en ambos switches de la estructura:
+
`portcfg ipif FC_switch_namefirst_port_name create FC_switch_IP_address netmask netmask_number vlan 2 mtu auto`

+
El siguiente comando crea direcciones ipf en los puertos ge0.dp0 y ge1.dp0 de FC_switch_A_1:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.82.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.82.11 netmask 255.255.0.0 vlan 2 mtu auto
----
+
El siguiente comando crea direcciones ipf en los puertos ge0.dp0 y ge1.dp0 de FC_switch_B_1:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.83.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.83.11 netmask 255.255.0.0 vlan 2 mtu auto
----
. Compruebe que las direcciones ipf se han creado correctamente en ambos switches:
+
`portshow ipif all`

+
En el ejemplo siguiente se muestran las interfaces IP en FC_switch_A_1:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
---------------------------------------------------------------------------
-----
 ge0.dp0      10.10.82.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.82.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
En el ejemplo siguiente se muestran las interfaces IP en FC_switch_B_1:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge0.dp0      10.10.83.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.83.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Cree el túnel FCIP en ambos conmutadores:
+
`portcfig fciptunnel`

+
El siguiente comando crea el túnel en FC_switch_A_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.82.10  -D 10.10.83.10 -b 10000000 -B 10000000
----
+
El siguiente comando crea el túnel en FC_switch_B_1:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.83.10  -D 10.10.82.10 -b 10000000 -B 10000000
----
. Compruebe que el túnel FCIP se ha creado correctamente:
+
`portshow fciptunnel all`

+
El siguiente ejemplo muestra que se creó el túnel y que los circuitos están activos:

+
[listing]
----
FC_switch_A_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
 --------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Crear un circuito adicional en cada interruptor:
+
`portcfg fcipcircuit 24 create 1 -S source-IP-address -D destination-IP-address --min-comm-rate 10000000 --max-comm-rate 10000000`

+
El siguiente comando crea un circuito en el switch FC_switch_A_1 para dp0:

+
[listing]
----
portcfg fcipcircuit 24  create 1 -S 10.10.82.11 -D 10.10.83.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
+
El siguiente comando crea un circuito en el conmutador FC_switch_B_1 para dp1:

+
[listing]
----
portcfg fcipcircuit 24 create 1  -S 10.10.83.11 -D 10.10.82.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
. Compruebe que todos los circuitos se han creado correctamente:
+
`portshow fcipcircuit all`

+
El siguiente ejemplo enumera los circuitos y muestra que su OpStatus está activo:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge0     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge1     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
 --------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Configurar los puertos que no son de E en el switch Brocade

Debe configurar los puertos que no son E-puertos en el switch de FC. En una configuración MetroCluster, son los puertos que conectan el switch a los iniciadores de HBA, las interconexiones FC-VI y los puentes FC a SAS. Estos pasos deben realizarse en cada puerto.

.Acerca de esta tarea
En el ejemplo siguiente, los puertos conectan un puente de FC a SAS:

--
* Puerto 6 en FC_FC_switch_A_1 en Site_A
* Puerto 6 en FC_FC_switch_B_1 en el Site_B


--
.Pasos
. Configure la velocidad del puerto para cada puerto que no sea E:
+
`portcfgspeed portspeed`

+
Debe utilizar la velocidad común más alta, que es la velocidad más alta admitida por todos los componentes de la ruta de datos: El SFP, el puerto de switch en el que está instalado SFP y el dispositivo conectado (HBA, puente, etc.).

+
Por ejemplo, los componentes pueden tener las siguientes velocidades admitidas:

+
** El SFP puede tener una capacidad de 4, 8 o 16 GB.
** El puerto del switch puede ser de 4, 8 o 16 GB.
** La velocidad máxima del HBA conectado es de 16 GB. La velocidad común más alta en este caso es de 16 GB, por lo que el puerto debe configurarse para una velocidad de 16 GB.
+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 6 16

FC_switch_B_1:admin> portcfgspeed 6 16
----


. Compruebe la configuración:
+
`portcfgshow`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow

FC_switch_B_1:admin> portcfgshow
----
+
En la salida de ejemplo, el puerto 6 tiene los siguientes ajustes; la velocidad se establece en 16 G:

+
[listing]
----
Ports of Slot 0                     0   1   2   3   4   5   6   7   8
-------------------------------------+---+---+---+--+---+---+---+---+--
Speed                               16G 16G 16G 16G 16G 16G 16G 16G 16G
AL_PA Offset 13                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Trunk Port                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Long Distance                       ..  ..  ..  ..  ..  ..  ..  ..  ..
VC Link Init                        ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked L_Port                       -   -   -   -   -  -   -   -   -
Locked G_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Disabled E_Port                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked E_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
ISL R_RDY Mode                      ..  ..  ..  ..  ..  ..  ..  .. ..
RSCN Suppressed                     ..  ..  ..  ..  ..  ..  ..  .. ..
Persistent Disable                  ..  ..  ..  ..  ..  ..  ..  .. ..
LOS TOV enable                      ..  ..  ..  ..  ..  ..  ..  .. ..
NPIV capability                     ON  ON  ON  ON  ON  ON  ON  ON  ON
NPIV PP Limit                       126 126 126 126 126 126 126 126 126
QOS Port                            AE  AE  AE  AE  AE  AE  AE  AE  ON
EX Port                             ..  ..  ..  ..  ..  ..  ..  ..  ..
Mirror Port                         ..  ..  ..  ..  ..  ..  ..  ..  ..
Rate Limit                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Credit Recovery                     ON  ON  ON  ON  ON  ON  ON  ON  ON
Fport Buffers                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Eport Credits                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Port Auto Disable                   ..  ..  ..  ..  ..  ..  ..  ..  ..
CSCTL mode                          ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port mode                         ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port over DWDM                    ..  ..  ..  ..  ..  ..  ..  ..  ..
FEC                                 ON  ON  ON  ON  ON  ON  ON  ON  ON
Fault Delay                         0   0   0   0   0   0   0   0   0
Non-DFE                             ..  ..  ..  ..  ..  ..  ..  ..  ..
----




== Configurar la compresión en puertos ISL en un switch Brocade G620

Si utiliza switches Brocade G620 y habilita la compresión en los ISL, debe configurarse en cada E-Port de los switches.

.Acerca de esta tarea
Esta tarea se debe realizar en los puertos ISL en ambos switches que utilizan el ISL.

.Pasos
. Deshabilite el puerto en el que desea configurar la compresión:
+
`portdisable port-id`

. Habilite la compresión en el puerto:
+
`portCfgCompress --enable port-id`

. Active el puerto para activar la configuración con compresión:
+
`portenable port-id`

. Confirme que se ha cambiado el ajuste:
+
`portcfgshow port-id`



En el ejemplo siguiente se habilita la compresión en el puerto 0.

[listing]
----
FC_switch_A_1:admin> portdisable 0
FC_switch_A_1:admin> portcfgcompress --enable 0
FC_switch_A_1:admin> portenable 0
FC_switch_A_1:admin> portcfgshow 0
Area Number: 0
Octet Speed Combo: 3(16G,10G)
(output truncated)
D-Port mode: OFF
D-Port over DWDM ..
Compression: ON
Encryption: ON
----
Puede utilizar el comando islShow para comprobar que E_Port se ha conectado con cifrado o compresión configurada y activa.

[listing]
----
FC_switch_A_1:admin> islshow
  1: 0-> 0 10:00:c4:f5:7c:8b:29:86   5 FC_switch_B_1
sp: 16.000G bw: 16.000G TRUNK QOS CR_RECOV ENCRYPTION COMPRESSION
----
Puede utilizar el comando portEncCompShow para ver qué puertos están activos. En este ejemplo puede ver que el cifrado y la compresión están configurados y activos en el puerto 0.

[listing]
----
FC_switch_A_1:admin> portenccompshow
User	  Encryption		           Compression	         Config
Port   Configured    Active   Configured   Active  Speed
----   ----------    -------  ----------   ------  -----
  0	   Yes	          Yes	     Yes	         Yes	    16G
----


== Configuración de la división en zonas en switches Brocade FC

Debe asignar los puertos del switch a zonas independientes para separar el tráfico de la controladora y del almacenamiento.



=== División en zonas para los puertos FC-VI

Para cada grupo de recuperación ante desastres de la MetroCluster, debe configurar dos zonas para las conexiones FC-VI que permiten el tráfico de la controladora a la controladora. Estas zonas contienen puertos del switch FC que se conectan a los puertos FC-VI del módulo de la controladora. Estas zonas son zonas de calidad de servicio.

Un nombre de zona QoS comienza con el prefijo QOSHid_, seguido por una cadena definida por el usuario para diferenciarlo de una zona normal. Estas zonas QoS son las mismas independientemente del modelo de puente FibreBridge que se esté utilizando.

Cada zona contiene todos los puertos FC-VI, uno para cada cable FC-VI de cada controladora. Estas zonas están configuradas para prioridad alta.

En las tablas siguientes se muestran las zonas de FC-VI para dos grupos de recuperación ante desastres.

*DR grupo 1 : QOSH1 Zona FC-VI para el puerto a/c* FC-VI

|===
| Switch FC | Sitio | Dominio del switch | 6505 / 6510 puertos | 6520 puertos | Puerto G620 | Conecta a... 


| FC_switch_A_1 | A. | 5 | 0 | 0 | 0 | Puerto FC-VI a de la controladora_a_1 


| FC_switch_A_1 | A. | 5 | 1 | 1 | 1 | Controladora_a_1 puerto FC-VI c 


| FC_switch_A_1 | A. | 5 | 4 | 4 | 4 | Controladora_a_2 Puerto FC-VI a 


| FC_switch_A_1 | A. | 5 | 5 | 5 | 5 | Controladora_a_2 Puerto FC-VI c 


| FC_switch_B_1 | B | 7 | 0 | 0 | 0 | Controller_B_1 puerto FC-VI a 


| FC_switch_B_1 | B | 7 | 1 | 1 | 1 | Controladora_B_1 puerto FC-VI c 


| FC_switch_B_1 | B | 7 | 4 | 4 | 4 | Controladora_B_2 Puerto FC-VI a 


| FC_switch_B_1 | B | 7 | 5 | 5 | 5 | Controladora_B_2 puerto FC-VI c 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| QOSH1_MC1_FAB_1_FCVI | 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5 
|===
*DR grupo 1 : QOSH1 Zona FC-VI para el puerto FC-VI b / d*

|===
| Switch FC | Sitio | Dominio del switch | 6505 / 6510 puertos | 6520 puertos | Puerto G620 | Conecta a... 


| FC_switch_A_2 | A. | 6 | 0 | 0 | 0 | Controladora_a_1 Puerto FC-VI b 


|  |  |  | 1 | 1 | 1 | Controladora_a_1 puerto FC-VI d 


|  |  |  | 4 | 4 | 4 | Controladora_a_2 Puerto FC-VI b 


|  |  |  | 5 | 5 | 5 | Controladora_a_2 Puerto FC-VI d 


| FC_switch_B_2 | B | 8 | 0 | 0 | 0 | Controladora_B_1 Puerto FC-VI b 


|  |  |  | 1 | 1 | 1 | Controladora_B_1 puerto FC-VI d 


|  |  |  | 4 | 4 | 4 | Controladora_B_2 Puerto FC-VI b 


|  |  |  | 5 | 5 | 5 | Controladora_B_2 Puerto FC-VI d 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| QOSH1_MC1_FAB_2_FCVI | 6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5 
|===
*DR grupo 2 : QOSH2 FC-VI zona para FC-VI puerto a / c*

|===
| Switch FC | Sitio | Dominio del switch | Puerto del switch |  |  | Conecta a... 


|  |  |  | 6510 | 6520 | G620 |  


| FC_switch_A_1 | A. | 5 | 24 | 48 | 18 | Controller_A_3 puertos FC-VI a 


|  |  |  | 25 | 49 | 19 | Controller_A_3 puertos FC-VI c 


|  |  |  | 28 | 52 | 22 | Controller_A_4 puertos FC-VI a 


|  |  |  | 29 | 53 | 23 | Controller_A_4 puertos FC-VI c 


| FC_switch_B_1 | B | 7 | 24 | 48 | 18 | Controller_B_3 puertos FC-VI a 


|  |  |  | 25 | 49 | 19 | Controladora_B_3 puertos FC-VI c 


|  |  |  | 28 | 52 | 22 | Controller_B_4 puertos FC-VI a 


|  |  |  | 29 | 53 | 23 | Controladora_B_4 puertos FC-VI c 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| QOSH2_MC2_FAB_1_FCVI (6510) | 5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29 


| QOSH2_MC2_FAB_1_FCVI (6520) | 5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53 
|===
*DR grupo 2 : QOSH2 FC-VI zona para FC-VI puerto b / d*

|===
| Switch FC | Sitio | Dominio del switch | 6510 puertos | 6520 puertos | Puerto G620 | Conecta a... 


| FC_switch_A_2 | A. | 6 | 24 | 48 | 18 | Controladora_a_3 puerto FC-VI b 


| FC_switch_A_2 | A. | 6 | 25 | 49 | 19 | Controller_A_3 puertos FC-VI d 


| FC_switch_A_2 | A. | 6 | 28 | 52 | 22 | Controladora_a_4 puerto FC-VI b 


| FC_switch_A_2 | A. | 6 | 29 | 53 | 23 | Controller_A_4 puertos FC-VI d 


| FC_switch_B_2 | B | 8 | 24 | 48 | 18 | Controladora_B_3 puerto FC-VI b 


| FC_switch_B_2 | B | 8 | 25 | 49 | 19 | Controladora_B_3 puertos FC-VI d 


| FC_switch_B_2 | B | 8 | 28 | 52 | 22 | Controladora_B_4 puerto FC-VI b 


| FC_switch_B_2 | B | 8 | 29 | 53 | 23 | Controladora_B_4 puertos FC-VI d 
|===
|===


| Zona en Fabric_2 | Puertos miembro 


| QOSH2_MC2_FAB_2_FCVI (6510) | 6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29 


| QOSH2_MC2_FAB_2_FCVI (6520) | 6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53 
|===
En la siguiente tabla se proporciona un resumen de las zonas de FC-VI:

|===


| Estructura | Nombre de zona | Puertos miembro 


.3+| FC_switch_A_1 y FC_switch_B_1  a| 
QOSH1_MC1_FAB_1_FCVI
 a| 
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5



 a| 
QOSH2_MC1_FAB_1_FCVI ( 6510)
 a| 
5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29



 a| 
QOSH2_MC1_FAB_1_FCVI (6520)
 a| 
5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53



.3+| FC_switch_A_2 y FC_switch_B_2  a| 
QOSH1_MC1_FAB_2_FCVI
 a| 
6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5



 a| 
QOSH2_MC1_FAB_2_FCVI (6510)
 a| 
6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29



 a| 
QOSH2_MC1_FAB_2_FCVI (6520)
 a| 
6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53

|===


=== División en zonas para puentes FibreBridge 7500N o 7600N usando un puerto FC

Si utiliza puentes FibreBridge 7500N o 7600N utilizando solo uno de los dos puertos FC, debe crear zonas de almacenamiento para los puertos puente. Tiene que comprender las zonas y los puertos asociados antes de configurar las zonas.

Los ejemplos muestran la división en zonas solo para el grupo de recuperación ante desastres 1. Si la configuración incluye un segundo grupo de recuperación ante desastres, configure la división en zonas del segundo grupo de recuperación ante desastres de la misma manera, utilizando los puertos correspondientes de las controladoras y los puentes.



==== Zonas requeridas

Debe configurar una zona para cada uno de los puertos FC de puente FC FC FC FC a SAS que permita el tráfico entre los iniciadores de cada módulo de controladora y el puente FC a SAS.

Cada zona de almacenamiento contiene nueve puertos:

* Ocho puertos de iniciador de HBA (dos conexiones por controladora)
* Un puerto que se conecta a un puerto FC puente FC FC FC FC FC FC FC FC-to-SAS


Las zonas de almacenamiento utilizan particiones estándar.

Los ejemplos muestran dos pares de puentes que conectan dos grupos de pilas en cada sitio. Como cada puente utiliza un puerto FC, hay un total de cuatro zonas de almacenamiento por estructura (ocho en total).



==== Nombre de puente

Los puentes utilizan el siguiente ejemplo de denominación: Grupo bridge_site_stack en par

|===


| Esta parte del nombre... | Identifica... | Los posibles valores son los siguientes: 


 a| 
sitio
 a| 
Sitio en el que reside físicamente el par puente.
 a| 
A o B



 a| 
grupo de pilas
 a| 
Número del grupo de pilas al que se conecta el par de puente.

Los puentes FibreBridge 7600N o 7500N admiten hasta cuatro pilas en el grupo de pilas.

El grupo de pilas no puede contener más de 10 bandejas de almacenamiento.
 a| 
1, 2, etc.



 a| 
ubicación en pareja
 a| 
Puente dentro del par de puente.un par de puentes se conectan a un grupo de pila específico.
 a| 
a o b

|===
Nombres de puente de ejemplo para un grupo de pila en cada sitio:

* bridge_A_1a
* puente_a_1b
* bridge_B_1a
* puente_B_1b




==== Grupo DR 1 - pila 1 en Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 5 | 2 | Puerto 0a de la controladora_a_1 


| FC_switch_A_1 | A. | 5 | 3 | Puerto 0c de controladora_a_1 


| FC_switch_A_1 | A. | 5 | 6 | Puerto 0a de la controladora_a_2 


| FC_switch_A_1 | A. | 5 | 7 | Puerto 0c de controladora_a_2 


| FC_switch_A_1 | A. | 5 | 8 | bridge_A_1a FC1 


| FC_switch_B_1 | B | 7 | 2 | Controladora_B_1 Puerto 0a 


| FC_switch_B_1 | B | 7 | 3 | Controladora_B_1 Puerto 0c 


| FC_switch_B_1 | B | 7 | 6 | Controladora_B_2 Puerto 0a 


| FC_switch_B_1 | B | 7 | 7 | Controladora_B_2 Puerto 0c 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOTR_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 6 | 2 | Controller_A_1 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 3 | Controller_A_1 puerto 0d 


| FC_switch_A_1 | A. | 6 | 6 | Controller_A_2 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 7 | Controller_A_2, puerto 0d 


| FC_switch_A_1 | A. | 6 | 8 | bridge_A_1b FC1 


| FC_switch_B_1 | B | 8 | 2 | Controller_B_1 Puerto 0b 


| FC_switch_B_1 | B | 8 | 3 | Controller_B_1 puerto 0d 


| FC_switch_B_1 | B | 8 | 6 | Controller_B_2 Puerto 0b 


| FC_switch_B_1 | B | 8 | 7 | Controller_B_2 Puerto 0d 
|===
|===


| Zona en Fabric_2 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 
|===


==== Grupo DR 1 - pila 2 en el sitio_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 5 | 2 | Puerto 0a de la controladora_a_1 


| FC_switch_A_1 | A. | 5 | 3 | Puerto 0c de controladora_a_1 


| FC_switch_A_1 | A. | 5 | 6 | Puerto 0a de la controladora_a_2 


| FC_switch_A_1 | A. | 5 | 7 | Puerto 0c de controladora_a_2 


| FC_switch_A_1 | A. | 5 | 9 | bridge_A_FC1 a 


| FC_switch_B_1 | B | 7 | 2 | Controladora_B_1 Puerto 0a 


| FC_switch_B_1 | B | 7 | 3 | Controladora_B_1 Puerto 0c 


| FC_switch_B_1 | B | 7 | 6 | Controladora_B_2 Puerto 0a 


| FC_switch_B_1 | B | 7 | 7 | Controladora_B_2 Puerto 0c 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOTR_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 6 | 2 | Controller_A_1 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 3 | Controller_A_1 puerto 0d 


| FC_switch_A_1 | A. | 6 | 6 | Controller_A_2 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 7 | Controller_A_2, puerto 0d 


| FC_switch_A_1 | A. | 6 | 9 | bridge_A_FC1 2b 


| FC_switch_B_1 | B | 8 | 2 | Controller_B_1 Puerto 0b 


| FC_switch_B_1 | B | 8 | 3 | Controller_B_1 puerto 0d 


| FC_switch_B_1 | B | 8 | 6 | Controller_B_2 Puerto 0b 


| FC_switch_B_1 | B | 8 | 7 | Controller_B_2 Puerto 0d 
|===
|===


| Zona en Fabric_2 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 
|===


==== Grupo DR 1 - pila 1 en Site_B

*MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Switch Brocade 6505, 6510, 6520, G620 o G610 | Conecta a... 


| FC_switch_A_1 | A. | 5 | 2 | Puerto 0a de la controladora_a_1 


| FC_switch_A_1 | A. | 5 | 3 | Puerto 0c de controladora_a_1 


| FC_switch_A_1 | A. | 5 | 6 | Puerto 0a de la controladora_a_2 


| FC_switch_A_1 | A. | 5 | 7 | Puerto 0c de controladora_a_2 


| FC_switch_B_1 | B | 7 | 2 | Controladora_B_1 Puerto 0a 


| FC_switch_B_1 | B | 7 | 3 | Controladora_B_1 Puerto 0c 


| FC_switch_B_1 | B | 7 | 6 | Controladora_B_2 Puerto 0a 


| FC_switch_B_1 | B | 7 | 7 | Controladora_B_2 Puerto 0c 


| FC_switch_B_1 | B | 7 | 8 | bridge_B_1a FC1 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOTA_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Switch Brocade 6505, 6510, 6520, G620 o G610 | Conecta a... 


| FC_switch_A_1 | A. | 6 | 2 | Controller_A_1 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 3 | Controller_A_1 puerto 0d 


| FC_switch_A_1 | A. | 6 | 6 | Controller_A_2 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 7 | Controller_A_2, puerto 0d 


| FC_switch_B_1 | B | 8 | 2 | Controller_B_1 Puerto 0b 


| FC_switch_B_1 | B | 8 | 3 | Controller_B_1 puerto 0d 


| FC_switch_B_1 | B | 8 | 6 | Controller_B_2 Puerto 0b 


| FC_switch_B_1 | B | 8 | 7 | Controller_B_2 Puerto 0d 


| FC_switch_B_1 | B | 8 | 8 | bridge_B_1b FC1 
|===
|===


| Zona en Fabric_2 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;8,8 
|===


==== Grupo DR 1 - pila 2 en Site_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 5 | 2 | Puerto 0a de la controladora_a_1 


| FC_switch_A_1 | A. | 5 | 3 | Puerto 0c de controladora_a_1 


| FC_switch_A_1 | A. | 5 | 6 | Puerto 0a de la controladora_a_2 


| FC_switch_A_1 | A. | 5 | 7 | Puerto 0c de controladora_a_2 


| FC_switch_B_1 | B | 7 | 2 | Controladora_B_1 Puerto 0a 


| FC_switch_B_1 | B | 7 | 3 | Controladora_B_1 Puerto 0c 


| FC_switch_B_1 | B | 7 | 6 | Controladora_B_2 Puerto 0a 


| FC_switch_B_1 | B | 7 | 7 | Controladora_B_2 Puerto 0c 


| FC_switch_B_1 | B | 7 | 9 | bridge_b_FC1 2a 
|===
|===


| Zona en Fabric_1 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOTA_FC1:*

|===
| Switch FC | Sitio | Dominio del switch | Brocade 6505, 6510, 6520, G620 o puerto de switch G610 | Conecta a... 


| FC_switch_A_1 | A. | 6 | 2 | Controller_A_1 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 3 | Controller_A_1 puerto 0d 


| FC_switch_A_1 | A. | 6 | 6 | Controller_A_2 Puerto 0b 


| FC_switch_A_1 | A. | 6 | 7 | Controller_A_2, puerto 0d 


| FC_switch_B_1 | B | 8 | 2 | Controller_B_1 Puerto 0b 


| FC_switch_B_1 | B | 8 | 3 | Controller_B_1 puerto 0d 


| FC_switch_B_1 | B | 8 | 6 | Controller_B_2 Puerto 0b 


| FC_switch_B_1 | B | 8 | 7 | Controller_B_2 Puerto 0d 


| FC_switch_B_1 | B | 8 | 9 | bridge_B_1b FC1 
|===
|===


| Zona en Fabric_2 | Puertos miembro 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


==== Resumen de las zonas de almacenamiento

|===


| Estructura | Nombre de zona | Puertos miembro 


.4+| FC_switch_A_1 y FC_switch_B_1 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 


.4+| FC_switch_A_2 y FC_switch_B_2 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


=== División en zonas para puentes FibreBridge 7500N con ambos puertos FC

Si utiliza puentes FibreBridge 7500N con ambos puertos FC, debe crear zonas de almacenamiento para los puertos de puente. Tiene que comprender las zonas y los puertos asociados antes de configurar las zonas.



==== Zonas requeridas

Debe configurar una zona para cada uno de los puertos FC de puente FC FC FC FC a SAS que permita el tráfico entre los iniciadores de cada módulo de controladora y el puente FC a SAS.

Cada zona de almacenamiento contiene cinco puertos:

* Cuatro puertos de iniciador de HBA (una conexión para cada controladora)
* Un puerto que se conecta a un puerto FC puente FC FC FC FC FC FC FC FC-to-SAS


Las zonas de almacenamiento utilizan particiones estándar.

Los ejemplos muestran dos pares de puentes que conectan dos grupos de pilas en cada sitio. Como cada puente utiliza un puerto FC, hay un total de ocho zonas de almacenamiento por estructura (dieciséis en total).



==== Nombre de puente

Los puentes utilizan el siguiente ejemplo de denominación: Grupo bridge_site_stack en par

|===


| Esta parte del nombre... | Identifica... | Los posibles valores son los siguientes: 


 a| 
sitio
 a| 
Sitio en el que reside físicamente el par puente.
 a| 
A o B



 a| 
grupo de pilas
 a| 
Número del grupo de pilas al que se conecta el par de puente.

Los puentes FibreBridge 7600N o 7500N admiten hasta cuatro pilas en el grupo de pilas.

El grupo de pilas no puede contener más de 10 bandejas de almacenamiento.
 a| 
1, 2, etc.



 a| 
ubicación en pareja
 a| 
Puente dentro del par de puente. Un par de puentes se conectan a un grupo de pilas específico.
 a| 
a o b

|===
Nombres de puente de ejemplo para un grupo de pila en cada sitio:

* bridge_A_1a
* puente_a_1b
* bridge_B_1a
* puente_B_1b




==== Grupo DR 1 - pila 1 en Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | 6505 / 6510 / G610 / G620 | 6520 puertos | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
2
 a| 
2
 a| 
Puerto 0a de la controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
6
 a| 
6
 a| 
Puerto 0a de la controladora_a_2



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
8
 a| 
8
 a| 
bridge_A_1a FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
Controladora_B_1 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
Controladora_B_2 Puerto 0a

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Puerto 0c de controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Puerto 0c de controladora_a_2



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controladora_B_1 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controladora_B_2 Puerto 0c

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOTR_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | 6505 / 6510 / G610 | 6520 | G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
8
 a| 
8
 a| 
8
 a| 
bridge_A_1a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2 Puerto 0b

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | 6505 / 6510 / G610 | 6520 | G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1 puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2, puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1 puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2 Puerto 0d

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9

|===


==== Grupo DR 1 - pila 2 en el sitio_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Puerto 0a de la controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Puerto 0a de la controladora_a_2



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_FC1 a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controladora_B_1 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controladora_B_2 Puerto 0a

|===
|===


| Zona en Fabric_1 hh | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Puerto 0c de controladora_a_1



| FC_switch_A_1  a| 
A.
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Puerto 0c de controladora_a_2



| FC_switch_A_1  a| 
A.
 a| 
5
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_A_FC1 2b



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controladora_B_1 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controladora_B_2 Puerto 0c

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
2
 a| 
0
 a| 
0
 a| 
Controller_A_1 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
6
 a| 
4
 a| 
4
 a| 
Controller_A_2 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_2a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2 Puerto 0b

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1 puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2, puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_A_2b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1 puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2 Puerto 0d

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11

|===


==== Grupo DR 1 - pila 1 en Site_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Puerto 0a de la controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Puerto 0a de la controladora_a_2



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
8
 a| 
Controladora_B_1 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
2
 a| 
Controladora_B_2 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
8
 a| 
8
 a| 
6
 a| 
bridge_B_1a FC1

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Puerto 0c de controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Puerto 0c de controladora_a_2



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
9
 a| 
Controladora_B_1 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
3
 a| 
Controladora_B_2 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
9
 a| 
9
 a| 
7
 a| 
bridge_B_1b FC1

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
bridge_B_1a FC2

|===
|===
| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1 puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2, puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1 puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2 Puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9

|===


==== Grupo DR 1 - pila 2 en Site_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Puerto 0a de la controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Puerto 0a de la controladora_a_2



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controladora_B_1 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controladora_B_2 Puerto 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_FC1 2a

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Puerto 0c de controladora_a_1



 a| 
FC_switch_A_1
 a| 
A.
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Puerto 0c de controladora_a_2



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controladora_B_1 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controladora_B_2 Puerto 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_B_FC1 2b

|===
|===


| Zona en Fabric_2 hh | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1 Puerto 0b



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2 Puerto 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_2a FC2

|===
|===


| Zona en Fabric_1 | Puertos miembro 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOTT_FC2:*

|===


| Switch FC | Sitio | Dominio del switch | Puerto 6505 / 6510 / G610 | 6520 puertos | Puerto G620 | Conecta a... 


 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1 puerto 0d



 a| 
FC_switch_A_2
 a| 
A.
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2, puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1 puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2 Puerto 0d



 a| 
FC_switch_B_2
 a| 
B
 a| 
8
 a| 
11
 a| 
11
 a| 
11
 a| 
bridge_B_2b FC2

|===
|===


| Zona en Fabric_2 | Puertos miembro 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


==== Resumen de las zonas de almacenamiento

|===


| Estructura | Nombre de zona | Puertos miembro 


 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10



 a| 
FC_switch_A_1 y FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10



 a| 
FC_switch_A_2 y FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


=== Configuración de la división en zonas en switches Brocade FC

Debe asignar los puertos del switch a zonas independientes para separar el tráfico de la controladora y del almacenamiento, con zonas para los puertos y las zonas de FC-VI para los puertos de almacenamiento.

.Acerca de esta tarea
Los pasos siguientes utilizan la división en zonas estándar para la configuración de MetroCluster.

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["División en zonas para los puertos FC-VI"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["División en zonas para puentes FibreBridge 7500N o 7600N usando un puerto FC"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["División en zonas para puentes FibreBridge 7500N con ambos puertos FC"]

.Pasos
. Cree las zonas FC-VI en cada switch:
+
`zonecreate "QOSH1_FCVI_1", member;member ...`

+
En este ejemplo se crea una zona FCVI QOS que contiene los puertos 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5:

+
[listing]
----
Switch_A_1:admin> zonecreate "QOSH1_FCVI_1", "5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5"
----
. Configurar las zonas de almacenamiento en cada switch.
+
Puede configurar la división en zonas para la estructura desde un switch de la estructura. En el ejemplo siguiente, la división en zonas está configurada en Switch_A_1.

+
.. Cree la zona de almacenamiento para cada dominio de switch en la estructura de switches:
+
`zonecreate name, member;member ...`

+
En este ejemplo se está creando una zona de almacenamiento para FibreBridge 7500N con los dos puertos FC. Las zonas contienen los puertos 5,2;5,6;7,2;7,6;5,16:

+
[listing]
----
Switch_A_1:admin> zonecreate "MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1", "5,2;5,6;7,2;7,6;5,16"
----
.. Cree la configuración en la primera estructura del switch:
+
`cfgcreate config_name, zone;zone...`

+
En este ejemplo se crea una configuración con el nombre CFG_1 y las dos zonas QOSH1_MC1_FAB_1_FCVI y MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1

+
[listing]
----
Switch_A_1:admin> cfgcreate "CFG_1", "QOSH1_MC1_FAB_1_FCVI; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1"
----
.. Agregue zonas a la configuración, si lo desea:
+
`cfgadd config_namezone;zone...`

.. Habilite la configuración:
+
`cfgenable config_name`

+
[listing]
----
Switch_A_1:admin> cfgenable "CFG_1"
----
.. Guarde la configuración:
+
`cfgsave`

+
[listing]
----
Switch_A_1:admin> cfgsave
----
.. Valide la configuración de la división en zonas:
+
`zone --validate`

+
[listing]
----
Switch_A_1:admin> zone --validate
Defined configuration:
cfg: CFG_1 QOSH1_MC1_FAB_1_FCVI ; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
zone: QOSH1_MC1_FAB_1_FCVI
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2;5,6;7,2;7,6;5,16
Effective configuration:
cfg: CFG_1
zone: QOSH1_MC1_FAB_1_FCVI
5,0
5,1
5,4
5,5
7,0
7,1
7,4
7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2
5,6
7,2
7,6
5,16
------------------------------------
~ - Invalid configuration
* - Member does not exist
# - Invalid usage of broadcast zone
----






== Configuración del cifrado ISL en switches Brocade 6510 o G620

En los switches Brocade 6510 o G620, puede utilizar de forma opcional la función de cifrado de Brocade en las conexiones ISL. Si desea utilizar la función de cifrado, debe realizar pasos de configuración adicionales en cada switch de la configuración de MetroCluster.

.Antes de empezar
* Debe tener switches Brocade 6510 o G620.
+

NOTE: La compatibilidad con el cifrado ISL en switches Brocade G620 solo se admite en ONTAP 9.4 y versiones posteriores.

* Debe haber seleccionado dos switches de la misma estructura.
* Debe haber revisado la documentación de Brocade para la versión del switch y del sistema operativo Fabric para confirmar los límites de ancho de banda y puerto.


.Acerca de esta tarea
Los pasos deben realizarse en ambos switches de la misma estructura.



=== Deshabilitación de Virtual Fabric

Para configurar el cifrado ISL, debe deshabilitar la estructura virtual en los cuatro switches que se usan en una configuración MetroCluster.

.Pasos
. Deshabilite la estructura virtual introduciendo el siguiente comando en la consola de switches:
+
`fosconfig --disable vf`

. Reinicie el conmutador.




=== Configure la carga útil

Después de deshabilitar la estructura virtual, debe establecer la carga útil o el tamaño del campo de datos en ambos switches de la estructura.

.Acerca de esta tarea
El tamaño del campo de datos no debe ser superior a 2048.

.Pasos
. Desactivar el interruptor:
+
`switchdisable`

. Configurar y establecer la carga útil:
+
`configure`

. Configure los siguientes parámetros del conmutador:
+
.. Configure el parámetro Fabric de la siguiente manera: `y`
.. Establezca los demás parámetros, como dominio, PID persistente basado en WWN, etc.
.. Establezca el tamaño del campo de datos: `2048`






=== Configuración de la política de autenticación

Debe configurar la política de autenticación y los parámetros asociados.

.Acerca de esta tarea
Los comandos deben ejecutarse en la consola del conmutador.

.Pasos
. Establezca el secreto de autenticación:
+
.. Comience el proceso de configuración:
+
`secAuthSecret --set`

+
Este comando inicia una serie de mensajes a los que se responde en los pasos siguientes:

.. Proporcione el nombre a nivel mundial (WWN) del otro switch en la estructura del parámetro "Enter peer WWN, dominio o nombre de switch".
.. Introduzca el secreto del mismo nivel para el parámetro "Enter peer secret".
.. Proporcione el secreto local para el parámetro "Enter local secret".
.. Introduzca `Y` Para el parámetro "está listo".
+
--
A continuación se muestra un ejemplo de configuración del secreto de autenticación:

[listing]
----
brcd> secAuthSecret --set

This command is used to set up secret keys for the DH-CHAP authentication.
The minimum length of a secret key is 8 characters and maximum 40
characters. Setting up secret keys does not initiate DH-CHAP
authentication. If switch is configured to do DH-CHAP, it is performed
whenever a port or a switch is enabled.

Warning: Please use a secure channel for setting secrets. Using
an insecure channel is not safe and may compromise secrets.

Following inputs should be specified for each entry.

1. WWN for which secret is being set up.
2. Peer secret: The secret of the peer that authenticates to peer.
3. Local secret: The local secret that authenticates peer.

Press enter to start setting up secrets > <cr>

Enter peer WWN, Domain, or switch name (Leave blank when done): 10:00:00:05:33:76:2e:99
Enter peer secret: <hidden>
Re-enter peer secret: <hidden>
Enter local secret: <hidden>
Re-enter local secret: <hidden>

Enter peer WWN, Domain, or switch name (Leave blank when done):
Are you done? (yes, y, no, n): [no] yes
Saving data to key store... Done.
----
--


. Establezca el grupo de autenticación en 4:
+
`authUtil --set -g 4`

. Establezca el tipo de autenticación en "dhCHAP":
+
`authUtil --set -a dhchap`

+
El sistema muestra la siguiente salida:

+
[listing]
----
Authentication is set to dhchap.
----
. Establezca la directiva de autenticación en el conmutador en on:
+
`authUtil --policy -sw on`

+
El sistema muestra la siguiente salida:

+
[listing]
----
Warning: Activating the authentication policy requires either DH-CHAP secrets or PKI certificates depending on the protocol selected. Otherwise, ISLs will be segmented during next E-port bring-up.
ARE YOU SURE  (yes, y, no, n): [no] yes
Auth Policy is set to ON
----




=== Activación del cifrado ISL en switches Brocade

Después de configurar la política de autenticación y el secreto de autenticación, debe habilitar el cifrado ISL en los puertos para que surta efecto.

.Acerca de esta tarea
* Estos pasos deben realizarse en una estructura de switch cada vez.
* Los comandos deben ejecutarse en la consola del switch.


.Pasos
. Habilite el cifrado en todos los puertos ISL:
+
`portCfgEncrypt --enable port_number`

+
En el ejemplo siguiente, el cifrado está activado en los puertos 8 y 12:

+
`portCfgEncrypt --enable 8`

+
`portCfgEncrypt --enable 12`

. Active el interruptor:
+
`switchenable`

. Compruebe que el ISL está en funcionamiento:
+
`islshow`

. Compruebe que el cifrado está activado:
+
`portenccompshow`

+
El ejemplo siguiente muestra que el cifrado está activado en los puertos 8 y 12:

+
[listing]
----

User Encryption
Port  configured     Active
----   ----------    ------
 8      yes          yes
 9      No           No
 10     No           No
 11     No           No
 12     yes          yes
----


.Qué hacer a continuación
Realizar todos los pasos de los switches de la otra estructura en una configuración MetroCluster.
