---
permalink: install-fc/task_rack_the_hardware_components_mcc_fabric_and_ip.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components 
summary: Si no ha recibido el equipo ya instalado en armarios, debe montar los componentes en rack. 
---
= Acumular en rack los componentes de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no ha recibido el equipo ya instalado en armarios, debe montar los componentes en rack.

.Acerca de esta tarea
Esta tarea debe realizarse en los dos sitios MetroCluster.

.Pasos
. Planifique la colocación de los componentes de MetroCluster.
+
El espacio en rack depende del modelo de plataforma de los módulos de la controladora, los tipos de switch y el número de pilas de bandejas de discos que haya en la configuración.

. Puesta a tierra apropiadamente usted mismo.
. Instale los módulos de la controladora en el rack o armario.
+
https://["Centro de documentación de AFF y FAS"]

. Instale los switches FC en el rack o armario.
. Instale las bandejas de discos, enciúdeles a encender y, a continuación, configure los ID de bandeja.
+
** Debe apagar y encender cada bandeja de discos.
** Los ID de bandeja deben ser únicos para cada bandeja de discos SAS dentro de cada grupo de recuperación ante desastres MetroCluster (incluidos ambos sitios).


. Instale cada puente FC-a-SAS:
+
.. Fije los soportes "'L'" de la parte frontal del puente a la parte delantera del bastidor (empotrado) con los cuatro tornillos.
+
Las aberturas de los soportes del puente "'L'" cumplen con el estándar del bastidor ETA-310-X para bastidores de 19 pulgadas (482.6 mm).

+
El _ATTO FiberBridge Installation and Operation Manual_ del modelo de puente contiene más información y una ilustración de la instalación.

+

NOTE: Para obtener un acceso adecuado al espacio del puerto y una capacidad de servicio de FRU, debe dejar espacio 1U por debajo del par de puentes y cubrir este espacio con un panel de supresión sin herramientas.

.. Conecte cada puente a una fuente de alimentación que proporcione una conexión a tierra correcta.
.. Encienda cada puente.
+

NOTE: Para obtener la máxima resiliencia, los puentes conectados a la misma pila de bandejas de discos deben conectarse a diferentes fuentes de alimentación.

+
El LED Bridge Ready puede tardar hasta 30 segundos en iluminarse, lo que indica que el puente ha completado su secuencia de prueba automática de encendido.




