---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: Si desea configurar ONTAP para su uso con LUN de cabina, debe configurar el agregado raíz y el volumen raíz, reservar espacio para operaciones de diagnóstico y recuperación, y configurar el clúster. 
---
= Configuración de ONTAP en un sistema que solo utiliza LUN de cabina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea configurar ONTAP para su uso con LUN de cabina, debe configurar el agregado raíz y el volumen raíz, reservar espacio para operaciones de diagnóstico y recuperación, y configurar el clúster.

.Antes de empezar
* El sistema ONTAP debe estar conectado a la cabina de almacenamiento.
* El administrador de la cabina de almacenamiento debe haber creado LUN y presentado a ONTAP.
* El administrador de la cabina de almacenamiento debe haber configurado la seguridad del LUN.


.Acerca de esta tarea
Debe configurar cada nodo que desee usar con LUN de cabina. Si el nodo está en una pareja de alta disponibilidad, debe completar el proceso de configuración de un nodo antes de continuar con la configuración del nodo del partner.

.Pasos
. Encienda el nodo principal y interrumpa el proceso de arranque pulsando Ctrl-C cuando vea el siguiente mensaje en la consola:
+
`Press CTRL-C for special boot menu.`

. Seleccione la opción *4 (limpiar configuración e inicializar todos los discos)* en el menú de arranque.
+
Se muestra la lista de LUN de cabina disponibles para ONTAP. Además, también se especifica el tamaño de LUN de la cabina necesario para la creación del volumen raíz. El tamaño requerido para la creación de volúmenes raíz difiere de un sistema ONTAP a otro.

+
** Si no se asignaron previamente LUN de cabina, ONTAP detecta y muestra los LUN de cabina disponibles, como se muestra en el siguiente ejemplo:
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** Si se asignaron previamente LUN de cabina, por ejemplo, a través del modo de mantenimiento, se marcan como partner local o como partner en la lista de los LUN de cabina disponibles, en función de si se seleccionaron los LUN de cabina del nodo en el que está instalando ONTAP o su partner de alta disponibilidad:
+
En este ejemplo, las LUN de cabina con números de índice 3 y 6 se marcan como "locales" porque se habían asignado previamente desde este nodo en particular:

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. Seleccione el número de índice que corresponde al LUN de cabina que desea asignar como volumen raíz.
+
El LUN de cabina debe tener el tamaño suficiente para crear el volumen raíz.

+
El LUN de cabina seleccionado para la creación del volumen raíz se Marca como "local (raíz)".

+
En el siguiente ejemplo, el LUN de la cabina con el número de índice 3 está marcado para la creación del volumen raíz:

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. Seleccione el número de índice que corresponde al LUN de cabina que desea asignar para utilizar en las opciones de diagnóstico y recuperación.
+
El LUN de cabina debe tener el tamaño suficiente para utilizar en las opciones de diagnóstico y recuperación. Si es necesario, también puede seleccionar varios LUN de cabina con un tamaño combinado mayor o igual que el tamaño especificado. Para seleccionar varias entradas, debe introducir los valores separados por comas de todos los números de índice que corresponden a los LUN de cabina que desea seleccionar para las opciones de diagnóstico y recuperación.

+
El siguiente ejemplo muestra una lista de LUN de cabina seleccionadas para la creación de volumen raíz y para las opciones de diagnóstico y recuperación:

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: Al seleccionar «'no'», se borra la selección de LUN.

. Introduzca `*y*` cuando el sistema le solicite que continúe con el proceso de instalación.
+
Se crean el agregado raíz y el volumen raíz, y se continúa el resto del proceso de instalación.

. Introduzca los detalles necesarios para crear la interfaz de gestión de los nodos.
+
En el ejemplo siguiente se muestra la pantalla de la interfaz de gestión de nodos con un mensaje que confirma la creación de la interfaz de gestión de nodos:

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


.Después de terminar
Después de configurar ONTAP en todos los nodos que desea usar con LUN de cabina, debe completar elhttps://["Proceso de configuración del clúster"]

.Información relacionada
https://["Referencias y requisitos de instalación de la virtualización FlexArray"]
