---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, cisco, fc, switch, nx, software 
summary: Debe descargar el archivo del sistema operativo del switch y el archivo RCF en cada switch de la configuración de la estructura de MetroCluster. 
---
= Descargar e instalar el software del switch FC NX-OS de Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar el archivo del sistema operativo del switch y el archivo RCF en cada switch de la configuración de la estructura de MetroCluster.

.Antes de empezar
Esta tarea requiere software de transferencia de archivos, como FTP, TFTP, SFTP o SCP para copiar los archivos en los switches.

.Acerca de esta tarea
Estos pasos deben repetirse en cada uno de los switches FC de la configuración de estructura de MetroCluster.

Debe utilizar la versión de software del switch compatible.

https://["Hardware Universe de NetApp"]


NOTE: Los resultados que se muestran son para los switches IP de Cisco; sin embargo, estos pasos también se aplican a los switches FC de Cisco.

.Pasos
. Descargue el archivo de software NX-OS admitido.
+
https://["Página de descarga de Cisco"]

. Copie el software del conmutador en el conmutador:
+
`copy sftp://root@server-ip-address/tftpboot/NX-OS-file-name bootflash: vrf management`

+
En este ejemplo, la `nxos.7.0.3.I4.6.bin` El archivo se copia desde el servidor SFTP 10.10.99.99 al bootflash local:

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. Verifique en cada switch que los archivos NX-OS del switch estén presentes en el directorio bootflash de cada switch:
+
`dir bootflash`

+
El siguiente ejemplo muestra que los archivos están presentes en `IP_switch_A_1`:

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Instale el software del conmutador:
+
`install all system bootflash:nxos.version-number.bin kickstart bootflash:nxos.version-kickstart-number.bin`

+
[listing]
----
IP_switch_A_1#  install all system bootflash:nxos.7.0.3.I4.6.bin kickstart bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "kickstart".
[####################] 100% -- SUCCESS

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "system".
[####################] 100% -- SUCCESS

Performing module support checks.                                                                                                            [####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Extracting "system" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Extracting "kickstart" version from image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS
...
----
+
El conmutador se reinicia automáticamente después de instalar el software del conmutador.

. Espere a que el conmutador se vuelva a cargar y, a continuación, inicie sesión en el conmutador.
+
Cuando el conmutador haya reiniciado, aparecerá el mensaje de inicio de sesión:

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. Compruebe que se ha instalado el software del conmutador:
+
`show version`

+
El siguiente ejemplo muestra el resultado:

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. Repita estos pasos en los tres switches FC restantes de la configuración de estructura MetroCluster.

