---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 'Debe asegurarse de que los vínculos entre switches \(ISL\) se encuentren en el mismo grupo de puertos y configurar la división en zonas para que las configuraciones de MetroCluster puedan compartir correctamente las estructuras de switches.' 
---
= Asegurar que los ISL se encuentren en el mismo grupo de puertos y configurar la división en zonas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que los vínculos entre switches (ISL) se encuentren en el mismo grupo de puertos y configurar la división en zonas para que las configuraciones de MetroCluster puedan compartir correctamente las estructuras de switches.

.Pasos
. Si los ISL no están en el mismo grupo de puertos, mueva uno de los puertos ISL al mismo grupo de puertos que el otro.
+
Se puede usar cualquier puerto disponible excepto 32 a 45, que sean utilizados por la nueva configuración de MetroCluster. Los puertos ISL recomendados son 46 y 47.

. Siga los pasos de link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configuración de la división en zonas en switches Brocade FC"] Para habilitar la conexión de enlaces y la zona QoS.
+
Los números de puerto al compartir estructuras son diferentes de los que se muestran en la sección. Cuando se compartan, utilice los puertos 46 y 47 para los puertos ISL. Si ha movido sus puertos ISL, debe utilizar el procedimiento en el link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurar los puertos E-ports (puertos ISL) en un switch FC de Brocade"] para configurar los puertos.

. [[step3_zones]] siga los pasos de la link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurar los puertos que no son de E en el switch Brocade"] Para configurar los puertos que no son de E.
. No elimine las zonas o conjuntos de zonas que ya existen en los conmutadores de entorno de administración (para el MetroCluster de estructura de 7-Mode) excepto las zonas de aislamiento del tráfico (TI) de <<step3_zones,Paso 3>>.
. Siga los pasos de la link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Configurar los puertos E-ports (puertos ISL) en un switch FC de Brocade"] Para agregar las zonas requeridas por el nuevo MetroCluster a los conjuntos de zonas existentes.
+
En el siguiente ejemplo se muestran los comandos y el resultado del sistema para crear las zonas:

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

