---
permalink: install-fc/task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, hardware, brocade, fc, transition 
summary: Si su configuración de MetroCluster de estructura 7-Mode utiliza switches Brocade 6510, puede compartir los switches existentes con la nueva configuración de Clustered MetroCluster. Las estructuras de switches compartidas significa que la nueva configuración de MetroCluster no requiere una estructura de switches nueva e independiente. Esta configuración temporal solo es compatible con el switch Brocade 6510 para la transición. 
---
= Configuración del hardware para compartir una estructura FC Brocade 6510 durante la transición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si su configuración de MetroCluster de estructura 7-Mode utiliza switches Brocade 6510, puede compartir los switches existentes con la nueva configuración de Clustered MetroCluster. Las estructuras de switches compartidas significa que la nueva configuración de MetroCluster no requiere una estructura de switches nueva e independiente. Esta configuración temporal solo es compatible con el switch Brocade 6510 para la transición.

.Antes de empezar
* La estructura MetroCluster 7-Mode debe usar los switches Brocade 6510.
+
Si la configuración de MetroCluster no utiliza actualmente switches Brocade 6510, los switches deben actualizarse a Brocade 6510 antes de seguir este procedimiento.

* La configuración de MetroCluster de estructura 7-Mode debe usar únicamente bandejas de almacenamiento SAS.
+
Si la configuración existente incluye bandejas de almacenamiento FC (como DS14mk4 FC), no se admite el uso compartido de estructuras de switches FC.

* Los SFP en los puertos del switch utilizados por la nueva configuración de MetroCluster en clúster deben admitir tasas de 16 Gbps.
+
El MetroCluster estructural 7-Mode existente puede seguir conectado a puertos que utilizan SFP de 8 Gbps o 16 Gbps.

* En cada uno de los cuatro switches Brocade 6510, deben estar disponibles los puertos 24 a 45 para conectar los puertos de los nuevos componentes MetroCluster.
* Debe verificar que los enlaces Inter-Switch (ISL) existentes estén en los puertos 46 y 47.
* Los switches Brocade 6510 deben ejecutar una versión de firmware FOS compatible con la configuración MetroCluster de estructura 7-Mode y ONTAP MetroCluster.


.Después de terminar
Después de compartir la estructura y completar la configuración de MetroCluster, puede realizar la transición de datos de la configuración de la estructura MetroCluster 7-Mode.

Después de realizar la transición de los datos, puede quitar el cableado de la estructura MetroCluster de 7-Mode y, si lo desea, mover el cableado ONTAP MetroCluster a los puertos con menor número previamente utilizados para el cableado MetroCluster de 7-Mode. Los puertos se muestran en la sección «Revisión de las asignaciones de puertos de switch FC para una MetroCluster de cuatro nodos». Debe ajustar la división en zonas de los puertos reorganizados.

link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Asignaciones de puertos para los switches FC cuando se utiliza ONTAP 9.1 y versiones posteriores"]

.Información relacionada
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transición basada en copias"]
