---
permalink: install-fc/task_mirror_the_root_aggregates_mcc_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, mirror, root, aggregates 
summary: Debe reflejar los agregados raíz en la configuración de MetroCluster para garantizar la protección de datos. 
---
= Mirroring de los agregados raíz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe reflejar los agregados raíz en la configuración de MetroCluster para garantizar la protección de datos.

.Antes de empezar
Debe haberse asegurado de que se cumplen los requisitos de SyncMirror para la configuración de MetroCluster con los LUN de cabina. Consultelink:reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html["Requisitos para una configuración de MetroCluster con LUN de cabina"].

.Acerca de esta tarea
Debe repetir esta tarea para cada controladora de la configuración de MetroCluster.

.Paso
. Reflejar el agregado raíz sin reflejar:
+
`storage aggregate mirror`

+
El siguiente comando refleja el agregado raíz para Controller_A_1:

+
[listing]
----
controller_A_1::> storage aggregate mirror aggr0_controller_A_1
----
+
El agregado raíz se refleja con LUN de cabina del grupo 1.


