---
permalink: install-fc/task_fmc_mcc_transition_configure_zone_and_qos.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, delete, ti, zoning, tod, settings 
summary: 'Debe eliminar la división en zonas de TI existente y volver a configurar los ajustes de entrega en orden \(IOD\) en la estructura del switch.' 
---
= Eliminación de la división en zonas de TI y configuración de los ajustes de IOD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe eliminar la división en zonas de TI existente y volver a configurar los ajustes de entrega en orden (IOD) en la estructura del switch.

.Pasos
. Identifique las zonas de TI configuradas en la estructura:
+
`zone --show`

+
El ejemplo siguiente muestra la zona FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --show
   Defined TI zone configuration:
   TI Zone Name:   FCVI_TI_FAB_2
   Port List:      1,0; 1,3; 2,0; 2,3
   configured Status: Activated / Failover-Disabled
   Enabled Status: Activated / Failover-Disabled
----
. Elimine las zonas de TI:
+
`zone --delete _zone-name_`

+
En el ejemplo siguiente se muestra la eliminación de la zona FCVI_TI_FAB_2.

+
[listing]
----
Brocade-6510:admin> zone --delete FCVI_TI_FAB_2
----
. Confirme que se han eliminado las zonas:
+
`zone --show`

+
La salida debe ser similar a la siguiente:

+
[listing]
----
Brocade-6510:admin> zone -–show

    Defined TI zone configuration:
    no TI zone configuration defined
----
. Guarde la configuración:
+
`cfgsave`

. Permitir la entrega bajo pedido:
+
`iodset`

. Seleccione la directiva 1 de ajuste avanzado del rendimiento (APT), la directiva de enrutamiento basada en puertos:
+
`aptpolicy 1`

. Desactivar el uso compartido dinámico de la carga (DLS):
+
`dlsreset`

. Verifique los ajustes de IOD:
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
La salida debe ser similar a la siguiente:

+
[listing]
----
Brocade-6510:admin> iodshow

IOD is set

Brocade-6510:admin> aptpolicy
 Current Policy: 1

 3 : Default Policy
 1: Port Based Routing Policy
 2: Device Based Routing Policy (FICON support only)
 3: Exchange Based Routing Policy
Brocade-6510:admin> dlsshow

DLS is not set
----

