---
permalink: install-fc/task_fcsw_configure_the_fc_switches_with_rcf_files_mcc.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, fc, switches, run, configuration, file 
summary: Si desea simplificar el proceso de configuración de los switches, puede descargar y aplicar archivos de configuración de referencia que proporcionen la configuración completa del conmutador para determinadas configuraciones. 
---
= Configurar los switches de FC ejecutando un archivo de configuración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea simplificar el proceso de configuración de los switches, puede descargar y aplicar archivos de configuración de referencia que proporcionen la configuración completa del conmutador para determinadas configuraciones.

Los archivos de configuración de referencia (RCF) no admiten configuraciones que utilicen ocho ISL. Si utiliza ocho ISL, deberá configurar los switches manualmente.

Los RCF se aplican a configuraciones MetroCluster de dos, cuatro y ocho nodos. Estos archivos configuran la estructura para la entrega en orden (IOD) de forma predeterminada.

La página de descarga de RCF indica el número de nodos admitidos por los diferentes modelos de switch.
