---
permalink: install-fc/task_peer_the_clusters_mcc_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, peering, cluster 
summary: Los clústeres de la configuración de MetroCluster deben tener una relación entre iguales para que puedan comunicarse entre sí y realizar las operaciones de mirroring de datos esenciales para la recuperación ante desastres de MetroCluster. 
---
= Una relación entre iguales de los clústeres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los clústeres de la configuración de MetroCluster deben tener una relación entre iguales para que puedan comunicarse entre sí y realizar las operaciones de mirroring de datos esenciales para la recuperación ante desastres de MetroCluster.

.Pasos
. Configure LIF de interconexión de clústeres mediante el procedimiento descrito en:
+
link:../upgrade/task_configure_intercluster_lifs_to_use_dedicated_intercluster_ports.html["Configurar las LIF de interconexión de clústeres"]

. Cree una relación de paridad de clústeres mediante el procedimiento descrito en:
+
link:concept_configure_the_mcc_software_in_ontap.html#peering-the-clusters["Una relación entre iguales de los clústeres"]


