---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, license, array, luns, configuration 
summary: Debe instalar la licencia V_StorageAttach en cada nodo MetroCluster que desee utilizar con LUN de cabina. No se pueden usar LUN de cabina en un agregado hasta que se instale la licencia. 
---
= Instalar la licencia para usar LUN de cabina en una configuración de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar la licencia V_StorageAttach en cada nodo MetroCluster que desee utilizar con LUN de cabina. No se pueden usar LUN de cabina en un agregado hasta que se instale la licencia.

.Antes de empezar
* Se debe instalar el clúster.
* Debe tener la clave de licencia de la licencia V_StorageAttach.


.Acerca de esta tarea
Debe usar una clave de licencia independiente para cada nodo en el que desea instalar la licencia V_StorageAttach.

.Pasos
. Instale la licencia V_StorageAttach.
+
`system license add`

+
Repita este paso con cada nodo de clúster en el que desee instalar la licencia.

. Compruebe que la licencia V_StorageAttach esté instalada en todos los nodos requeridos de un clúster.
+
`system license show`

+
En el siguiente ejemplo, se muestra que la licencia V_StorageAttach está instalada en los nodos de cluster_A:

+
[listing]
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----

