---
permalink: install-fc/task_fmc_mcc_transition_reenable_the_switch_fabric_and_verify_operation.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reenable, switch, fabric, verify, operation 
summary: Debe habilitar la estructura del switch de FC y asegurarse de que los switches y los dispositivos funcionen correctamente. 
---
= Volver a habilitar la estructura del switch y verificar el funcionamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe habilitar la estructura del switch de FC y asegurarse de que los switches y los dispositivos funcionen correctamente.

.Pasos
. Habilite los interruptores:
+
`switchCfgPersistentEnable`

+
Si este comando no está disponible, el conmutador debe estar en estado habilitado después del `fastBoot` se emite el comando.

+
** En el ejemplo siguiente se muestra el comando emitido en FC_switch_A_1:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----
** En el ejemplo siguiente se muestra el comando emitido en FC_switch_B_1:
+
[listing]
----
FC_switch_B_1:admin> switchCfgPersistentEnable
----


. Compruebe que los interruptores están en línea y que todos los dispositivos están correctamente conectados:
+
`switchShow`

+
En el ejemplo siguiente se muestra el comando emitido en FC_switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchShow
----
+
En el ejemplo siguiente se muestra el comando emitido en FC_switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchShow
----
. Ejecute la utilidad fmc_dc para garantizar que el MetroCluster de estructura 7-Mode funciona correctamente.
+
Puede ignorar los errores relacionados con la división en zonas y la conexión en enlaces de aislamiento de tráfico (TI).

. Repita las tareas para la segunda estructura del switch.

