---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file 
summary: 'Debe descargar el archivo de configuración de referencia \(RCF\) en cada switch de la configuración de la estructura de MetroCluster.' 
---
= Descarga del archivo RCF del switch FC de Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debes descargar el archivo de configuración de referencia (RCF) en cada conmutador de la configuración de la estructura de MetroCluster.

.Acerca de esta tarea
Para utilizar estos RCF, el sistema debe estar ejecutando ONTAP 9.1 o una versión posterior y debes usar la configuración de puertos para ONTAP 9.1 o una versión posterior.

Si planea utilizar solo uno de los puertos FC en los puentes FibreBridge, configure los conmutadores de canal de fibra de back-end manualmente siguiendo las instrucciones que se encuentran en la sección link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Asignaciones de puertos para conmutadores FC"] .

.Pasos
. Consulta la tabla de RCF en la página de descargas de RCF de Brocade e identifica el RCF adecuado para cada conmutador de tu configuración.
+
Los RCF deben aplicarse a los switches correctos.

. Descarga los RCF de los switches desde la página https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["Descarga de RCF de MetroCluster"].
+
Los archivos se deben colocar en una ubicación en la que puedan transferirse al conmutador. Hay un archivo separado para cada uno de los cuatro switches que conforman la estructura de dos switches.

. Repita estos pasos en cada switch de la configuración.

