---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, storage, arrays, fc, switches, configuration 
summary: Debe conectar las cabinas de almacenamiento a switches FC para que los sistemas ONTAP de la configuración de MetroCluster puedan acceder a un LUN de cabina específico a través de al menos dos rutas. 
---
= Cableado de las cabinas de almacenamiento a switches FC en una configuración MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conectar las cabinas de almacenamiento a switches FC para que los sistemas ONTAP de la configuración de MetroCluster puedan acceder a un LUN de cabina específico a través de al menos dos rutas.

.Antes de empezar
* Las cabinas de almacenamiento deben estar configuradas para presentar LUN de cabina en ONTAP.
* Las controladoras ONTAP deben estar conectadas a los switches FC.
* Los ISL deben estar conectados entre los switches FC en los sitios MetroCluster.
* Debe repetir esta tarea para cada cabina de almacenamiento en ambos sitios de MetroCluster.
* Debe conectar las controladoras en una configuración MetroCluster a las cabinas de almacenamiento a través de switches FC.


.Pasos
. Conecte los puertos de la cabina de almacenamiento a puertos del switch de FC.
+
En cada sitio, conecte los pares de puertos redundantes de la cabina de almacenamiento a switches FC en estructuras alternativas. Esto ofrece redundancia en las rutas para acceder a los LUN de cabina.



.Información relacionada
* La configuración de la división en zonas de switches le permite definir qué LUN de cabina pueden ver un sistema ONTAP específico en la configuración de MetroCluster.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["División en zonas de switches en una configuración de MetroCluster con LUN de cabina"]

* En una configuración de MetroCluster con LUN de cabina, debe conectar los puertos de la cabina de almacenamiento que forman un par de puertos redundante a switches FC alternativos.
+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.html["Ejemplo de cableado de los puertos de la cabina de almacenamiento a switches FC en una configuración MetroCluster de dos nodos"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.html["Ejemplo de cableado de los puertos de la cabina de almacenamiento a switches FC en una configuración MetroCluster de cuatro nodos"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.html["Ejemplo de cableado de los puertos de la cabina de almacenamiento a switches FC en una configuración MetroCluster de ocho nodos"]


