= 
:allow-uri-read: 


Algunas plataformas utilizan una VLAN para la interfaz de IP de MetroCluster. De manera predeterminada, cada uno de los dos puertos utiliza una VLAN diferente: 10 y 20.

+ Si es compatible, también puede especificar una VLAN diferente (no predeterminada) superior a 100 (entre 101 y 4095) mediante el `-vlan-id` parámetro del `metrocluster configuration-settings interface create` comando.

+ Las siguientes plataformas *no* soportan el `-vlan-id` parámetro:

+ ** FAS8200 y AFF A300 ** AFF A320 ** FAS9000 y AFF A700 ** AFF C800, ASA C800, AFF A800 y ASA A800

+ Todas las demás plataformas soportan el `-vlan-id` parámetro.

+ Las asignaciones VLAN predeterminadas y válidas dependen de si la plataforma soporta el `-vlan-id` parámetro:

+

[role="tabbed-block"]
====
.Plataformas compatibles con <code>-vlan-id</code>
--
VLAN predeterminada:

* Cuando no se especifica el `-vlan-id` parámetro, las interfaces se crean con VLAN 10 para los puertos “A” y VLAN 20 para los puertos “B”.
* La VLAN especificada debe coincidir con la VLAN seleccionada en el RCF.


Rangos de VLAN válidos:

* VLAN predeterminada 10 y 20
* VLAN 101 y superior (entre 101 y 4095)


--
.Plataformas que no admiten <code>-vlan-id</code>
--
VLAN predeterminada:

* No aplicable La interfaz no requiere que se especifique una VLAN en la interfaz de MetroCluster. El puerto del switch define la VLAN que se usa.


Rangos de VLAN válidos:

* Todas las VLAN no se excluyen explícitamente al generar el RCF. La RCF le avisa si la VLAN no es válida.


--
====