= 
:allow-uri-read: 


[role="lead"]
Restablezca y restaure los valores predeterminados en los módulos de la controladora.

. En el símbolo del SISTEMA del CARGADOR, devuelva las variables de entorno a su configuración predeterminada: `set-defaults`
. Arrancar el nodo en el menú de arranque: `boot_ontap menu`
+
Después de ejecutar este comando, espere a que se muestre el menú de inicio.

. Borre la configuración del nodo:
+
--
** Si está utilizando sistemas configurados para ADP, seleccione opción `9a` desde el menú de inicio, y responda `no` cuando se le solicite.
+

NOTE: Este proceso es disruptivo.

+
La siguiente pantalla muestra el indicador del menú de inicio:

+
[listing]
----

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a
...

########## WARNING: AGGREGATES WILL BE DESTROYED ##########
This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:

The aggregates visible from this node do not contain
data that needs to be preserved.
This option (9a) has been executed or will be executed
on the HA partner node (and DR/DR-AUX partner nodes if
applicable), prior to reinitializing any system in the
HA-pair or MetroCluster configuration.
The HA partner node (and DR/DR-AUX partner nodes if
applicable) is currently waiting at the boot menu.
Do you want to abort this operation (yes/no)? no
----


--
+
** Si su sistema no está configurado para ADP, escriba `wipeconfig` En el símbolo del sistema del menú de inicio y, a continuación, pulse Intro.
+
La siguiente pantalla muestra el indicador del menú de inicio:

+
[listing]
----

Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  wipeconfig
This option deletes critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?: yes
Rebooting to finish wipeconfig request.
----



