---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= Novedades en las funciones de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada versión del software de gestión de datos ONTAP 9 ofrece funciones nuevas y mejoradas que mejoran las funcionalidades, la capacidad de gestión y el rendimiento de las configuraciones de ONTAP MetroCluster.

Para obtener información detallada sobre problemas conocidos, limitaciones y precauciones sobre la actualización que afectan a las configuraciones de ONTAP MetroCluster, consulte la https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP 9"^]. Debe iniciar sesión con su cuenta de NetApp o crear una cuenta para acceder a las Notas de la versión.

[cols="20,65,15"]
|===
| Funciones admitidas en la configuración de MetroCluster | Descripción y dónde obtener más información | Comienzo disponible 


 a| 
Compatibilidad con Flash Cache para sistemas FAS50 en configuraciones IP de MetroCluster
 a| 
La caché flash es compatible con los sistemas FAS50 en configuraciones IP MetroCluster .

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["Asignación de discos en sistemas FAS50 con caché flash"]
 a| 
ONTAP 9.18.1



 a| 
Compatibilidad con IP de MetroCluster para cifrado integral
 a| 
El cifrado de extremo a extremo es compatible con los siguientes sistemas para cifrar el tráfico de back-end, como NVlog y datos de replicación de almacenamiento, entre los sitios en una configuración de IP de MetroCluster .

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80
* FAS50, FAS70, FAS90


link:../maintain/task-configure-encryption.html["Configure el cifrado integral en una configuración IP de MetroCluster"]
 a| 
ONTAP 9.17.1



 a| 
Cambios de límites para las configuraciones de IP de MetroCluster
 a| 
ONTAP 9.17.1 incluye las siguientes actualizaciones de límites para configuraciones de IP de MetroCluster de cuatro nodos:

* Los sistemas AFF C800, AFF A800, AFF A900, AFF A90 y AFF A1K tienen los siguientes límites actualizados:
+
** Límites de FlexVol volume por nodo: 1250
** Límites de SVM: 64 SVM por clúster
** Número de LIF: 256 LIF por clúster


* Los sistemas AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70 y AFF A50 tienen los siguientes límites actualizados:
+
** Límites de FlexVol volume por agregado (individual o múltiple): 625
** Límites de FlexVol volume por nodo: 1250
** Límites de FlexVol volume por par de alta disponibilidad (HA): 2500
** Límites de FlexVol volume por clúster: 5000
** Límites de SVM: 64 SVM por clúster
** Número de LIF: 256 LIF por clúster




Consulte la link:https://hwu.netapp.com["Hardware Universe"^] Para más información.
 a| 
ONTAP 9.17.1



 a| 
Actualización del firmware de FibreBridge mediante credenciales
 a| 
Puede actualizar el firmware en los puentes FibreBridge usando credenciales si el servidor las requiere para descargar el paquete de firmware.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["Actualización del firmware en un puente FiberBridge"]
 a| 
ONTAP 9.16.1



 a| 
Compatibilidad de movilidad de datos de SVM para migrar configuraciones de MetroCluster
 a| 
ONTAP admite las siguientes migraciones de SVM de MetroCluster:

* Migración de una SVM entre una pareja de alta disponibilidad que no es MetroCluster y una configuración MetroCluster IP
* Migración de una SVM entre dos configuraciones MetroCluster IP
* Migración de una SVM entre una configuración MetroCluster FC y una configuración MetroCluster IP


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["Movilidad de datos de SVM"^]
 a| 
ONTAP 9.16.1



 a| 
Soporte de autenticación MD5 para grupos de pares BGP
 a| 
ONTAP admite la autenticación MD5 en grupos de pares BGP para proteger las sesiones BGP. Cuando MD5 está habilitado, las sesiones BGP solo se pueden establecer y procesar entre pares autorizados, evitando posibles interrupciones de la sesión por parte de un actor no autorizado.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Configurar las LIF de IP virtual (VIP)"^]
 a| 
ONTAP 9.16.1



 a| 
Compatibilidad con IP de MetroCluster para cifrado integral
 a| 
El cifrado de extremo a extremo es compatible con los sistemas AFF A400, AFF C400, FAS8300 y FAS8700 para cifrar el tráfico de back-end, como NVlog y datos de replicación de almacenamiento, entre los sitios en una configuración de IP de MetroCluster .

link:../maintain/task-configure-encryption.html["Configure el cifrado integral en una configuración IP de MetroCluster"]
 a| 
ONTAP 9.15.1



 a| 
Aumento del límite de volúmenes para configuraciones IP de MetroCluster de cuatro nodos en sistemas AFF A800 y AFF C800
 a| 
En configuraciones MetroCluster IP de cuatro nodos, los siguientes límites de volúmenes para los sistemas AFF A800 y AFF C800 han aumentado:

* El número máximo de volúmenes de FlexVol por agregado ha aumentado de 200 a 625.
* El número máximo de volúmenes FlexVol por nodo ha aumentado de 800 a 1250.
* La cantidad máxima de volúmenes FlexVol por par HA aumentó de 1600 a 2500.

 a| 
ONTAP 9.15.1



 a| 
Soporte de IP de MetroCluster para NVMe
 a| 
El protocolo de host front-end NVMe/TCP se admite en configuraciones IP de MetroCluster de cuatro nodos.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configuraciones SAN en un entorno MetroCluster"^]
 a| 
ONTAP 9.15.1



 a| 
Aumento del límite de volúmenes para configuraciones IP de MetroCluster de cuatro nodos en sistemas AFF A900
 a| 
En configuraciones MetroCluster IP de cuatro nodos, los siguientes límites de volúmenes para los sistemas AFF A900 han aumentado:

* El número máximo de volúmenes de FlexVol por agregado ha aumentado de 200 a 625.
* El número máximo de volúmenes FlexVol por nodo ha aumentado de 800 a 1250.
* La cantidad máxima de volúmenes FlexVol por par HA aumentó de 1600 a 2500.

 a| 
ONTAP 9.14.1



 a| 
Compatibilidad con almacenamiento de objetos S3 en agregados reflejados y no reflejados
 a| 
Puede habilitar un servidor de almacenamiento de objetos S3 en una SVM en un agregado reflejado o no reflejado en configuraciones de MetroCluster IP y FC.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Soporte de S3 con MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Compatibilidad para aprovisionar un bloque de S3 en agregados reflejados y no reflejados de un clúster de MetroCluster
 a| 
Puede crear un bucket en un agregado reflejado o no reflejado en las configuraciones de MetroCluster.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["Cree un bloque de ONTAP S3 en un agregado reflejado o no reflejado de una configuración de MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Transición de FC de MetroCluster a IP de MetroCluster mediante un switch compartido para el almacenamiento conectado a Ethernet y MetroCluster IP
 a| 
Puede realizar la transición de forma no disruptiva de una configuración MetroCluster FC a una IP de MetroCluster mediante un switch de almacenamiento compartido.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Realizar la transición de forma no disruptiva de un FC de MetroCluster a una configuración IP de MetroCluster (ONTAP 9.8 y posterior)"]
 a| 
ONTAP 9.13.1



 a| 
Transiciones no disruptivas de una configuración FC de MetroCluster de ocho nodos a una configuración IP de MetroCluster
 a| 
Puede realizar la transición de cargas de trabajo y datos de forma no disruptiva de una configuración FC de MetroCluster de ocho nodos existente a una nueva configuración de IP de MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Realice la transición de forma no disruptiva de una configuración MetroCluster FC a una MetroCluster IP"]
 a| 
ONTAP 9.13.1



 a| 
Actualizaciones de la configuración IP de MetroCluster de cuatro nodos mediante conmutación de sitios y conmutación de estado
 a| 
Es posible actualizar controladoras en una configuración IP de MetroCluster de cuatro nodos mediante la conmutación de sitios y la conmutación con `system controller replace` comandos.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["Actualice las controladoras en una configuración IP de MetroCluster en cuatro nodos"]
 a| 
ONTAP 9.13.1



 a| 
La conmutación automática no planificada asistida por mediador (MAUSO) se activa para un cierre medioambiental
 a| 
Si un sitio se cierra correctamente debido a un cierre ambiental, se activa MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Cómo admite el Mediador ONTAP la conmutación automática no planificada"]
 a| 
ONTAP 9.13.1



 a| 
Se admiten configuraciones IP de MetroCluster de ocho nodos
 a| 
Es posible actualizar las controladoras y el almacenamiento en una configuración IP de MetroCluster de ocho nodos. Para ello, se debe expandir la configuración para convertirse en una configuración temporal de doce nodos y, a continuación, quitar los grupos anteriores de recuperación ante desastres.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["Actualice una configuración IP de MetroCluster de cuatro nodos"]
 a| 
ONTAP 9.13.1



 a| 
Conversión de la configuración de IP de MetroCluster a una configuración de switch de MetroCluster de almacenamiento compartido
 a| 
Es posible convertir una configuración IP de MetroCluster en una configuración de switch de MetroCluster de almacenamiento compartido.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["Sustituya un switch IP"]
 a| 
ONTAP 9.13.1



 a| 
Función de cambio forzado automático de MetroCluster en una configuración de IP de MetroCluster
 a| 
Se puede habilitar la función de conmutación automática forzada de MetroCluster en una configuración de IP de MetroCluster. Esta característica es una extensión de la función de cambio no planificado asistido por Mediator (MAUSO).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["Limitaciones de conmutación automática de sitios"]
 a| 
ONTAP 9.12.1



 a| 
S3 en una SVM en un agregado no reflejado en una configuración de IP de MetroCluster
 a| 
Puede habilitar un servidor de almacenamiento de objetos ONTAP Simple Storage Service (S3) en una máquina virtual de almacenamiento SVM en un agregado no reflejado en una configuración de IP de MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["Soporte de S3 con MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Soporte de IP de MetroCluster para NVMe
 a| 
El protocolo NVMe/FC se admite en configuraciones IP MetroCluster de cuatro nodos.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["Configuraciones SAN en un entorno MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
Compatibilidad con IPsec para el protocolo de host front-end en configuraciones FAS de MetroCluster e IP de MetroCluster
 a| 
La compatibilidad con IPsec para el protocolo de host front-end (como NFS e iSCSI) está disponible en configuraciones FAS de MetroCluster IP y MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurar la seguridad IP (IPsec) a través del cifrado de cable"^]
 a| 
ONTAP 9.12.1



 a| 
Transición de una configuración FC de MetroCluster a una configuración IP de AFF A250 o FAS500f MetroCluster
 a| 
Puede realizar la transición de una configuración FC de MetroCluster a una configuración IP de MetroCluster de AFF A250 o FAS500f.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["Mueva las conexiones del clúster local"]
 a| 
ONTAP 9.11.1



 a| 
Grupos de consistencia
 a| 
Los grupos de coherencia son compatibles con las configuraciones MetroCluster.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["Grupos de consistencia en configuraciones de MetroCluster"^]
 a| 
ONTAP 9.11.1



 a| 
Actualización de controladoras simplificada de nodos en una configuración MetroCluster FC
 a| 
Se ha simplificado el procedimiento de actualización para el proceso de actualización mediante la conmutación de sitios y la conmutación de estado.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Actualice controladoras en una configuración MetroCluster FC mediante la conmutación de sitios y la conmutación de estado"]
 a| 
ONTAP 9.10.1



 a| 
Compatibilidad con IP para enlace compartido en la capa 3
 a| 
Las configuraciones de IP de MetroCluster se pueden implementar con conexiones back-end enrutadas por IP (capa 3).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["Consideraciones sobre las redes de área amplia de capa 3"]
 a| 
ONTAP 9.9.1



 a| 
Compatibilidad con configuraciones MetroCluster de ocho nodos
 a| 
Los clústeres permanentes de ocho nodos se admiten en configuraciones de IP y MetroCluster con conexión a la estructura.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Instale y cablee los componentes del MetroCluster"]
 a| 
ONTAP 9.9.1

|===