---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Con cada versión se proporcionan nuevas funciones del Mediador ONTAP.  Esto es lo nuevo. 
---
= ¿Qué novedades incluye la compatibilidad de ONTAP Mediator con MetroCluster?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca las nuevas funciones y mejoras de MetroCluster para la compatibilidad con ONTAP Mediator.

Para obtener detalles sobre las características y mejoras de cada versión de ONTAP Mediator, consultelink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["¿Qué novedades hay en ONTAP Mediator?"^] .

[cols="4,2"]
|===
| Capacidad de mediador de ONTAP | Comienzo disponible 


 a| 
IPv6 es compatible con ONTAP Mediator 1.11 o posterior en configuraciones IP de MetroCluster .

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Configurar el mediador de ONTAP para una configuración de IP de MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 agrega soporte para administrar hasta diez configuraciones IP de MetroCluster utilizando una sola instancia de ONTAP Mediator.

link:../install-ip/concept_mediator_requirements.html["Prepárese para instalar el mediador ONTAP en una configuración IP de MetroCluster."]
 a| 
ONTAP 9.18.1



 a| 
La conmutación automática no planificada asistida por mediador (MAUSO) es compatible en el caso de un cierre medioambiental.

Si un sitio se cierra correctamente debido a un cierre ambiental, se activa MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Cómo ONTAP Mediator admite la conmutación automática no planificada"]
 a| 
ONTAP 9.13.1



 a| 
Soporte inicial para ONTAP Mediator en configuraciones IP de MetroCluster
 a| 
ONTAP 9,7

|===