---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= Novedades en la compatibilidad con la configuración de MetroCluster de las funciones de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cada versión del software de gestión de datos ONTAP 9 ofrece funciones nuevas y mejoradas que mejoran las funcionalidades, la capacidad de gestión y el rendimiento de las configuraciones de ONTAP MetroCluster.

Para obtener información detallada sobre problemas conocidos, limitaciones y precauciones sobre la actualización que afectan a las configuraciones de ONTAP MetroCluster, consulte la https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP 9"^]. Debe iniciar sesión con su cuenta de NetApp o crear una cuenta para acceder a las Notas de la versión.

[cols="20,65,15"]
|===
| Funciones admitidas en la configuración de MetroCluster | Descripción | Comienzo disponible 


 a| 
Compatibilidad con almacenamiento de objetos S3 en agregados reflejados y no reflejados
 a| 
Puede habilitar un servidor de almacenamiento de objetos S3 en una SVM en un agregado reflejado o no reflejado en configuraciones de MetroCluster IP y FC.

https://docs.netapp.com/us-en/ontap/s3-config/index.html["Información general de la configuración de S3"]
 a| 
ONTAP 9.14.1



 a| 
Compatibilidad para aprovisionar un bloque de S3 en agregados reflejados y no reflejados de un clúster de MetroCluster
 a| 
Puede crear un bucket en un agregado reflejado o no reflejado en las configuraciones de MetroCluster.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["Cree un bucket en un agregado reflejado o no reflejado en una configuración de MetroCluster"]
 a| 
ONTAP 9.12.1



 a| 
Compatibilidad con IPsec para el protocolo de host front-end en configuraciones FAS de MetroCluster e IP de MetroCluster
 a| 
La compatibilidad con IPsec para el protocolo de host front-end (como NFS e iSCSI) está disponible en configuraciones FAS de MetroCluster IP y MetroCluster.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Configurar la seguridad IP (IPsec) a través del cifrado de cable"]
 a| 
ONTAP 9.11.1



 a| 
Grupos de consistencia
 a| 
Los grupos de coherencia son compatibles con las configuraciones MetroCluster.

https://docs.netapp.com/us-en/ontap/mediator/index.html["Instale o actualice el servicio Mediator de ONTAP"]
 a| 
ONTAP 9,7



 a| 
Reflejos FabricPool en configuraciones MetroCluster
 a| 
Puede configurar un FabricPool reflejado en configuraciones de MetroCluster para organizar los datos inactivos en dos zonas de fallos distintas.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["Configuración de almacenes de objetos para FabricPool en una configuración de MetroCluster"]
 a| 
ONTAP 9,7



 a| 
Recuperación ante desastres de SVM
 a| 
Las máquinas virtuales de almacenamiento activas (SVM) en una configuración de MetroCluster pueden usarse como orígenes con la función de recuperación ante desastres de SVM de SnapMirror.
 a| 
ONTAP 9,5

|===