---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Con cada versión se proporcionan nuevas funciones del Mediador ONTAP.  Esto es lo nuevo. 
---
= Novedades en la compatibilidad de ONTAP Mediator con MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga información sobre las nuevas características y mejoras de IP de MetroCluster para la compatibilidad con ONTAP Mediator.

Para obtener detalles sobre las características y mejoras de cada versión de ONTAP Mediator, consultelink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["¿Qué novedades hay en ONTAP Mediator?"^] .

[cols="4,1"]
|===
| Capacidad de mediador de ONTAP | Comienzo disponible 


 a| 
A partir de ONTAP Mediator 1.12.1, una única instancia de ONTAP Mediator configurada con HTTPS puede supervisar simultáneamente las siguientes configuraciones:

* Un máximo de diez configuraciones IP de MetroCluster de cuatro nodos o cinco de ocho nodos si se instalan en un host con al menos 8 núcleos de CPU y al menos 16GB de RAM.
* Una configuración IP de MetroCluster de cuatro nodos y una relación entre iguales activa de SnapMirror si se instala en un sistema operativo host con una CPU de dos núcleos.


link:../install-ip/concept_mediator_requirements.html#mediator-multiple-mccip["Conoce más sobre la compatibilidad de ONTAP Mediator con varias configuraciones IP de MetroCluster"].
 a| 
ONTAP 9.19.1



 a| 
ONTAP Mediator 1.12 admite configurar un ONTAP Mediator que use HTTPS para la comunicación en configuraciones IP de MetroCluster. HTTPS proporciona mayor seguridad al cifrar sesiones completas usando SSL/TLS. Puedes elegir instalar un ONTAP Mediator que solo use el protocolo HTTPS. El paquete SCST no se instala si se usa este método de instalación. Para más información sobre la instalación de un ONTAP Mediator que solo use el protocolo HTTPS, consulta link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["Opciones de instalación HTTPS e iSCSI para ONTAP Mediator"^].

link:../install-ip/concept_mediator_requirements.html#select-a-communication-protocol-for-ontap-mediator["Más información sobre los protocolos iSCSI y HTTPS en ONTAP Mediator"].
 a| 
ONTAP 9.19.1



 a| 
IPv6 es compatible con ONTAP Mediator 1.11 o posterior en configuraciones IP de MetroCluster .

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Configurar el mediador de ONTAP para una configuración de IP de MetroCluster"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 agrega soporte para administrar hasta diez configuraciones IP de MetroCluster utilizando una sola instancia de ONTAP Mediator.

link:../install-ip/concept_mediator_requirements.html["Prepárese para instalar el mediador ONTAP en una configuración IP de MetroCluster."]
 a| 
ONTAP 9.18.1



 a| 
La conmutación automática no planificada asistida por mediador (MAUSO) es compatible en el caso de un cierre medioambiental.

Si un sitio se cierra correctamente debido a un cierre ambiental, se activa MAUSO.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Cómo ONTAP Mediator admite la conmutación automática no planificada"]
 a| 
ONTAP 9.13.1



 a| 
Soporte inicial para ONTAP Mediator en configuraciones IP de MetroCluster
 a| 
ONTAP 9,7

|===