---
permalink: maintain/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, port, assignments, system, two, initiator, ports 
summary: Puede configurar sistemas FAS8020, AFF8020, FAS8200 y AFF A300 utilizando un único puerto de iniciador para cada estructura y dos puertos de iniciador para cada controladora. 
---
= Las asignaciones de puertos para los sistemas que utilizan dos puertos iniciadores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar sistemas FAS8020, AFF8020, FAS8200 y AFF A300 utilizando un único puerto de iniciador para cada estructura y dos puertos de iniciador para cada controladora.

.Acerca de esta tarea
Puede seguir el cableado para el puente FibreBridge 6500N o el puente FibreBridge 7500N o 7600N utilizando sólo un puerto FC (FC1 o FC2). En lugar de usar cuatro iniciadores, conecte solo dos iniciadores y deje los otros dos que están conectados al puerto del switch vacío.

Debe aplicar el archivo RCF correcto para la configuración del puente FibreBridge 6500N.

Si la división en zonas se realiza manualmente, siga la división en zonas utilizada para un puente FibreBridge 6500N o FibreBridge 7500N o 7600N que utilice un puerto FC (FC1 o FC2). En esta situación, se agrega un puerto de iniciador en lugar de dos a cada miembro de la zona por estructura.

Puede cambiar la división en zonas o realizar una actualización de FibreBridge 6500 a FibreBridge 7500 con el procedimiento _Cambio en caliente de un puente FibreBridge 6500N con un puente FibreBridge 7500N o 7600N del link:../maintain/index.html["Mantener los componentes de MetroCluster"].

En la siguiente tabla se muestran las asignaciones de puertos para los switches de FC cuando se utiliza ONTAP 9.1 y versiones posteriores.

|===


4+| Configuraciones que utilizan puentes FibreBridge 6500N o FibreBridge 7500N o 7600N utilizando sólo un puerto FC (FC1 o FC2) 


4+| MetroCluster 1 o Grupo DR 1 


.2+| Componente .2+| Puerto 2+| Modelos de switch Brocade 6505, 6510, 6520, 7840, G620, G610 y DCX 8510-8 


| Se conecta al switch FC... | Se conecta al puerto del switch... 


 a| 
controller_x_1
 a| 
Puerto a FC-VI
 a| 
1
 a| 
0



 a| 
Puerto FC-VI b
 a| 
2
 a| 
0



 a| 
Puerto FC-VI c
 a| 
1
 a| 
1



 a| 
Puerto d de FC-VI
 a| 
2
 a| 
1



 a| 
Puerto HBA a
 a| 
1
 a| 
2



 a| 
Puerto HBA b
 a| 
2
 a| 
2



 a| 
Puerto HBA c
 a| 
-
 a| 
-



 a| 
Puerto HBA d
 a| 
-
 a| 
-



 a| 
Pila 1
 a| 
bridge_x_1a
 a| 
1
 a| 
8



 a| 
bridge_x_1b
 a| 
2
 a| 
8



 a| 
Apilar y
 a| 
bridge_x_ya
 a| 
1
 a| 
11



 a| 
bridge_x_yb
 a| 
2
 a| 
11

|===
En la siguiente tabla se muestran las asignaciones de puertos para los switches de FC cuando se utiliza ONTAP 9.0.

|===


4+| Configuración de dos nodos de MetroCluster 


.2+| Componente .2+| Puerto 2+| Brocade 6505, 6510 o DCX 8510-8 


| FC_switch_x_1 | FC_switch_x_2 


 a| 
controller_x_1
 a| 
Puerto a FC-VI
 a| 
0
 a| 
-



 a| 
Puerto FC-VI b
 a| 
-
 a| 
0



 a| 
Puerto HBA a
 a| 
1
 a| 
-



 a| 
Puerto HBA b
 a| 
-
 a| 
1



 a| 
Puerto HBA c
 a| 
2
 a| 
-



 a| 
Puerto HBA d
 a| 
-
 a| 
2

|===