---
permalink: maintain/concept_migrating_root_volumes_to_a_new_destination.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, volumes, new, destination 
summary: Es posible que deba mover volúmenes raíz a otro agregado raíz dentro de una configuración MetroCluster de dos o cuatro nodos. 
---
= Cuándo migrar volúmenes raíz a un nuevo destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba mover volúmenes raíz a otro agregado raíz dentro de una configuración MetroCluster de dos o cuatro nodos.



== La migración de volúmenes raíz dentro de una configuración MetroCluster de dos nodos

Para migrar volúmenes raíz a un nuevo agregado raíz dentro de una configuración MetroCluster de dos nodos, debería hacer referencia a https://["Cómo mover mroot a un nuevo agregado raíz en un Clustered MetroCluster de 2 nodos con conmutación de sitios"]. Este procedimiento muestra cómo migrar sin interrupciones los volúmenes raíz durante una operación de conmutación de MetroCluster. Este procedimiento es ligeramente diferente al procedimiento utilizado en una configuración de cuatro nodos.



== Migrar volúmenes raíz dentro de una configuración MetroCluster de cuatro nodos

Para migrar volúmenes raíz a un nuevo agregado raíz dentro de una configuración MetroCluster de cuatro nodos, puede usar la http://["migración-raíz del nodo del sistema"] command mientras cumple con los siguientes requisitos.

* Puede utilizar la migración-root del nodo del sistema para mover agregados raíz dentro de una configuración MetroCluster de cuatro nodos.
* Deben duplicarse todos los agregados raíz.
* Puede añadir nuevas bandejas en ambos sitios con unidades más pequeñas para alojar el agregado raíz.
* Debe comprobar los límites de unidades que admite la plataforma antes de conectar unidades nuevas.
+
https://["Hardware Universe de NetApp"]

* Si mueve el agregado raíz a unidades más pequeñas, debe tener en cuenta el tamaño mínimo de volumen raíz de la plataforma para garantizar que se guarden todos los archivos de núcleo.



NOTE: El procedimiento de cuatro nodos también se puede aplicar a una configuración de ocho nodos.
