---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: Debe asegurarse de seleccionar el procedimiento correcto al realizar tareas de mantenimiento del hardware de MetroCluster. 
---
= Obtenga información sobre el mantenimiento de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda a preparar las tareas de mantenimiento de MetroCluster y a elegir el procedimiento de mantenimiento correcto para su configuración.



== Prepárese para las tareas de mantenimiento

Revise la información de link:enable-console-logging-before-maintenance.html["Prepárese para el mantenimiento de MetroCluster"] antes de realizar cualquier procedimiento de mantenimiento.


NOTE: Debe habilitar el registro de la consola y quitar la supervisión de ONTAP Mediator o tiebreaker antes de realizar tareas de mantenimiento.



== Procedimientos de mantenimiento para diferentes tipos de configuraciones de MetroCluster

* Si tiene una configuración de IP de MetroCluster, revise los procedimientos que se indican en link:task-modify-ip-netmask-properties.html["Procedimientos de mantenimiento de las configuraciones IP de MetroCluster"].
* Si tiene una configuración de MetroCluster FC, revise los procedimientos en link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["Procedimientos de mantenimiento de configuraciones MetroCluster FC"].
* Si no encuentra el procedimiento en la sección específica de su configuración, revise los procedimientos en link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["Procedimientos de mantenimiento para todas las configuraciones MetroCluster"].




== Todos los demás procedimientos de mantenimiento

La siguiente tabla proporciona enlaces a procedimientos relacionados con el mantenimiento de MetroCluster que no se encuentran en las tres secciones enumeradas anteriormente:

|===


| Componente | Tipo MetroCluster (FC o IP) | Tarea | Procedimiento 


 a| 
Software ONTAP
 a| 
Ambas
 a| 
Actualización de software ONTAP
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["Actualización, reversión o degradación"^]



 a| 
Módulo del controlador
 a| 
Ambas
 a| 
Sustitución de FRU (incluidos módulos de controladora, tarjetas PCIe, tarjeta FC-VI, etc.)


NOTE: No es posible mover un módulo de controladora de almacenamiento o una tarjeta NVRAM entre los sistemas de almacenamiento MetroCluster.
 a| 
https://docs.netapp.com/platstor/index.jsp["Documentación de los sistemas de hardware de ONTAP"^]



 a| 
Renovación y ampliación
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["Actualización y ampliación de MetroCluster"]



 a| 
Transición de la conectividad FC a IP
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Transición de FC de MetroCluster a IP de MetroCluster"]



 a| 
Bandeja de unidades
 a| 
FC
 a| 
El resto de procedimientos de mantenimiento de bandejas. Se pueden utilizar los procedimientos estándar.
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Mantener bandejas de discos DS460C DS212C y DS212C"^]



 a| 
IP
 a| 
Todos los procedimientos de mantenimiento de bandejas. Se pueden utilizar los procedimientos estándar.

Si se añaden bandejas para un agregado no reflejado, consulte http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["Consideraciones que tener en cuenta al utilizar agregados no reflejados"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Mantener bandejas de discos DS460C DS212C y DS212C"^]



 a| 
Ambas
 a| 
Adición en caliente de bandejas IOM12 a una pila de bandejas IOM6
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Bandejas añadidas en caliente con módulos IOM12 a una pila de bandejas con módulos IOM6"^]

|===