---
permalink: maintain/reference_fb_replace_a_power_supply.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, replacing, failed, power, supply, module 
summary: Cuando se produce un cambio en el estado de un módulo de fuente de alimentación al puente, puede extraer e instalar el módulo de fuente de alimentación. 
---
= Sustitución en caliente de un módulo de fuente de alimentación con fallos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se produce un cambio en el estado de un módulo de fuente de alimentación al puente, puede extraer e instalar el módulo de fuente de alimentación.

Puede ver el cambio de estado de un módulo de fuente de alimentación a través de los LED del puente. También puede ver el estado de los módulos de fuente de alimentación a través de la GUI de ExpressNAV y la CLI de puente, a través del puerto serie o a través de Telnet.

* Este procedimiento es NDO (no disruptivo) y tarda aproximadamente 15 minutos en completarse.
* Necesita la contraseña de administrador y el acceso a un servidor FTP o SCP.



NOTE: El _ATTO FiberBridge Installation and Operation Manual_ de su puente de modelos contiene más información acerca de las interfaces de administración.

Puede acceder a este y otros contenidos del sitio web de ATTO utilizando el enlace proporcionado en la página de descripción de ATTO FibreBridge.
