---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: Es posible que necesite actualizar un archivo RCF en un conmutador MetroCluster IP. Por ejemplo, una actualización de ONTAP o de firmware del switch requieren un nuevo archivo RCF. 
---
= Actualice los archivos RCF en switches MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que necesite actualizar un archivo RCF en un conmutador MetroCluster IP. Por ejemplo, si la versión del archivo RCF que ejecuta en los switches no es compatible con la versión de ONTAP, la versión del firmware del switch o ambos.



== Compruebe que el archivo RCF es compatible

Si va a cambiar la versión de ONTAP o la versión de firmware del switch, debe comprobar que tiene un archivo RCF compatible con esa versión. Si utiliza el generador RCF, se generará el archivo RCF correcto.

.Pasos
. Utilice los siguientes comandos de los conmutadores para comprobar la versión del archivo RCF:
+
[cols="30,70"]
|===


| Desde este switch... | Emita este comando... 


 a| 
Switch Broadcom
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Switch Cisco
 a| 
`IP_switch_A_1# show banner motd`

|===
+
Para cualquiera de los dos conmutadores, busque la línea en la salida que indica la versión del archivo RCF. Por ejemplo, la siguiente salida procede de un conmutador Cisco, que indica que la versión del archivo RCF es "'v1.80'".

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Para comprobar qué archivos son compatibles con una versión, conmutador y plataforma ONTAP específica, utilice el RcfFileGenerator. Si puede generar el archivo RCF para la configuración que tiene o a la que desea actualizar, se admite.
. Para verificar que el firmware del switch es compatible, consulte lo siguiente:
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^]






== Actualice los archivos RCF

Si va a instalar un nuevo firmware de conmutador, debe instalar el firmware del conmutador antes de actualizar el archivo RCF.

.Acerca de esta tarea
* Este procedimiento interrumpe el tráfico del conmutador donde se actualiza el archivo RCF. El tráfico se reanudará una vez que se aplique el nuevo archivo RCF.
* Realice los pasos en un conmutador a la vez, en el siguiente orden: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.


.Pasos
. Compruebe el estado de la configuración.
+
.. Compruebe que los componentes de MetroCluster están en buen estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
La operación se ejecuta en segundo plano.

+
.. Después del `metrocluster check run` la operación finaliza, se ejecuta `metrocluster check show` para ver los resultados.
+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Comprobar el estado de la operación de comprobación de MetroCluster en ejecución:
+
`metrocluster operation history show -job-id 38`

.. Compruebe que no hay alertas de estado:
+
`system health alert show`



. Prepare los switches IP para la aplicación de los nuevos archivos RCF.
+
Siga los pasos para su proveedor de switches:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Restablezca el conmutador IP Broadcom a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Restablezca el conmutador IP de Cisco a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Restablece el switch NVIDIA IP SN2100 a los valores predeterminados de fábrica"]


. Descargue e instale el archivo IP RCF, según el proveedor del switch.
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Descargue e instale los archivos Broadcom IP RCF"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Descargue e instale los archivos Cisco IP RCF"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Descargue e instale los archivos NVIDIA IP RCF"]
+

NOTE: Si tiene una configuración de red L2 compartida o L3, es posible que deba ajustar los puertos ISL en los switches intermedio/cliente. El modo de puerto de switch puede cambiar del modo de acceso al modo de "tronco". Sólo continúe con la actualización del segundo par de conmutadores (A_2, B_2) si la conectividad de red entre los conmutadores A_1 y B_1 está totalmente operativa y la red está en buen estado.




