---
permalink: maintain/task_online_or_offline_the_mcc_ip_interface.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, online, offline, ip, interface port 
summary: Al realizar tareas de mantenimiento es posible que deba desconectar el puerto de la interfaz IP de MetroCluster. 
---
= Puertos de interfaz IP de MetroCluster en línea u fuera de línea
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando realiza tareas de mantenimiento, es posible que deba desconectar u conectar un puerto de interfaz IP de MetroCluster.

.Acerca de esta tarea
link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.

.Pasos
Puede usar los siguientes pasos para conectar un puerto de interfaz IP de MetroCluster o desconectarlo.

. Configure el nivel de privilegio en Advanced.
+
[source, cli]
----
set -privilege advanced
----
+
*Ejemplo de salida*

+
[listing]
----
Cluster A_1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y
----
. Desconecte el puerto de la interfaz IP de MetroCluster.
+
[source, cli]
----
system ha interconnect link off -node <node_name> -link <link_num, 0 or 1>
----
+
*Ejemplo de salida*

+
[listing]
----
Cluster_A1::*> system ha interconnect link off -node node-a1 -link 0
----
+
.. Compruebe que la interfaz de IP de MetroCluster está sin conexión.
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*Ejemplo de salida*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  disabled  down              4          3  false
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----


. Conecte el puerto de la interfaz IP de MetroCluster.
+
[source, cli]
----
system ha interconnect link on -node <node_name> -link <link_num, 0 or 1>
----
+
*Ejemplo de salida*

+
[listing]
----
Cluster_A1::*> system ha interconnect link on -node node-a1 -link 0
----
+
.. Compruebe que el puerto de la interfaz IP de MetroCluster está en línea.
+
[source, cli]
----
Cluster_A1::*> system ha interconnect port show
----
+
*Ejemplo de salida*

+
[listing]
----
Cluster_A1::*> system ha interconnect port show
                               Physical  Link
                Link           Layer     Layer      Physical   Physical  Active
Node            Monitor  Port  State     State       Link Up  Link Down  Link
--------------  -------  ----  --------  ---------  --------  ---------  ------
node-a1        off
                            0  linkup    active            5          3  true
                            1  linkup    active            4          2  true
node-a2        off
                            0  linkup    active            4          2  true
                            1  linkup    active            4          2  true
2 entries were displayed.
----



