---
permalink: maintain/task_rename_a_cisco_ip_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, rename, cisco, ip, switch 
summary: Es posible que deba cambiar el nombre de un switch IP de Cisco a fin de proporcionar nomenclatura coherente en toda la configuración. 
---
= Cambiar el nombre de un switch IP de Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba cambiar el nombre de un switch IP de Cisco a fin de proporcionar nomenclatura coherente en toda la configuración.

En los ejemplos de esta tarea, el nombre del conmutador se cambia de `myswitch` para `IP_switch_A_1`.

. Entre al modo de configuración global:
+
`*configure terminal*`

+
En el ejemplo siguiente se muestra el indicador del modo de configuración. Ambas indicaciones muestran el nombre del conmutador de `myswitch`.

+
[listing]
----
myswitch# configure terminal
myswitch(config)#
----
. Cambie el nombre del conmutador:
+
`*switchname new-switch-name*`

+
Si va a cambiar el nombre de ambos switches de la estructura, utilice el mismo comando de cada switch.

+
El símbolo del sistema de la CLI cambia para reflejar el nuevo nombre:

+
[listing]
----
myswitch(config)# switchname IP_switch_A_1
IP_switch_A_1(config)#
----
. Salir del modo de configuración:
+
`*exit*`

+
Se muestra el indicador del interruptor de nivel superior:

+
[listing]
----
IP_switch_A_1(config)# exit
IP_switch_A_1#
----
. Copie la configuración actual en ejecución en el archivo de configuración de inicio:
+
`*copy running-config startup-config*`

. Compruebe que el cambio de nombre del switch sea visible en el símbolo del sistema del clúster ONTAP.
+
Tenga en cuenta que se muestra el nuevo nombre del conmutador y el nombre del conmutador antiguo (`myswitch`) no aparece.

+
.. Entre en el modo de privilegios avanzado, pulse `*y*` cuando se le solicite: +
`*set -privilege advanced*`
.. Mostrar los dispositivos conectados: +
`*network device-discovery show*`
.. Vuelva al modo de privilegio admin: +
`*set -privilege admin*`
+
El siguiente ejemplo muestra que el conmutador aparece con el nuevo nombre, `IP_switch_A_1`:

+
[listing]
----
cluster_A::storage show> set advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster_A::storage show*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device                    Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node_A_2/cdp
            e0M    LF01-410J53.mycompany.com(SAL18516DZY)
                                             Ethernet125/1/28  N9K-C9372PX
            e1a    IP_switch_A_1(FOC21211RBU)
                                             Ethernet1/2       N3K-C3232C
            e1b    IP_switch_A_1(FOC21211RBU)
                                             Ethernet1/10      N3K-C3232C
.
.
.                                             Ethernet1/18      N9K-C9372PX
node_A_1/cdp
            e0M    LF01-410J53.mycompany.com(SAL18516DZY)
                                             Ethernet125/1/26  N9K-C9372PX
            e0a    IP_switch_A_2(FOC21211RB5)
                                             Ethernet1/1       N3K-C3232C
            e0b    IP_switch_A_2(FOC21211RB5)
                                             Ethernet1/9       N3K-C3232C
            e1a    IP_switch_A_1(FOC21211RBU)
.
.
.
16 entries were displayed.
----



