---
permalink: maintain/task_change_an_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, fc, switch 
summary: 'Es posible que deba cambiar el proveedor de un switch FC (de Cisco a Brocade o viceversa), cambiar el modelo de switch o ambos.' 
---
= Cambie el proveedor o modelo de switches FC
:allow-uri-read: 


[role="lead"]
Es posible que deba cambiar el proveedor de switches FC de Cisco a Brocade o viceversa, cambiar el modelo de switch o cambiar ambos.

.Acerca de esta tarea
* Este procedimiento se aplica cuando utiliza switches validados NetApp.
* Debe realizar los pasos de este procedimiento en una estructura a la vez, para ambas estructuras en la configuración.


.Pasos
. [[STEP_1,Paso 1]]Compruebe el estado de la configuración.
+
.. Compruebe que la MetroCluster esté configurada y en modo normal de cada clúster: `*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Compruebe que el mirroring está habilitado en cada nodo: `*metrocluster node show*`
+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Compruebe que los componentes de MetroCluster sean los mismos en buen estado: `*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Compruebe que no hay alertas de estado: `*system health alert show*`


. Configure los nuevos switches antes de la instalación.
+
Siga los pasos indicados en link:../install-fc/concept-configure-fc-switches.html["Configure los switches FC"].

. Desconecte las conexiones de los interruptores antiguos quitando las conexiones en el siguiente orden:
+
.. Desconecte las interfaces MetroCluster FC y FCVI.
.. Desconecte los puentes ATTO FibreBridge.
.. Desconecte los ISL de MetroCluster.


. Apague los interruptores antiguos, retire los cables y sustituya físicamente los interruptores antiguos por el interruptor nuevo.
. Conecte los cables de los interruptores en el siguiente orden:
+
Debe seguir los pasos indicados en link:../install-fc/task_configure_the_mcc_hardware_components_fabric.html["Cableado de una configuración MetroCluster estructural"].

+
.. Conecte los cables ISLs al sitio remoto.
.. Conecte los puentes ATTO FibreBridge.
.. Conecte los cables de las interfaces MetroCluster FC y FCVI.


. Encienda los interruptores.
. Repita para comprobar que la configuración de MetroCluster sea correcta <<Paso 1>>.
. Repita los pasos 1 a 7 para el segundo tejido de la configuración.

