---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Actualización del firmware en switches MetroCluster IP. 
---
= Actualizar el firmware en switches MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba actualizar el firmware en un switch MetroCluster IP.



== Compruebe que el RCF es compatible

Al cambiar la versión de ONTAP o la versión de firmware del switch, debe verificar que tiene un archivo de configuración de referencia (RCF) compatible con esa versión. Si utiliza link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^]la herramienta, se genera el RCF correcto para la configuración.

.Pasos
. Utilice los siguientes comandos de los switches para verificar la versión de RCF:
+
[cols="30,70"]
|===


| Desde este switch... | Emita este comando... 


 a| 
Switch Broadcom
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Switch Cisco
 a| 
`IP_switch_A_1# show banner motd`



 a| 
Switch NVIDIA SN2100
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
Localice la línea en el resultado del comando que indica la versión de RCF. Por ejemplo, la siguiente salida de un conmutador Cisco indica que la versión RCF es «`v1,80`».

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Para comprobar qué archivos son compatibles con una versión, conmutador y plataforma de ONTAP específica, utilice el link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator para MetroCluster IP"^]. Si puede generar el RCF para la configuración existente o a la que desea actualizar, es compatible.
. Para verificar que el firmware del switch es compatible, consulte lo siguiente:
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^]






== Actualice el firmware del switch

.Acerca de esta tarea
Debe repetir esta tarea en cada uno de los conmutadores sucesivamente.

link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.

[[step_1_fw_upgrade]]
.Pasos
. Compruebe el estado de la configuración.
+
.. Compruebe que la MetroCluster esté configurada y en modo normal de cada clúster:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Compruebe que el mirroring está habilitado en cada nodo:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Compruebe que los componentes de MetroCluster sean los mismos en buen estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
La operación se ejecuta en segundo plano.

.. Después del `metrocluster check run` la operación finaliza, ejecute:
+
`metrocluster check show`

+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Compruebe que no hay alertas de estado:
+
`system health alert show`



. Instale el software en el primer interruptor.
+

NOTE: Debe instalar el software del conmutador en los conmutadores en el siguiente orden: Switch_A_1, switch_B_1, Switch_A_2, switch_B_2.

+
Siga los pasos para instalar el software de switch en el tema correspondiente dependiendo de si el tipo de switch es Broadcom, Cisco o NVIDIA:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Descargue e instale el software EFOS del conmutador Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Descargue e instale el software Cisco Switch NX-OS"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Descargue e instale el software NVIDIA SN2100 switch Cumulus"]


. Repita el paso anterior con cada uno de los conmutadores.
. Repetición <<step_1_fw_upgrade,Paso 1>> para comprobar el estado de la configuración.

