---
permalink: maintain/task_add_lsls_to_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, isl, cisco, switch 
summary: Es posible que deba agregar ISL a un switch si va a agregar o actualizar hardware, como controladoras adicionales o más rápidas, o switches más rápidos. 
---
= Añadiendo lSLs a un switch de Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba agregar ISL a un switch si va a agregar o actualizar hardware, como controladoras adicionales o más rápidas, o switches más rápidos.

.Acerca de esta tarea
* Complete todos los pasos en ambos switches para garantizar la conectividad ISL.
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.


.Pasos
. Deshabilite los puertos ISL de los ISL que se van a añadir en ambos switches de la estructura:
+
`*FC_switch_A_1#config t*`

+
Introduzca los comandos de configuración, uno por línea. Finalice con CTRL-Z después de introducir todos los comandos de configuración.

+
[listing]
----

	FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Inserte los SFP en los puertos que va a añadir como puertos ISL y cablee según lo establecido en la _Guía de instalación y configuración_.
+
Asegúrese de que estos puertos aparecen en la _Guía de instalación y configuración_ del conmutador al que los está agregando.

. Configure los puertos ISL de acuerdo con _Installation and Configuration Guide_.
. Habilite todos los puertos ISL (si no está habilitado) en ambos switches de la estructura:
+
`*FC_switch_A_1# config t*`

+
Introduzca los comandos de configuración, uno por línea. Terminar con CTRL-Z.

+
[listing]
----

 FC_switch_A_1# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Compruebe que se han establecido ISL entre los dos switches:
+
`*show topology isl*`

. Repita el procedimiento en la segunda tela:
+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

