---
permalink: maintain/task_add_shelves_using_shared_storage.html 
sidebar: sidebar 
keywords: metrocluster, maintain, shelf, shelves, add, ns224, 
summary: Es posible que tenga que añadir bandejas NS224 a un MetroCluster mediante switches de MetroCluster de almacenamiento compartido. 
---
= Adición de bandejas a una IP de MetroCluster mediante switches de MetroCluster de almacenamiento compartido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que tenga que añadir bandejas NS224 a un MetroCluster mediante switches de MetroCluster de almacenamiento compartido.

A partir de ONTAP 9.10.1, puede añadir bandejas NS224 de un MetroCluster utilizando los switches de almacenamiento compartido / MetroCluster. Es posible añadir más de una bandeja a la vez.

.Antes de empezar
* Los nodos deben ejecutar ONTAP 9.9.1 o una versión posterior.
* Todas las bandejas NS224 conectadas actualmente deben estar conectadas a los mismos switches que MetroCluster (configuración de switch de almacenamiento compartido / MetroCluster).
* Este procedimiento no se puede utilizar para convertir una configuración con bandejas NS224 conectadas directamente o con bandejas NS224 conectadas a switches Ethernet dedicados a una configuración mediante switches de almacenamiento compartido/MetroCluster.
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.




== Envío de un mensaje de AutoSupport personalizado antes del mantenimiento

Antes de realizar el mantenimiento, debe emitir un mensaje de AutoSupport para notificar al soporte técnico de NetApp que se está realizando el mantenimiento. Al informar al soporte técnico de que el mantenimiento está en marcha, se evita que abran un caso basándose en que se ha producido una interrupción.

.Acerca de esta tarea
Esta tarea debe realizarse en cada sitio MetroCluster.

.Pasos
. Para evitar la generación automática de casos de soporte, envíe un mensaje de AutoSupport para indicar que la actualización está en curso.
+
.. Emita el siguiente comando:
+
`system node autosupport invoke -node * -type all -message "Maint=10h Adding or Removing NS224 shelves"_`

+
En este ejemplo se especifica una ventana de mantenimiento de 10 horas. Es posible que desee permitir tiempo adicional, dependiendo de su plan.

+
Si el mantenimiento se completa antes de que haya transcurrido el tiempo, puede invocar un mensaje de AutoSupport que indique el final del período de mantenimiento:

+
`system node autosupport invoke -node * -type all -message MAINT=end`

.. Repita el comando en el clúster de partners.






== Comprobación del estado de la configuración de MetroCluster

Debe verificar el estado y la conectividad de la configuración de MetroCluster antes de llevar a cabo la transición.

.Pasos
. Compruebe el funcionamiento de la configuración de MetroCluster en ONTAP:
+
.. Compruebe si el sistema es multivía:
+
`node run -node _node-name_ sysconfig -a`

.. Compruebe si hay alertas de estado en ambos clústeres:
+
`system health alert show`

.. Confirme la configuración del MetroCluster y que el modo operativo es normal:
+
`metrocluster show`

.. Realizar una comprobación de MetroCluster:
+
`metrocluster check run`

.. Mostrar los resultados de la comprobación de MetroCluster:
+
`metrocluster check show`

.. Ejecute Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Descargas de NetApp: Config Advisor"]

.. Después de ejecutar Config Advisor, revise el resultado de la herramienta y siga las recomendaciones del resultado para solucionar los problemas detectados.


. Compruebe que el clúster esté en buen estado:
+
`cluster show -vserver Cluster`

+
[listing]
----
cluster_A::> cluster show -vserver Cluster
Node           Health  Eligibility   Epsilon
-------------- ------  -----------   -------
node_A_1    true    true          false
node_A_2    true    true          false

cluster_A::>
----
. Compruebe que todos los puertos del clúster estén activos:
+
`network port show -ipspace cluster`

+
[listing]
----
cluster_A::> network port show -ipspace cluster

Node: node_A_1-old

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2-old

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

cluster_A::>
----
. Compruebe que todas las LIF del clúster estén en funcionamiento:
+
`network interface show -vserver Cluster`

+
Cada LIF de clúster debería mostrar el valor true para es Home y tener un administrador de estado/Oper de up/up

+
[listing]
----
cluster_A::> network interface show -vserver cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1-old_clus1
                       up/up      169.254.209.69/16  node_A_1   e0a     true
            node_A_1-old_clus2
                       up/up      169.254.49.125/16  node_A_1   e0b     true
            node_A_2-old_clus1
                       up/up      169.254.47.194/16  node_A_2   e0a     true
            node_A_2-old_clus2
                       up/up      169.254.19.183/16  node_A_2   e0b     true

4 entries were displayed.

cluster_A::>
----
. Compruebe que la reversión automática está habilitada en todas las LIF del clúster:
+
`network interface show -vserver Cluster -fields auto-revert`

+
[listing]
----
cluster_A::> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
           node_A_1-old_clus1
                        true
           node_A_1-old_clus2
                        true
           node_A_2-old_clus1
                        true
           node_A_2-old_clus2
                        true

    4 entries were displayed.

cluster_A::>
----




== Aplicar el nuevo archivo RCF a los conmutadores


NOTE: Si el conmutador ya está configurado correctamente, puede omitir estas secciones siguientes y pasar directamente a. <<Configuración del cifrado MACsec en switches Cisco 9336C>>, si corresponde o a. <<Conexión de la nueva bandeja NS224>>.

* Es necesario cambiar la configuración del switch para añadir bandejas.
* Debe revisar los detalles del cableado en link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_3232c_9336c.html#cabling-a-aff-a800-to-a-cisco-3232c-or-cisco-9336c-switch["Asignaciones de puertos de la plataforma"^].
* Debe utilizar la herramienta **RcfFileGenerator** para crear el archivo RCF para su configuración. La link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^] también ofrece información general sobre el cableado por puerto para cada switch. Asegúrese de elegir la cantidad correcta de bandejas. Existen archivos adicionales creados junto con el archivo RCF que proporcionan un diseño detallado del cableado que se ajusta a sus opciones específicas. Use esta información general sobre el cableado para verificar el cableado cuando cablee las nuevas bandejas.




=== Actualización de archivos RCF en switches MetroCluster IP

Si va a instalar un nuevo firmware de conmutador, debe instalar el firmware del conmutador antes de actualizar el archivo RCF.

Este procedimiento interrumpe el tráfico del conmutador donde se actualiza el archivo RCF. El tráfico se reanudará una vez que se aplique el nuevo archivo RCF.

.Pasos
. Compruebe el estado de la configuración.
+
.. Compruebe que los componentes de MetroCluster están en buen estado:
+
`*metrocluster check run*`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
La operación se ejecuta en segundo plano.

+
.. Después del `metrocluster check run` la operación finaliza, se ejecuta `metrocluster check show` para ver los resultados.
+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. Para comprobar el estado de la operación de comprobación de MetroCluster en ejecución, utilice el comando: +
`*metrocluster operation history show -job-id 38*`
.. Compruebe que no hay alertas de estado: +
`*system health alert show*`


. Prepare los switches IP para la aplicación de los nuevos archivos RCF.




=== Restablecer los valores predeterminados de fábrica del conmutador IP de Cisco

Antes de instalar una nueva versión de software y RCF, debe borrar la configuración del conmutador Cisco y realizar la configuración básica.

Debe repetir estos pasos en cada uno de los switches IP de la configuración de IP de MetroCluster.

. Restablezca el interruptor a los valores predeterminados de fábrica:
+
.. Borrar la configuración existente: `write erase`
.. Vuelva a cargar el software del conmutador: `reload`
+
El sistema se reinicia e introduce el asistente de configuración. Durante el arranque, si recibe el aviso Anular provisión automática y continuar con la configuración normal?(yes/no)[n], debe responder `yes` para continuar.

.. En el asistente de configuración, introduzca los ajustes básicos del switch:
+
*** Contraseña de administrador
*** Nombre del switch
*** Configuración de gestión fuera de banda
*** Pasarela predeterminada
*** Servicio SSH (RSA) después de completar el asistente de configuración, el switch se reinicia.


.. Cuando se le solicite, introduzca el nombre de usuario y la contraseña para iniciar sesión en el conmutador.
+
El ejemplo siguiente muestra las indicaciones y respuestas del sistema al configurar el conmutador. Los soportes angulares (`<<<`) muestra dónde se introduce la información.

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

Enter the password for "admin": password
Confirm the password for "admin": password
---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of the system. Setup configures only enough connectivity for management of the system.

Please register Cisco Nexus3000 Family devices promptly with your supplier. Failure to register may affect response times for initial service calls. Nexus3000 devices must be registered to receive entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime to skip the remaining dialogs.
----
+
Debe introducir información básica en el siguiente conjunto de avisos, incluidos el nombre del switch, la dirección de administración y la puerta de enlace, y seleccionar SSH con RSA.

+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
   Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
   Number of rsa key bits <1024-2048> [1024]:
 Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
 Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
El conjunto final de avisos completa la configuración:

+
[listing]
----
The following configuration will be applied:
 password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
 no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. Guarde la configuración:
+
[listing]
----
IP_switch-A-1# copy running-config startup-config
----
. Reinicie el conmutador y espere a que se vuelva a cargar:
+
[listing]
----
IP_switch-A-1# reload
----
. Repita los pasos anteriores en los otros tres switches de la configuración IP de MetroCluster.




=== Descargar e instalar el software del switch Cisco NX-OS

Debe descargar el archivo del sistema operativo del conmutador y el archivo RCF en cada switch de la configuración IP de MetroCluster.

Esta tarea requiere software de transferencia de archivos, como FTP, TFTP, SFTP o SCP para copiar los archivos en los switches.

Estos pasos deben repetirse en cada switch IP de la configuración de IP de MetroCluster.

Debe utilizar la versión de software del switch compatible.

link:https://hwu.netapp.com["Hardware Universe de NetApp"^]

. Descargue el archivo de software NX-OS admitido.
+
link:https://software.cisco.com/download/home["Descarga de software de Cisco"^]

. Copie el software del conmutador en el conmutador: `+copy sftp://root@server-ip-address/tftpboot/NX-OS-file-name bootflash: vrf management+`
+
En este ejemplo, el archivo nxos.7.0.3.I4.6.bin se copia desde el servidor SFTP 10.10.99.99 en el bootflash local:

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. Verifique en cada switch que los archivos NX-OS del switch estén presentes en el directorio bootflash de cada switch: `dir bootflash:`
+
El ejemplo siguiente muestra que los archivos están presentes en IP_switch_A_1:

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Instale el software del conmutador: `install all nxos bootflash:nxos.version-number.bin`
+
El conmutador se volverá a cargar (reiniciar) automáticamente después de instalar el software del conmutador.

+
En el ejemplo siguiente se muestra la instalación del software en IP_switch_A_1:

+
[listing]
----
IP_switch_A_1# install all nxos bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS       [####################] 100%            -- SUCCESS

Performing module support checks.            [####################] 100%            -- SUCCESS

Notifying services about system upgrade.     [####################] 100%            -- SUCCESS



Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless



Images will be upgraded according to following table:
Module       Image   Running-Version(pri:alt)         New-Version   Upg-Required
------  ----------   ------------------------  ------------------   ------------
     1        nxos                7.0(3)I4(1)         7.0(3)I4(6)   yes
     1        bios         v04.24(04/21/2016)  v04.24(04/21/2016)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] y


Install is in progress, please wait.

Performing runtime checks.         [####################] 100%    -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
IP_switch_A_1#
----
. Espere a que el conmutador se vuelva a cargar y, a continuación, inicie sesión en el conmutador.
+
Cuando el conmutador haya reiniciado, aparecerá el mensaje de inicio de sesión:

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. Compruebe que se ha instalado el software del conmutador: `show version`
+
El siguiente ejemplo muestra el resultado:

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. Repita estos pasos en los tres switches IP restantes de la configuración IP de MetroCluster.




== Configuración del cifrado MACsec en switches Cisco 9336C

Si lo desea, puede configurar el cifrado MACsec en los puertos ISL WAN que se ejecutan entre los sitios. Debe configurar MACsec después de aplicar el archivo RCF correcto.


NOTE: El cifrado MACsec sólo se puede aplicar a los puertos WAN ISL.



=== Requisitos de licencia para MACsec

MACsec requiere una licencia de seguridad. Para obtener una explicación completa del esquema de licencias de Cisco NX-OS y de cómo obtener y solicitar licencias, consulte https://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/licensing/guide/b_Cisco_NX-OS_Licensing_Guide/b_Cisco_NX-OS_Licensing_Guide_chapter_01.html["Guía de licencias de Cisco NX-OS"]



=== Habilitar ISL WAN de cifrado Cisco MACsec en configuraciones IP de MetroCluster

Puede habilitar el cifrado MACsec para los switches Cisco 9336C en los ISL WAN en una configuración IP MetroCluster.

. Entre en el modo de configuración global: `configure terminal`
+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. Active MACsec y MKA en el dispositivo: `feature macsec`
+
[listing]
----
IP_switch_A_1(config)# feature macsec
----
. Copie la configuración en ejecución en la configuración de inicio: `copy running-config startup-config`
+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----




=== Desactivación del cifrado Cisco MACsec

Es posible que deba deshabilitar el cifrado MACsec para los switches Cisco 9336C en los ISL WAN en una configuración IP de MetroCluster.


NOTE: Si desactiva el cifrado, también debe eliminar las claves.

. Entre en el modo de configuración global: `configure terminal`
+
[listing]
----
IP_switch_A_1# configure terminal
IP_switch_A_1(config)#
----
. Desactive la configuración de MACsec en el dispositivo: `macsec shutdown`
+
[listing]
----
IP_switch_A_1(config)# macsec shutdown
----
+

NOTE: Si selecciona la opción no, se restaurará la función MACsec.

. Seleccione la interfaz que ya ha configurado con MACsec.
+
Puede especificar el tipo de interfaz y la identidad. En el caso de un puerto Ethernet, utilice el puerto o la ranura ethernet.

+
[listing]
----
IP_switch_A_1(config)# interface ethernet 1/15
switch(config-if)#
----
. Elimine la cadena de claves, la directiva y la cadena de claves de reserva configuradas en la interfaz para eliminar la configuración de MACsec: `no macsec keychain keychain-name policy policy-name fallback-keychain keychain-name`
+
[listing]
----
IP_switch_A_1(config-if)# no macsec keychain kc2 policy abc fallback-keychain fb_kc2
----
. Repita los pasos 3 y 4 en todas las interfaces en las que esté configurado MACsec.
. Copie la configuración en ejecución en la configuración de inicio: `copy running-config startup-config`
+
[listing]
----
IP_switch_A_1(config)# copy running-config startup-config
----




=== Configuración de una cadena de claves y claves MACsec

Para obtener más información sobre la configuración de una cadena de claves MACsec, consulte la documentación de Cisco del conmutador.



== Conexión de la nueva bandeja NS224

.Pasos
. Instale el kit de montaje de raíl incluido con la bandeja mediante el folleto de instalación incluido en la caja del kit.
. Utilice el folleto de instalación para instalar y proteger la bandeja en los soportes de soporte, así como en el rack o armario.
. Conecte los cables de alimentación a la bandeja, fíjelos con el retenedor del cable de alimentación y, a continuación, conecte los cables de alimentación a distintas fuentes de alimentación para obtener flexibilidad.
+
Una bandeja se enciende cuando está conectada a una fuente de alimentación; no tiene interruptores de alimentación. Cuando funciona correctamente, el LED bicolor de una fuente de alimentación se ilumina en verde.

. Establezca el ID de bandeja en un número único dentro de la pareja de alta disponibilidad y en toda la configuración.
. Conecte los puertos de la bandeja en el siguiente orden:
+
.. Conecte NSM-A, e0a al conmutador (Switch-A1 o Switch-B1)
.. Conecte NSM-B, e0a al conmutador (Switch-A2 o Switch-B2)
.. Conecte el NSM-A y el e0b al interruptor (interruptor A1 o interruptor B1)
.. Conecte el NSM-B, e0b al interruptor (interruptor-A2 o interruptor-B2)


. Utilice la distribución de cableado generada con la herramienta **RcfFileGenerator** para conectar la bandeja a los puertos apropiados.
+
Una vez que la bandeja nueva se ha cableado correctamente, ONTAP la detecta automáticamente en la red.


