---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: Es posible que necesite actualizar un archivo RCF en un conmutador MetroCluster IP. Por ejemplo, una actualización de ONTAP o de firmware del switch requieren un nuevo archivo RCF. 
---
= Actualice los archivos RCF en switches MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que tengas que actualizar un archivo de configuración de referencia (RCF) en un switch IP de MetroCluster. Por ejemplo, si la versión del RCF que estás usando en los switches no es compatible con la versión de ONTAP, la versión del firmware del switch o ambas.

.Antes de empezar
* Si vas a instalar un nuevo firmware para el switch, debes instalar el firmware del switch antes de actualizar el RCF.
* Antes de actualizar el RCF, link:task_upgrade_firmware_on_mcc_ip_switches.html["Compruebe que el RCF es compatible"].
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.


.Acerca de esta tarea
* Este procedimiento interrumpe el tráfico en el switch donde se actualiza el RCF. El tráfico se reanuda cuando se aplica el nuevo RCF.
* Realice los pasos en un conmutador a la vez, en el siguiente orden: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.


.Pasos
. Compruebe el estado de la configuración.
+
.. Compruebe que los componentes de MetroCluster están en buen estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
La operación se ejecuta en segundo plano.

+
.. Después del `metrocluster check run` la operación finaliza, se ejecuta `metrocluster check show` para ver los resultados.
+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Comprobar el estado de la operación de comprobación de MetroCluster en ejecución:
+
`metrocluster operation history show -job-id 38`

.. Compruebe que no hay alertas de estado:
+
`system health alert show`



. link:../install-ip/switch-move-cluster-lifs.html["Mueve las LIF del clúster"] antes de iniciar la actualización.
. Prepare los switches IP para la aplicación de los nuevos RFC.
+
Siga los pasos para su proveedor de switches:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Restablezca el conmutador IP Broadcom a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Restablezca el conmutador IP de Cisco a los valores predeterminados de fábrica"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Restablece el switch NVIDIA IP SN2100 a los valores predeterminados de fábrica"]


. Descarga e instala los archivos RCF de IP, según el fabricante de tu switch.
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Descarga e instala los archivos RCF de IP de Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Descargue e instale los Cisco IP RCF"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Descargue e instale los NVIDIA IP RCF"]
+

NOTE: Si tiene una configuración de red L2 compartida o L3, es posible que deba ajustar los puertos ISL en los switches intermedio/cliente. El modo de puerto de switch puede cambiar del modo de acceso al modo de "tronco". Sólo continúe con la actualización del segundo par de conmutadores (A_2, B_2) si la conectividad de red entre los conmutadores A_1 y B_1 está totalmente operativa y la red está en buen estado.



. Repite los pasos anteriores para cada uno de los switches.
+

NOTE: Una vez que hayas configurado los switches en la primera estructura (Switch_A_1, Switch_B_1), debes repetir los pasos para mover las LIF del clúster en la segunda estructura (Switch_A_2, Switch_B_2). Consulta link:../install-ip/task_install_and_cable_the_mcc_components.html["Conoce cómo configurar los switches IP MetroCluster"].


