---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Actualización del firmware en switches MetroCluster IP. 
---
= Actualización del firmware en switches MetroCluster IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba actualizar el firmware en un switch MetroCluster IP.

.Acerca de esta tarea
Debe repetir esta tarea en cada uno de los conmutadores sucesivamente.

link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.

[[step_1_fw_upgrade]]
.Pasos
. Compruebe el estado de la configuración.
+
.. Compruebe que la MetroCluster esté configurada y en modo normal de cada clúster:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Compruebe que el mirroring está habilitado en cada nodo:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Compruebe que los componentes de MetroCluster sean los mismos en buen estado:
+
`metrocluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Compruebe que no hay alertas de estado:
+
`system health alert show`



. Instale el software en el primer interruptor.
+

NOTE: Debe instalar el software del conmutador en los conmutadores en el siguiente orden: Switch_A_1, switch_B_1, Switch_A_2, switch_B_2.

+
Siga los pasos para instalar el software de switch en el tema correspondiente dependiendo de si el tipo de switch es Broadcom, Cisco o NVIDIA:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Descargue e instale el software EFOS del conmutador Broadcom"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Descargue e instale el software Cisco Switch NX-OS"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Descargue e instale el software NVIDIA SN2100 switch Cumulus"]


. Repita el paso anterior con cada uno de los conmutadores.
. Repetición <<step_1_fw_upgrade,Paso 1>> para comprobar el estado de la configuración.

