---
permalink: maintain/task_disable_encryption_on_brocade_fc_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, disable, encryption, brocade, fc, switch 
summary: Puede que deba deshabilitar el cifrado en los switches Brocade FC. 
---
= Deshabilitación del cifrado en switches Brocade FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede que deba deshabilitar el cifrado en los switches Brocade FC.

.Pasos
. Envíe un mensaje de AutoSupport desde ambos sitios que indique el inicio del mantenimiento.
+
[listing]
----
cluster_A::> autosupport invoke -node * -type all -message MAINT=4h
----
+
[listing]
----
cluster_B::> autosupport invoke -node * -type all -message MAINT=4h
----
. Compruebe el funcionamiento de la configuración de MetroCluster en el clúster A.
+
.. Confirme la configuración del MetroCluster y que el modo operativo es normal: +
`*metrocluster show*`
+
[listing]
----
cluster_A::> metrocluster show
----
.. Realice una comprobación de MetroCluster: +
`*metrocluster check run*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check run
----
.. Mostrar los resultados del control MetroCluster: +
`*metrocluster check show*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check show
----


. Comprobar el estado de ambos interruptores:
+
`*fabric show*`

+
[listing]
----
switch_A_1:admin> fabric show
----
+
[listing]
----
switch_B_1:admin> fabric show
----
. Desactivar ambos interruptores:
+
`*switchdisable*`

+
[listing]
----
switch_A_1:admin> switchdisable
----
+
[listing]
----
switch_B_1:admin> switchdisable
----
. Compruebe las rutas disponibles para los nodos en cada clúster:
+
`*sysconfig*`

+
[listing]
----
cluster_A::> system node run -node node-name -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node node-name -command sysconfig -a
----
+
Dado que la estructura del switch está deshabilitada, la configuración de almacenamiento del sistema debe ser Single-Path ha.

. Compruebe el estado del agregado para ambos clústeres.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
El resultado del sistema debe mostrar que los agregados se reflejan y son normales para ambos clústeres:

+
[listing]
----
mirrored,normal
----
. Repita los siguientes subpasos desde el símbolo del sistema del administrador en ambos switches.
+
.. Muestra los puertos cifrados: +
`*portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. Desactive el cifrado en los puertos cifrados: +
`*portcfgencrypt – disable _port-number_*`
+
[listing]
----
switch_A_1:admin> portcfgencrypt --disable 40
switch_A_1:admin> portcfgencrypt --disable 41
switch_A_1:admin> portcfgencrypt --disable 42
switch_A_1:admin> portcfgencrypt --disable 43
----
.. Establezca el tipo de autenticación en All:
+
`*authUtil --set -a all*`

+
[listing]
----
switch_A_1:admin> authUtil --set -a all
----
.. Establezca la directiva de autenticación en el conmutador. para desactivar: +
`*authutil --policy -sw off*`
+
[listing]
----
switch_A_1:admin> authutil --policy -sw off
----
.. Establezca el grupo Diffie-Hellman de autenticación en +*+ : +
`*authutil --set -g **`
+
[listing]
----
switch_A_1:admin> authUtil --set -g *
----
.. Eliminar la base de datos de claves secretas: +
`*secAuthSecret --remove -all*`
+
[listing]
----
switch_A_1:admin> secAuthSecret --remove -all
----
.. Confirme que el cifrado está desactivado en los puertos: +
`*portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. Activar el interruptor: +
`*switchenable*`
+
[listing]
----
switch_A_1:admin> switchenable
----
.. Confirme el estado de los ISL: +
`*islshow*`
+
[listing]
----
switch_A_1:admin> islshow
----


. Compruebe las rutas disponibles para los nodos en cada clúster:
+
`*sysconfig*`

+
[listing]
----
cluster_A::> system node run -node * -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node * -command sysconfig -a
----
+
La salida del sistema debe indicar que la configuración del almacenamiento del sistema ha cambiado a Quad-Path ha.

. Compruebe el estado del agregado para ambos clústeres.
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
El sistema debe mostrar que los agregados se reflejan y son normales para ambos clústeres, tal y como se muestra en el siguiente resultado del sistema:

+
[listing]
----
mirrored,normal
----
. Compruebe el funcionamiento de la configuración de MetroCluster en el clúster A.
+
.. Realice una comprobación de MetroCluster: +
`*metrocluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run
----
.. Mostrar los resultados del control MetroCluster: +
`*metrocluster check show*`
+
[listing]
----
cluster_A::> metrocluster check show
----


. Envíe un mensaje de AutoSupport desde ambos sitios donde se indique el fin del mantenimiento.
+
[listing]
----
cluster_A::> autosupport invoke -node node-name -type all -message MAINT=END
----
+
[listing]
----
cluster_B::> autosupport invoke -node node-name -type all -message MAINT=END
----

