---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch 
summary: Es posible que deba cambiar la velocidad de los puertos ISL en un switch para mejorar la calidad del ISL. Las islas que viajan a mayores distancias podrían necesitar su velocidad reducida para mejorar la calidad. 
---
= Cambio de la velocidad de los puertos ISL en un switch FC de Cisco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba cambiar la velocidad de los puertos ISL en un switch para mejorar la calidad del ISL. Las islas que viajan a mayores distancias podrían necesitar su velocidad reducida para mejorar la calidad.

.Acerca de esta tarea
* Complete todos los pasos en ambos switches para garantizar la conectividad ISL.
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.


.Pasos
. Deshabilite los puertos ISL de los ISL que desea cambiar la velocidad de ambos switches en la estructura:
+
`*FC_switch_A_1# config t*`

+
Escriba los comandos de configuración, uno por línea. Termine con CTRL-Z después de haber introducido todos los comandos de configuración.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Cambie la velocidad de los puertos ISL en ambos switches de la estructura:
+
`*FC_switch_A_1# config t*`

+
Escriba los comandos de configuración, uno por línea. Termine con CTRL-Z después de haber introducido todos los comandos de configuración.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+

NOTE: Las velocidades para puertos son 16 = 16,000 Gbps, 8 = 8,000 Gbps, 4 = 4,000 Gbps.

+
Compruebe que estos puertos ISL para el switch se enumeran en la _Guía de instalación y configuración de MetroCluster con conexión a la estructura_.

. Habilite todos los puertos ISL (si no está habilitado) en ambos switches de la estructura:
+
`*FC_switch_A_1# config t*`

+
Escriba los comandos de configuración, uno por línea. Termine con CTRL-Z después de haber introducido todos los comandos de configuración.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Compruebe que se han establecido ISL entre los dos switches:
+
`*show topology isl*`

+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
. Repita el procedimiento para la segunda estructura del interruptor.

