---
permalink: maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches, cleanupfiles, cisco 
summary: Es posible que necesite actualizar un archivo RCF en un conmutador IP de Cisco. Por ejemplo, una actualización de ONTAP o de firmware del switch requieren un nuevo archivo RCF. 
---
= Actualice los archivos RCF en switches IP de Cisco mediante CleanUpFiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que tengas que actualizar un archivo de configuración de referencia (RCF) en un conmutador IP de Cisco. Por ejemplo, tanto una actualización de ONTAP como una actualización de firmware del conmutador requieren un nuevo RCF.

.Acerca de esta tarea
* A partir de la versión 1.4a de RcfFileGenerator, hay una nueva opción para cambiar (actualizar, degradar o reemplazar) la configuración del switch en switches IP de Cisco sin necesidad de realizar un 'borrado de escritura'.
* link:enable-console-logging-before-maintenance.html["Active el registro de la consola"] antes de realizar esta tarea.


* El switch Cisco 9336C-FX2 tiene dos tipos de almacenamiento de switch diferentes con un nombre diferente en el RCF. Use la siguiente tabla para determinar el tipo de almacenamiento Cisco 9336C-FX2 correcto para su configuración:
+
[cols="3*"]
|===
| Si va a conectar el siguiente almacenamiento... | Elija el tipo de almacenamiento Cisco 9336C-FX2... | Ejemplo de banner de RCF/MOTD 


 a| 
** Bandejas SAS conectadas directamente
** Bandejas NVMe conectadas directamente
** Bandejas NVMe conectadas a switches de almacenamiento dedicados

 a| 
9336C-FX2: Solo almacenamiento directo
 a| 
`* Switch    : NX9336C (direct storage, L2 Networks, direct ISL)`



 a| 
** Bandejas SAS conectadas directamente
** Bandejas NVMe conectadas a los switches IP de MetroCluster



NOTE: Se requiere al menos una bandeja NVMe conectada con Ethernet
 a| 
9336C-FX2: Almacenamiento SAS y Ethernet
 a| 
`* Switch    : NX9336C (SAS and Ethernet storage, L2 Networks, direct ISL)`

|===


.Antes de empezar
Puede utilizar este método si la configuración cumple los siguientes requisitos:

* Se aplica la configuración RCF estándar.
* El  https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"] debe ser capaz de crear el mismo RCF que se aplica, con la misma versión y configuración (plataformas, VLANs).
* El RCF que se ha aplicado no fue suministrado por NetApp para una configuración especial.
* El RCF no se modificó antes de que se aplicara.
* Se siguieron los pasos para restablecer los ajustes de fábrica del switch antes de aplicar el RCF actual.
* No se realizaron cambios en la configuración del conmutador (puerto) después de aplicar el RCF.
+
Si no cumples estos requisitos, entonces no puedes usar los CleanUpFiles que se crean al generar los RCF. Sin embargo, puedes aprovechar la función para crear CleanUpFiles genéricos: la limpieza usando este método se deriva del resultado de `show running-config` y es una buena práctica.

+

NOTE: Debe actualizar los interruptores en el siguiente orden: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2. O bien, puede actualizar los interruptores Switch_A_1 y Switch_B_1 al mismo tiempo, seguidos de los interruptores Switch_A_2 y Switch_B_2.



.Pasos
. link:../install-ip/switch-move-cluster-lifs.html["Mueve las LIF del clúster"] antes de iniciar la actualización.
. Averigua cuál es la versión actual de RCF y qué puertos y VLAN se utilizan: `IP_switch_A_1# show banner motd`
+

NOTE: Debe obtener esta información de los cuatro switches y completar la siguiente tabla de información.

+
[listing]
----
* NetApp Reference Configuration File (RCF)
*
* Switch : NX9336C (SAS storage, L2 Networks, direct ISL)
* Filename : NX9336_v1.81_Switch-A1.txt
* Date : Generator version: v1.3c_2022-02-24_001, file creation time: 2021-05-11, 18:20:50
*
* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700
*              MetroCluster 2 : AFF-A320, FAS9000, AFF-A700, AFF-A800
* Port Usage:
* Ports 1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 111
* Ports 3- 4: Intra-Cluster Node Ports, Cluster: MetroCluster 2, VLAN 151
* Ports 5- 6: Ports not used
* Ports 7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 111, 151
* Ports 9-10: MetroCluster 1, Node Ports, VLAN 119
* Ports 11-12: MetroCluster 2, Node Ports, VLAN 159
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used
*

#
IP_switch_A_1#
----
+
En este resultado, debe recopilar la información que se muestra en las dos tablas siguientes.

+
|===


| Información genérica | MetroCluster | SQL Server 


| Versión de RCF |  | 1.81 


| Tipo de interruptor |  | NX9336 


| Tipología de red |  | Redes L2, ISL directo 


| Tipo de almacenamiento |  | Almacenamiento SAS 


.2+| Plataformas | 1 | AFF A400 


| 2 | FAS9000 
|===
+
|===
| Información de VLAN | Red | Configuración de MetroCluster | Puertos de switch | Centro a | Centro B 


.4+| Clúster local VLAN .2+| Red 1 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.2+| Red 2 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.4+| MetroCluster de VLAN .2+| Red 1 | 1 | 9, 10 | 119 | 119 


| 2 | 11, 12 | 159 | 159 


.2+| Red 2 | 1 | 9, 10 | 219 | 219 


| 2 | 11, 12 | 259 | 259 
|===
. [[Crear-archivos-RCF-y-CleanUpFiles-o-crear-genéricos-CleanUpFiles]] Crea los RCF y CleanUpFiles, o crea genéricos CleanUpFiles para la configuración actual.
+
Si su configuración cumple los requisitos descritos en los requisitos previos, seleccione *opción 1*. Si su configuración *no* cumple los requisitos descritos en los requisitos previos, seleccione *opción 2*.

+
[role="tabbed-block"]
====
.Opción 1: crear los RCF y CleanUpFiles
--
Utilice este procedimiento si la configuración cumple los requisitos.

.Pasos
.. Utiliza RcfFileGenerator 1.4a (o posterior) para crear los RCF con la información que obtuviste en el paso 1. La nueva versión de RcfFileGenerator crea un conjunto adicional de CleanUpFiles que puedes usar para revertir parte de la configuración y preparar el switch para aplicar una nueva configuración RCF.
.. Compara el banner motd con los RCF que se aplican actualmente. Los tipos de plataforma, el tipo de switch, el puerto y el uso de VLAN deben ser los mismos.
+

NOTE: Debes usar el CleanUpFiles de la misma versión que el RCF y con exactamente la misma configuración. Usar cualquier CleanUpFile no funcionará y podría requerir un restablecimiento completo del switch.

+

NOTE: La versión de ONTAP para la que se ha creado el RCF no es relevante. Solo importa la versión del RCF.

+

NOTE: Es posible que el RCF (aunque sea la misma versión) incluya menos o más plataformas. Asegúrate de que tu plataforma esté en la lista.



--
.Opción 2: Crear CleanUpFiles genérico
--
Utilice este procedimiento si la configuración * no cumple todos los requisitos.

.Pasos
.. Recupere la salida de `show running-config` de cada switch.
.. Abra la herramienta RcfFileGenerator y haga clic en 'Crear archivos genéricos de CleanUpFiles' en la parte inferior de la ventana
.. Copie la salida que ha recuperado en el paso 1 del interruptor "uno" en la ventana superior. Puede eliminar o dejar la salida predeterminada.
.. Haga clic en 'Crear archivos CUF'.
.. Copie el resultado de la ventana inferior en un archivo de texto (este archivo es CleanUpFile).
.. Repita los pasos c, d y e para todos los switches de la configuración.
+
Al final de este procedimiento, debería tener cuatro archivos de texto, uno para cada conmutador. Puede utilizar estos archivos de la misma forma que CleanUpFiles que puede crear utilizando la opción 1.



--
====
. [[Crear los nuevos archivos RCF para la nueva configuración]] Crea los «nuevos» archivos RCF para la nueva configuración. Crea estos archivos del mismo modo que lo hiciste en el paso anterior, pero selecciona la versión correspondiente de ONTAP y RCF.
+
Después de completar este paso, deberías tener dos conjuntos de RCF, cada conjunto compuesto por doce archivos.

. Descargue los archivos en el bootflash.
+
.. Descarga el CleanUpFiles que creaste en <<Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles,Crea los RCF y CleanUpFiles, o crea CleanUpFiles genéricos para la configuración actual>>
+

NOTE: Este CleanUpFile es para el RCF actual que se está aplicando y *NO* para el nuevo RCF al que quieres actualizar.

+
Ejemplo de CleanUpFile para Switch-A1: `Cleanup_NX9336_v1.81_Switch-A1.txt`

.. Descarga los «nuevos» RCF que has creado en <<Create-the-new-RCF-files-for-the-new-configuration,Crea los 'nuevos' RCF para la nueva configuración.>>
+
Ejemplo de RCF para Switch-A1: `NX9336_v1.90_Switch-A1.txt`

.. Descarga el CleanUpFiles que creaste en <<Create-the-new-RCF-files-for-the-new-configuration,Crea los 'nuevos' RCF para la nueva configuración.>> este paso es opcional: puedes usar el archivo en el futuro para actualizar la configuración del switch. Coincide con la configuración aplicada actualmente.
+
Ejemplo de CleanUpFile para Switch-A1: `Cleanup_NX9336_v1.90_Switch-A1.txt`

+

NOTE: Debe utilizar CleanUpFile para la versión RCF correcta (coincidente). Si utiliza CleanUpFile para una versión de RCF diferente o una configuración diferente, puede que la limpieza de la configuración no funcione correctamente.

+
El ejemplo siguiente copia los tres archivos en el bootflash:

+
[listing]
----
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.81_MetroCluster-IP_L2Direct_A400FAS8700_xxx_xxx_xxx_xxx/Cleanup_NX9336_v1.81_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//NX9336_v1.90_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//Cleanup_NX9336_v1.90_Switch-A1.txt bootflash:
----
+

NOTE: Se le pedirá que especifique el enrutamiento y el reenvío virtuales (VRF).



. Aplique CleanUpFile o CleanUpFile genérico.
+
Parte de la configuración se revierte y los puertos de switch se "desconectan".

+
.. Confirme que no hay cambios pendientes en la configuración de inicio: `show running-config diff`
+
[listing]
----
IP_switch_A_1# show running-config diff
IP_switch_A_1#
----


. Si ve la salida del sistema, guarde la configuración en ejecución en la configuración de inicio: `copy running-config startup-config`
+

NOTE: El resultado del sistema indica que la configuración de inicio y la configuración en ejecución son diferentes y los cambios pendientes. Si no guarda los cambios pendientes, no podrá retroceder utilizando una recarga del conmutador.

+
.. Aplicar CleanUpFile:
+
[listing]
----

IP_switch_A_1# copy bootflash:Cleanup_NX9336_v1.81_Switch-A1.txt running-config

IP_switch_A_1#
----
+

NOTE: La secuencia de comandos puede tardar un tiempo en volver al indicador del switch. No se espera ningún resultado.



. Vea la configuración en ejecución para verificar que se borra la configuración: `show running-config`
+
La configuración actual debe mostrar:

+
** No se han configurado mapas de clases ni listas de acceso IP
** No hay ningún mapa de directivas configurado
** No hay ninguna política de servicio configurada
** No se configuró ningún perfil de puerto
** Todas las interfaces Ethernet (excepto mgmt0 que no deben mostrar ninguna configuración y sólo se debe configurar VLAN 1).
+
Si compruebas que alguno de los elementos anteriores está configurado, es posible que no puedas aplicar una nueva configuración de RCF. Sin embargo, puedes volver a la configuración anterior recargando el switch *sin* guardar la configuración en ejecución en la configuración de inicio. El switch se iniciará con la configuración anterior.



. Aplica el RCF y comprueba que los puertos estén online.
+
.. Aplica el RCF.
+
[listing]
----
IP_switch_A_1# copy bootflash:NX9336_v1.90-X2_Switch-A1.txt running-config
----
+

NOTE: Aparecen algunos mensajes de advertencia mientras se aplica la configuración. Por lo general, no se esperan mensajes de error. Sin embargo, si ha iniciado sesión mediante SSH, puede recibir el siguiente error: `Error: Can't disable/re-enable ssh:Current user is logged in through ssh`

.. Una vez aplicada la configuración, compruebe que el clúster y los puertos MetroCluster están conectados con uno de los siguientes comandos, `show interface brief`, `show cdp neighbors`, o. `show lldp neighbors`
+

NOTE: Si cambió la VLAN del clúster local y actualizó el primer switch del sitio, es posible que la supervisión del estado del clúster no informe el estado como "correcto" porque las VLAN de las configuraciones nuevas y antiguas no coinciden. Después de actualizar el segundo interruptor, el estado debe volver a correcto.

+
Si la configuración no se aplica correctamente o no desea conservar la configuración, puede volver a la configuración anterior volviendo a cargar el conmutador *sin* guardando la configuración en ejecución en la configuración de inicio. El conmutador aparecerá con la configuración anterior.



. Guarde la configuración y vuelva a cargar el conmutador.
+
[listing]
----
IP_switch_A_1# copy running-config startup-config

IP_switch_A_1# reload
----
. Modifica todas las LIF del clúster para habilitar la reversión automática:
+
.. Vuelve a activar la reversión automática:
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

+
[listing]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert true

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.

cluster_A::*>
----
.. Revertir todos los LIF del clúster que no están actualmente en sus puertos de origen a sus puertos de origen:
+
`network interface revert -vserver Cluster -lif *`

+
Espera unos minutos a que los LIF vuelvan a su puerto de origen:

.. Comprueba que todos los LIF estén en sus puertos de origen:
+
[listing]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      192.168.204.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      192.168.204.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      192.168.204.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      192.168.204.97/18  node_A_2      e4b     true
4 entries were displayed.
----
.. Comprueba el estado de los nodos de MetroCluster:
+
`metrocluster node show`

+
[listing]
----
cluster_A::*> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.

cluster_A::*>
----



