---
permalink: maintain/task_hot_add_a_sas_disk_shelf_in_a_direct_attached_mcc_configuration_us_sas_optical_cables.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, sas, disk, shelf, direct, attached, fc, configuration, optical, cables 
summary: Puede utilizar cables ópticos SAS para añadir en caliente una bandeja de discos SAS a una pila existente de bandejas de discos SAS en una configuración FC MetroCluster de conexión directa, o como una nueva pila a un HBA SAS o un puerto SAS integrado en la controladora. 
---
= Añadir en caliente una bandeja de discos SAS en una configuración MetroCluster FC de conexión directa mediante cables ópticos SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar cables ópticos SAS para añadir en caliente una bandeja de discos SAS a una pila existente de bandejas de discos SAS en una configuración FC MetroCluster de conexión directa, o como una nueva pila a un HBA SAS o un puerto SAS integrado en la controladora.

* Este procedimiento no es disruptivo y tarda aproximadamente dos horas en completarse.
* Necesita la contraseña de administrador y el acceso a un servidor FTP o SCP.
* Si va a añadir una bandeja IOM12 a una pila de bandejas IOM6, consulte link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Añadir en caliente bandejas IOM12 a una pila de bandejas IOM6"].


Esta tarea se aplica a una configuración de MetroCluster FC en la que el almacenamiento está conectado directamente a las controladoras de almacenamiento con cables SAS. No se aplica a configuraciones FC de MetroCluster mediante puentes FC a SAS o estructuras de switches FC.

.Pasos
. Siga las instrucciones para añadir en caliente una bandeja de discos SAS en _Installation Guide_ correspondiente al modelo de su bandeja de discos con el fin de realizar las siguientes tareas para añadir en caliente una bandeja de discos:
+
.. Instale una bandeja de discos para una adición en caliente.
.. Encienda las fuentes de alimentación y configure el ID de bandeja para una adición de activo.
.. Cablee la bandeja de discos añadida en caliente.
.. Verifique la conectividad SAS.



