---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge 
summary: Al planificar la configuración de MetroCluster, debe conocer los componentes de hardware y software necesarios y compatibles. Para mayor comodidad y claridad, también debe comprender las convenciones de nomenclatura que se utilizan para los componentes en ejemplos de la documentación. Por ejemplo, un sitio se denomina Sitio A y el otro se denomina Sitio B. 
---
= Componentes de hardware y convenciones de nomenclatura de MetroCluster necesarios para configuraciones de ampliación conectadas a puente de dos nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al planificar la configuración de MetroCluster, debe conocer los componentes de hardware y software necesarios y compatibles. Para mayor comodidad y claridad, también debe comprender las convenciones de nomenclatura que se utilizan para los componentes en ejemplos de la documentación. Por ejemplo, un sitio se denomina Sitio A y el otro se denomina Sitio B.



== Software y hardware compatibles

El hardware y el software deben ser compatibles con la configuración FC de MetroCluster.

https://hwu.netapp.com["Hardware Universe de NetApp"]

Al usar sistemas AFF, todos los módulos de controladora de la configuración MetroCluster deben configurarse como sistemas AFF.



== Redundancia del hardware en la configuración de MetroCluster

Debido a la redundancia del hardware en la configuración de MetroCluster, hay dos componentes de cada sitio. Los sitios son asignados arbitrariamente las letras A y B y los componentes individuales son asignados arbitrariamente los números 1 y 2.



== Requisito para dos clústeres ONTAP de un solo nodo

La configuración de MetroCluster de ampliación con conexión a puente requiere dos clústeres ONTAP de un solo nodo.

La nomenclatura debe ser única en la configuración de MetroCluster.

Nombres de ejemplo:

* Sitio A: Cluster_A
* Centro B: Cluster_B




== Requisito para dos módulos de controladora de almacenamiento

La configuración de MetroCluster de ampliación con conexión en puente requiere dos módulos de controladora de almacenamiento.

Las controladoras deben cumplir con los siguientes requisitos:

* La nomenclatura debe ser única en la configuración de MetroCluster.
* Todos los módulos de controladora de la configuración de MetroCluster deben ejecutar la misma versión de ONTAP.
* Todos los módulos de controladora de un grupo de recuperación ante desastres deben ser del mismo modelo.
* Todos los módulos de controladoras de un grupo de recuperación ante desastres deben utilizar la misma configuración FC-VI.
+
Algunos módulos de controladora admiten dos opciones para la conectividad FC-VI:

+
** Puertos FC-VI integrados
** Una tarjeta FC-VI en la ranura 1
+
No se admite una combinación de un módulo de controladora usando puertos FC-VI integrados y otro usando una tarjeta FC-VI complementaria. Por ejemplo, si un nodo utiliza una configuración FC-VI integrada, los demás nodos del grupo DR también deben utilizar la configuración de FC-VI integrada.





Nombres de ejemplo:

* Centro A: Controller_A_1
* Centro B: Controller_B_1




== Requisito de los puentes FC a SAS

La configuración de MetroCluster de ampliación conectada a puente requiere dos o más puentes FC a SAS en cada sitio.

Estos puentes conectan las bandejas de discos SAS a los módulos de controladoras.


NOTE: Los puentes FibreBridge 6500N no se admiten en configuraciones que ejecuten ONTAP 9.8 y posteriores.

* Los puentes FibreBridge 7600N y 7500N admiten hasta cuatro pilas SAS.
* Cada pila puede utilizar distintos modelos de IOM, pero todas las bandejas de una pila deben utilizar el mismo modelo.
+
Los modelos de IOM admitidos dependen de la versión de ONTAP que ejecute.

* La nomenclatura debe ser única en la configuración de MetroCluster.


Los nombres sugeridos utilizados como ejemplos de este procedimiento identifican el módulo de la controladora al que se conecta el puente y el puerto.

Nombres de ejemplo:

* Centro A:
+
** puente_a_1_``__port-number__``
** puente_a_2_``__port-number__``


* Centro B:
+
** puente_B_1_``__port-number__``
** puente_B_2_``__port-number__``






== Requisito para al menos cuatro bandejas SAS (recomendado)

La configuración de MetroCluster de ampliación conectada a puente requiere al menos dos bandejas SAS. Sin embargo, se recomiendan dos bandejas en cada sitio para permitir la propiedad de disco por bandeja, con un total de cuatro bandejas SAS.

Se admite un mínimo de una bandeja en cada sitio.

Nombres de ejemplo:

* Centro A:
+
** Bandeja_a_1_1
** Bandeja_a_1_2


* Centro B:
+
** Shelf_B_1_1
** Shelf_B_1_2






== Mezcla módulos IOM12 e IOM 6 en una pila

Su versión de ONTAP debe admitir la mezcla de bandejas. Consulte la herramienta de matriz de interoperabilidad (IMT) para ver si la versión de ONTAP admite la combinación de bandejas. https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"^]

Para obtener más información sobre la mezcla de estantes, consulte: https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Bandejas añadidas en caliente con módulos IOM12 a una pila de bandejas con módulos IOM6"^]
