---
permalink: install-stretch/concept_choosing_the_correct_installation_procedure_for_your_configuration_mcc_install.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, correct, procedure, configuration 
summary: Debe elegir el procedimiento de instalación correcto en función de cómo se conectan los controladores de almacenamiento a los estantes de almacenamiento. 
---
= Elección del procedimiento de instalación correcto para su configuración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe elegir el procedimiento de instalación correcto en función de cómo se conectan los controladores de almacenamiento a los estantes de almacenamiento.

|===


| Para este tipo de instalación... | Utilice estos procedimientos... 


 a| 
Configuración con ampliación de dos nodos con puentes FC a SAS
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_atto.html["Cableado de una configuración de MetroCluster elástico de dos nodos conectada a puente"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Configuración del software MetroCluster en ONTAP"]




 a| 
Configuración con ampliación de dos nodos con cableado SAS de conexión directa
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_sas.html["Cableado de una configuración de MetroCluster ampliado con conexión a SAS de dos nodos"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Configuración del software MetroCluster en ONTAP"]


|===