---
permalink: install-stretch/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, additional, information 
summary: Puede obtener más información sobre la configuración y el funcionamiento de MetroCluster en la documentación de NetApp. 
---
= Dónde encontrar información adicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener más información acerca de la configuración y el funcionamiento de MetroCluster.



== MetroCluster e información variada

|===


| Información | Asunto 


 a| 
https://["Documentación de ONTAP 9"^]
 a| 
* Guías de All MetroCluster




 a| 
 a| 
* Una descripción técnica del funcionamiento y la configuración de MetroCluster FC.
* Prácticas recomendadas para la configuración de MetroCluster FC.




 a| 
https://["Instalación y configuración de MetroCluster estructural"]
 a| 
* Arquitectura MetroCluster FAS
* Cableado de la configuración
* Configurar los puentes de FC a SAS
* Configurar los switches FC
* Configurar MetroCluster en ONTAP




 a| 
https://["Instalación y configuración de IP de MetroCluster: Diferencias entre las configuraciones de ONTAP MetroCluster"]
 a| 
* Arquitectura MetroCluster IP
* Cableado de la configuración
* Configurar MetroCluster en ONTAP




 a| 
https://["Gestión y recuperación ante desastres de MetroCluster"]
 a| 
* Configuración de MetroCluster
* Conmutación, reparación y conmutación de estado
* Recuperación ante desastres (DR)




 a| 
link:../maintain/index.html["Mantener componentes de MetroCluster"]
 a| 
* Directrices de mantenimiento en una configuración de MetroCluster FC
* Sustitución o actualización de hardware. Procedimientos de actualización del firmware para puentes FC-a-SAS y switches FC
* Añadir en caliente una bandeja de discos en una configuración FC MetroCluster estructural o con ampliación
* Eliminación en caliente de una bandeja de discos en una configuración FC MetroCluster estructural o con ampliación
* Reemplazar el hardware en un centro de recuperación ante desastres en una configuración FC de MetroCluster estructural o con ampliación
* Expandir una configuración de FC de MetroCluster con estructura de dos nodos o con ampliación a una configuración MetroCluster de cuatro nodos.
* Expandir una configuración de FC de MetroCluster con estructura de cuatro nodos o con ampliación a una configuración FC de MetroCluster de ocho nodos.




 a| 
https://["Transición de FC de MetroCluster a IP de MetroCluster"]

https://["Guía de actualización y ampliación de MetroCluster"]
 a| 
* Actualizar o actualizar una configuración de MetroCluster
* Realizar la transición de una configuración de MetroCluster FC a una configuración de IP de MetroCluster
* Ampliar una configuración de MetroCluster mediante la adición de nodos adicionales




 a| 
https://["Instalación y configuración del software MetroCluster Tiebreaker"]
 a| 
* Supervisión de la configuración de MetroCluster con el software MetroCluster Tiebreaker




 a| 
Documentación de Active IQ Unified Manager

https://["Documentación de NetApp: Guías de productos y recursos"^]
 a| 
* Supervisar la configuración y el rendimiento de MetroCluster




 a| 
https://["Transición basada en copias"]
 a| 
* Transición de datos de sistemas de almacenamiento 7-Mode a sistemas de almacenamiento en clúster




 a| 
https://["Conceptos de ONTAP"]
 a| 
* Cómo funcionan los agregados reflejados


|===