---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: Puede obtener más información sobre la configuración y el funcionamiento de MetroCluster en la amplia documentación de NetApp. 
---
= Dónde encontrar información adicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener más información acerca de la configuración y el funcionamiento de MetroCluster.



== MetroCluster e información variada

|===


| Información | Asunto 


 a| 
link:../index.html["Documentación de MetroCluster"]
 a| 
* Toda la información sobre MetroCluster




 a| 
http://www.netapp.com/us/media/tr-4375.pdf["Informe técnico de NetApp 4375: MetroCluster de NetApp para ONTAP 9.3"^]
 a| 
* Una descripción técnica general de la configuración y el funcionamiento de MetroCluster.
* Prácticas recomendadas para la configuración de MetroCluster.




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["Instalación y configuración de MetroCluster estructural"]
 a| 
* Arquitectura MetroCluster FAS
* Cableado de la configuración
* Configurar los puentes de FC a SAS
* Configurar los switches FC
* Configurar MetroCluster en ONTAP




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["Instalación y configuración de MetroCluster con ampliación"]
 a| 
* Ampliación de la arquitectura de MetroCluster
* Cableado de la configuración
* Configurar los puentes de FC a SAS
* Configurar MetroCluster en ONTAP




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["Instalación y configuración de IP de MetroCluster"]
 a| 
* Arquitectura MetroCluster IP
* Cableado de la configuración
* Configurar MetroCluster en ONTAP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Instalación y configuración del software MetroCluster Tiebreaker 1.21"]
 a| 
* Supervisión de la configuración de MetroCluster con el software MetroCluster Tiebreaker




 a| 
Documentación de Active IQ Unified Manager https://www.netapp.com/support-and-training/documentation/["Documentación de NetApp: Guías de productos y recursos"^]
 a| 
* Supervisar la configuración y el rendimiento de MetroCluster




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Transición basada en copias"]
 a| 
* Transición de datos de sistemas de almacenamiento 7-Mode a sistemas de almacenamiento en clúster


|===