---
permalink: manage/task_verify_a_successful_switchback.html 
sidebar: sidebar 
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful 
summary: 'Después de llevar a cabo la conmutación de estado, querrá confirmar que todos los agregados y las máquinas virtuales de almacenamiento \(SVM\) hayan vuelto a conectarse y estén en línea.' 
---
= Verificación de una conmutación de regreso exitosa
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de llevar a cabo la conmutación de estado, querrá confirmar que todos los agregados y las máquinas virtuales de almacenamiento (SVM) hayan vuelto a conectarse y estén en línea.

. Compruebe que los agregados de datos conmutados están conmutados de nuevo:
+
`storage aggregate show`

+
En el siguiente ejemplo, aggr_b2 en el nodo B2 ha vuelto a activarse:

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal
----
. Verifique que todas las SVM sync-destination del cluster superviviente estén latentes (mostrando un estado operativo de “alto”):
+
`vserver show -subtype sync-destination`

+
[listing]
----
node_B_1::> vserver show -subtype sync-destination
                                 Admin    Operational  Root
Vserver       Type    Subtype    State    State        Volume    Aggregate
-----------   ------- ---------- -------- ----------   --------  ----------
...
cluster_A-vs1a-mc data sync-destination
                               running    stopped    vs1a_vol   aggr_b2

----
+
Los agregados de sincronización-destino de la configuración de MetroCluster adjuntan automáticamente el sufijo "'-mc'" a su nombre para ayudar a identificarlos.

. Compruebe que las SVM de origen sincronizado en el clúster de desastres están activas y en ejecución:
+
`vserver show -subtype sync-source`

+
[listing]
----
node_A_1::> vserver show -subtype sync-source
                                  Admin    Operational  Root
Vserver        Type    Subtype    State    State        Volume     Aggregate
-----------    ------- ---------- -------- ----------   --------   ----------
...
vs1a           data    sync-source
                                  running  running    vs1a_vol  aggr_b2

----
. Confirme que las operaciones de conmutación de estado han sido realizadas correctamente mediante el `metrocluster operation show` comando.
+
|===


| Si el resultado del comando muestra... | Realice lo siguiente... 


 a| 
Que el estado de la operación de conmutación de estado sea correcto.
 a| 
El proceso de conmutación de estado ha finalizado y puede continuar con el funcionamiento del sistema.



 a| 
Que la operación de regreso o la operación de continuación de regreso del agente es parcialmente exitosa.
 a| 
Realice la corrección sugerida que se proporciona en el resultado del `metrocluster operation show` comando.

|===


Debe repetir las secciones anteriores para realizar la rotación en la dirección opuesta. Si Site_A hizo una conmutación de Site_B, haga que Site_B haga una conmutación de Site_A.
